### ISSUE TITLE
 Uncaught TypeError using data-native-menu:false in contextual filter example

### ISSUE THREAD

**Issue by jsbriantes** [signalpoint/DrupalGap#1004]
Hello. I'm following the example for contextual filters in views  [http://docs.drupalgap.org/7/Views/Views_Contextual_Filters](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters )  
 If I add **'data-native-menu': 'false'** into the attributes of the "select" element, then I get an error in the console when it is executing pageshow function: 

> Uncaught TypeError: Cannot read property 'substring' of undefined  

Is there anyway I can use this popup selector?. Thanks.

**Comment by signalpoint** [comment]
@jsbriantes You'd probably have to create your own Form and have it interact with your Views Render Array by manually passing along contextual filters and then re-rendering your results as needed. I unfortunately won't be adding any new improvements to the D7 version of the Views Contextual Filter stuff within core.

**Comment by jsbriantes** [comment]
Ok. Thanks for your help.
