### ISSUE TITLE
Cross-site request forgery protection locks drupalgap connection

### ISSUE THREAD

**Issue by jsbriantes** [signalpoint/DrupalGap#1005]
I have installed [Security Kit module](https://www.drupal.org/project/seckit) and It has checked (by default) _HTTP origin_ in "Cross-site request forgery" section. With this configuration, Drupalgap can't connect from a device (or emulator), and I get "403 -forbbiden" error in console log (also an error on drupal system log about It's been locking ?=drupalgap/system/connect.json).  
This problem happens only when I run the App with a device (Galaxy S5) or android emulator. If I run as web-app in browser, I works good. If I unchek this options, the app runs well from the device. 
Is there any solution to have this security option enabled? Thanks.

**Comment by signalpoint** [comment]
@jsbriantes This may have to do with the cordova white list plugin. Have you tried configuring that to allow connection to your site from the app?

I'm not familiar with the Security Kit module, so I don't know for sure. I do have a Galazy S5 though ;)

**Comment by jsbriantes** [comment]
Thanks. I'll review cordova whilelist plugin.
