### ISSUE TITLE
User registration and passwd request

### ISSUE THREAD

**Issue by IWantToImprovemySkills** [signalpoint/DrupalGap#1015]
Good morning Tyler, I wanted to thank you before with push_notifications, in the end i utilized the rules to manage the notifications for specific groups. :) 
Now, I'm not sure how ask this simple question but I'd like to remove the possibility for users to register and request passwords from the app form. The problem lies here: I can't figure how to remove those buttons, even if I search in the app modules (ex. users.js and users_form.js) and I even try to remove what it seems to be the code for generating them, but they do not disappear.
(I tried to remove this searching for "register")
      'user/register': {
        'title': t('Register'),
        'page_callback': 'drupalgap_get_form',
        'page_arguments': ['user_register_form'],
        'access_callback': 'user_register_access',
        options: {reloadPage: true}
      },

I know this is probably the dumbest question ever asked and I apologize for it.
Thank you in advance

**Comment by IWantToImprovemySkills** [comment]
Nevermind Tyler XD, i got rid of them using css..... still, I wonder why going through users.js and users.form.js doesn't change anything

**Comment by signalpoint** [comment]
@IWantToImprovemySkills You can use `hook_form_alter()` within your app's custom module to remove those buttons from the form: http://docs.drupalgap.org/7/Forms/Altering_Forms

If you want to hack DrupalGap core (or contribute to it), run `npm install` from the `www` directory of your app, then you can run the `grunt` command which compiles all the code in the `src` folder into the `drupalgap.min.js` file included in the index.html file. This is why you were making changes to those .js files, and nothing was changin.
