### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by farzinaghdam** [signalpoint/DrupalGap#1017]
I probably shouldn't post here about this but I couldn't contact the maintainers the drupalgap.org. There seems to be a problem with the website! looks like styling files are not being served. I was wondering if it is still safe to download modules etc. Thanks. 

The error message 
The specified file temporary://fileu3xqft could not be copied, because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

**Comment by signalpoint** [comment]
@zhinio Thank you for pointing this out, and this is a fine place to post any DrupalGap related issues.

I have fixed the problem with www.drupalgap.org, somehow some group file permissions got messed up the sites/default/files folder. Everything should be back to normal now, and you can download modules (which actually just downloads them from GitHub).
