### ISSUE TITLE
formAttachSubmissionHandler - failed to find form in DOM: UserLoginForm (8.x)

### ISSUE THREAD

**Issue by zak-schlemmer** [signalpoint/DrupalGap#1020]
I am receiving this error in console:

`formAttachSubmissionHandler - failed to find form in DOM: UserLoginForm`

It does not appear to try to POST when attempting to authenticate via the app.

**Comment by zak-schlemmer** [comment]
My above comment was somewhat incorrect.

In order to resolve the issue I had to rollback the min.js file to:

https://github.com/signalpoint/DrupalGap/commit/bef66c0cf2b1fa1efd154af87f353e1ac76be7c3

The error is in console on page load of the login form.

**Comment by signalpoint** [comment]
@zak-schlemmer Thank you for pointing out the exact date of breakage. I believe I've fixed this issue with the following two commits to DrupalGap:

- https://github.com/signalpoint/DrupalGap/commit/2c619a86f922a067d1624316b39248e2fa302918
- https://github.com/signalpoint/DrupalGap/commit/99c1f20f299545795aecbe512938a853c2ef0085

Update to the latest `drupalgap.min.js` and you should be good to go.

**Comment by zak-schlemmer** [comment]
@signalpoint 

Thank you!

The issue has been resolved.
