### ISSUE TITLE
Local Tasks

### ISSUE THREAD

**Issue by SegaWeb** [signalpoint/DrupalGap#1022]
The latest version of drupalgap.min.js no displays Local Tasks. How to fix? Or I'm doing something wrong. If you use drupalgap-7.0.2.min.js, then the menu works on all entities.
![022](https://user-images.githubusercontent.com/40003898/41902608-8f5b10d8-793c-11e8-84fc-01f6b7621df6.png)
![011](https://user-images.githubusercontent.com/40003898/41902609-8f84ad08-793c-11e8-94bc-2cea11022bd7.png)

**Comment by SegaWeb** [comment]
in function menu_block_view_pageshow(options) options.menu_name does not contain primary_local_tasks

**Comment by signalpoint** [comment]
@SegaWeb Does your `settings.js` file contain the entry for the primary local tasks in the theme/region/block settings?

**Comment by SegaWeb** [comment]
drupalgap.settings.blocks.easystreet3 = {
  header: {
    user_menu_anonymous: {
      roles: {
        value: ['anonymous user'],
        mode: 'include',
      }
    },
    user_menu_authenticated: {
      roles: {
        value: ['authenticated user'],
        mode: 'include',
      }
    },
    main_menu: { }
  },
  sub_header: {
    title: { }
  },
  navigation: {
    primary_local_tasks: { }
  },
  content: {
    messages: { },
    main: { },
  },
  footer: {
    powered_by: { }
  }
};

This is contained in settings.js
Do I need to add somewhere else?

**Comment by SegaWeb** [comment]
I found my mistake. In the new drupalgap.min.js settings templates are transferred to the js file theme. I did not add the right regions there ...

/**
 * Implements hook_TYPE_tpl_html().
 */
function easystreet3_page_tpl_html() {
  return '<div {:drupalgap_page_attributes:}>' +
            '{:header:}'+
		     '{:sub_header:}'+
		     '{:navigation:}'+
		     '{:content:}'+
		     '{:footer:}'+
          '</div>';
}

Thanks for the help!
