### ISSUE TITLE
Jquery Mobile Datepicker Widget

### ISSUE THREAD

**Issue by SegaWeb** [signalpoint/DrupalGap#1024]
I'm trying to add a Datepicker Widget Jquery Mobile (http://demos.jquerymobile.com/1.4.5/datepicker/#ui-page-top). 

But after adding in the index.html file or hook_install in my custom module and adding attributes 'data-role': 'date' (textfield), all the time I get an error "drupalgap_goto_generate_page_and_go - TypeError: Cannot read property '_defaults' of undefined"

What could be the reason?
Thank!

**Comment by signalpoint** [comment]
@SegaWeb I used grep to look through all of the source code for DrupalGap 7 and jDrupal 7, neither of which has any code that tries to access a property called `_defaults` from an object. This sounds like a problem in your custom module's code, or a problem in the jQuery date picker.

**Comment by SegaWeb** [comment]
So I can not understand!

In custom module (in hook_form_alter) I I just added:
`
form.elements['s_test'] = {
type: 'textfield',
id: drupalgap_form_get_element_id('my_new_elementsss', form_id),
title: 'Date field',
attributes: {
'data-role': 'date',
'data-inline': "false"
}
};
`

In index.html include js and css (as well as in the instructions)
`<link rel="stylesheet" href="https://rawgithub.com/arschmitz/jquery-mobile-datepicker-wrapper/master/jquery.mobile.datepicker.css" />
<script src="https://rawgithub.com/arschmitz/jquery-mobile-datepicker-wrapper/master/jquery.mobile.datepicker.js"></script>`

**Comment by SegaWeb** [comment]
Understood the problem. In addition to jquery.mobile.datepicker.js, you must first add jquery.ui.datepicker.js.
