### ISSUE TITLE
drupalgap_goto -- reloadPage

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#105]
I think the line 241 in includes/theme.inc.js ...

``` javascript
else if (typeof variables.options.reloadPage !== 'undefined' && variables.options.reloadPage) {
```

needs to be

``` javascript
else if (typeof variables.options.attributes.reloadPage !== 'undefined' && variables.options.attributes.reloadPage) {
```

the "attributes" key is missing in the object. I can do a pull request, not sure if you want me to for such a simple thing. Line 241.

Also, this format from the doc

``` javascript
var my_link = l('Users', 'user-listing', {reloadPage:true});
```

doesn't work.

**Comment by scotthooker** [comment]
Confirmed: tested and working. Thanks!

**Comment by signalpoint** [comment]
The only problem I see with the code above is that reloadPage isn't technically an attribute that will be attached to the html link element (e.g. id, class, style, etc). It's just an option that needs to be passed along to drupalgap_goto().

The format from the documentation does work for me, for example using:

```
l('Clothes', 'clothes', {reloadPage:true});
```

Results in an html link like this:

```
<a onclick="javascript:drupalgap_goto('clothes', {reloadPage:true});" class="ui-link">Clothes</a>
```

Will you guys please post any code that isn't working with the latest commit (excluding the patch from above)?

Thank you!

**Comment by scotthooker** [comment]
I gather it is links in hook menu in settings.js that don't work that way as there is no way to pass in that argument other that in an attribute. At least that is the case for me

**Comment by signalpoint** [comment]
Here's an example menu link for settings.js with a reloadPage and custom attributes, this goes inside the 'links' array of a menu:

```
{'title':'Users','path':'user-listing','options':{reloadPage:true, 'attributes':{'data-icon':'info'}}}
```

The trick is any attributes need to be bundled inside the options. This will render a menu link that looks something like this:

```
<a onclick="javascript:drupalgap_goto('user-listing', {reloadPage:true});" data-icon="info" other-attributes="blah blah">...</a>
```

**Comment by scotthooker** [comment]
Perfect.

**Comment by signalpoint** [comment]
Great, thanks @scotthooker .

@cschaub - does this code work for you, or do you still need to use the patch you mentioned above?

**Comment by chrisschaub** [comment]
Well, I switched the order ... I put reloadPage:true before the 'attributes... -- and it started working! The last example seems to work as well.
