### ISSUE TITLE
Password field for registration.

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#106]
I think it would be cool to add the option to send a password on the registration form. I have a use case where the client wants a user to be able to register with an email and password only. It's a one line addition to pass "password" to the service. I can submit a patch. The service already supports this because Drupal does.

**Comment by signalpoint** [comment]
@cschaub - Interesting, I didn't know Drupal core supported passwords during registration. If that is indeed the case, I'd really like to have DrupalGap listen to the settings defined on the Drupal site, then have the user registration form dynamically know what to do.

**Comment by chrisschaub** [comment]
Yeah, that seems sane. The services module definitely allows you send the password as part of the request during registration.

**Comment by chrisschaub** [comment]
Found a service 

http://drupalcode.org/project/er_svc.git

That works with the email registration module ... checking it out.

**Comment by signalpoint** [comment]
The user registration form now completely listens to Drupal's user account settings and dynamically places the e-mail address field and password field(s) on the form when necessary. Resolved with the 7.x-1.7-alpha release.
