### ISSUE TITLE
Add reloadPage option to hook_menu() items

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#107]
Any implementations of hook_menu() should be able to add a reloadPage option to their menu item(s). This will allow the developers to have control over which pages will be forced to reload.

For example, the user login and registration pages should never be cached, but they are right now (since DrupalGap by default caches pages).

**Comment by chrisschaub** [comment]
I think what you've already coded will work, it just has a few issues that I posted earlier. One was a simple bug related to the object's tree structure.

**Comment by signalpoint** [comment]
Added example use of reloadPage in a hook_menu() to the documentation:

http://drupalgap.org/node/134

**Comment by signalpoint** [comment]
The latest commit makes a slight modification, hook_menu() items now use an 'options' variable to store the 'reloadPage' setting. Documentation udpated:

http://drupalgap.org/node/134
