### ISSUE TITLE
.map files not found

### ISSUE THREAD

**Issue by simonemarin** [signalpoint/DrupalGap#108]
Hi
I am accesing my Drupalgap project from localhost/ripple, just plain 1.x without any extra files (phonegap).

I get this error:
Uncaught SyntaxError: Unexpected token u Insertion.js:1
GET http://localhost/hello/icon.png 404 (Not Found) ripple.js:48
GET http://localhost/hello/jquery.min.map 404 (Not Found) /hello/jquery.min.map:1
GET http://localhost/hello/jquery.mobile-1.3.1.min.map 404 (Not Found) /hello/jquery.mobile-1.3.1.min.map:1

**Comment by signalpoint** [comment]
.map files are not associated with DrupalGap in any way. So I have no idea where those are coming from.

What type of development environment are you using? http://drupalgap.org/node/132

**Comment by simonemarin** [comment]
I am in Chrome + Ripple

**Comment by signalpoint** [comment]
Sorry, I have no idea where these .map files are coming from. They are in no way associated with DrupalGap. Is this something Ripple is perhaps trying to bring into the environment with a side feature?

**Comment by chancez** [comment]
FYI The map file is the way for jquery to map the compressed minified version of jquery to the uncompressed version for debugging purposes.

http://jquerybyexample.blogspot.com/2013/01/all-you-need-to-know-about-jquery-source-maps.html

**Comment by signalpoint** [comment]
@ecnahc515 - thanks for pointing this out.

@simonemarin - are you still having the issue with the .map files not being found?

**Comment by signalpoint** [comment]
As @ecnahc515 mentioned, the .map files are used to help debug jQuery. To obtain the map files, download the jQueryMobile zip file and extract the .map file to your PhoneGap www directory:

http://jquery.com/download/

Also download the jQuery .map file to your PhoneGap www directory:

http://jquery.com/download/

Note, these files aren't required, but are handy for debugging jQuery and jQueryMobile.
