### ISSUE TITLE
No fields are loaded axcept title on load node

### ISSUE THREAD

**Issue by simonemarin** [signalpoint/DrupalGap#109]
Hi
when I load a node I can see only the Title, if I dig into the console I can see how the json is corectly loaded with all the nodes files, but they are not displayed.
I expect at least the body and and image field to be renderered.
No errors apart those listed in https://github.com/signalpoint/DrupalGap/issues/108
tx
S.

**Comment by signalpoint** [comment]
Duplicate of #97, closing.
