### ISSUE TITLE
7.1 vs 7.2 ?

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#11]
Wondering if I should use the 7.2 app code, seems cleaner? Also, wondering if there is any integration with the legal module for user registration.

Thanks for the hard work!

**Comment by signalpoint** [comment]
Hi there, thanks for the kind words!

Please use the 7.x-1.x branch. I got a little too excited with naming conventions and realized a 2.x branch can't exist if there isn't a nice 1.x branch out first ;)

I'll be removing the 7.x-2.x branch soon.
