### ISSUE TITLE
Clear Entities From Local Storage on Application Startup

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#111]
Since entity JSON is cached in local storage (after a call to node_load(123) for example), the app should clear out any entities left in local storage when it first starts up. We can't just clear the entire local storage, because there could be other data that should persist through app exit/entry.

**Comment by simonemarin** [comment]
Let this be a setting so one can keep as much as possible in local storage in production but enforce cache clearing in debug mode.

**Comment by signalpoint** [comment]
@simonemarin - good point, this should be configurable. It will be available in settings.js

**Comment by signalpoint** [comment]
@simonemarin - thanks again for suggesting this as a configurable option. It is now available, more info here: http://drupalgap.org/node/174
