### ISSUE TITLE
Add popup (dropdown) menu support

### ISSUE THREAD

**Issue by simonemarin** [signalpoint/DrupalGap#114]
Hi
I d like to add a dorpdown menu. 

In the following example nested list items are created and then manipulated with jquery
http://jsfiddle.net/nirmaljpatel/nQTTC/

But natively jquery.mobile supports the select menu widget, which is built upon options
http://api.jquerymobile.com/selectmenu/

Is it ok to use options as menu links to pages? 
tx
Simone

**Comment by signalpoint** [comment]
@simonemarin - amazing! I'm glad jQM supports this. I've been wondering about this for a while and haven't  researched it yet, so this is great news. Should be pretty simple to implement when the time comes. Thanks for the example code and working jQM page!

**Comment by signalpoint** [comment]
See here:
- http://api.jquerymobile.com/popup/
- http://stackoverflow.com/a/6270701/763010
- http://stackoverflow.com/a/18063349/763010

**Comment by signalpoint** [comment]
Without further ado, this feature has been added:

http://drupalgap.org/node/264
