### ISSUE TITLE
Developing in Chrome with Ripple

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#12]
So, I've checked out the latest code 7.1-x. I can get it to run in the IOS debugger, but I used to be able to debug the 1.02 in Chrome. Now, it's just a blank screen. I'll try to track it down, just an fyi. Maybe you have an idea. I like the new structure with the settings up front.

**Comment by signalpoint** [comment]
I actually have never tried debugging in Chrome. This may have some more information: http://drupal.org/node/1690356 - It is a little dated though.

Thanks for the kind words about the new structure of 7.x-1.x. Be sure to do another pull, I have changed up MANY things since yesterday.

I'll leave this issue open until we figure out how to debug in Chrome.

**Comment by chrisschaub** [comment]
Debugging works in chrome if you add a ...

--disable-web-security

option to the chrome invocation path. And then I'm using the Ripple emulator plugin for chrome ...

https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc

which allows you to do more inspecting in chrome, helpful for me. Just an fyi. You do have to turn off the local proxy if you are crossing domains.

**Comment by signalpoint** [comment]
Thank you for this information about ripple emulation. I am going to close this ticket. Please re-open or start a new one for other ripple related issues.

**Comment by signalpoint** [comment]
@cschaub - Using the remote proxy in Ripple, have you ever been able to successfully login with DrupalGap? I can see the login result is successful, but all subsequent page visits are as an anonymous user. Do you know if it is something to do with the remote proxy not holding sessions properly? Or do we need to write a cookie to the browser? (https://drupal.org/node/2013781). I'm curious if you've ever done anything as an authenticated user in Ripple, I haven't been able to. However, when I compile directly to my Android device, authentication works fine.

**Comment by signalpoint** [comment]
I should also clarify that my DrupalGap install is running from within localhost, and the settings.js site_path variable is configured to point to a Drupal site hosted live on the web.

**Comment by signalpoint** [comment]
#51 <--- A bunch of related info here.

**Comment by chrisschaub** [comment]
So, just to cap it off with some comments. I've gotten login to work, with a view caveats. If you are using ripple to talk to drupal on the same host (maybe in a virtual machine), you should give the drupal instance a real local domain, something like mydrupal.dev, and put this in the /etc/hosts file. You also need to disable the Cross Domain Proxy under settings in RIpple. The only other gotcha is that you can't be logged into Drupal in the same browser as you are testing logins via Ripple, this causes some cookie weirdness. So, I use Ripple with Chrome and Firefox for logging into Drupal natively.

Oh, and one more thing. You need to start chrome with:

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security

This helps prevent a bunch of cross-domain security issues when doing dev.

**Comment by signalpoint** [comment]
I had an interesting conversation with @mheinke today in IRC. It turns out if for example you have a Drupal site available at http://www.example.com and then make a new folder i.e. http://www.example.com/app , then this login problem with Ripple doesn't exist (probably since there is no crossing over to a subdomain like http://app.example.com).

**Comment by chrisschaub** [comment]
Yes, there are no cross domain issues. That is why I launch Chrome with
security disabled, fixes the issue.

On Fri, Aug 30, 2013 at 3:33 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> I had an interesting conversation with @mheinkehttps://github.com/mheinketoday in IRC. It turns out if for example you have a Drupal site available
> at http://www.example.com and then make a new folder i.e.
> http://www.example.com/app , then this login problem with Ripple doesn't
> exist (probably since there is no crossing over to a subdomain like
> http://app.example.com).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/12#issuecomment-23587504
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by amitsedai** [comment]
I have begun using Chrome Ripple for debugging UI. However for the latest build of drupalgap, when selecting Cordova version 2.0.0 under platforms gives a blank page. Upon selecting Cordova 1.0 , the app seems to work fine.  Just to be sure, I downloaded the latest Drupalgap from github and made minimal modifications for Chrome ripple.
Was this a known problem?

For the app I was developing, pages which had ajax calls for display are not rendered.

**Comment by signalpoint** [comment]
@amitsedai - I often get the white screen of death (WSOD) when first loading the app. Typically if I append the 
"index.html?enableripple=cordova-2.9.0" string to the end of my URL, that gets Ripple to load fine. Please note, even with this on the end of the URL, the Ripple UI still says that Cordova 1 is being used (I think that is a bug on their end).

Regarding the "pages which had ajax calls for display are not rendered" problem, will you please open a new issue with more details about it? Thanks!

**Comment by signalpoint** [comment]
Closing this issue. The work around to be able to develop in Chrome with Ripple is to install DrupalGap within the same domain as your Drupal site. For example, if your Drupal site is available at example.com, then install DrupalGap at example.com/mobile-application as the place to run the app. No need to disable web securtiy. For more information, see the Ripple guide: http://drupalgap.org/node/103
