### ISSUE TITLE
Pass error text to error_page

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#120]
It would be nice to be able to pass error text to the error_page for display. Otherwise, it's hard to tell the user what error occurred.

**Comment by signalpoint** [comment]
I added a quick-n-dirty solution above. It now takes a second optional user message argument that will be displayed to the user in an alert dialog.

```
drupalgap_error('error info for the developer', 'error info for the user');
```

I agree it would be better if the user's message could be displayed on the error page itself, but that'll take a bit more effort. That'll have to wait for another day, or if someone feels like attacking it, go for it!

**Comment by chrisschaub** [comment]
How about we just update an "error" property of the global drupalgap
object. It would always contain the last error message?

drupalgap.error = 'some message';

And then a new function drupalgap_fetch_error() that prints the message and
then clears the value.

On Sun, Aug 4, 2013 at 12:55 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> I added a quick-n-dirty solution above. It now takes a second optional
> user message argument that will be displayed to the user in an alert dialog.
> 
> drupalgap_error('error info for the developer', 'error info for the user');
> 
> I agree it would be better if the user's message could be displayed on the
> error page itself, but that'll take a bit more effort. That'll have to wait
> for another day, or if someone feels like attacking it, go for it!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/120#issuecomment-22075752
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by signalpoint** [comment]
Interesting. How about we use drupalgap_error_set() and drupalgap_error_get() ?

Then drupalgap.error could be an array, then when error set is called, it will:

drupalgap.error.push = 'Some error message';

Then when the system error page callback is about to display the error page, it can call the error get function, which will iterate over all the errors, place them into a string, clear out any previous errors in the drupalgap.error array, then return the string.

How does this sound? Want to implement it? ;)

**Comment by signalpoint** [comment]
#124 should be taken into consideration when implementing a solution for this. Perhaps using something like this would be more elegant in the long run:

```
drupalgap_set_message('something bad happened', 'error');
```

**Comment by signalpoint** [comment]
Now that drupalgap_set_message() is implemented, I think this resolves this issue. Feel free to re-open if need be.
