### ISSUE TITLE
How to filter a data in views using a drupalgap?.

### ISSUE THREAD

**Issue by sanee** [signalpoint/DrupalGap#123]

**Comment by signalpoint** [comment]
@sanee - If your view has exposed filters on it, then you can send along values for those exposed filters in the URL. Here is an example of passing along exposed filter values in the URL (see step number 2):

http://tylerfrankenstein.com/code/drupal-commerce-price-range-navigation

See the DrupalGap Views documentation for more info: http://drupalgap.org/views

**Comment by signalpoint** [comment]
http://drupalgap.org/node/82

Resolved with the 7.x-1.7-alpha release.
