### ISSUE TITLE
Code issue with page.tpl caching

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#127]
This if statment ...

``` javascript
      if (drupalgap.settings.cache &&
          drupalgap.settings.cache.theme_registry &&
          !drupalgap.settings.cache.theme_registry) {
          file_options.cache = false;
       }
```

seems wrong. It's in function function drupalgap_goto_generate_page_and_go in common.js. I think it should be ...

``` javascript
      if (drupalgap.settings.cache &&
          !drupalgap.settings.cache.theme_registry) {
          file_options.cache = false;
       }
```

**Comment by signalpoint** [comment]
@cschaub - Thanks for catching this. The second boolean expression was meant to make sure the theme_registry cache setting was defined, before checking its true/false value (backwards compatibility for settings.js files that haven't been updated with the latest default.settings.js file). I've adjusted the boolean. Please let me know if this doesn't seem right. Thanks!
