### ISSUE TITLE
reloadPage, entity_load and localStorage

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#128]
I thought I was going mad! I kept setting reloadPage = true, change some node data on the server, but no change reflected on the client. I tracked it down to Drupalgap's entity_load function ...

``` javascript
function entity_load(entity_type, ids) {
...
    var local_storage_key = entity_local_storage_key(entity_type, entity_id);
    // Process options if necessary.
    if (options) {
      // If we are resetting, remove the item from localStorage.
      if (options.reset) { window.localStorage.removeItem(local_storage_key); }
    }
    // Attempt to load the entity from local storage.
    var entity = window.localStorage.getItem(local_storage_key);
...
```

which means that once you load a node, that's it! It gets saved and retrieved from LocalStorage from there forward. And there's no way to really clear LocalStorage, even if you logout. I feel like reloadPage should force the item out of LocalStorage so that updated results are retrieved from the server.

**Comment by chrisschaub** [comment]
Maybe a "cache" option for entities? If set to false, no LocalStorage for entities?

**Comment by signalpoint** [comment]
Yup, you found the Easter egg. I was waiting for someone to call this out. Sorry for the maddening.

The drupalgap_goto() function (and beyond) needs to be improved to be smart enough to to watch for the reloadPage option, determine if the page path will contain an entity_load() call (e.g. node/_/ user/_/ comment/*, etc), then set the 'reset' option for entity_load().

Then something like this code would auto purge the entity from local storage when reloading the page:

```
drupalgap_goto('node/123', {reloadPage:true});
```

On the flip side, if someone specified the page be reloaded but not the entity, then something like this would be nice to have as well:

```
drupalgap_goto('node/123', {reloadPage:true, reset:false});
```

**Comment by signalpoint** [comment]
@cschaub - thanks again for pointing this out, it should be resolved now. More info here: http://drupalgap.org/node/174
