### ISSUE TITLE
Loading nodes (and entities) asynchronously

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#138]
Just a thought. In order to give a real feel of responsiveness w/ transitions, it might be good to create an empty page, switch to it and then load nodes (pages?) with the spinner. That way, when you click you immediately transition to the new page with headers etc while the node is loading. If there is an error, it can just display on that page. I have a client who was wanting it to feel a bit more IOS responsive. Just an idea.

**Comment by signalpoint** [comment]
Related issue: #59

Agreed this one would be fantastic to have. It will take quite a bit of re-working, but it is definitely needed in the long run. Basically any system pages that load entities (node/123, user/123, taxonomy/term/456, etc). Need to have a pageshow callback that will dynamically inject the entity content into the page.

**Comment by chrisschaub** [comment]
How about we call a new function based on drupalgap_prepare_argument_entities() from within pageshow? That would be pretty minimal. Maybe just argument_entity_load() which wraps entity_load?

**Comment by chrisschaub** [comment]
Ok, I see the complexity. The entire page_view setup with passed arguments would have to be changed to a pageshow event to be after the transition has occurred. It's sort of a collison of Drupal's "view" operation more appropriately mapping to pageshow. Also, I think it would have to be a flow like -> click -> transition to empty page -> pageshow -> hide contents (opacity 0, maybe with fade out) -> show spinner -> node_load -> render_theme -> show_contents. 

The positive effect might be a more responsive feel and smoother transitions because you are moving to an empty page initially, easy to render. Then you could set the opacity to 1 (maybe with fade in) to show the rendered page.

It does seem like pretty major surgery.

**Comment by signalpoint** [comment]
Yup, you're right. It does go against Drupal's "view" of passing page arguments to call back functions. But I agree that we need to make the call that loaded entities can't be passed to their corresponding page callbacks, they must be retrieved via their pageshow callbacks, dynamically rendered then injected into the page.

So I shall work on adjusting the page system to longer dynamically load entities during the page call back, and have that wait until a pageshow callback requests it happen.

**Comment by signalpoint** [comment]
@cschaub - the commit above has node pages now loading via the pageshow callback. It also no longer uses synchronous calls to get the node, instead using asynchronous. Big time UX improvement already. This branch is extremely unstable at the moment. However, if you are only in need of viewing nodes, then it should be pretty stable. Every other entity type needs to be converted to match this new mechanism, so they are all broken at the moment.

**Comment by chrisschaub** [comment]
Hey Tyler. Any eta on this? Just trying to plan for an app. Thanks!

**Comment by signalpoint** [comment]
@cschaub - the complete implementation is still a ways out. It needs to be adjusted for all other core entity types as well. Right now, this branch works decent for viewing nodes (except node title are currently broken because the title callback system needs to be changed to async as well). I have a current project that needs this feature as well, so I should be able to get 'read only' nodes working (hopefully by the end of the day today).

**Comment by chrisschaub** [comment]
That's great, I really need it too. Can you pull the node view part into
the main alpha? I'm going to work on the error handling ticket today.

**Comment by signalpoint** [comment]
I can't pull it into main alpha unfortunately, it would totally screw that branch for a while and quite a few folks are using it now :P

I'd recommend checking out the branch, then merging alpha into it if you need to.

**Comment by signalpoint** [comment]
@cschaub - FYI - I merged branch 7.x-1.x-alpha into branch 7.x-1.x-issue-138.

**Comment by chrisschaub** [comment]
Thanks, a big help.

**Comment by signalpoint** [comment]
@cschaub - OK, the page title_callback system is now asynchronous as well. So when using this branch to 'read-only' nodes, you should be all set. Node titles are now being set. Please read the UPGRADE.txt doc for full details, mainly the system 'header' block has now been renamed to 'title', so your "Blocks" settings will need be updated in settings.js. Also, any title_callback implementations need to call the provided callback function to get the title properly set. An example is contained in the UPGRADE.txt file.

**Comment by signalpoint** [comment]
@cschaub and anybody else interested, FYI...

These changes have now finally been merged into the 7.x-1.x-alpha branch. All entity viewing and editing is now down by asynchronously loading the entity, instead of via a synchronously call.

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.
