### ISSUE TITLE
Flags Support

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#140]
How can flags be implemented using DrupalGap? 
I was not able to find a solution and hence I created a page that takes an argument, checks if its a flag and then updates it and returns a JSON output. However, I was not able to connect to the page using drupalgap.views_datasource.call(I am not sure if this is the right approach). 
Please do guide on how I can proceed. Thanks.

**Comment by signalpoint** [comment]
We'll need a contrib module for DrupalGap that understands how to deal with Flag.

www.drupalgap.org/project/modules

Check out these pages for an example of how to use views datasource:

http://drupalgap.org/node/82
http://drupalgap.org/node/119

If you'd like to contribute to make Flag a possibility in DrupalGap, please let me know, thanks!

**Comment by chrisschaub** [comment]
There's already a "flag_services" module that I'm messing with.

**Comment by signalpoint** [comment]
https://drupal.org/project/flag_service

Ok, sounds like we'll need the flag contrib module for DrupalGap to include service resource calls for the flag_service module.

For examples of how to implement service resource calls with the DrupalGap API check out files in here: https://github.com/signalpoint/DrupalGap/tree/7.x-1.x-alpha/modules/services

**Comment by amitsedai** [comment]
Thank you for quick response. I have been working for last 2 weeks building an app using DrupalGap. I was able to create 2 custom modules, creating multiple pages, fetch data from views using JSON, theme etc. Thank you for making drupalgap simple and powerful.

I would be interested in creating a module for flag. I would need some guidance on services and ajax callbacks, but that should be fine.

**Comment by signalpoint** [comment]
Thank you for the kind words about DrupalGap, I'm glad it working for you!

To get started, I'd recommend creating a GitHub Repo called: flag

Then adding a sandbox project: http://drupalgap.org/node/add/project

Point the sandbox to the github url.

Then check out some of the files that already implement the DrupalGap Services API to get a feel for creating custom service resource calls:

https://github.com/signalpoint/DrupalGap/tree/7.x-1.x-alpha/modules/services

That should get the module started in the right direction.

**Comment by amitsedai** [comment]
I have created the github repo and project. Thanks.

For now I resolved the flag issue by creating a custom module at Drupal which takes an argument, which can be a flag name and executes it. This seems to work for me here. However a better solution would have been better.

**Comment by janexip** [comment]
Have anyone had successfully worked with the flag service? I tried something quick in my custom module to check if a piece of content has been flagged, and got this error: 

error (Not found: Could not find resource flag.)

Please shed some light. Thanks.

Here is my code:

```
var retrieve_options = {
        'type':'get',
        'path':'flag/is_flagged.json',
        'success':function(data){
            alert('success');
        },
    }
         var is_flagged = {
                "flag_name" : "product_like",
                "entity_id" : 20640, 
                "uid" : 1,
        };
        try {
        var api_options = drupalgap_chain_callbacks(retrieve_options, is_flagged);
        drupalgap.api.call(api_options);
      }
      catch (error) {
        navigator.notification.alert(
          error,
          function(){},
          'flag Retrieve Error',
          'OK'
        );
      }
```

**Comment by signalpoint** [comment]
The error is saying that there is no resource called 'flag' under the 'drupalgap' endpoint. Navigate to admin/structure/services/list/drupalgap/resources and check to make sure there is a flag resource, if not it sounds like you'll need the https://drupal.org/project/flag_service module.

Then you'll need to figure out the path to use and any argument(s) that need to be passed along to the service resource.

@amitsedai did start a sandbox contrib module:

http://drupalgap.org/project/flag
https://github.com/amitsedai/flag

But there isn't any code contributed that I can see. @dontmcyn  I'd recommend contacting @amitsedai for further assistance. Please report back here any progress and we can see about putting together the Flag contrib module for DrupalGap, thanks!

**Comment by janexip** [comment]
Thanks, I did install the flag service module, but didn't know it was not enabled as resource. I Enabled "flag" under  admin/structure/services/list/drupalgap/resources, and this solved the "could not find resource" error, but now it says "error (Not found: Could not find the controller.)". Is there some other configuration I'm missing? 

My system connect test was successful, and everything else works great except for this piece of flag code that I wrote. I am using Cordova 3.2 and installed every plugin as you mentioned.

@amitsedai and @cschaub, could you share your experience working with flags? Thanks!

I'm trying out information from here for the path and arguments:
http://drupal.stackexchange.com/questions/42042/what-is-the-proper-format-for-the-flag-service-calls

**Comment by signalpoint** [comment]
@dontmcyn - on the Drupal site of things, take a look at the flag_service_services_resources() in flag_service.module, that tells us about the different services available in the flag resource.

For example, a path to use to call the service within DrupalGap should be something like:

```
path: flag/is_flagged
method: POST
parameters: flag_name=blah
                  entity_id=123
                  uid=456     (this one is optional)
```

Now that I typed this out, I see you have that already listed above, nicely done. Just try POST instead of GET.

Take a look at this file for an example of how to implement a contrib module's custom service resource in DrupalGap:

https://github.com/signalpoint/commerce/blob/master/commerce.js

If we place code like that in the flag.js file started by @amitsedai, then we can make flag calls using code like this:

```
drupalgap.services.flag.is_flagged.call({...blah...});
```

**Comment by signalpoint** [comment]
@dontmcyn - nevermind the part about chaining the callbacks, you were passing in the correct order, I've removed that code mention from my previous comment.

**Comment by janexip** [comment]
Much thanks! It's working for me now. I can share my flag.js. Where should I put it?
Making flag calls looks like this for me:

var is_flagged = {
             "flag_name" : 'blah',
             "entity_id" : 123
              "uid" : 1,
        };
drupalgap.services.flag.is_flagged.call({
            'data':is_flagged,
            'success':function(data) {
                alert(JSON.stringify(data, null, 4));
            },
 });

There's also flag/unflag action and countall.

**Comment by signalpoint** [comment]
@dontmcyn - Nicely done. I'd recommend making a Fork of @amitsedai repo (https://github.com/amitsedai/flag) and then submit a pull request with your flag.js changes. Once they are merged into that repo, then it'll match with the link on the project page: http://www.drupalgap.org/project/flag

@amitsedai - If you're not interested in being the 'master' repo, no worries just let us know, and we can have @dontmcyn host it, thanks!

**Comment by amitsedai** [comment]
I had found a workaround , hence didn't invest in working on this module. Apologies. 
@dontmcyn - Please feel free to create a new repo or merge with mine. Thanks.

**Comment by janexip** [comment]
Thanks @signalpoint  and @amitsedai ! I created a new repo because it's easier for me. 
It's here: https://github.com/dontmcyn/flag
Please let me know if you see any problem with it. Thanks again for guiding me through this.

**Comment by signalpoint** [comment]
@amitsedai - thank you for the follow up. P.S. I've had a few people comment on how nice your App looks on the DrupalGap App's page.

@dontmcyn - Nicely done. What is your www.drupalgap.org user name? I'll update the project page to be attached to your repo.

**Comment by janexip** [comment]
Sorry for the late reply. My user name is dontmcyn. It is currently pending approval.

**Comment by signalpoint** [comment]
@dontmcyn  - I've updated the node ownership to you.

**Comment by signalpoint** [comment]
Flag support has been added, use this contrib module:

http://drupalgap.org/project/flag
