### ISSUE TITLE
CCK Text Field Not getting saved at server

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#141]
There is a content type called status, which has a text field called: field_status_message for any user message. However, the entered data does not get reflected in the server. However the content gets saved on body field.

I enabled debug feature of services and I could see no data for field_status_message being sent to the server.

Am I missing something?

Also, is it possible to add additional parameter while calling node/add/status like Message, Video, Link etc (Ex: node/add/status/Message or node/add/status/?type=Message). I could see that the call path becomes node_add_status after being rendered by drupalgap.
Thanks.

**Comment by signalpoint** [comment]
This is a bug, thanks for reporting it. Currently, when the entity '?data=' string is assembled (e.g. drupalgap_node_assemble_data(), etc - https://github.com/signalpoint/DrupalGap/tree/7.x-1.x-alpha/modules/services) it doesn't take into account any custom fields on the entity type. The drupalgap_node_assemble_data() function (and others related to it, comment, user, taxonomy, etc) needs to take into consideration custom fields values available in the form state. The fields for an entity can dynamically be retrieved with drupalgap_field_info_instances(). Then it would be a matter of iterating over each field in that entity type, and then check the form_state['values']['my_field_name'] to see if any data needs to be appended to the ?data= string.

**Comment by amitsedai** [comment]
Thanks. I added the field in the following format and it worked:

if (options.node.field_status_message) {
        data += '&node[field_status_message][' + drupalgap.settings.language + '][0][value]=' +
          encodeURIComponent(options.node.field_status_message[drupalgap.settings.language][0].value);
}

I could see that from options we can get the type of content. Is there a method available that can provide the list of fields present in a content type? Based on the fields list, it should be easier to provide data to the fields before node creation.

**Comment by signalpoint** [comment]
A call to drupalgap_field_info_instances('node', node.type) will get you a list of fields dynamically. Then if you iterate over them and attach and encode those field values to 'data' that should be huge progress for that function.

**Comment by amitsedai** [comment]
Thanks. I was able to so. I implemented drupalgap_field_info_instance under node.js as follows. 

var node_fields_list = drupalgap_field_info_instances('node', options.node.type);
var node_fields = Object.keys(node_fields_list);
//console.log(node_fields);
$(node_fields).each(function(index,field_name){  
  if(field_name in options.node){
    var field_data = eval("options.node."+field_name+"['"+drupalgap.settings.language+"'][0].value");
    if(field_data){  
      data += '&node['+field_name+'][' + drupalgap.settings.language + '][0][value]=' +
          encodeURIComponent(field_data);
    }
  }

});

It worked for me. Thanks again!

**Comment by signalpoint** [comment]
@amitsedai - awesome! Great work. Will you please submit a pull request for this? Then your account will be attributed to the contribution ;)

**Comment by amitsedai** [comment]
Thank you. Just submitted a pull request. I am new to git at-least in just what I did :)

**Comment by signalpoint** [comment]
@amitsedai - What I would recommend is to go to https://github.com/signalpoint/DrupalGap and click the 'Fork' button. After that you'll have a page like this https://github.com/amitsedai/DrupalGap , this new page will have a new 'git clone' url to use.

Clone your forked copy of DrupalGap into your development environment, then bring in the custom code you were working on. After that, you can commit the code to your forked copy of DrupalGap, then push it up to git hub.

From there, you can then submit a Pull Request on github from your forked copy and send it here (I'm pretty sure you can attach the pull request directly to this issue). Then we'll be able to see your code listed on the 'Files Changed' tab on the DrupalGap issue that is created for the pull request. Then we'll be able to merge in your changes.

**Comment by amitsedai** [comment]
As instructed, I did a fork, applied the change and did a pull request for merge. Please find the link here: https://github.com/signalpoint/DrupalGap/pull/144

Thanks.

**Comment by amitsedai** [comment]
Removed Body field which was repeating twice and made small changes for options_select widget type. https://github.com/amitsedai/DrupalGap/commit/10926db3a120e5b8a63f2cd2b9b6885a64bc8e57

**Comment by amitsedai** [comment]
CCK Values are still being sent with the new change. Here is a commit that fixes:
https://github.com/amitsedai/DrupalGap/commit/9869bfd5c99392718cace4f6fa289057c9a849af

**Comment by signalpoint** [comment]
@amitsedai - thanks! Yeah that was definitely a sloppy bug by me :P
