### ISSUE TITLE
Can argument be passed while calling node/add similar to nodereference url or entity reference prepopulate in DrupalGap

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#142]
Hi,

Thanks for the assistance. I seem to run into issues while developing an app in DrupalGap. There is a content type called status which allows various options like message, image, link available as a select list in the form to be posted. Is it possible to pass link like: node/add/status/Message or node/add/status/?type=Message.

I tried both ways but it didnt work. Is there a way to achieve this in DrupalGap?

Drupal allows setting of the field via node reference url or entity reference prepopulate. Even if I am able to access the argument via the URL should also work for me now.

**Comment by signalpoint** [comment]
@amitsedai - Since the functionality you described is available in Drupal contrib module(s), a corresponding contributed module(s) would need to be developed for DrupalGap. I'd recommend creating a sandbox project on drupalgap.org (use the same machine name as the modules available on drupal.org), then have the module implement DrupalGap's hook_form_alter(), from there the implementation should be able to call arg() to see what's in the URL, then alter the form as necessary setting any default values.

**Comment by amitsedai** [comment]
Thanks. However I am at a loss to figure out how to pass additional argument so during form_alter, the appropriate default value can be set. I can think of ways like creating a custom menu that allows additional argument. At the page write a function to set a variable and call the url without the additional argument. Under form alter set the type as the variable set. drupalgap.js does have a drupalgap global variable whose data many module seem to use and alter.  Do let me know if this process is right.

I failed when I tried providing URL argument,  node/add/status/Image - I get 404 - Not Found Page.
If I place the argument as node/add/status?data=Image, I get template_process_page - Syntax Error for expression: #node_add_status?data=Image.

I wrote a custom module that alters the form and changes the type of some fields to make it editable. But with the options above the node edit form does not open.

I did have a look at template_process_page in theme.inc.js. Somewhere at the end of the function, I guess at the eval function the error gets thrown. I couldn't figure out more.

**Comment by signalpoint** [comment]
@amitsedai - thanks for all of this information. Correct, drupalgap.js does have a global drupalgap variable used hold much information about the environment, and many of the core DrupalGap modules add/edit data to this variable (e.g. drupalgap.settings).

I was worried that ?'s in the URL may collide with the page system. The drupalgap_goto() and drupalgap_goto_prepare_path() functions would need to be improved to extract any extra variables provided by the ? in the url, then set them aside somewhere so developers can use them later, and so the page path will route correctly.

**Comment by amitsedai** [comment]
As a temporary measure. I declared a global variable in mycustom module, say in the format: 
var mycustom = {
    patharg:0,
};

In mycustom module I added a menu as:  node/add/status/% and added a page callback. In the page callback function of the module, I assigned the patharg to the argument(URL argument) and then issued drupalgap_goto('node/add/status'). In the form alter method, I captured the patharg data that was set.

I am not sure if this can work as a standard solution, but it does resolve this issue for now.

**Comment by signalpoint** [comment]
Interesting approach, I'm glad something was feasible given the tools available. I'll mark this as closed for now, if it needs to be re-opened for a global solution, that is ok.

**Comment by amitsedai** [comment]
Got simpler solution available in node.js inside modules folder.
Added menu like this in a custom module:
'node/add/status/%':{
        'title':'Add content',
        'page_callback':'node_add_page_by_type',
        'page_arguments':[2],
      },

Captured arg(3) and that did the job :)
