### ISSUE TITLE
Add a display mode for DG in Drupal

### ISSUE THREAD

**Issue by simonemarin** [signalpoint/DrupalGap#145]
Hi
why not having a specific display mode in Drupal when loading nodes? I am not sure how far we can go about theming hte template but surely there would be the ideal place to give fields an order and deciding the formats.
Simone

**Comment by signalpoint** [comment]
Yup, I agree this would be an awesome feature to have. Right now, DG just inherits from the 'Default' display mode in Drupal. I personally don't have any experience creating a custom display mode for entities, so this will take me some time to figure out

**Comment by simonemarin** [comment]
Actually Drupalgap is rendering the default display mode, not the full content dm, so here we go we have our own dedicated display mode.
cheers

**Comment by simonemarin** [comment]
There is something I don t understand though, looking at /drupalgap/node/NID.json I can see that al fields are extracted form the DB, even those which are hidden. So, how the heck does the application get the order and visibility of the fields?

**Comment by signalpoint** [comment]
Right, DG uses the default display mode when deciding how to display labels/values/weights. The weight (order) visibility is determined by drupalgap_entity_render_content() which uses the 'field info instances' data provided by Drupal (there is data about field weights and visibility rules bundled in this data). The DrupalGap module System Connect resource bundles this info so the app can use it.

**Comment by signalpoint** [comment]
This feature has been added.

http://drupalcode.org/project/drupalgap.git/commit/05c248a

It won't be available until 7.x-1.7-alpha of the mobile app dev kit is out, and until the 7.x-1.5 version of the drupal module is out. If you need it before then, just grab the latest dev copies of both.

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.

**Comment by signalpoint** [comment]
@simonemarin Just a reminder, this was a great idea you had! It really has been one of the best features of DG to date :)

**Comment by simonemarin** [comment]
Hi Tyler,
thank you for the message!

We are currently working on a Service driven app but I am only doing the
server side/Drupal stuff while the app developer is doing his own
implementation but I showed him all the goodness of DG and especially for
the commerce part we may use it, I don t know everythng is still very
green.
He said he is really looking forward to the Angular implementation.
I  hope we can contribute something back in the future.
Simone
