### ISSUE TITLE
Fields on Terms pages

### ISSUE THREAD

**Issue by simonemarin** [signalpoint/DrupalGap#147]
Ciao
since in D7 now terms are fieldable entities, custom fields (ie not just Name and Description) should be loaded just as we do on node_load.
Simone

**Comment by signalpoint** [comment]
@simonemarin - when using the taxonomy_term_load() inside of DG, does your custom field info for the term come back in JSON form?

If not, then it sounds like the Services module needs to report all that info back to us when using the Taxonomy Retrieve resource.

If on the other hand, the Services module does return to us that custom data, then the taxonomy term page in DG would need to be expanded to use drupalgap_entity_render_content(), similar to how the node page view is rendered in DG.

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.
