### ISSUE TITLE
Double firing of events, custom module, mystery solved

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#150]
So, when binding to specific events with jquerymobile, some of the events like pageinit can fire twice. The documentation says/eludes to this at various points. I put all of my event handlers in a custom drupalgap module per Tyler's suggestion. IT worked except many of my "on" handlers would fire twice. A simple fix is to do an "off" before you "on" ...

``` javascript
$(document).off("panelbeforeopen")
             .on("panelbeforeopen", ".ui-page-active #panel", function(e) {
```

this makes sure things only fire once. Just posting here in case it helps somebody else.

**Comment by signalpoint** [comment]
@cschaub - thanks for this information. I wonder if its functionality could be incorporated into drupalgap_jqm_page_event_fire() to improve the prevention of double event firings.

**Comment by chrisschaub** [comment]
Well, any handlers within the the events should be coded as off/on. I think
the double firing is really a jquerymobile thing/bug. If I code my events
in a events.js fine and include it in index.html then the events fire only
once. But if the events are included by another include, it double fires
without the off/on.

On Mon, Aug 26, 2013 at 11:00 AM, Tyler Frankenstein <
notifications@github.com> wrote:

> @cschaub https://github.com/cschaub - thanks for this information. I
> wonder if its functionality could be incorporated into
> drupalgap_jqm_page_event_fire() to improve the prevention of double event
> firings.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/150#issuecomment-23273819
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.
