### ISSUE TITLE
drupalgap_item_list_populate error

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#153]
I have seen the previous errors on this, but this is the latest version of DrupalGap I upgraded to this morning and errors are slightly different.
DrupalGap Version: 7.x-1.6-alpha
I did try 

Issue:
Error - When I try to edit and save a page, it displays
drupalgap_item_list_populate - Error: cannot call methods on listview prior to initialization; attempted to call method 'destroy'
Node gets updated on server

However, when I try creating a new node, the node does not get created and I get a blank page with a header which has Node mentioned. However, one of the content type gets created but fails for others. I have removed any kind of form_alter so that these do not get messed up. The permission for user for creating and updating the content type are provided.

I looked at the services log, I found some error: Notice: Undefined index: nid in _node_resource_create() (line 312 ...services/resources/node_resource.inc) during node creation.

I am not sure if this is a drupalgap or services related bug. A similar issue: https://drupal.org/node/2053761

Thanks.

**Comment by signalpoint** [comment]
@amitsedai - thanks for reporting this. The error listed below is definitely DG related:

```
Error: cannot call methods on listview prior to initialization; attempted to call method 'destroy'
```

I'm pretty sure it has to do with the 'comment list' that is trying to be rendered on the node. It also most likely has to do with trying to reload/transition/rebuild the same page we're already on.

As for the error thrown by the Services module, I haven't seen that one before. It seems odd that a missing nid would be happening in the node create resource.

**Comment by amitsedai** [comment]
Right. It happens consistently when trying to create for few content types. And yes it seems to be linked with comments list.

The content type which gets saved, I get a alert
_drupalgap_form_submit -
TypeError: Result of expression 'fn' [undefined] is not an object
This gets saved though.

The content types that do not get saved have only text fields, ironically. However the one gets saved has computed fields, and select list which are manipulated as text fields at drupalgap.

Thanks.

**Comment by signalpoint** [comment]
Perhaps if we give a unique id to the node comment list element (e.g. place the node id in the list element id, so instead of using the 'comment_listing_items' as the jqm_item_list id, use something like node_123_comment_listing_items), this may help the issue.

**Comment by amitsedai** [comment]
For the issue of some content types not getting saved at the server end was due to a module called: Node buttons edit [https://drupal.org/project/node_buttons_edit]

Once disabled, the nodes got created :)

**Comment by amitsedai** [comment]
I have seen the drupalgap_item_list_populate error error message  displayed for even one message present in the node

**Comment by signalpoint** [comment]
Since the advent and usage of jDrupal, I believe these issues have been sorted out with how the creation/editing of nodes is accomplished. This should no longer be an issue.
