### ISSUE TITLE
Entity reference field not rendered

### ISSUE THREAD

**Issue by simonemarin** [signalpoint/DrupalGap#155]
Hi
entity rederence fields are not rendered, json excerpt : 

```
"field_entity_reference": {

    "und": [
        {
            "target_id": "6"
        }
    ]

},
```

**Comment by signalpoint** [comment]
We will need a DG contrib called entityreference for this. It will need to implement hook_field_formatter_view() at a minimum. As you pointed out above, the JSON returned by a node retrieve resource is minimal (i.e. it only contains the entity id). So we may need a corresponding 'drupalgap_entityreference' module on the Drupal side that overrides the default Services node retrieve resource and replaces any entity reference fields with more info about the referenced entity. Alternatively, the entityreference for the App would need to be smart enough to fetch the referenced entity (but this would require an additional call to the server).

**Comment by signalpoint** [comment]
Use this contrib module for Entity Reference support:

http://drupalgap.org/project/entityreference
