### ISSUE TITLE
Image Upload doesnt seem to work

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#157]
I tried attaching an image via the device but it almost never works. In the form, the image button appears but with 'undefined' mentioned. Is that a problem?

Using the camera, I captured a photo and a success alert popped up. But when I clicked on node save, the image didnt upload. The services for file are all enabled. Am I missing something?

The device is Android 2.2

Thanks.

**Comment by amitsedai** [comment]
Apologies for my constant requests on places where I fail. I am new to Mobile Apps as well as Javascripting. I have been able to make some progress.

I modified the success function as follows:

html += 'function ' + imagefield_success + '(message) {'
            + 'alert('success!'); ' 
            + 'var image = $("#' + drupalgap_get_page_id(drupalgap_path_get()) + '"); '
            + 'image.style.display = \'block\'; '
            + 'image.src = "data:image/jpeg;base64," + message; '
            +'}';

However, I am not able to get the value part in the form state during submit or even in the data URL at the node.js in the node.js file under services module.

How can I pass it as a value to the server from the form? Or is there any other way.

Thanks.

**Comment by signalpoint** [comment]
@amitsedai - The 'undefined' appearing on the button was a bug. I just fixed that a day or two ago, pull the latest copy for that fix.

I now see that the image upload feature was never really fully implemented, I have a project that needs that right now so I'll be working on it a bit. Your code is on the right path, we just need to first call the file create resource to get the file id, then we can attach that to the field_image when creating/updating a node.

**Comment by amitsedai** [comment]
I did some additional ajax processing looking at: http://tylerfrankenstein.com/code/drupal-services-file-create-example-json-and-jquery and drupalgap.js drupalgap_check_connection function for sending options parameter.

Please find them below. It does post the image to server :)

```
    html += 'function ' + imagefield_success + '(message) {'
                + 'alert("Image Captured Successfully. Uploading Image Now"); ' 
                + ' var file = { '
                    + ' "file": message ,'
                    + ' "filename":"my_image5.jpg", '
                    + ' "mimeType":"image/jpeg", '
                    + ' "filepath":"public://my_image5.jpg", '
                + ' }; '            
                + ' var options = { '
                    +  '"success":function(result){ '
                    +  'alert("Image Successfully Uploaded: "); ' 
                    + ' console.log(JSON.stringify(result));'
                    + ' var image = $("#' + element_id + '"); '
                    + ' image.src = result.fid; '
                    + ' image.innerHTML = "Image Uploaded"; '
                    + '}, '
                    + ' "error":function(jqXHR, textStatus, errorThrown) {'
                        +  'alert("Error Thrown: "+errorThrown+" Text Status: "+textStatus); ' 
                    + ' } '
                + '};'
                + 'options.file = file;'
                + ' drupalgap.services.file.create.call(options); '
        +'}';
```

There is just 2  problems I am facing. 
- I am not able to modify the form image field and set the fid' here [ var image = $("#' + element_id + '"); '] 
- How to capture the file name of the image from the camera / phone.

Thanks.

**Comment by amitsedai** [comment]
The process of putting single quotes for adding a script seems tedious. I believe a function that returns the output should be easier to code.

**Comment by amitsedai** [comment]
Great. Thanks :+1:

**Comment by signalpoint** [comment]
@amitsedai - thanks for the code. I've built upon it and expanded it to properly set the form state values and data string assembly. Nodes are now created with image fields attached! :)

Right now, the file name is just generated as the UTC time. This can be a separate issue if it needs attention.

**Comment by amitsedai** [comment]
@signalpoint - Thank You. The image renders after upload in the edit form. And the image get displayed during node render. That's awesome :)

However, as an improvement the image renders bigger for the portrait mode of the mobile device. In the landscape mode the image adjusts itself. Adjustment for the portrait mode can be included.

Thanks again.

**Comment by amitsedai** [comment]
Node images were already displayed previously. Apologies for the excitement. The user profile pics at the My Account Pages however are not rendered.

**Comment by signalpoint** [comment]
@amitsedai - I saw the same problem with the portrait vs. landscape mode, but I didn't feel compelled to fix it at the time. Please feel free to make a new issue # for that problem.

The profile picture implementation will need to be updated to use this new image field set up (if the profile picture is even considered an image field, I'm not sure if it still is its own 'thing' like it has been for so long). We'll need a separate issue # for that as well.

**Comment by nevkatz** [comment]
Quick question related to this: should I need a custom services module to upload a file from my DrupalGap app using an ajax call? I am not sure how to set up a Drupalgap services endpoint for a file upload. My main goal is for the app to upload a JSON file with user data to the site.

**Comment by signalpoint** [comment]
> Quick question related to this: should I need a custom services module to upload a file from my DrupalGap app using an ajax call?

@nevkatz No, you can use the File resource included with the Services module.

**Comment by nevkatz** [comment]
Thank you! I am trying to upload a JSON file using an ajax call to services, and after about 7 hours I am stumped.  I have tried creating my own service endpoint but I get the "missing controller" message and with the drupalgap service I am getting "missing data the file upload cannot be completed" — even though I have included the filename in both the request and the data. 

I gather that anon users may not be able to post, but I am not sure what is needed to "log in" to the drupal site — or whether it is easier to add nodes than files. I was thinking that I  may need several ajax calls: one for grab the token, one for the connect.json step, one for logging in, and finally, one for uploading the file.  Any insight on what to try would be terrific.

**Comment by signalpoint** [comment]
@nevkatz jDrupal (and DrupalGap) take care of all your token, login, logout needs, so that shouldn't matter. The file create resource uses base64 encoded strings, and is derived from this example: http://tylerfrankenstein.com/code/drupal-services-file-create-example-json-and-jquery

There is a file create raw resource can be used with this example provided by @luxio here: https://gist.github.com/signalpoint/8a0dc14c9553552a046a97abe9f2e48c

I haven't had a chance to use it yet, but he has successfully used it in the past.

Both resources are provided by the Services module, so it's very unlikely you need to create your own.

**Comment by nevkatz** [comment]
Thanks Tyler! I so appreciate the quick response. I have been following that example and have integrated the new piece on tokens. I am checking with our network admin on whether file permissions on our drupalgap site might be the problem. I am using a new services endpoint with services authentication (not OAuth) and have checked all the "resource" boxes to make sure I'm not missing anything. I am trying uploading files after manually logging in with the app, which seems like it should be sufficient based on what you tell me.

 I've been using the FF poster though the tokens run out pretty quick and the connect.json step doesn't work yet - so potentially a problem with site config. I'm going to work with the poster a bit more and will also try node upload to see if it works any better. I'll also check out @luxio's resource. 

I originally thought base64 was just for images, but now it seems like good practice for encoding other file types as well like application/json, correct? 

This is for an app with learning games wherein each learning activity is a node. The goal is for it to upload data on users - for each activity node, how long it has taken them to complete an activity, how many tries, etc. - and make that data visualizable for site admins. For me, uploading JSON data seems to make the most sense, though creating nodes with data in them might work better (or at least potentially sidestep any file permissions issues in my site directory and open the door for using views.) 

Except for data upload, everything so far (offline support, SD card storage and retrieval, etc.) seems to be working. The data upload looks like the last major step in determining whether this will work for us. Any additional thoughts on what to try are more than welcome.
