### ISSUE TITLE
Clicking Logout generates Error Message

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#158]
This issue comes up very consistently. On clicking the logout button an alert is flashed multiple times.
drupalgap_user_has_role- TypeError: Result of expression 'e' [undefined] is not an object,

**Comment by amitsedai** [comment]
The custom blocks,in my case menus present at settings.js which had deny for anonymous user is displayed even after logout.

The content fragments in the front page made visible only to authenticated users is not shown(Works fine)

**Comment by amitsedai** [comment]
The error message is not getting displayed now. Thanks.

**Comment by signalpoint** [comment]
Thanks, I think this was related to #163

**Comment by amitsedai** [comment]
The error message appears now after logout. I am not sure why it didn't come then.

**Comment by signalpoint** [comment]
Related issue #169

**Comment by signalpoint** [comment]
Fixed by #183.
