### ISSUE TITLE
Add datetime support

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#159]
We need support for datetime fields.

**Comment by signalpoint** [comment]
Postponing this issue until #178 is resolved.

**Comment by rich-dawson** [comment]
I believe that this has been resolved as I am using the <a href="https://github.com/signalpoint/date">datetime sandbox module</a> and it seems to be working just fine.

**Comment by signalpoint** [comment]
Yup, the date sandbox module works for when the "Field Type" is set to "Date" and the "Widget" is set to "Select list", e.g.

```
admin/structure/types/manage/article/fields
```

It most likely will not work for other date field types and/or widgets.

We'll close this for now, re-open if need be.

**Comment by virendra007** [comment]
hi,

I am new in drupal gap.
I have placed the date module in www/app/modules but how to enable it and how it will work for date popup, 
For ex: for text field i used such code and working fine

```
form.elements.name = {
            'title':'Name',
            'type':'textfield',
            'required':true,
            'display':'horizontal',
            options:{
                attributes:{
                    'data-theme':'a'
                }
            }
        };
```

But For date popup i used

```
form.elements.name = {
            'title':'Name',
            'type':'date',
            'required':true,
            'display':'horizontal',
            options:{
                attributes:{
                    'data-theme':'a'
                }
            }
        }; 
```

Its not working , please help me out.

Thanks in advance

**Comment by signalpoint** [comment]
@virendra007 

Enabling modules: http://drupalgap.org/node/74

Date popup isn't supported (yet). The date module for DrupalGap needs to be expanded to support date pop ups:

http://www.drupalgap.org/project/date

**Comment by virendra007** [comment]
Hi,

I have upload the date module in www/app/moduls and mentioned it in settings.js, so its directly enabled or need to do some more setting for enabling like Drupal , if yes then please describe

**Comment by signalpoint** [comment]
@virendra007 Once you declare it in settings.js, it will be enabled, no other action is required.

**Comment by virendra007** [comment]
hi

I have done as u replied but when i declare date its not populating
calender ....please help me out, (as u mentioned that date module need to
put in modules and mentioned in settings.js)

On Fri, May 30, 2014 at 6:46 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> @virendra007 https://github.com/virendra007 Once you declare it in
> settings.js, it will be enabled, no other action is required.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/159#issuecomment-44649105
> .

## 

_Thanks,Virendra Soni_

**Comment by signalpoint** [comment]
@virendra007 The calendar (date popup) isn't supported. Someone (maybe you) needs to expand upon the date module to add calendar support.

Plus, it looks like you are trying to declare your own custom date field on a form, I don't think that will work at all. This module is meant to add support for date fields on your content type(s).

**Comment by virendra007** [comment]
Ok..got it now I will work on date module so other can't get such prob..

**Comment by signalpoint** [comment]
@virendra007 Sounds good. I would recommend making a "fork" of the date module, and working on your forked version, then you can issue a "pull request" to get your changes pushed back into the main repo. Good luck, and happy coding!

**Comment by soketes** [comment]
Hi!
I have a problem, field dates display always the now time, not the real date and when I edit a node (node type different [transports]) the field is empty...
