### ISSUE TITLE
undefined error getting user permissions

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#16]
When my app first loads, I get an undefined error, traced back to the line in ./DrupalGap/modules/services/services.js that tries to get the permissions

if (options.service == 'drupalgap_system' && options.resource == 'connect') {
     permissions = options.data.user_roles_and_permissions;  
}

options.data.user_roles_and_permissions is undefined. I am testing as an anonymous user.

**Comment by signalpoint** [comment]
If you change the line inside the boolean to this, you should be all set:

permissions = options.data.user_permissions;

Once the next recommended version module (7.x-1.3) is released, this will be fixed for this branch.
