### ISSUE TITLE
Force Authentication Module Shows Error during Login

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#161]
I am not sure if this is the place for posting issues with contrib modules.

In the user login page after providing the login user name and password, it is not redirected to front page.

On clicking the Login button again, an error pops up:
error: (Not Acceptable: Already logged in as username.)["Already logged in as username."][undefined]

Also, the front page of the app can be shown for anonymous users. Based on whether a previous page has been set or not, redirecting anonymous users to login page can be worked upon.

What about reloading the front page and providing that to anonymous users instead of login?

Thanks.

**Comment by signalpoint** [comment]
Thanks for reporting this, the correct place would be to report it on the contrib module's github issue queue located here:

https://github.com/signalpoint/force_authentication/issues/1

I've migrated your issue over to there, thanks!
