### ISSUE TITLE
Form Alter Changed: form_id returns an object instead of Form ID

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#162]
function custom_form_alter(form, form_state, form_id) { 
alert(JSON.stringify(form_id));
}

The form_id now returns an object.

**Comment by khayong** [comment]
It seem like it has problem to handle multiple hook_form_alter(). Once I commented out function image_form_alter() (which added recently), my custom hook implementation get the correct form_id.

**Comment by khayong** [comment]
Commited the fix. https://github.com/khayong/DrupalGap/commit/e68ccc3484cea07ba55c7703b1d0785d4c0c0eef

**Comment by amitsedai** [comment]
After applying the commit changes, I get an error when I try to log in:
module_invoke - TypeError: Result of expression 'form.elements.type' [undefined] is not an object

**Comment by khayong** [comment]
I couldn't simulate the error, the login at my side is fine.

**Comment by amitsedai** [comment]
@khayong: I tried once again seeing your comments. The error comes consistently during login. Once logged in , however other forms work fine.

Even after removing the custom form alter, still the issue persists for me.

**Comment by signalpoint** [comment]
@amitsedai - I am not able to reproduce this error either. After pulling in the fix from @khayong , user login still works fine for me as well.

**Comment by amitsedai** [comment]
Please close this issue. The error popup was due to my custom code fault. Thanks.
