### ISSUE TITLE
User Picture does not display in the user account page

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#165]

**Comment by amitsedai** [comment]
This commit fixed the issue:
https://github.com/amitsedai/DrupalGap/commit/e0d7c25a6e96a269504ab0faadf51d9ae2b9a030

Changes of rendering of the image from a local copy to remote image URL

**Comment by signalpoint** [comment]
@amitsedai - please see this comment (https://github.com/signalpoint/DrupalGap/pull/166#issuecomment-23626014) for info on how we can get this fix into the alpha branch, thanks! I can add the one line manually for you, but I'd like you to get credit for it via a pull request! :)

**Comment by amitsedai** [comment]
Please find the new commit here: https://github.com/amitsedai/DrupalGap/commit/07f56be0e25f4141d868387ba2b8e897205f3ded

I have updated the pull request.

Thanks.

**Comment by signalpoint** [comment]
@amitsedai - thank you for the fix, profile pictures are back!
