### ISSUE TITLE
Node Edit Option appears for nodes for which Edit permission is not provided

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#172]

**Comment by signalpoint** [comment]
@amitsedai - will you please describe your site's permissions set up for node editing. Right now, DG uses the node_access() function to determine wether or not the user can edit the node, and it currently only checks to see if the user is the author of the node. It needs to be expanded to check user_access() for permissions like 'edit own <content-type>' and 'edit all <content-type'.

**Comment by amitsedai** [comment]
Its a basic permission set which allows a user to create but not to edit or delete. When I try to edit and save, it throws an alert.
 error(Unauthorized: Access denied for user [username])

 The delete option also shows during edit.

**Comment by signalpoint** [comment]
@amitsedai - thanks for clarifying. This should be a pretty easy fix, the node_access() function will just need to ask user_access() if the current user has the 'edit own' or 'edit all' permission for the current content type, then this should be fixed.

**Comment by amitsedai** [comment]
This commit resolves the issue: https://github.com/amitsedai/DrupalGap/commit/d0015a5f8b77dab0c3971c2a1872bdd22c3800e3

Providing additional parameter for node_access for specifying view, edit or delete will be helpful for checking if delete button needs to be displayed in the node edit form. This is reduce duplicate code for additional checks.

**Comment by signalpoint** [comment]
Fixed via #173.
