### ISSUE TITLE
Capturing image by camera throws error

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#175]
While capturing image, error message is thrown at the console:
drupalgap_error() - _image_phonegap_camera_getPicture_success - TypeError: Result of expression 'image_phonegap_camera_options[options.field_name]' [undefined] is not an object.

**Comment by amitsedai** [comment]
The commit fixes the issue: https://github.com/amitsedai/DrupalGap/commit/fef60c4236bb1068471f62b34c27f724db9f2ff8

**Comment by signalpoint** [comment]
Fixed via #173.
