### ISSUE TITLE
Displaying block only for user page does not seem to work

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#176]
I wanted to add additional information for display in the user account page. I tried using block for displaying data in user page but somehow the pages option in the block config did not work.

Example block that was placed in the content region in settings.js file:
'custom_block_check':{
    'pages':{
        'value':['user'],
        'mode':'include',
    },
},

Other options for pages I tried: 
'user/%/view'
'user/'+drupalgap.user.uid+'/view'

Am I missing something?

**Comment by signalpoint** [comment]
@amitsedai - good catch. You're not missing anything. The drupalgap_check_visibility() function needs to be expanded to understand wildcards. For example,

```
user/*
```

Please keep in mind the 'user' page is a special page, in that if the user is anonymous, we redirect them to 'user/login', and if they are authenticated, we redirect them to 'user/[uid]'.

**Comment by signalpoint** [comment]
@amitsedai - the latest snapshot of 7.x-1.x-alpha contains the fix to allow wildcards on block visibility rules in settings.js:
`
my_custom_block: {
  pages: ['user/*'],
  mode: 'include'
}
`
I've updated the documentation to include an example of this new feature:

http://drupalgap.org/node/168

Update to the latest version of 7.x-1.x-alpha for this bug fix. Alternatively, it will be available in the 7.x-1.8-alpha release (or the 7.x-1.x-rc1 release) when it is ready.
