### ISSUE TITLE
Android Back Button on App Front Page Goes to Blank Page

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#177]
When I hit back (on an Android device) and I'm already at the first page, no history, it just takes me to a black screen. I'm assuming this might be the first "blank" page that jquery mobile adds? Doesn't happen on IOS, just Android.

**Comment by signalpoint** [comment]
@cschaub - good catch. I've seen this one before. This is a bug with the drupalgap_back() function. It needs to be expanded to be smart enough to not move back if there is no where to go.

**Comment by chrisschaub** [comment]
How about a simple

``` javascript
/**
 * Change the page to the previous page.
 */
function drupalgap_back() {
  try {
    if (history.length > 0) {
      drupalgap.back = true;
      history.back();
      drupalgap_path_set(drupalgap.back_path);
      return false;
    }
  }
  catch (error) {
    alert('drupalgap_back' + error);
  }
}
```

**Comment by signalpoint** [comment]
@cschaub - thanks for the lead on this. Unfortunately history.length was reporting a value of 2 for me (that seems weird), so I didn't want to rely on the history length value. Then it occurred to me to just check to see if we're on the front page, and if we are, don't go back. Fixed, thanks!
