### ISSUE TITLE
Comment  form does not reload after submission

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#180]
On submitting a comment, it gets posted to the server but the page does not get reloaded and the comment form with posted data still remains.

In the entity.js file under drupalgap_entity_form_submit a drupal_goto is made for the destination

drupalgap_goto(destination, {'form_submission':true}); 

The destination is the same as the page where the node is submitted. I tried appending reloadPage:true but didnt work.

**Comment by signalpoint** [comment]
@amitsedai - there is a bug somewhere in drupalgap_goto() and/or drupalgap_goto_generate_page_and_go() in deciding how to "rebuild" the page when a form is being submitted and the destination is the same page.

Things get strange in jQM when trying to remove/rebuild the page you are already on. From my understanding, jQM can't transition to the 'next' page if the current page gets removed from the DOM, even if the 'next' page is the same page we're on.

Maybe just the 'content' area could be rebuilt. It's important to note that if local storage caching is enabled in settings.js, we'll have to watch out for a cached node/comments being loaded again.

**Comment by amitsedai** [comment]
I guess a simpler solution would be to keep the comment form on a different page than node. An add comment link can appear at  the node page before the list of comments below which would redirect to a new comment form page.

**Comment by signalpoint** [comment]
@amitsedai - Agreed. Ultimately though, it would be best if DG understood the comment settings applied to the content type. For example, there is

disabled
show comment form on node (above or below comment listing)
show comment form on separate page
etc

Check your content type 'edit' screen for all the options. Those options should be bundled somewhere in the data that is returned to DG via the DG system connect... I'm not sure exactly where it is though.

**Comment by signalpoint** [comment]
The comment form now upon submission inserts the new comment directly into the DOM, then clears out the form.
