### ISSUE TITLE
Image Uploaded does not get saved in the server

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#182]
The image added through Add Image displays the image in the form but it does not get submitted to the server.

The drupalgap_node_assemble_data does not display the image field during submit.

**Comment by signalpoint** [comment]
@amitsedai - With the latest 7.x-1.x-alpha branch, I was able to post an image to an Article node last night without issue. Please try pulling in the latest changes. If that doesn't work, please let me know further details, thanks!

**Comment by amitsedai** [comment]
Thanks. I did a pull request and got updates. However even with the changes I was not able to post the image to the server.

The image appears in the form after image clicked is saved but does not get posted to the server. I have a form alter present for the node I am trying to post.

**Comment by amitsedai** [comment]
Yup. The image got successfully posted in a node that had no form alter for validate. The node for which validate was present does not submit the image.

**Comment by signalpoint** [comment]
@amitsedai - so when you attach a custom form validation handler to the node_edit form via hook_form_alter(), the image doesn't get submitted properly? If not, what form is this happening on?

Please note, image_form_alter() inserts a custom validation handler (_image_field_form_validate()) on the front of the form's validate array. This custom validation handler, calls the file create resource and then sets the new image id onto the field in the form state values.

**Comment by amitsedai** [comment]
It mostly looks like multiple image submit option was provided at the server. Once that was set to one, it worked. Thanks.

**Comment by signalpoint** [comment]
@amitsedai - ok, thanks. This sounds related to #178 , once that one is finished up, we'll be able to use multi-value fields.

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.
