### ISSUE TITLE
Menu Cache?

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#186]
So, I have my anon/auth menu in system.js. Is there a good way to have them be dynamic? I sometimes have to changes the paths a bit based on context. Any way to clear the menu manually?

Thanks.

**Comment by signalpoint** [comment]
You should be able to use the reloadPage option on your link in settings.js, e.g.:

```
drupalgap.settings.menus['user_menu_anonymous'] = {
  links:[
    {title:'My Link','path':'my_path',options:{reloadPage:true}}
  ]
};
```

That'll force the page (and its menus) to be rebuilt, I think. Please let me know if that works or not.

**Comment by signalpoint** [comment]
More info: http://drupalgap.org/node/134

**Comment by chrisschaub** [comment]
I think the issue is that I'm trying to make a dynamic path. I'm appending
a variable to the end of a path that changes as the user doest things in
the app. It seems like the menu links don't change once they are set.

On Tue, Oct 15, 2013 at 5:41 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> More info: http://drupalgap.org/node/134
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/186#issuecomment-26379016
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
I just made it a block instead, used within a panel. Blocks don't seem to be cached in the same way.
