### ISSUE TITLE
Clear history

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#189]
Is there a way to clear the browsing history so the back button doesn't work. We have a page in our app that we want to be a "start over" page, clear the slate.

**Comment by signalpoint** [comment]
@cschaub - not that I know of.

I would use Visiblity Rules on the 'back button region link' to hide the back button on a certain page(s).

http://drupalgap.org/node/173
http://drupalgap.org/node/168

I'm not sure about overriding the hardware back button though. drupalgap_back() may need extra logic/parameters if someone wants to prevent the back from happening.

**Comment by signalpoint** [comment]
@cschaub There is this function available now:

http://api.drupalgap.org/global.html#drupalgap_remove_pages_from_dom

That will remove all the pages from the DOM, except the current page.

Then you could probably use jQuery hide() on the back button.

Is this still an issue for you?
