### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by uniquename** [signalpoint/DrupalGap#19]
I'm still wondering about the version numbers. 

As you pointed out here https://github.com/signalpoint/DrupalGap/issues/16, there is a "bug" in the app, which would be solved once the drupal modul is in next version.

So I think, it would be necessary to represent the modul version in the app versioning.

**Comment by signalpoint** [comment]
Thanks for the suggestion. Once we get closer to a solid "1.0" idea I will revisit this and add ideas/suggestions here as well. Thanks!

**Comment by signalpoint** [comment]
We're now using more appropriate version numbers, e.g. 1.x which match between module and mobile application development kit.
