### ISSUE TITLE
Duplicate CSS IDs in Taxonomy listings

### ISSUE THREAD

**Issue by paulmarschik** [signalpoint/DrupalGap#190]
We're using within our project some taxonomy listings for navigation through the the articles.

First call of a page with a list of a specific taxonomy vocabulary was always correct. But after some navigation through the pages, the lists are randomly mixed up.

After some debugging i've found the problem. The function taxonomy_vocabulary_pageshow(vid) in modules/taxonomy/taxonomy.js, line 296 always using the same CSS-Id for the generated lists. This results in duplicate CSS-Ids in the DOM.

The problem can be fixed by adding the vid to the CSS-Id in modules/taxonomy/taxonomy.js, line 341:

  drupalgap_item_list_populate("#taxonomy_term_listing_items", items);

==>

  drupalgap_item_list_populate("#taxonomy_term_listing_items_" + vid, items);

and modules/taxonomy/taxonomy.js, line 306:

  attributes:{
    id:"taxonomy_term_listing_items"
  }

==>

  attributes:{
    id:"taxonomy_term_listing_items_" + vid
  }

Maybe similar problems occures with taxonomy terms (modules/taxonomy/taxonomy.js, lines 211, 246).

**Comment by signalpoint** [comment]
@paulmarschik - thanks Paul. I've added this fix. In the future, if you'd like, please make a fork of DrupalGap, then submit a Pull Request with your code fix(es) and your GitHub user account will be attributed as the contributor. Thanks!
