### ISSUE TITLE
drupalgap_error() - entity_load - No success callback function was provided to node_load() by caller

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#191]
This bug happens when anonymous users try to view a node. The node/%/edit local task has a node_access() for its access_callback function. node_access() hasn't been updated to use async entity loading, and that is why this bug exists.

**Comment by signalpoint** [comment]
To get around this, open app/settings.js and comment out (or delete) the "primary_local_tasks" block from your theme's region. For example, in app/settings.js

```
/**
 * Blocks
 */
drupalgap.settings.blocks.my_theme = {
  /* ... other regions ... */
  sub_navigation:{
    /* ... other blocks ... */
    primary_local_tasks:{}, /* comment out, or delete this line */
    /* ... other blocks ... */
  },
  /* ... other regions ... */
};
```

This will allow anonymous users to view a node, but it will take away local task menu links (e.g. the node edit button for node authors).

**Comment by JrEv** [comment]
I received this error when viewing a node from a JSON Drupal view.

When I accessed my view and click on an item from my list, I get it.

First box says, sorry, there was a problem loading node #76 I click o.k
Next box contains the error "node_access - TypeError: Cannot read property 'uid' of undefined".
I click o.k and the node loads. Then any subsequent requests there is no error on that specific node.

The error does not occur on internal app pages ex. my contact page loads from a module.js

I did as suggested above and it solved my issue and popup error box went away.

**Comment by ice423cube** [comment]
I had a questions.  I tried to leave in the primary_local_tasks block and use roles like the below?  In theory this should fix the problem but it doesn't.  Any thoughts?  Just trying to get the function for both unauthenticated users people and authenticated users.

```
primary_local_tasks:{
      roles:{
        value:['authenticated user'],
        mode:'include',
      }
},
```

**Comment by signalpoint** [comment]
Fixed. You can now leave the `primary_local_tasks` block in your settings.js file.
