### ISSUE TITLE
includes element in drupalgap.modules.custom throws 'failed to load module' error

### ISSUE THREAD

**Issue by aikaterine** [signalpoint/DrupalGap#192]
I am writing custom module that has included files. If I declare the module in settings.js like so:

  {name:'my_module',
    includes:[
      {name:'included_file'},
    ]
  }

the app throws a cannot load module error. If I take out includes, then it loads fine. Any clues?

**Comment by signalpoint** [comment]
That should work. When it throws a cannot load module error, that typically means you have a syntax error in your JS file(s).

**Comment by signalpoint** [comment]
I've confirmed this will work, and have added documentation for it:

http://drupalgap.org/node/186

Again, the cannot load module error most likely means there is a syntax error in a JS file(s) for your module.

**Comment by aikaterine** [comment]
I missed this response. Yes, it did work. Thanks!
