### ISSUE TITLE
Retriving Data from a Drupal View

### ISSUE THREAD

**Issue by JrEv** [signalpoint/DrupalGap#194]
This may be straight forward, but I am missing something fundamental, it may be my skill level. So if anyone want to help, that would be great.

I have a simple app with working menus and pages and is working 100%.
Using one of my buttons, I would like to retrieve data from a view. This is where I'm stumped. I am following examples and presentations from the site.
Before I add the code to retrieve JSON Data.

```
function my_module_JSON_button_page() {
 return {
  my_text:{
   markup:"<p>Hello JSON Button</p>"
  }
 };
}
```

After

```
function my_module_JSON_button_page() {
drupalgap.views_datasource.call ({
 'path':'content/mobile-json-list-view',
 'success':function(data){
  if (data.nodes.length > 0) {
    var items = [];
    $.each(data.nodes, function(index, object){
      var node = object.node;
      $('#my_content_list').append('<div>' + 1(node.title, 'node/' + node.nid) + '</div>');
    });
  }
 },
});
}
```

Has anyone successfully done this? It seems like 
Thanks

**Comment by signalpoint** [comment]
@JrEv - I've updated the documentation to be more clear: http://drupalgap.org/node/82

**Comment by JrEv** [comment]
I got it working, this is great, this community rocks
