### ISSUE TITLE
drupalgap_taxonomy_vocabularies_extract Error

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#196]
When first go to my drupalgap site or logout.  I get the following error.  

drupalgap_error() - 
drupalgap_taxonomy_vocabularies_extract - TypeError: Cannot read property ‘length’ of undefined

I am using ripple not sure if that makes a difference.

Thanks,
Joe

**Comment by signalpoint** [comment]
@ice423cube - To fix this, use the development version of the DrupalGap module on your Drupal site.

https://drupal.org/project/drupalgap

Or you can wait until the 7.x-1.5 version of the module comes out.

There is a new feature added to the DrupalGap module system connect resource that returns to us information about taxonomy structure. That should fix it!

**Comment by ice423cube** [comment]
Wow super fast response.  I upgraded to the dev version and that fixed it.  Thanks so much.  Drupalgap is the best thing in the world.  I love it!
