### ISSUE TITLE
Only Node Title is Displayed

### ISSUE THREAD

**Issue by zawlinoo** [signalpoint/DrupalGap#202]
Only title is print out in node detail view. Other fields are not showing. Can you please check?

**Comment by signalpoint** [comment]
See here: http://drupalgap.org/node/184

Turn off entity caching in the settings.js file, and/or add this to the top of your settings.js file to debug:
`
window.localStorage.clear();
`

**Comment by zawlinoo** [comment]
It went well. Thank you.
