### ISSUE TITLE
Arguments in visibility rules

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#203]
You can't use wildcard pages in visibility rules as the page_id does't match.

**Comment by signalpoint** [comment]
I've taken the second issue mentioned and placed it into its own issue: #204

**Comment by signalpoint** [comment]
@scotthooker I've updated the documentation to include an example of this new feature:

http://drupalgap.org/node/168

Update to the latest version of 7.x-1.x-alpha for this bug fix. Alternatively, it will be available in the 7.x-1.8-alpha release (or the 7.x-1.x-rc1 release) when it is ready.
