### ISSUE TITLE
template_process_page - TypeError

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#205]
template_process_page - TypeError: 'undefined' is not an object (evaluating 'page_html.replace')

**Comment by signalpoint** [comment]
Happens very intermittently, possibly because of a custom module's async operations. Try getting rid of the eval statements if possible and better null/endefined checks.

**Comment by gogog** [comment]
Tyler, 

Getting several 'undefined' type errors: "TypeError: 'undefined' is not an object". Don' know if it relates to the async operations issue.

Installed Platform:
xcode: 5.02
iOS: 7.0
cordova: 3.3.1-0.3.1  
drupalgap drupal: 7.x-1.5 2014-Jan-23
drupalgap git: 7.x-1.x-alpha 2 6 2014 download 
Drupal: 7.26

Basic install on SimpleTestMe: just drupalgap (views, services, views_datasource...)

(1) iPhone Simulator shows drupalgap homepage. 
(2) Created user (in Drupal), added article. Set create/edit/delete privileges in Drupal for Article for authenticated users. 

on ios simulator:
- Able to login into users account on ios simulator.
- Select My Account: - shows user name and date
- No edit privileges:

Errors: 
2014-02-07 08:51:13.089 ExampleApp[15842:70b] user_edit_access - TypeError: 'undefined' is not an object (evaluating 'account.uid')

2014-02-07 08:51:13.571 ExampleApp[15842:70b] entity_load - success - TypeError: 'undefined' is not an object (evaluating 'c.success')

2014-02-07 08:51:13.603 ExampleApp[15842:70b] WARNING: theme_() does not exist

James

**Comment by signalpoint** [comment]
@gogog I believe #191 is partly related to the issue you are describing. Also, just yesterday I committed a fix for the 'edit privileges' on user accounts. Grab the latest snapshot of the mobile app dev kit for that fix: www.drupalgap.org/download

**Comment by signalpoint** [comment]
This issue has been fixed along with #191.
