### ISSUE TITLE
.on() replaces .live() for jQuery 1.9

### ISSUE THREAD

**Issue by lefnire** [signalpoint/DrupalGap#21]
Not urgent, since you're recommending jQM 1.2.0 & jQuery 1.7 which use `.live()`. But heads up if you look into upgrading compatibility, replace `.live()` calls with `.on()`.

If I get to upgrading compatibility myself, I'll submit a PR on a branch with all the necessary changes I can find.

**Comment by signalpoint** [comment]
Thank you for the information. Here's some related information: https://github.com/signalpoint/DrupalGap/issues/7

I shall keep this in mind as we move forward with jQuery and jQM versions. Thank you for offering another PR, we look forward to seeing what you come up with, thanks!

**Comment by signalpoint** [comment]
There are no more calls to live(), hey have all been replaced with on() or bind().
