### ISSUE TITLE
Replace alert() and confirm() calls with PhoneGap's alert functionality

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#212]
Any alerts inside DrupalGap display "index.html" in the header of the alert which looks horrible and isn't reassuring to the user that they are using a quality app.

**Comment by signalpoint** [comment]
@scotthooker This commit (just now - https://github.com/signalpoint/DrupalGap/commit/a7ae9e495cab4b96c3930da44f4b8aa3316aa622) has replaced all alert() calls with drupalgap_alert() calls. drupalgap_alert() utilizes PhoneGap's navigator.notification.alert() function and allows you to pass in an alertCallback, title, and/or button name.

I've updated the documentation with examples:

http://drupalgap.org/node/207

The only thing that is left is to make a drupalgap_confirm() function that uses http://docs.phonegap.com/en/edge/cordova_notification_notification.md.html#notification.confirm.

Then replace any confirm() calls with drupalgap_confirm().

**Comment by scotthooker** [comment]
@signalpoint nicely done. Sorry about all my issues lately just stuff I'm noticing as I'm doing my update

**Comment by signalpoint** [comment]
This is fixed, grab the latest snapshot of the SDK for the fix, or wait until the next recommended release is available.
