### ISSUE TITLE
Block visibility exclude doesn't work

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#215]
Excluding a block by path doesn't work. 

E.g.

I excluded a block to not display on user/login

It still displays.

**Comment by signalpoint** [comment]
@scotthooker This works for me, here's my settings.js syntax:

```
my_custom_block: {
  pages: {
    value: ['user/login'],
    mode: 'exclude'
  }
}
```

Do you also have "roles" visibility rules applied to the block in settings.js ?

**Comment by signalpoint** [comment]
Actually, this appears to be a bug if you have more than one "value".

**Comment by scotthooker** [comment]
Ah ok that's the problem then.
