### ISSUE TITLE
Registration in app Work with Captcha

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#216]
This would prevent bots from creating accounts on the sites and still allow people to register in the app.

Thanks,
Joe

**Comment by signalpoint** [comment]
Use this code snippet in a custom module on your Drupal website:

```
function my_module_form_alter(&$form, &$form_state, $form_id) {
  // Disable captcha on DrupalGap user register form.
  if ($form_id == 'user_register_form') {
    if (arg(0) == 'drupalgap') {
      unset($form['captcha']);
    }
  }
}
```

This will allow captcha on the website, and disable it in the app.

**Comment by ice423cube** [comment]
That is perfect.  Thanks!

**Comment by signalpoint** [comment]
This topic has been expanded upon:

http://drupalgap.org/node/217

Please note, you'll have to use an #after_build (mentioned in the linked article) if your module's weight is great than the weight of the module supplying the form. Better yet, just use an after build handler no matter what, and you won't have to worry about the weight.

**Comment by coolman7** [comment]
Is this compatible with recaptcha 7.x.-2.0 ?

I'm using recaptcha 7.x.-2.0 and I did everything explained in http://drupalgap.org/node/217 but I'm getting "The answer you entered for the  CAPTCHA was not correct" error message.
