### ISSUE TITLE
How to exclude header button in other pages?

### ISSUE THREAD

**Issue by zawlinoo** [signalpoint/DrupalGap#218]
how can I add another page value to exclude in the following code.

```
pages:{
        value:[''],
        mode:"exclude"
 }
```

**Comment by signalpoint** [comment]
Just separate the values by comma.

value:['', 'blah'],

I just fixed a bug with this the other day, so be sure to download the latest development snapshot.

**Comment by zawlinoo** [comment]
I was trying at first but it didn't work. Thanks. Its solved by downloading newer version.
