### ISSUE TITLE
Excluding pages not working in normal menu.

### ISSUE THREAD

**Issue by zawlinoo** [signalpoint/DrupalGap#219]
Is the normal menu can't be exclude from other pages? For example, drupalgap.settings.menus['blah'] inside this setting links can't be hide as we wish. drupalgap.settings.menus.regions['header'] is fine. Am i doing something wrong?

**Comment by signalpoint** [comment]
Each menu (including custom menus) will automatically have a block created to handle its display. If you have a menu 'blah':

`drupalgap.settings.menus['blah'] = { ... }`

Then there is a corresponding block for it automatically created by DrupalGap. However, you need to specify where this block displays in a region on your theme:

`drupalgap.settings.blocks.my_custom_theme.blah = { ... visibility rules go here ... }`

More information available in the Getting Started Guide:

http://drupalgap.org/node/83
http://drupalgap.org/node/85

If there is a bug with this, feel free to re-open the issue.

**Comment by zawlinoo** [comment]
Its work.. Thanks.
