### ISSUE TITLE
Node page overriding

### ISSUE THREAD

**Issue by zawlinoo** [signalpoint/DrupalGap#220]
I want to add some static links in note detail pages. I was copying node.tpl.html to my custom theme folder and did overriding stuffs but i can't see my stuffs.

**Comment by signalpoint** [comment]
This feature hasn't been implemented yet. There is a duplicate issue here:

#18 

Stop by #drupal-drupalgap on IRC if you're interested in implementing this feature, and I can offer some insight.

**Comment by signalpoint** [comment]
@zawlinoo check out this page for a new hook that can be used to override a node's page: http://drupalgap.org/node/520
