### ISSUE TITLE
How to add taxonomy link in page_pageshow().

### ISSUE THREAD

**Issue by zawlinoo** [signalpoint/DrupalGap#221]
I was adding taxonomy from node in page_pageshow(). It was fine is showing name. But i wanna link the taxonomy term to its related term page. Is that possible?

**Comment by signalpoint** [comment]
Yes, taxonomy term page view is built in, it uses the same path that Drupal uses. So just use something like this:

```
l(term.name, 'taxonomy/term/' + term.tid)
```

**Comment by zawlinoo** [comment]
How to taxonomy term's node listing? I was creating content view with taxonomy filter and call back function. But its seem didn't work. Please have a look. Thanks a lot for your helps.

here is my json output from view.

{"nodes":[{"node":{"title":"Hola","nid":"14","tid":"1","Image":"http://dev-drupal.local/sites/default/files/styles/test/public/field/image/nodejs-wallpaper-nsfw.jpg?itok=T5RXeaBF","name":"Blah"}}],"view":{"name":"drupagap_view","display":"page_3","path":"taxonomy/term/1","root":"nodes","child":"node","pages":null,"page":null,"count":1,"limit":null}} 

menu function.

'taxonomy/term/%': {
        'title': 'custom Taxonomy term',
        'page_callback': 'custom_taxonomy_term_page',
        'page_arguments': [2],
        'pageshow': 'custom_taxonomy_term_pageshow'
},

**Comment by signalpoint** [comment]
taxonomy_term_index()

http://drupalgap.org/node/200

Then build a list:

http://drupalgap.org/node/119
