### ISSUE TITLE
Multiple Taxonomy Term Reference Fields on Node Add/Edit Form Doesn't Fetch Terms

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#226]
If you have two taxonomy term reference fields on a node content type, the second vocabulary (ordered by field weight) doesn't get its terms fetched and dynamically injected into the select list.

**Comment by chrisschaub** [comment]
Trying to figure out why this is happening. Seems like only autocomplete works.

**Comment by signalpoint** [comment]
@cschaub - I'd start with looking at options_field_widget_form(), and make sure the inline JS pageshow callback specified at the end of that function is getting called for each taxonomy term reference field (which isn't happening, only the 1st is getting called). Alternatively, look at taxonomy_field_widget_form().

**Comment by chrisschaub** [comment]
Man, I can't get debugging to work at all. Trying to fix this issue, but console.log and alerts just don't work. I've installed the cordova plugins for console and dialog among others, but no dice. Is there some trick to getting console.log working with Drupalgap? It works on my other builds that are in the app store! Using cordova 3.0.10

**Comment by signalpoint** [comment]
@cschaub Are you using the make file after making changes to the src/ folder to re-build the bin/drupalgap.js file?

Have you installed the console plugin (not necessary in Ripple)?

Or are you editing the bin/drupalgap.js file directly (not recommended)?

**Comment by chrisschaub** [comment]
Ahh, thanks. So, I think the issue is the pageshow only gets fired the first time. Something with how on binds. They don't all fire. I can see the script in the page, and the first one works. Still working on it.

**Comment by chrisschaub** [comment]
https://github.com/signalpoint/DrupalGap/pull/246
