### ISSUE TITLE
Is that possible android native notifications for new contents?

### ISSUE THREAD

**Issue by zawlinoo** [signalpoint/DrupalGap#228]

**Comment by signalpoint** [comment]
Check out Push Notifications:

http://www.drupalgap.org/project/push_notifications

@scotthooker may be able to help you with it.

**Comment by scotthooker** [comment]
Ping me if you need help. It's still a dev version of a generic module really. May need a few tweaks.

**Comment by signalpoint** [comment]
Thanks, re-open if neeeded.

**Comment by zawlinoo** [comment]
Thanks bros.. I'll try it first and let you know.
