### ISSUE TITLE
how to get term names instead of term ids in node view

### ISSUE THREAD

**Issue by mazewei** [signalpoint/DrupalGap#232]
hi,
i try since two days to change the term ids (tags and authors) to term names. Is there a hook or function which i can use for?

Thanks for advise! Cool stuff your module!

Matthias

![auswahl_141](https://f.cloud.github.com/assets/6942140/2410590/c0236ed2-aabe-11e3-895f-b25ec19fd496.png)
![auswahl_140](https://f.cloud.github.com/assets/6942140/2410593/c463ce60-aabe-11e3-9f4a-782506adb694.png)

**Comment by signalpoint** [comment]
@mazewei - Just yesterday I was chatting about this very topic with @ice423cube.

He was able to accomplish it with this GIST:

https://gist.github.com/ice423cube/9516375

I would be interested in moving this feature into DG core (and/or in the DG module).

**Comment by mazewei** [comment]
Hy Tyler,
i tried this, but i think its not a good solution, because its not a problem to get the term names from the service and there is no reason to manipulate the result with this hook.

I tried also to manipulate the service request but in the app. But it do not work. I dont know why....

```
function taxonomy_field_formatter_view(entity_type, entity, field, instance,
  langcode, items, display) {
  try {
    var element = {};
    // If items is a string, convert it into a single item JSON object.
    if (typeof items === 'string') {
      items = {0: {tid: items}};
    }
    if (!empty(items)) {
      $.each(items, function(delta, item) {
    item.name = entity_load('taxonomy_term', item.tid);
    //dpm(item.name); (everytime empty, i dont understand why) 
          element[delta] = {
            theme: 'link',
            text: item.name,
            path: 'taxonomy/term/' + item.tid
          };
      });
    }
    return element;
  }
  catch (error) { console.log('taxonomy_field_formatter_view - ' + error); }
}
```

Logfile:

-> this is the service request
GET: http://example.com/?q=drupalgap/taxonomy_term/342.json
-> this is the output from dpm(item.name) from my script
"<null>"

But i don't get the names, i programming javascript since monday, i think thats the main problem....  I also tried the hook "hook_field_formatter_view()" but this takes no effect. 

Any ideas?

Best regards

Matthias

**Comment by mazewei** [comment]
ok, i have made a php solution, maybe you want to integrate in the "real" drupal modul? Than i will add a backend. It is based on the https://gist.github.com/ice423cube/9516375 but more flexible and ready for all term fields a page have. I you want tell me!

If i install my module the service bring me this

```
[field_keywords] => Array
    (
        [und] => Array
            (
                [0] => Array
                    (
                        [value] => Gefühle
                        [tid] => 342
                    )

                [1] => Array
                    (
                        [value] => Emotionen
                        [tid] => 343
                    )

                [2] => Array
                    (
                        [value] => Emphathie
                        [tid] => 344
                    )

            )

    )
```

So i have to copy the "function taxonomy_field_formatter_view" in my custom drupalgap module and change 
- text: item.tid, 
  to 
- text: item.value,

Now i get term names instead of term ids.

![auswahl_142](https://f.cloud.github.com/assets/6942140/2422428/4765fdc2-ab8e-11e3-8357-9a6fc5342c05.png)

Regards
Matthias

**Comment by signalpoint** [comment]
@mazewei Yes, please post your solution as a GIST if possible. Then we can look to get it put into DrupalGap core/module, thanks!

**Comment by mazewei** [comment]
https://gist.github.com/mazewei/9568147

**Comment by signalpoint** [comment]
This has been fixed. Grab the latest development snapshots of the module and SDK for the fix. Or wait until the next recommended release is available for both.
