### ISSUE TITLE
Table populate

### ISSUE THREAD

**Issue by quiquee** [signalpoint/DrupalGap#233]
I have added the possibility to populate a table in the same manner as it is done with  drupalgap_item_list_populate 
/**
- Given an html table element id and an array of items, this will clear the
- table, populate it with the items, and then refresh the list.
- @param {String} table_css_selector
- @param {Array} items
- items follow the.
  */
  function drupalgap_table_populate(table_css_selector, items) {
  try { ...
  I can push this changes to git . 
  Changes are to  well to src/drupalgap.js and src/includes/theme.inc.js
  I am not very used to git but I believe I can branch and create a branch for you to merge it. Just let me know. I am happy to continue contributing.
  Thank you

**Comment by signalpoint** [comment]
@quiquee Thank you for your contribution! Yes, I would recommend making a "fork" of DrupalGap, committing your changes to your fork, then "Submit a Pull Request" with DrupalGap, and I can merge in your changes.

**Comment by quiquee** [comment]
That is great. I have done a fork and commited the changes and tested it. Thank you very much.
