### ISSUE TITLE
Error (wrong var name) in image_style_url() function of Drupalgap

### ISSUE THREAD

**Issue by Thibault87** [signalpoint/DrupalGap#235]
I found an error that make the theme_image and theme image_style not usable. (And maybe some other functions)

In the file drupalgap.js , for thi functions, you are using the var drupalgap.settings.file_public_path (that is undefined).

You should replace it to Drupal.settings.file_public_path

took me a while figuring out what was wrong.

Hope this could help !

**Comment by signalpoint** [comment]
@Thibault87 thanks for pointing this out, I've fixed the bug. Grab the latest development snapshot for the fix. Alternatively, this fix will become available in 7.x-1.8-alpha.
