### ISSUE TITLE
Can't save custom bundles 

### ISSUE THREAD

**Issue by rich-dawson** [signalpoint/DrupalGap#236]
Hello,

This issue comes out of some comments I posted to the "getting started" guide found here:  http://www.drupalgap.org/node/197 

It seems that the issue I'm having may have something to do with my specific implementation of DrupalGap. 

The code I am using is as follows and may be found in the getting started page I linked to earlier where "my_custom_bundle" is a bundle I created through Drupal's admin UI:

```
var node = {
  title:"Hello World",
  type:"my_custom_bundle"
};
node_save(node, {
  success:function(result) {
    alert("Saved node #" + result.nid);
  }
});
```

This code works perfectly when I use with bundles "page" or "article" but nothing else works as expected. Oddly, when I use "book" the alert message returns the message "Saved node #null" though no content is actually created. Custom bundles, and even the "forum" bundle (using the forum module) simply show the loading screen but ultimately fail to load the alert or create a new node. 

I have checked the machine name on the "structure>content types" page repeatedly but nothing seems to work for my custom bundles when trying to create a new node.

**Comment by signalpoint** [comment]
Are you using the latest development snapshot of the SDK and the latest development snapshot of the DrupalGap Drupal module?

What type of fields are on your custom content type?

How is your environment setup? i.e. localhost+remote drupal site, localhost+localhost drupalsite, other?

**Comment by rich-dawson** [comment]
Thanks for your quick responses Tyler, I appreciate the support. 

I am using the following setup:

-Drupalgap module version: 7.x-1.5
-Drupalgap SDK version: 7.x-1.7-alpha
-Drupal version: 7.26
-Phonegap version: 3.4.0-0.19.7
-Cordova version: 3.4.0-0.1.3

Field Types are as follows (note that I have not modified the fields on the book content type or forum and am still having issues with them as well):
-Title (which displays as genotype to users but still has the machine name "title")
-Text **multiple instances**
-Email (from Email module)  **multiple instances**
-Date (from the Date/Time module) **multiple instances**
-List (text) **multiple instances**
-Long text and summary
-Long text
-Image
-Integer
-Barcode (from the Barcode module)
-Boolean
-Entity reference (from the Entity Reference module)

My environment is setup as only a remote Drupal site at the moment, no localhost development environment for the time being unfortunately.

**Comment by signalpoint** [comment]
@rich-dawson 

Try upgrading to the development snapshot of the DrupalGap SDK and Module first.

Where are you running the app,  in Ripple, on an emulator, or a mobile device?

It's crucial to watch the console.log() messages, and switch Drupal.settings.debug to true in settings.js

Hopefully that will give more insight.

**Comment by rich-dawson** [comment]
I will try to upgrade and see if that helps. I am running on a Samsung Galaxy S4 and doing everything with the node.js command-line interface. I will be sure to set Drupal.settings.debug to true in settings and see if I get anything helpful back.

**Comment by signalpoint** [comment]
@rich-dawson 

Be sure to enable console debugging in the terminal, so you can watch the output. (I've never done this, but it should work).

Also, try switching some of your required fields to optional, because it's possible they can't be submitted without that data. Either way, the console.log() should report what's wrong with the node_save() attempt.

Also, are you using the internal node/add/my_custom_type page inside of DrupalGap to create the node, or are you trying to do it programmatically?

**Comment by rich-dawson** [comment]
Update: I successfully created a new node from a new custom content type which I just created with no added fields and machine name test. I successfully ran the code above using "test" for type which was successful.

**Comment by signalpoint** [comment]
@rich-dawson Good to hear. It most likely has to do with a custom field on your content type. For example, bar code isn't supported that I know of (it's possible to add field support though). Get that Drupal.settings.debug set to true and review the console.log and it should reveal which field is causing the problem. Check out some of the sandbox DG modules on drupalgap.org to see how some of them have added support for additional fields (date, geofield, etc).

**Comment by rich-dawson** [comment]
I added a barcode field to the custom "test" content type and had no problem saving the content. I then added a required field and was unable to save the new node. The problem now I suppose is that I need to be able to create new nodes and am unsure how to populate the required fields. I viewed the help document located here: http://www.drupalgap.org/node/216 and see that textfields are supported (all of my required fields are text fields). I don't see an example of how to implement this though, would the following be correct? 

var node = {
    title:"Hello World",
    field_custom_field:"N/A",
    type:"test"
};
node_save(node, {
    success:function(result) {
    alert("Saved node #" + result.nid);
    }
});         

Apologies for the lack of log info, my java console refuses to run thanks to software policies I'm unable to override at the moment.

**Comment by signalpoint** [comment]
@rich-dawson 

In DrupalGap, set your front page to:

node/add/test

And try to use that form first, if possible. That'll give you an idea of how it works.

If you're creating the nodes programmatically yourself, then the JSON structure you POST is the same as the structure you can retrieve with GET.

http://www.example.com/?q=drupalgap/node/123.json

Create a node on your site through the UI, add the barcode there, take note of the node id, then navigate to the example URL above, replacing it with your newly created node id.

Copy the JSON output and paste it into jsonlint.com to see the structure you need to send.

If you want to use the build in DrupalGap form (which would benefit others), then you'll have to start contributed module for barcode for drupalgap and implement hook_field_formatter_view() and hook_field_widget_form().

**Comment by rich-dawson** [comment]
Thank you very much for your assistance Tyler, you are an extremely helpful developer!

**Comment by rich-dawson** [comment]
Just to follow up on this topic for anyone who may view it in the future: The barcode module renders barcodes on the fly (based on tokens), so it's not likely that anyone would need to use the hooks mentioned by @signalpoint above with the barcode module because there's no need for Drupalgap to do any of the rendering.
