### ISSUE TITLE
Working with drupalgap and git

### ISSUE THREAD

**Issue by quiquee** [signalpoint/DrupalGap#238]
I was thinking of adding some documentation on how to work with drupalgap and git, in a way that makes sense. But obviously I am not sure of what way that is, as I am not very good with git

The issue is that I cloned the whole grupalgap and I have then since there done my own development in app/

What I would like is to have in git only the contents of my app directory and still be able to update my drupalgap contents to www and still keep my own repository under app

Question is,
Can users clone a branch of drupalgap to www and then refresh their own repository with updates in that drupalgap branch?
Is this compatible with keeping the app/ directory with their own repository? for example there is a README file in that directory that is not part of the user's app

Before trying to find a solution through symlinks or similar, which I dont specialy like, I would like to know your opinion on what is the best way of doing it

Thank you !

**Comment by signalpoint** [comment]
@quiquee Unfortunately/fortunately symlinks have worked best for myself. Here is my typical setup on localhost:

Install and setup a Drupal 7 site here:

```
/var/www/drupal-7
```

So it can be accessed here:

```
http://localhost/drupal-7
```

From here, I'll navigate into that directory with a terminal, then clone my fork of DrupalGap:

```
cd /var/www/drupal-7
git clone [insert-clone-url-from-github]
mv DrupalGap mobile-application
```

Now the mobile app can be run inside of Chrome + Ripple here:

http://localhost/drupal-7/mobile-application

At this point, I typically create a new repository for each app that I am working on. Here's a typical directory structure of the new repo:

```
android/*
ios/*
app
app/settings.js
app/modules/*
app/themes/*
```

The android and ios directories hold the resources individual to those platforms, and the app directory just holds the settings.js file and the app's modules and themes directory.

I'll then clone this repo to my Desktop:

```
cd ~/Desktop
git clone [my-app-github-clone-url]
```

Then I'll head back to the mobile-application directory and make symlinks to the settings.js file, and the modules and themes directories:

```
cd /var/www/drupal-7/mobile-application
ln -s ~/Desktop/example_repo/app/settings.js
ln -s ~/Desktop/example_repo/app/modules
ln -s ~/Desktop/example_repo/app/themes
```

Then I can open /var/www/drupal-7/mobile-application in my favorite IDE, and then modify DrupalGap core and the individual project as needed.

Then I can do git commits for DrupalGap core:

```
cd /var/www/drupal-7/mobile-application
git add README
git commit -m "Update README"
git push origin 7.x-1.x-alpha
```

And do individual commits for my app:

```
cd ~/Desktop/example_repo
git add app/settings.js
git commit -m "Add new settings."
git push
```

Sometimes I run into permissions issues when localhost can't access my Desktop, then I'll just clone the individual app's repo somewhere into the Drupal site directory.

**Comment by quiquee** [comment]
That is very useful,
for the server side I dont have a particular issue, as the code is self
contained
for the app section I will follow the symlink approach. I will test it and
once I feel confident I will add it to the doc

Thanks !!

On Sat, Apr 5, 2014 at 5:43 PM, Tyler Frankenstein <notifications@github.com
