### ISSUE TITLE
Drupalgap for HTML5 website

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#240]
So, we've had really solid success with Drupalgap for both iOS and Android appstores. What about using it for a mobile first website framework? Drupal as admin interface, Drupalgap as front-end to Drupal. Seems like most of the pieces are there and it's really the way most of us test before we compile.

**Comment by signalpoint** [comment]
@cschaub This is on my personal goals list for 2014. As always, if you've got some spare lines of code, push/pull them as needed. Or if this is for work, and somebody wants to throw money at the problem, that always speeds it up ;)

**Comment by chrisschaub** [comment]
Well, we're going to give it a go. I'll push anything useful. One area is using things like wysiwyg or panopoly on the drupal side. Basically, the responsiveness of any type of body content. We're thinking wysiwyg with some parsing to add data-role to the markup might be in order. It would be great if drupal had a plugin like Wordpress' pagebuilder. It's just like panels, but the content is stored in body, and is responsive.

**Comment by signalpoint** [comment]
Duplicate: #39
