### ISSUE TITLE
Register and Login with just Email and Password

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#241]
Just about every app in the world does enter email address, password and re-enter password to register for their apps.  What if we did this too.  You could easily do it with use user registration password (https://drupal.org/project/user_registrationpassword) and Logintoboggan just email to login (https://drupal.org/project/logintoboggan).  That would be a great improvement.  All you would have to do is re jigger the reg page and login page.  Everyone remembers the email address. The logintoboggan module supports just email and make your user name automatically.  So This.Is.My.Email@example.com would create a user name "This.Is.My.Email" automatically.  You still have to activate the account with the link from inside your email (which is great to make sure they are real people) but you don't have to remember to create a password and if you don't then wait for another email with your one time login link.  Just a thought.  It would be quick and nice for everyone ;-).

**Comment by ice423cube** [comment]
Here's an older issue about this: https://drupal.org/node/1431724

**Comment by signalpoint** [comment]
@ice423cube Users can now login with their e-mail address. Add the logintoboggan module to your DrupalGap app:

https://github.com/signalpoint/logintoboggan

And upgrade the DrupalGap module on your site to the latest development snapshot:

https://drupal.org/project/drupalgap

**Comment by signalpoint** [comment]
There are three modules potentially at play here:

https://drupal.org/project/email_registration
https://drupal.org/project/user_registrationpassword
https://drupal.org/project/logintoboggan

**Comment by signalpoint** [comment]
This is now possible using one or both of these sandbox modules:

http://drupalgap.org/project/logintoboggan
http://drupalgap.org/project/email_registration
