### ISSUE TITLE
Drupalgap Dev Not allowing me to create or edit basic pages

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#244]
When I have drupalgap 7.x-1.5+10-dev installed i am not able to create (/node/add/page) or edit any basic pages.  I can add and edit other content types.  The only error I am getting is listed below when someone is trying to access the app "http://www.mywebsite.com/?q=drupalgap/node/1614.json",  When i uninstall it I am able to edit and create basic page content types.  I am now running the latest Drupal 7.26 and services 7.x-3.5.  I did flush all my cache and rebuild permissions.

Notice: Undefined index: module in drupalgap_services_request_postprocess_alter() (line 188 of /home1/valleyv1/public_html/sites/all/modules/drupalgap/drupalgap.module).

**Comment by signalpoint** [comment]
@ice423cube Did you try completely disabling, then uninstalling, the DrupalGap module? Then upgrading to the Dev version of it?

**Comment by ice423cube** [comment]
No.  I just uploaded it and then did an update.php

**Comment by signalpoint** [comment]
@ice423cube Ok, try completely uninstalling the module from the "Modules" -> "Uninstall" tab after you've disabled it. Then try re-enabling the dev version of the module.

Make backups before doing anything crazy though ;)

**Comment by ice423cube** [comment]
Ok.  I will try that.  The whole site is down now.  Yeah hosting company ;-)

**Comment by ice423cube** [comment]
Since my server is down.  I did it locally and i am still having the same issue.  Can't create or edit basic pages.

**Comment by ice423cube** [comment]
I can add, edit, delete other content types no problem.

**Comment by signalpoint** [comment]
@ice423cube I just installed a fresh copy of Drupal 7, with the latest development snapshot of the DrupalGap module and SDK, I'm able to add/edit basic pages without issue. Maybe contact me on IRC and provide some admin credentials, and I can take a look.

**Comment by signalpoint** [comment]
@ice423cube To follow up, we discovered the 'authored by' field on the form is getting a form error, but no message is displayed. This is preventing the form from submitting.

**Comment by ice423cube** [comment]
Holly carp. I found it.  There is some conflict with the Node Hierarchy Module, but not the main module you can still use that.  It is the sub-module "Node Hierarchy Children Embed" this part of the modules Allows a nodes children to be embedded on the node detail page with Views.  I don't need it but I thought it might be good for you to know.  So to fix this just uncheck "Node Hierarchy Children Embed" and then your back in the game.
