### ISSUE TITLE
Navbar in footer

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#249]
Is there a way to make a menu as a block in the footer become a navbar. I've tried adding data-role in various place, no dice so far.

**Comment by signalpoint** [comment]
@cschaub I'd make a new region in my theme's JS file, and set the data-role on that region to 'navbar'.

I'd then add that region to my theme's page.tpl.html file somewhere near the bottom. That way it appears in the "footer" area of the page template, but actually gets rendered as a navbar.

I'd then place menus/blocks in that region via settings.js

**Comment by chrisschaub** [comment]
Well, I'd like to have a navbar in a fixed footer. That way, the navbar can be fixed as well. Jquerymobile supports this, but I'm not sure the data-role gets carried over in the drupalgap theme layer.

**Comment by signalpoint** [comment]
@cschaub The data-role specified in e.g. my_theme.js will/should carry over into the page:

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x-alpha/themes/easystreet3/easystreet3.js

**Comment by chrisschaub** [comment]
Hmmm, but not sure you can make that navbar fixed ...

```
<div data-role="footer">        
    <div data-role="navbar">
        <ul>
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
            <li><a href="#">Three</a></li>
        </ul>
    </div><!-- /navbar -->
</div><!-- /footer -->
```

**Comment by signalpoint** [comment]
@cschaub I don't think the navbar should be inside the footer, it should be sitting outside of it (I think). Then you can apply the data-position="fixed" attribute.

**Comment by chrisschaub** [comment]
Right, but if it is outside, there's no way to make it fixed. I think only footers and headers can be fixed?

**Comment by chrisschaub** [comment]
I think it's possible from the doc ...

http://demos.jquerymobile.com/1.2.1/docs/toolbars/footer-persist-a.html

**Comment by signalpoint** [comment]
@cschaub Ok, then I'd try to make a navbar region as usual, then in the page.tpl.html file, wrap the region's placeholder in a div footer with data position fixed.

```
<div data-role="footer" data-position="fixed">
  {:my_navbar_region:}
</div>
```
