### ISSUE TITLE
TypeError: 'undefined' is not an object on field_info_instances and field_info_fields 

### ISSUE THREAD

**Issue by ianmen** [signalpoint/DrupalGap#25]
Hi,

I'm getting the following error when trying to access field_info_fields and field_info_instances  from the data object:

TypeError: 'undefined' is not an object

In this code (drupalgap_system.js:12) : 

```
drupalgap.field_info_instances = data.field_info_instances;
drupalgap.field_info_fields = data.field_info_fields;
```

Is there an error in the JSON module on the Drupal side ?

-Bob

---

After updating to the development version I see this is fixed

**Comment by signalpoint** [comment]
Update to the 7.x-1.x-dev module and you should be all set:

http://drupal.org/project/drupalgap

**Comment by ianmen** [comment]
Thanks that did the trick.

**Comment by signalpoint** [comment]
Whoops, I should leave this open until a recommended release has this fixed. Thank you for the debugging information!

**Comment by ianmen** [comment]
Maybe this is more an open issues to the Drupal Module then to the phonegap part.

**Comment by signalpoint** [comment]
This should be fixed now that new release are available.
