### ISSUE TITLE
Reloading Current Page

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#254]
As it stands right now, drupalgap_goto() prevents navigating to the current page, even if the reloadPage option is set to true. Let's make this possible. However, it is important to note that jQM always needs at least one page in the DOM, and when reloading a page, the page is removed from the DOM. So we need to figure out a way to reload the current page, without removing it from the DOM. If we end up having to remove it from the DOM, then a dummy empty page needs to be generated during the transition.

**Comment by rich-dawson** [comment]
I'm glad that you brought this up as I experienced this issue with my own application. To get around it I simply embedded an anchor tag which calls back the target page when clicked. This was the only workable solution I encountered as things are currently. 

For example: <.a onclick="my_page()">Go to my page...<./a>

Before this solution I had actually attempted to use either a dummy page, or to alternate between two identical pages (alternating was simply inelegant).

**Comment by liquidcms** [comment]
i didnt really get the anchor idea.. but the dummy page was something i had thought of before seeing this and it seems to work well.

simply add 2 menu items with all the same parameters except 2 different path values.

then in my form submit code (i am trying to get form to submit and then refresh values on that page) i have this:

```
if (drupalgap_get_page_id() == 'placemarks_favorites') {
  drupalgap_goto('placemarks_favorites_dummy', {reloadPage:true});
}
else {
  drupalgap_goto('placemarks_favorites', {reloadPage:true});
}
```

**Comment by signalpoint** [comment]
@liquidcms That's an interesting approach, thanks for sharing!

**Comment by signalpoint** [comment]
This now works, see here for details: http://drupalgap.org/node/134

**Comment by jomarocas** [comment]
please update the documentation, i lose lot of time reading this http://docs.drupalgap.org/7/Developer_Guide/Caching_and_Performance
