### ISSUE TITLE
Audio field support

### ISSUE THREAD

**Issue by ronlinet** [signalpoint/DrupalGap#255]
I can see that the project is handling images. 
It would be useful to include support for audio field too?
In my case I use https://drupal.org/project/audiofield.

**Comment by signalpoint** [comment]
@ronlinet Are you interested in implementing a solution for this? If so, the first step would be to create a Sandbox DrupalGap module:

http://drupalgap.org/node/add/project

The name of the project would be: AudioField
The machine name would be: audiofield

Then to get the audio field to display on a node (not on the node edit form, that is more complex and we'll wait until later to do that), implement hook_field_formatter_view():

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x-alpha/src/modules/api/api.js#L340

e.g.

```
audiofield_field_formatter_view(...)
```

Use `dpm(field)` and `dpm(item)` inside of that function to start building it.

If you're not interested, that is fine, just let me know and I'll start on it when I have some time. If you need it ASAP I am available at an hourly rate to get it done, thanks!

**Comment by signalpoint** [comment]
@ronlinet Also, create  a project on GitHub called `audiofield` to house the code for the module.

**Comment by ronlinet** [comment]
Hi signalpoint. 

For the moment I am going through the documentation to figure out how to populate a list with drupal view. All is well documented and it is just a matter of time to get through this. I will get back with git repository when I will get through the basic steps. Not in rush at all for the moment. 

Your help is kindly appreciated.

**Comment by ronlinet** [comment]
The github repository and drupalgap project is created > http://drupalgap.org/project/audiofield . 

Thanks to drupalgap documentation I am already able to to load lists with JSONs generated by drupal remote site. 

Then next step will be to build basic page interaction to display different category listing to allow a user to chose the appropriate audio content. One this is done I will be able to dedicate my time to drupalgap audio field module. 

@signalpoint keep on doing ! Clinching the mobile platform with drupal is exactly what we were missing .

**Comment by signalpoint** [comment]
@ronlinet How did this go? I just wanted to check in on this because I didn't see any code in the repo you created. Please let me know, thanks!

**Comment by signalpoint** [comment]
The project has been updated: http://www.drupalgap.org/project/audiofield

**Comment by billycheuk** [comment]
Hi

Could there be more clues that can be found here?

I learnt the image field on a Drupal node/add turns out a 'Take Photo' together with a 'Browse' button in Drupalgap.  However the Audiofield on a Drupal node/add gets a 'null' in DrupalGap though installing the Drupalgap Audiofield along.  Any tips to turn out a 'Voice Recorder'(Audio Capture' and a 'Browse'?.  Thank you.

**Comment by signalpoint** [comment]
@billycheuk It looks like no one has implemented `hook_field_widget_form()` yet in audio.js : https://github.com/huythuytq/AudioField/blob/master/audiofield.js

Many other contrib modules for DrupalGap have examples of how to implement that hook. Please open an issue with the audio module for future support, thank you.
