### ISSUE TITLE
Use both roles and pages visibility rules in blocks

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#256]
There is a bug with the blocks no allowing you to use both 'roles' and 'pages' visibility rules applied to a specific block.  Example below:

```
home_logged_in:{
           pages:{
        value:['intro_page'],
        mode:'include'
      },
      roles:{
        value:['authenticated user'],
        mode:'include',
      }
        }
```

**Comment by ice423cube** [comment]
TYLER: It shouldn't be too bad, this is the function that needs to be adjusted: http://api.drupalgap.org/global.html#drupalgap_check_visibility

**Comment by signalpoint** [comment]
#250 - duplicate issue.
