### ISSUE TITLE
Allow custom href for menu link

### ISSUE THREAD

**Issue by johnpitcairn** [signalpoint/DrupalGap#259]
I'd like to add a menu link to the header region to open a custom jquery mobile panel. All it needs is href="#menu-panel" and no path. It does not seem to be possible to add this via drupalgap.settings.menus.regions.header.links - options.attributes.href is ignored.

My only other option is to create and add a block with the relevant html to the region (which does work). I guess I'm wondering why this distinction is forced on the developer?

**Comment by johnpitcairn** [comment]
I see no reason why the href attribute should not be honored if it is set and there is no path. It's a simple change. Forked and pull request sent.

**Comment by signalpoint** [comment]
@johnpitcairn Awesome! I've merged in your pull request, thanks for hopping on board!
