### ISSUE TITLE
Need help getting started

### ISSUE THREAD

**Issue by jaarong** [signalpoint/DrupalGap#26]
I created an app using this tutorial a couple of months ago:  http://www.tylerfrankenstein.com/code/android-app-with-drupal-7-services-phonegap-and-jquery-mobile

At the time, I really didn't understand all of this, but wanted to learn more about it.  The tutorial worked well for me, and the app has more features than originally planned (Thanks!).  Now, I'm starting a new app, and realize I need to use the code in this repo so that the app is more future-proof, because it's obviously updated more and has more capability than the code in the tutorial.  

The problem is, coming from that tutorial, things were fairly simple and linear.  I'm looking through this new code (being a newbie to JS) and I see modules being loaded, there are initialize functions now, and each function seems to be very interdependent on other functions and even the page HTML being a certain way.  

My first question would be, how would you recommend customizing this?  Basically fork the code for my own application?  Or can I pull some of the scripts out, put them in a js folder, customize them to my needs, and the whole thing still be dependent on the the core module functions?   

Second is more specific and really the point if your looking for the TL;DR in this post, I'm getting a DrupalGap API error on startup that says "Access is denied for user anonymous".  Which is true, the site doesn't allow anonymous users to access any content.  But, why doesn't it just allow me to login?

**Comment by signalpoint** [comment]
Thanks for checking out the old tutorial. That tutorial is what inspired this whole project.

I would recommend forking DrupalGap for your own application.

Then I would set up a custom module (checkout the DrupalGap/modules/example folder for more info).

Here is the module that we use to power the DrupalGap mobile application available in the markets: https://github.com/signalpoint/dg_pro

We are trying to follow in Drupal's footsteps with this plan:
- modifications to Drupal Core should work and benefit everyone
- any custom modifications you need for your specific application should go in your custom module(s)

If DrupalGap core isn't flexible enough (which it surely isn't, it needs lots of improvements) and you need a hook, or something, just let us know.

And of course it is open source, so feel free to make as many changes as you want. Anything you do that can benefit the project as a whole, please submit a pull request and we can look into getting the code into core.

As for the 'Access is denied for user anonymous' problem. Please see this issue for more information: http://drupal.org/node/1907972

Also, be sure to check out the troubleshooting topics here: http://drupal.org/node/1603690

**Comment by jaarong** [comment]
Thanks for the information.  I did go through the troubleshooting and the modules reports everything is in order.  The Firefox Poster plugin pointed me to a potential problem though.  When I try to access the content through the drupalgap datasource view, I get an access denied message even when my user auth is correct.  Taking the authenticated role off lets me view it perfectly.  So, it has something to do with the user auth.  My site is using the LDAP module to authenticate, so I'm thinking that may be the problem.  I have no idea if Services works with LDAP or not.

**Comment by jaarong** [comment]
No, it doesn't as of today without writing a custom module.

**Comment by signalpoint** [comment]
I was afraid of LDAP causing problems. I use that exclusively for one project, but haven't yet tried putting Services on top of it. That's disappointing, I'll have to confront LDAP vs. Services someday though.

**Comment by signalpoint** [comment]
Closing issue. Getting started guide now available online: http://www.drupalgap.org/get-started
