### ISSUE TITLE
Custom Service Resource with Arguments

### ISSUE THREAD

**Issue by arielestigarribia** [signalpoint/DrupalGap#262]
Hello 
I need some help about "Custom Service Resource with Arguments"
http://www.drupalgap.org/node/203

How do I have to use the arguments (my_param) to filter the query in the my_module.resource.inc file?

**my_module.resource.inc**

```
<?php

function my_module_get_user_count() {
  return db_query("SELECT COUNT(uid) FROM {users}")->fetchField();
}
```

**Comment by arielestigarribia** [comment]
Done!

**Comment by signalpoint** [comment]
@arielestigarribia I'm glad you figured it out, please feel free to add/edit the documentation with any new information you find, thanks!
