### ISSUE TITLE
Error when i click on the results of views (via render array)

### ISSUE THREAD

**Issue by sperlari** [signalpoint/DrupalGap#266]
I'm trying to display views via Render Array and it works but when I click on a single result it returns me this error: " entity_load(node) - only single ids supported!"

What does it mean? There is a way to fix that?

Thanks in advance!

**Comment by signalpoint** [comment]
@spexy90 As long as your items link to e.g. node/123 it should work without issue. Using the HTML inspector in Ripple, verify the drupalgap_goto() call on the links is going to a path like e.g. node/123.

If that doesn't work, share your Views JSON URL that supplies your data, and also share your DrupalGap code here.

**Comment by sperlari** [comment]
ok, thanks! I'm trying!

**Comment by sperlari** [comment]
I'm trying with ripple but it doesn't work for me!
Is there a way to have an html inspector with cordova/phonegap and emulator?

**Comment by signalpoint** [comment]
@spexy90 Please share your Ripple URL, if it isn't on localhost. Also, share the link to your Views JSON results, if it isn't on localhost.

And if you haven't already, update the DrupalGap module and SDK to the latest development snapshots: www.drupalgap.org/download

The feature you're trying to access isn't available in the last recommended release.

**Comment by sperlari** [comment]
http://www.concorsimusicali.it/mobile-application/ 

I'm trying with default views of drupalgap module and it works. Now the problem is when i click on a result: it returns me only the names of the fields of the specific content page without data. (i set the display settings of drupalgap correctly)..why?

**Comment by signalpoint** [comment]
@spexy90 Since it appears your fields are not part of Drupal core, you'll need to add some contrib modules to your DG app. For example, if you look at the console.log in Chrome's inspector in Ripple, you'll see these error messages:

```
WARNING: drupalgap_entity_render_field - link_field_formatter_view()does not exist! drupalgap.js:5201
WARNING: drupalgap_entity_render_field - lightbox2_field_formatter_view()does not exist! drupalgap.js:5201
WARNING: drupalgap_entity_render_field - fivestar_field_formatter_view()does not exist! drupalgap.js:5201
2
WARNING: drupalgap_entity_render_field - date_field_formatter_view()does not exist! 
```

For starters, try downloading the link, date, fivestar and lightbox modules for DG and add them to your app:

http://drupalgap.org/project/modules/
http://drupalgap.org/node/74

**Comment by sperlari** [comment]
Ok, yes. I installed modules but I don't see any changes.
In my app there are fields without data. Is there a module for text fileds?

**Comment by signalpoint** [comment]
@spexy90 Well I've used those modules to get fields like that to show up. If you have a multi lingual site that could be causing issues.

Text fields should be supported in DrupalGap core.

Please open a separate issue(s) if need be, as we are getting away from the original issue in this thread, thanks!
