### ISSUE TITLE
WSOD on real iPhone

### ISSUE THREAD

**Issue by mfuggle** [signalpoint/DrupalGap#267]
I have DrupalGap working in the Chrome Ripple emulator but when I try to access the mobile page on a real iPhone I can see the Title (DrupalGap) but after that there is nothing just a WSOD.

I have tried to track down the issue without success. If someone could point in the right direction that would be great.

Cheers
Martin Fuggle

**Comment by signalpoint** [comment]
@mfuggle When you say "when I try to access the mobile page on a real iPhone" do you mean you are visiting your /mobile-application Ripple site in your iPhone's browser? Or are you actually compiling the app (e.g. via xCode) and installing it on your iPhone?

**Comment by mfuggle** [comment]
Hmmm - I suspect  have a lot to learn. I was trying to access the /mobile-application (or in my case /mobile) site in my iPhone browser.

**Comment by signalpoint** [comment]
@mfuggle Correct, you will NOT be able to access e.g. /mobile-application from your iPhone, because Ripple only works as a Chrome plugin. Maybe there is a Ripple plugin for Chrome's iOS browser, I'm not sure though. I'm an Android guy, and have never tried.

When I want to compile the app(s) to run on an actual device, I follow Option 2's instructions here:

http://www.drupalgap.org/node/132

**Comment by mfuggle** [comment]
That makes sense. I'm in France at the moment but live in Australia so I don't have all of the facilities I need on an old Macbook I brought with me (like XCode). Maybe I'll have to wait until I get back.

**Comment by signalpoint** [comment]
@mfuggle I'd also like to point out that eventually I will be dropping the PhoneGap dependency from DrupalGap, and replacing it as a plugin, which will allow the App to function as a Web Application as well. Then we'll be able to visit e.g. /mobile-application on any device/browser and it'll work. I've got this on my "to do" list by the end of this year.

**Comment by mfuggle** [comment]
That would be great. A the moment my stuff is on a shared server so I don't think I can go much further without switching to a dedicated server instance and I don't want to do that at the moment.
