### ISSUE TITLE
file naming conventions

### ISSUE THREAD

**Issue by uniquename** [signalpoint/DrupalGap#27]
just on thought I came across playing around with the code... having a couple of files open in my editor, I realized that it is kind of annoying, to have like three tabs showing "node.js", module, page script and services include.

having line 484 in modules_load like
module_path =  module_base_path + '/' + module.name + '.module.js';

and 490 like 
modules_paths.push(module_base_path + '/'+ module + '.' + include_object.name + '.inc.js');

would make a naming convention like

node.js = page script
node.module.js = module
services.node.inc.js = include file for services

**Comment by signalpoint** [comment]
The file naming conventions have been ironed out over time, closing this issue.
