### ISSUE TITLE
Empty fields not sent to Services update so can't empty already set values

### ISSUE THREAD

**Issue by lifeinpoetry** [signalpoint/DrupalGap#275]
I noticed this recently. If you set a value for a text field, select field, etc., send the form, go back to the form, and then try to empty it by deleting all your text, selecting 'None,' etc.  nothing happens because only non-empty values are sent to Services update.

**Comment by signalpoint** [comment]
@GabrielleV thanks for pointing this bug out, I've fixed it. Grab the latest dev snapshot of the SDK for the fix:

www.drupalgap.org/download

**Comment by lifeinpoetry** [comment]
@signalpoint Thanks for fixing it so quickly, off to download the latest dev snapshot.
