### ISSUE TITLE
Node Language Code Undefined

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#28]
Original issue:

http://drupal.org/node/1931262

When clicking on a node on the dashboard, this error may show up:

'node.body[node.language]' [undefined] is not an object. at undefined:37.

When changing node language from "English" to "Neutral" in the node, the problem is fixed.

**Comment by yosemai** [comment]
Yes I subscribe this.  I'm trying to set nodes to 'und' language
