### ISSUE TITLE
Add support for list_boolean

### ISSUE THREAD

**Issue by lifeinpoetry** [signalpoint/DrupalGap#284]
Doesn't exist at this point.

Which leads to the value of the checkbox being wrong. In my case it's meant be "1" but has "0." Would need to do something with field.settings.allowed_values and shift and then shift to get "on" and "off" values. Using the "on" value to see if it's checked. Plus allowing the "on" value to be the label of the field, depending on instance.widget.settings.display_label.

Hope that's enough info.

**Comment by signalpoint** [comment]
@GabrielleV Please share your exact field settings / widget / etc, and I'll see what I can come up with, thanks!

i.e.

Field Type: Boolean ?
Widget: Singe on/off checkbox OR Check boxes/radio buttons ?
On value: ?
Off value: ?
Required: ?
Default value: ?
number of values: ?

**Comment by signalpoint** [comment]
Fixed.

**Comment by lifeinpoetry** [comment]
Sorry for not getting back earlier. Glad to hear it's fixed. :)
