### ISSUE TITLE
form submit handler and drupalgap_goto

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#285]
Is there a simple way to hijack a form submit handler to prevent node submit from going to node view?

**Comment by signalpoint** [comment]
@chrisschaub Try something like this:

```
form.action = 'my_path';
```

Do that in a hook_form_alter() to modify the node_edit_form.

**Comment by signalpoint** [comment]
Closing for now, re-open if it doesn't work.

**Comment by jomarocas** [comment]
hi, i used this, and doesnt work, always redirect to home
is simply this is my code for form submit and i try to modify the code of module user.forms.js but without works, thanks

`function my_module_form_alter(form, form_state, form_id) {
  try {
    if (form_id == 'user_register_form') {
      form.action = 'calendar';
    }

  }
  catch (error) { console.log('my_module_form_alter - ' + error); }
}`

**Comment by signalpoint** [comment]
@jomarocas You'd need to replace `drupalgap_goto('');` in https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/user/user.forms.js#L165 with `form.action` and it should work. You need to use grunt or the makefile to build the src code directory into the bin file(s): http://docs.drupalgap.org/7/Developer_Guide/DrupalGap_Core

**Comment by jomarocas** [comment]
sorry but dont working good  
          // the front page.
            if (form.auto_user_login) {
              user_login(account.name, account.pass, {
                  success: function(result) {
                    drupalgap_goto('menu-principal');
                  }
              });
            }
            else { drupalgap_goto('menu-principal'); }

and also make

```
        if (form.auto_user_login) {
          user_login(account.name, account.pass, {
              success: function(result) {
                form.action = 'menu-principal';
              }
          });
        }
        else { form.action = 'menu-principal' }
```

and still dont working
