### ISSUE TITLE
Request new password (reset password) inside the app

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#290]
Allow people the option to reset their password inside the app if they forgot it.  Allow them to provide an email address and then get the password emailed to them.  Which will allow them a onetime log in and then be prompted to reset their password.

**Comment by signalpoint** [comment]
There is an important issue with the Services module to take into consideration here: https://www.drupal.org/node/1303400

This feature is dependant on the outcome of this patch: https://www.drupal.org/node/1303400#comment-8975163

**Comment by ice423cube** [comment]
Is this possible now?  It looks like they closed that issue https://www.drupal.org/node/1303400?

**Comment by signalpoint** [comment]
@ice423cube No, the DG interface hasn't been updated to utilize this yet. I believe jDrupal needs to be updated as well to accommodate the new resource.

**Comment by signalpoint** [comment]
Here's a workaround that can be done via hook_form_alter() in a DrupalGap module:

```
if (form_id == 'user_login_form') {
  // Add a 'Request new password' link.
  form.suffix += '<div><center>' + l(
    'Request new password',
    Drupal.settings.site_path + '/user/password',
    { InAppBrowser: true }
  ) + '</center></div>';
}
```

**Comment by signalpoint** [comment]
Fixed: http://drupalgap.org/node/532
