### ISSUE TITLE
drupalgap_back() can still result in going to a blank page

### ISSUE THREAD

**Issue by obsidiandesign** [signalpoint/DrupalGap#298]
The fix to the drupalgap_back() function from [#177] can still lead to a blank page being served.  The issue stems from the fact that drupalgap.back_path is not reset after drupalgap_path_set(drupalgap.back_path) is called.  This causes drupalgap.path to be repeatedly set to the last value of drupalgap.back_path and so the conditional at the beginning of the function always returns true, unless 1) you are starting on the front screen or 2) you click the home button to get to the home screen.  Otherwise, when pressing the android hardware back button, you will go past the front screen and end on a blank screen.

**Comment by signalpoint** [comment]
@obsidiandesign Thanks for the debug info. Any ideas on the fix for this?

**Comment by obsidiandesign** [comment]
It seems that changing:
`if (drupalgap_path_get() != drupalgap.settings.front) {`
to
`if ($('.ui-page-active').attr('id') == drupalgap.settings.front) {` takes care of it.  I went a bit further and made it so that the back button went to the previous page except from the front page, where a dialog to close the box appears:

```
function drupalgap_back() {
  try {
    if ($('.ui-page-active').attr('id') == drupalgap.settings.front) {
      if (confirm('Exit ' + drupalgap.settings.title + '?')) {
        navigator.app.exitApp();
      }
    }  else {
      drupalgap.back = true;
      history.back();
      drupalgap_path_set(drupalgap.back_path);
    }
    return false;
    }
  catch (error) { alert('drupalgap_back' + error); }
}
```

**Comment by signalpoint** [comment]
@obsidiandesign Cool, I am adding this now. I can't figure out how to give your user name credit for the commit.

If you create a fork of DrupalGap, then clone your fork, make the change, commit the change, push the change, then submit a pull request, you'll be listed as the contributor to this fix. Please let me know if you're interested ASAP, thanks!

**Comment by ntym4ek** [comment]
This wouldn't work if route contains '-' symbol.
If drupalgap.settings.front set to 'main-catalog', $('.ui-page-active').attr('id') will return 'main_catalog'.

**Comment by signalpoint** [comment]
@ntym4ek Yes, that is correct and an unfortunate over sight on my part when I started building this a few years ago. I'd recommend using underscores instead of hyphens in DrupalGap paths.
