### ISSUE TITLE
Citations for modifying code

### ISSUE THREAD

**Issue by shuaib234abc** [signalpoint/DrupalGap#3]
I want to make a commercial iphone application using drupalgap. I want to modify the drupalgap code. Will I have to cite anywhere?

Since the code is under GNU license, will I have to make my modified code open source too.

Thank you!

**Comment by signalpoint** [comment]
I don't think you need to make your code open source. We have built a few
closed-source applications so far.

However, I am not the familiar with the fine print of the GNU license.

But you have my permission to take the code and modify it all you want and
keep your code private :)

On Sat, Sep 15, 2012 at 12:37 AM, shuaib234abc notifications@github.comwrote:

> I want to make a commercial iphone application using drupalgap. I want to
> modify the drupalgap code. Will I have to cite anywhere?
> 
> Since the code is under GNU license, will I have to make my modified code
> open source too.
> 
> Thank you!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/3.

## 

Regards,
Tyler Frankenstein

http://www.tylerfrankenstein.com

**Comment by signalpoint** [comment]
The LICENSE.txt file was added a while ago, so that should clear this up.
