### ISSUE TITLE
list_integer shows no value selected when there actually is a value

### ISSUE THREAD

**Issue by lifeinpoetry** [signalpoint/DrupalGap#300]
I have some select field dropdowns (list_integer) in DrupalGap on my Profile2 entity form. However, the value gets written over by the following in options_field_widget_form:

```
          items[delta].options[''] = '- None -';
          items[delta].value = '';
```

When I replaced that with: 

```
          items[delta].options[''] = '- None -';
          if (empty(items[delta].value)) {
            items[delta].value = '';
          }
```

the right values were selected when I reloaded the form.

**Comment by signalpoint** [comment]
@GabrielleV thanks, looks good! I also took your code and applied it to required select lists. Next time, feel free to create a pull request, that way GitHub will properly attribute the contribution to you ;)
