### ISSUE TITLE
More than two local tasks... puts active class on the wrong one

### ISSUE THREAD

**Issue by lifeinpoetry** [signalpoint/DrupalGap#301]
Not sure if I'm doing this wrong or if this is a bug. In hook_menu I have:

```
  items['user/%/content'] = {
    'title': "User's Content",
    'title_callback': 'sinet_user_content_page_title',
    'title_arguments': [1],
    'page_callback': 'sinet_user_content_page',
    'page_arguments': [1],
    'pageshow': 'sinet_user_content_page_pageshow'
  };
  items['user/%/content/view'] = {
    'title': 'Content',
    'type': 'MENU_DEFAULT_LOCAL_TASK',
    'weight': 1
  };
  items['user/%/content/comments'] = {
    'title': "Comments",
    'title_callback': 'sinet_user_comments_page_title',
    'title_arguments': [1],
    'page_callback': 'sinet_user_comments_page',
    'page_arguments': [1],
    'pageshow': 'sinet_user_comments_page_pageshow',
    'weight': 2,
    'type': 'MENU_LOCAL_TASK'
  };
  items['user/%/content/statuses'] = {
    'title': "Statuses",
    'title_callback': 'sinet_user_statuses_page_title',
    'title_arguments': [1],
    'page_callback': 'sinet_user_statuses_page',
    'page_arguments': [1],
    'pageshow': 'sinet_user_statuses_page_pageshow',
    'weight': 3,
    'type': 'MENU_LOCAL_TASK'
  };
```

This leads to the following when I click a link with a href of user/1/content:

![wrongmenuitemhighlighted](https://cloud.githubusercontent.com/assets/437978/3621578/32344b68-0e1a-11e4-8915-5d18635492fe.jpg)

The actual content that is supposed to be at the link shows up fine, it's just that the active class is on Statuses instead of Content.

**Comment by signalpoint** [comment]
@GabrielleV - your code looks right. That just sounds like a bug with the local task menu system.

On a side note, your app is looking great. Excellent use of icons. I'm curious how you got the home and back icons the way you did. And I'm also extra curious about the drop down menu you have going on the top right. Just today I was looking at #114 and building a plan for that fix. Feel free to share any of your code there if possible, thanks!

**Comment by lifeinpoetry** [comment]
Thanks!

I used classes available in jQuery  to position the buttons in the header. This is what my header code looks like in settings:

```
drupalgap.settings.menus.regions['header'] = {
  links:[
    /* Home Button */
    {
      title:'Home',
      path:'',
      options:{
        attributes:{
          "data-icon":"home",
          "class":"ui-btn-left",
          "data-iconpos":"notext"
        }
      },
      pages:{
        value:[''],
        mode:"exclude"
      }
    },
    /* Back Button */
    {
      title:'Back',
      options:{
        attributes:{
          "data-icon":"back",
          "class":"ui-btn-left",
          "onclick":"javascript:drupalgap_back();",
          "data-iconpos":"notext"
        }
      },
      pages:{
        value:[''],
        mode:"exclude"
      }
    },
    /* Menu Button */
    {
      title:'Menu',
      options:{
        attributes:{
          "data-icon":"bars",
          "class":"ui-btn-right",
          "onclick":"javascript:_sinet_slide_menu();",
          "data-iconpos":"notext"
        }
      },
    }
  ]
};
```

The menu on the side just slides down when clicked on and slides back up when clicked on again. I looked at #114 and it seems they were suggesting select. I just use a standard jqm_item_list. It looks like this when I first click on it:

![slidemenu](https://cloud.githubusercontent.com/assets/437978/3622725/940e19d2-0e3c-11e4-9244-f9620f7755bb.jpg)

If there were a more automated way to go about I'd definitely be interested because the links to some of the items lead to other menus so I have to check what is visible and what is not. The code is a bit of a mess.

**Comment by signalpoint** [comment]
@GabrielleV I may have fixed this issue while fixing another issue. Will you please pull in the latest snapshot of the SDK, and see if that fixes your problem?

**Comment by signalpoint** [comment]
@GabrielleV a few more things...
- With your home and back buttons, did you have to use custom CSS so they did not render on top of eachother?
- Will you share some of your code for your slide menu? I'd like to add support for menus like that.
- The latest dev snapshot of the SDK, automatically will turn your home and back button into a control group now, since they are both on the left side of the region. I've made a separate issue to turn off the control group wrap, for those that don't want the wrapper: #302

**Comment by lifeinpoetry** [comment]
@signalpoint  If I put 'Content' at the very end it will show up at as the last item with the active class. Weight doesn't seem to factor in on this particular menu but since I want to put 'Content' as the first menu item it doesn't fix my particular issue.

**Comment by lifeinpoetry** [comment]
@signalpoint

 **1.** Icons

Yes. I put

```
div[data-role="header"] a[data-icon="back"] {
  left: 2.5em;
}
```

Sorry, missed that part when I was looking at it though it wouldn't work if people used a different icon.

**2.** For the slide menu.

The following code hasn't been run through javascript lint but it's what is run when you click the menu button on the right. It does load some further menus in my case that will appear when you click 'Info' or 'Site.' 

```
function _sinet_slide_menu() {
  if ($.mobile.pageContainer.pagecontainer( "getActivePage" ).find('#main_flat_menu').size() === 0) {
    menu_load('menu-a-menu-no-depth', {
      success: function(results) {
        var menu_items = {
          items: [],
          attributes: {'id': 'main_flat_menu'}
        };
        $.each(results.tree, function(index, menu_item) {
          menu_items.items.push(l(menu_item.link.title, menu_item.link.path));
        });
        var html = theme('jqm_item_list', menu_items);
        $.mobile.pageContainer.pagecontainer( "getActivePage" ).find('#main_menu_flat_wrapper').append(html).trigger('create');
      }
    });
  }
  if ($.mobile.pageContainer.pagecontainer( "getActivePage" ).find('#main_site_menu').size() === 0) {
    menu_load('menu-a-menu-site', {
      success: function(results) {
        var menu_items = {
          items: [],
          attributes: {'id': 'main_site_menu'}
        };
        $.each(results.tree, function(index, menu_item) {
          if (menu_item.link.path == 'users') { menu_item.link.path = 'user-listing'; }
          else if (menu_item.link.path == 'tracker') { menu_item.link.path = 'node-listing';  }
          menu_items.items.push(l(menu_item.link.title, menu_item.link.path));
        });
        var html = theme('jqm_item_list', menu_items);
        $.mobile.pageContainer.pagecontainer( "getActivePage" ).find('#main_menu_site_wrapper').append(html).trigger('create');
      }
    });
  }

  $('.region_navigation_slide').slideUp();

  if ($('.region_navigation_slide').is(":visible") || $('.region_hidden_navigation').is(":visible")) {
    $('.shade').hide();
    $('.region_hidden_navigation').slideUp();
  } else {
    $('.shade').show();
    $('.region_hidden_navigation > div').hide();
    $('.region_hidden_navigation > div[id$="menu_navigation_slide_menu"]').show();

    $('.region_hidden_navigation').slideDown();
  }

  return false;
}
```

The CSS is:

```
.region_hidden_navigation {
  position: fixed;
  z-index: 1101;
  top: 0;
  left: 0;
  width: 100%;
  margin: 0;
  padding: 0;
  margin-top: 42px;
}
```

The region is:

```
        "hidden_navigation":{
          "attributes":{
            "data-role":"navbar",
            "style":"display:none",
          }
        },
```

The following adds the dark background but I'm likely going to remove it:

```
.shade {
  display: none;
  position: absolute;
  top: 42px;
  bottom: 0;
  width: 100%;
  min-height: 468px;
  z-index: 39 !important;
  background: #333;
  padding: 0;
}
```

**3.** Thanks for adding a control group, will look into using it.

**Comment by signalpoint** [comment]
@GabrielleV the latest dev snapshot of the bin/drupalgap.js should now fix the majority of these problems. Please try it out.

I'm curious if the latest version also resolves your menu link's "weight" issue described here: https://github.com/signalpoint/DrupalGap/issues/301#issuecomment-49531662

Please confirm, thanks!
