### ISSUE TITLE
Float Field

### ISSUE THREAD

**Issue by Plabanm** [signalpoint/DrupalGap#322]
Hello

In my content type there are some link fields. when going through the app it saying field type is not supported. As well as float is not supported either.

Screen shot of the problem.....
![screen shot 2014-08-05 at 10 41 28](https://cloud.githubusercontent.com/assets/4824797/3809504/d8862fcc-1c84-11e4-81bc-247e0622b7ae.png)

JavaScript consol ....

```
Console was cleared
Ripple :: Environment Warming Up (Tea. Earl Gray. Hot.)
Uncaught SyntaxError: Unexpected token u apizoom.net/mobile-application/:1
Failed to load resource: the server responded with a status of 404 (Not Found) http://apizoom.net/mobile-application/config.xml
'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.
cordova :: Initialization Finished (Make it so.)
The key "target-densitydpi" is not supported. apizoom.net/mobile-application/:7
cordova :: fired deviceready event!
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
number_field_widget_form - element type not supported (number_float)
WARNING: _drupalgap_form_render_element_item() - Field number_float not supported.
Object
WARNING: _drupalgap_form_render_element() - user_reference_field_widget_form() does not exist for the "user_reference" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
```

**Comment by signalpoint** [comment]
@Plabanm Did you install the link module? http://www.drupalgap.org/project/link

Float isn't supported yet, but it should be pretty easy to add. Checkout the number_field_widget_form() function.

**Comment by Plabanm** [comment]
Hello
Yes, I have installed link module. Did not work. I have added to settings.js..
is there anything else I should do to make it work ?
I am kinda new in this... Little bit more information will be very helpful about float.

cheers

**Comment by Plabanm** [comment]
I have tried to add this bit of code but not working..

<code>
case 'number_float':
        // Change the form element into a number, and then set its min/max
        // attributes along with the step.
        items[delta].type = 'Float';
        if (!empty(instance.settings.max)) {
          items[delta].options.attributes['min'] = instance.settings.min;
        }
        if (!empty(instance.settings.max)) {
          items[delta].options.attributes['max'] = instance.settings.max;
        }
        items[delta].options.attributes['step'] = 2;
        break;
</code>

**Comment by signalpoint** [comment]
@Plabanm try just adding this:

```
switch (element.type) {
      case 'number_integer':
      case 'number_float':
```

Then I think jQM will map it properly: http://stackoverflow.com/a/8099775/763010

**Comment by Plabanm** [comment]
Tried both ways... not working..
how about Link Field .. not working either..

**Comment by signalpoint** [comment]
@Plabanm are you running the makefile to compile the bin/drupalgap.js file?

Please make a separate issue for the link module (check for duplicates first).

**Comment by Plabanm** [comment]
no. I did not. guess thats the problem. 
I am working With Google Chrome and the Ripple Emulator...
seems like the instruction for compiling is for  PhoneGap and a Mobile Device (or emulator)..

please help.

**Comment by signalpoint** [comment]
@Plabanm These instructions will work for any development platform:

http://www.drupalgap.org/node/224

Or you can edit the bin/drupalgap.js file directly (not recommended).

**Comment by Plabanm** [comment]
Hello again ...

Tried compiling and both ways..
not working.. any other suggestion  ?

cheers

**Comment by signalpoint** [comment]
@Plabanm for better support, I need more information than just "not working".

To accurately debug this, please at minimum, paste the code you are trying here, or push up the broken code into your forked repo, and we can take a look.

**Comment by Plabanm** [comment]
Sorry about that.. I will keep in mind for future requests.
Anyways .. It worked.
you were right all along. Simple fix worked.
here is the newly complied file https://www.dropbox.com/s/83gkp8b5ysjyrp3/drupalgap.js

Thanks for your help. 
Cheers.

**Comment by signalpoint** [comment]
@Plabanm thank you for pointing out the problem, and testing the fix. I've committed the fix, grab the latest bin/drupalgap.js for the fix.
