### ISSUE TITLE
Link Field

### ISSUE THREAD

**Issue by Plabanm** [signalpoint/DrupalGap#325]
Hello
I have link as field type. Although when viewing the node everything is working problem is when I ma trying to create a node. Links field shown as not supported. I have installed and added to settings.js but no result.

here is a screet shot...

![screen shot 2014-08-05 at 10 41 28](https://cloud.githubusercontent.com/assets/4824797/3817371/6bde854c-1cd7-11e4-9ae5-f5547a7ee881.png)

code snippet from JS console 
<code>Object
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element() - link_field_widget_form() does not exist for the "link_field" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
number_field_widget_form - element type not supported (number_float)
WARNING: _drupalgap_form_render_element_item() - Field number_float not supported.
Object
WARNING: _drupalgap_form_render_element() - user_reference_field_widget_form() does not exist for the "user_reference" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
Object</code>

Thanks for your help :)

**Comment by signalpoint** [comment]
@Plabanm sorry, I thought this was already implemented. I guess not. So in the link.js file this will need to be added:

```
/**
 * Implements hook_field_widget_form().
 */
function link_field_widget_form(form, form_state, field, instance, langcode, items, delta, element) {
  try {
    //dpm('link_field_widget_form');
    //dpm(items);
  }
  catch (error) { console.log('link_field_widget_form - ' + error); }
}
```

It will then have to be fully implemented, check out other module's implementation of hook_field_widget_form() for examples (i.e. number, options, text, date, geofield, etc: http://api.drupalgap.org/)

I'd recommend making a fork of the link module, then cloning it. Then you'll be able to push up your contributions: https://github.com/signalpoint/link

**Comment by Plabanm** [comment]
I am new and confused. Please help me.
At least give me more info..
I tried some code..
No change.. 

Please help me. Link field is very important for my project.

**Comment by signalpoint** [comment]
@Plabanm You use hook_field_widget_form() to specify how the field will be displayed on an entity's form.

Go to api.drupalgap.org, and search for '_field_widget_form' and you'll see how other modules implement it. Essentially you need to use dpm() to look inside the field and instance objects, and from their inner variables/properties you can determine how to set up the widget when it shows up on a form through the DrupalGap Forms API.

This is a more advanced topic, but it is learnable ;)

**Comment by Plabanm** [comment]
It is but given my experience, Situation and what I have seen so far, I won't be able to fix it.
I am looking at using text filed and convert it to link.

Is there any way that I can turn off those Link Field coming visible on my app ? Its better be invisible then saying not supported ! 

please let me know. Or if anyone can fix the issue will be greatly appreciated.

Cheers

**Comment by signalpoint** [comment]
@Plabanm You can use hook_form_alter() on the node_edit form in a custom module to set the access of the field to false:

```
form.elements['my_custom_field'].access = false;
```

Alternatively, feel free to sponsor an hour or two of development (www.easystreet3.com/purchase-time), and the Link module should be able to be completed ;)

**Comment by Plabanm** [comment]
I would but $130 is big money..
I am a student and this is a small part of my project. chosen big, chosen wrong.
hope you understand.

cheers

**Comment by signalpoint** [comment]
@Plabanm Understandable, best of luck with the schoolings!

I do have a few projects coming up that need the Link field, so I'm sure it'll get implemented in the next few weeks/months.

**Comment by Plabanm** [comment]
weeks sounds better than months :)
I will be watching for updates.

Thanks for all the support.

**Comment by signalpoint** [comment]
The hook_field_widget_form() function has been implemented in the link module for drupalgap: https://github.com/signalpoint/link/blob/7.x-1.x/link.js
