### ISSUE TITLE
hook_form_alter() with async vs sync, and form state values callback

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#326]
I'm trying to add a select list using form_alter to an existing form. I keep getting this error on the select list I'm trying to add:

options_field_widget_form - TypeError: Cannot read property 'widget' of undefined 

```
form.elements['foo_select'] = {
                type: 'select',
                title: 'Select a Foo',
                name: 'foo_select',
                id: 'edit-commerce-checkout-view-foo_select',
                required: true,
                options: result.valid_card_options,
                widget: {type: 'options_select'},
                default_value: result.default_valid_card_options
              }; 
```

Do I need the "widget" stuff? Any help is appreciated.

**Comment by signalpoint** [comment]
@chrisschaub If you're adding a custom select list, you won't need the widget stuff. Widgets are only used for fields.

What does a dpm(result.valid_card_options) look like?

What form are you altering? If it's a built in commerce form (i.e. add to cart), it's possible another field is having widget problems.

It appears its something to do with Commerce, so FYI: https://github.com/signalpoint/commerce/blob/7.x-1.x/commerce.js#L693

^ That's an bug, if you haven't already, be sure to change that to your product reference field's machine name.

**Comment by chrisschaub** [comment]
So, it was interesting. We've been working on extending the commerce module for Drupalgap to have commerce_cardonfile and commerce_nodepay modules. We're almost there and will try to submit stuff back via git. Anyway, as a side note about form_alter, maybe for the doc.

If you are using hook_form_alter in drupalgap and want to make a call with a try/success, you need to make sure the call is "synchronous", not "async" which is the default. So, ..

```
async: false,
success: ...
```

That way, your fetching data finishes and then the form gets altered. Otherwise, your for gets altered but the data to inject or alter the form has not arrived yet! Just a little gotcha that had me stumped for a bit. Not really a drupalgap problem, more of jQuery design issue that impacts the form_alter hook concept.

Thanks!

**Comment by signalpoint** [comment]
@chrisschaub That's good news RE: commerce stuff, definitely please contribute that stuff if you can when you're done.

As for the hook_form_alter() with an async call, you're right. Any async calls will finish after the form has already been altered. Switching to sync is the way around it, but could be bad for user experience depending on connection factors.

This same "problem" holds true during form validation and submission. Related issue: https://www.drupal.org/node/2170491

I think it would be nice if we eventually had an e.g. after_build handler that could be attached to forms which would fire on the pageshow event for extra modifications.

**Comment by chrisschaub** [comment]
Yeah, the after_build might be nice. What is the best way to set the weight of elements during form_alter? Thanks!

**Comment by signalpoint** [comment]
@chrisschaub it should just be:

```
form.elements['my_element'].weight = 123;
```

Remember, didn't you implement that fix? ;)

**Comment by chrisschaub** [comment]
Ooops, yes sorry!

On Fri, Aug 8, 2014 at 11:52 AM, Tyler Frankenstein <
notifications@github.com> wrote:

> @chrisschaub https://github.com/chrisschaub it should just be:
> 
> form.elements['my_element'].weight = 123;
> 
> Remember, didn't you implement that fix? ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/326#issuecomment-51628538
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
One last question on this form_alter stuff. I've altered a form, added a few fields. I enter values in the text boxes, submit and the added fields come through as empty, null. Is there something I have to do besides altering a form to allow the added fields to get posted? They appear on the screen but the data does not get passed somehow. The un-altered fields are getting passed.

**Comment by signalpoint** [comment]
@chrisschaub Depends what you mean be "added a few fields". I'm assuming you mean you've added custom form elements to the form. The DGFAPI does (do its best to) assemble the form state values and pass them along to submit handlers.

Please share you form alterations, and the dpm(form_state), and any service calls.

**Comment by chrisschaub** [comment]
Yeah, I've added a few form elements. They show in the form, form_state --
but the values do not make it from the form into the _submit handler. So
somehow the form_state is not getting updated on submit?
- Chris

On Mon, Aug 11, 2014 at 8:02 AM, Tyler Frankenstein <
notifications@github.com> wrote:

> @chrisschaub https://github.com/chrisschaub Depends what you mean be
> "added a few fields". I'm assuming you mean you've added custom form
> elements to the form. The DGFAPI does (do its best to) assemble the form
> state values and pass them along to submit handlers.
> 
> Please share you form alterations, and the dpm(form_state), and any
> service calls.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/326#issuecomment-51776485
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by signalpoint** [comment]
@chrisschaub  Please share your form alterations here so it can be debugged, or I can't accurately debug this.

**Comment by chrisschaub** [comment]
So, I haven't pasted it in because it's a little complicated. Let me explain the situation a bit more. We are using the commerce module for drupalgap. We have two add-on modules, nodepay and commerce_cardonfile that both have form_alter hooks to add things to the checkout form. The fields get added just fine, but I think the function that assembles the form_state on submit is getting stale information. It probably doesn't surface on a single form_alter. Here's a simplified example of a field that draws and accepts input, but does not get passed on submit. The field is there, just with a null value.

```
function commerce_cardonfile_form_alter(form, form_state, form_id) {
  if (form_id == 'commerce_checkout_view') {
    // payment info fields ...
    form.elements['card_number'] = {
      type: 'textfield',
      title: 'Card Number',
      options:{attributes:{}}
    };
  }
}
```

Oddly, I have to add the "options" or it doesn't work, get a js error. Anyway, I think the problem is in function drupalgap_form_state_values_assemble() which seems to not know about all of the fields on submit. So to reproduce, maybe try adding two custom modules with form_alter to add some fields to the commerce checkout form. Just waking up, getting coffee, going to be debugging this further but any insight is appreciated.

**Comment by chrisschaub** [comment]
Ahhh, I think I have it solved. I'm calling a custom submit function and forgot to add the line to assemble the form_state. Just reviewed commerce and you are calling it there.

**Comment by signalpoint** [comment]
@chrisschaub That's good. Yes you are right, you may or may not have to place your values into the form state depending on the element. The DGFAPI does its best to auto assemble the form state values.

Also, I'd like to point out the `value_callback` property that can be used on form elements. Check out the webform.js file for example usage:

https://github.com/signalpoint/webform/blob/7.x-3.x/webform.js

Essentially, you set a function name on your element:

```
my_element.value_callback = 'my_custom_function';
```

And the function will be called:

```
function my_custom_function(id, element) {
  // Figure out my value, return it, examples:
  return 'abc';
  return 123;
  return { foo: bar; }
}
```

Look inside `id` and `element` for ways to access to the form element's widget.

**Comment by chrisschaub** [comment]
Ok, that wasn't it -- it was much simpler. And maybe something for the doc. You have to use drupalgap_form_get_element_id so that the id of your form element can be found by the code that populates the form_state. If you free form your ids then it will never get passed. I changed the alter to be this ...

```
title: 'Select a Card',
id: drupalgap_form_get_element_id(field_name, form_id),
```

and the values started passing. Maybe I missed it in the doc? Thanks!

**Comment by signalpoint** [comment]
@chrisschaub Thanks for pointing that out. I've updated the docs to include an example of adding an element to an existing form:

http://drupalgap.org/node/156

As you pointed out, it's important to note that the DGFAPI apparentely does not automatically give an element an id, when that element has been appended via a hook_form_alter(), so you have to give your custom element its own id, using the function mentioned above, or else your element's value will not get assembled into the form state values.
