### ISSUE TITLE
How to Search for Drupal Content

### ISSUE THREAD

**Issue by loveisabird777** [signalpoint/DrupalGap#33]
hi ,

i want step by step tutorial or guidance for creating a drupalgap app that can search content on drupal site .

can anybody help me 

regards

**Comment by divinzer** [comment]
hi. I want that too

help me TT

나의 iPhone에서 보냄
1. 3. 13. 18:21 loveisabird777 notifications@github.com 작성:

**Comment by ghost** [comment]
Also say I have a webform module and I wish my users to fill up the webform how can i do it from Drupalgap Or may be I define my own kind of content type which has images , locations ( lat lon) and description so how can i do it in drupal gap

**Comment by signalpoint** [comment]
At this time DrupalGap doesn't support Drupal's core search. The easiest way to accomplish something similar, is setting up a View (w/ views datasource, views json) that takes in a node title contextual filter and applies the mysql LIKE query. The JSON results of the view w/ contextual filter can then be fed to the App and displayed.

**Comment by signalpoint** [comment]
@loveisabird777, as for webform and location support, these have been migrated to separate issues here:

https://github.com/signalpoint/DrupalGap/issues/34
https://github.com/signalpoint/DrupalGap/issues/35

**Comment by signalpoint** [comment]
This feature has been added, see here:

http://drupalgap.org/node/231

**Comment by ghost** [comment]
Hi can you put a tutorial with view search ? Say for example I want a
proximity search based on the gps location from my phone is that possible ?
Can you please guide ?

**Comment by signalpoint** [comment]
@loveisabird777 It is possible, unfortunately I don't have time to offer free support on that topic. If you're interested in sponsoring an hour of development, I can make it happen.

**Comment by ghost** [comment]
What kind of development ?

**Comment by signalpoint** [comment]
@loveisabird777 If you'd like to purchase (aka sponsor) an hour of development (www.easystreet3.com/purchase-time), I can write up a tutorial on this. Otherwise, I've added it to my list of requested tutorials. Good luck, and happy coding!

**Comment by mkinnan** [comment]
Does Drupalgap support search in Views yet? It appears to be broken if it does:

![search](https://cloud.githubusercontent.com/assets/13283396/15766239/9e602432-28f9-11e6-86cc-2012815b5a55.PNG)

console.log error:
`list_views_exposed_filter - TypeError: Cannot set property 'All' of null`
