### ISSUE TITLE
Listing page node

### ISSUE THREAD

**Issue by Arch1S** [signalpoint/DrupalGap#333]
Content list displays only 10 items, and I have 100 items, the list does not display pages. Visible only to the first page. Tell me what's the problem?

**Comment by signalpoint** [comment]
The built in node listing page doesn't have paging support.

To build your own list of nodes, with paging, check out this page (and sub pages): http://drupalgap.org/node/82

**Comment by Arch1S** [comment]
thank you! 

sorry for the simple question 

how do I make these buttons << >> on node?

![views-pager-top](https://cloud.githubusercontent.com/assets/67203/3946716/6440ef9e-267a-11e4-9b21-e6d2aac3a6a1.png)

**Comment by signalpoint** [comment]
```
<div data-role="controlgroup" data-type="horizontal">
<a data-role="button">&laquo;</a>
<a data-role="button">&raquo;</a>
</div>
```

**Comment by Arch1S** [comment]
thank you signalpoint

please tell me the code to the page switched

**Comment by signalpoint** [comment]
@Arch1S Please refer to the online documentation for more information, or create separate issues.

Information about DrupalGap Pages can be found here: http://drupalgap.org/node/75
