### ISSUE TITLE
Navigating pages

### ISSUE THREAD

**Issue by Arch1S** [signalpoint/DrupalGap#334]
how to make that button << >> to switch pages?

![views-pager-top](https://cloud.githubusercontent.com/assets/67203/3956151/0bdca86e-2708-11e4-925b-5e59bdd9e1e4.png)

**Comment by signalpoint** [comment]
@Arch1S Views paging is built into DrupalGap core: http://drupalgap.org/node/251

If you are interested in making your own buttons, that navigate to custom pages in the app, look at this page: http://drupalgap.org/node/137

**Comment by Arch1S** [comment]
@signalpoint how to call views paging?

**Comment by signalpoint** [comment]
Views paging is built into DrupalGap core. Please spend some time reading through the docs online, it explains how Views work in DrupalGap: http://drupalgap.org/node/82

**Comment by Arch1S** [comment]
all docs revised, it is impossible to make the pages 
you have sample code as in the picture?

![drupal-views-pager-ui](https://cloud.githubusercontent.com/assets/67203/3957872/d234161c-2719-11e4-86a7-1056b7fca098.png)

**Comment by signalpoint** [comment]
@Arch1S I don't understand the question.

**Comment by Arch1S** [comment]
sample code from the picture you have?
sorry translate google

**Comment by signalpoint** [comment]
This page contains sample code to display a View: http://drupalgap.org/node/219

This page contains instructions on how to create the View: http://drupalgap.org/node/234

**Comment by Arch1S** [comment]
works thanks @signalpoint !!
