### ISSUE TITLE
Webform Module Support

### ISSUE THREAD

**Issue by loveisabird777** [signalpoint/DrupalGap#34]
Say I have a webform content type and I wish my users to fill up the webform, how can I do that with DrupalGap?

**Comment by signalpoint** [comment]
DrupalGap doesn't support the Webform module at this time. It is on our roadmap, but it is still a ways out. Please feel free to contribute to help this come to light.

**Comment by signalpoint** [comment]
Webform support has been added: http://drupalgap.org/project/webform

**Comment by chethanap** [comment]
Hi, I love Drupal but I am not an expert - truly appreciate any help and guidance.

I have been trying to create an app with webforms without much luck. Here is what I have done so far 
(followed the instructions from Building Mobile Apps by Example, Tyler Frankenstein - https://www.youtube.com/watch?v=Q8-G8g-ixi4 and
http://www.drupalgap.org/project/webform)

Installed Drupal 7.41
Modules – 
- Admin_menu
- Ctools
- Drupalgap
- Entity
- Entityreference
- Libraries
- Services
- Views
- Views_datasource

With the above modules, I am able to view the contents (basic page and articles) on Google Ripple emulator. 

Added few more modules to bring in webform functionality (followed instructions from  http://drupalgap.org/project/webform, applied the patch and did the configuration instructions)
• Webform
• Webform_service (applied the patch)
• Uuid
• Webform_submission_uuid

When I add these modules to create web forms, it even stops displaying the contents of basic page and articles which were working just fine on Google Ripple before. And Webforms does not even work.

so the issues I have –
1.  Before installing the webform (& it’s related modules) module, I was able to see the contents on my app (Chrome  Ripple) but after that, the app does not show anything. It lists the contents but when I click on it will take me to a blank screen with “View” (selected) and “Edit” options without displaying the content.
2.  Webform is not at all working (nothing is working on the app for that matter)

I also tried installing webform from http://drupalgap.org/project/modules in Configuration -> Web Services -> DrupaGap -> Modules. With that, it added up one more tab “Results”  (View, Edit, Results) for each content (including page and article) type without displaying any content. And also, when I click on “Results”, it shows an error message “Webform_submission_index is deprecated! Use webform_submissions() instead”. Not sure how to fix that either.

I keep testing the connection in Drupalgap and it is connecting properly (The system connect test was successful, DrupalGap is configured properly!).

I am not sure whether I need to do anything in Views. I tried adding ‘Content: Body (Body)’ under ‘Fields’ for Structure->Views->’drupalgap_content’ but no luck.

I must be missing something very important but I am not able to figure it out.It would be extremely  helpful if any of the drupal experts can create a tutorial on webforms for mobile apps. Thanks.

**Comment by signalpoint** [comment]
@chethanap Next time please open a new issue since this one has been closed for 1.5 years. We need to see the console.log output from your developer tools, that should provide insight in what the problem is.

**Comment by chethanap** [comment]
Thanks for your reply. I am extremely sorry. I am very new to this - please guide me. How/where should I open a new issue. Since my issue was related to webform, I put it here. It would be very helpful if you can add a tutorial on DrupalGap Webforms.
