### ISSUE TITLE
Content and Users not displaying in Ripple simulator

### ISSUE THREAD

**Issue by mfuggle** [signalpoint/DrupalGap#345]
I have just reinstalled Drupalgap and use Chrome with the Ripple simulator. The mobile app displays fine but the lists of Content and Users no longer display any entries. A list of Taxonomies displays OK. Any ideas what might be causing this?

**Comment by signalpoint** [comment]
@mfuggle The default content and user lists are powered by these Views:

```
admin/structure/views/view/drupalgap_content
admin/structure/views/view/drupalgap_users
```

Check the settings on those Views in the Drupal UI, and verify they are returning results.

They are really only meant for demonstration, and you should look to build your own Views:

http://www.drupalgap.org/node/82

Also, set `drupalgap.settings.debug` to `true` in the settings.js file, then in Chrome, open the JavaScript console to watch for calls made to the server. That should reveal to you information about the app's attempts to call the server for the lists of content and/or users.

**Comment by clivesj** [comment]
If the data displays the View succesfully in Drupal but not in the app, clear the cache.
