### ISSUE TITLE
Views Exposed Filters

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#354]

**Comment by signalpoint** [comment]
Support for Views Exposed Filters has been added. As of writing this comment, the following exposed filters have support:
- Published
- List (text) / Select list
- Taxonomy Term Reference

The architecture for this feature is ready to support other exposed filters. Whenever an exposed filter isn't supported, info will be output to the console.log() explaining which function(s) need to be implemented to support that particular exposed filter. If you want support for an individual exposed filter, please try contributing to DrupalGap core, or add a separate issue for each filter needed.

**Comment by signalpoint** [comment]
There is now a documentation for Views Exposed Filters on the website: http://drupalgap.org/node/498

**Comment by TheDucc** [comment]
I have followed the documentation to the letter (including changing the submit button label to "Apply Filters"); to no success.
This is my view output in JSON:

```
{
    "nodes": [
        {
            "node": {
                "title": "Article 1",
                "nid": "2"
            }
        },
        {
            "node": {
                "title": "Article 2",
                "nid": "3"
            }
        }
    ],
    "view": {
        "name": "my_articles",
        "display": "page",
        "path": "my-articles",
        "root": "nodes",
        "child": "node",
        "pages": null,
        "page": null,
        "count": 2,
        "limit": null
    }
}
```

I suspect that the view object should contain and exposed_data item based on these lines of code:
<code>
// Render the exposed filters, if there are any.

```
var views_exposed_form_html = '';

if (typeof results.view.exposed_data !== 'undefined') {

  views_exposed_form_html = drupalgap_get_form(

    'views_exposed_form', {

      exposed_data: results.view.exposed_data,

      exposed_raw_input: results.view.exposed_raw_input,

      filter: results.view.filter,

      variables: variables

    }

  );

}
```

</code>

But forcing the IF to be true gives me a error when trying to get the form.
Can you offer some guidance on my error?

**Comment by signalpoint** [comment]
@TheDucc this feature hasn't quite been officially released yet, you'll need to update the DrupalGap module on your Drupal site to the dev version for this to function properly, and update the DrupalGap SDK to the latest `bin/drupalgap.js`.

When set up properly, you'll see JSON related to the exposed filters in lieu of your first example block above.

**Comment by TheDucc** [comment]
SUCCESS!!
Many thanks for the quick and completely useful response.

dmducc

**Comment by stvx** [comment]
I have followed everything on the documentations, updated the drupal gap latest bin/drupalgap.js. but no results yet, Do i need to manually create a block for the drop down filter?? what did I miss??

**Comment by signalpoint** [comment]
@stvx You must use a Views Render Array in DrupalGap to have the exposed filters show up. At this time only a few different types of filters are supported. Set debug to true in settings.js and watch the console.log output, what does it say?

**Comment by stvx** [comment]
It works, .... Thanks a lot...
But when i click on the list I get an error that says  " failed to load entity, only single id's supported " and doesn't allow to display or edit the node, 
What went wrong??

**Comment by signalpoint** [comment]
@stvx thank you for reporting the resolution of this issue. If you have a new issue, please open a new issue, however be advised that a Google search for that error will most likely results for you, please try that at a minimum, thank you.

**Comment by nithinkolekar** [comment]
> this feature hasn't quite been officially released yet, you'll need to update the DrupalGap module on your Drupal site to the dev version for this to function properly

If we use dev version then "install the SDK" button will not shown just as described here http://drupalgap.org/node/132 and we can't setup mobile-application directory. Is there any workaround for this if we need to test "views exposed filter"?

**Comment by signalpoint** [comment]
@nithinkolekar where did you see that message? The feature has been released for a while now.

**Comment by nithinkolekar** [comment]
@signalpoint 
its in the same admin/config/services/drupalgap path where it should show  "install the SDK" and install the required files to mob-app directory. But with drupalgap-7.x-2.x-dev.tar.gz (from DO) that button is missing and there is no other method described in any of the tutorials at druapalgap.org on how to install SDK manually into drupal website , ie can we create mob-app directory manually and extract the SDK code in that directory.
I updated to dev version manually after following http://drupalgap.org/node/132  with 7.x-1.13 (which is a recommended version currenly) for intial working setup. Now I can only see only apply button in ripple emulator with missing select list exposed filter which is a term reference. Other pagination elements(http://drupalgap.org/node/251) are showing and working properly.

**Comment by signalpoint** [comment]
@nithinkolekar All documentation on drupalgap.org refers to DrupalGap 7.x-1.x.

DrupalGap 2.x (for Drupal 7 and/or 8), is not ready for production, and its documentation will exist in the "docs" folder within the source code for the project: https://github.com/signalpoint/DrupalGap/tree/7.x-2.x/docs

Did you use Drush to update to the dev version? I've noticed some Drush installations ignore the fact that I have 7.x-2.x _not_ specified as the recommended version, and it'll still grab it anyway. Just be careful to stick with 7.x-1.x.

**Comment by nithinkolekar** [comment]
@signalpoint 
Just removed mob-app directory, uninstalled 7.x-2.x , cleared cache and finally installed 7.x-1.x dev just as you mentioned but still, only "Apply" button is rendering in emulator. I also checked whether is is ovelapping the select element but it is not rendering at all in exposed form.(checked in chrome's developer tools). 
BTW that exposed filter's select element is showing properly while previewing in views JSON display.

Is there something we have to add to render array code( http://drupalgap.org/node/219)?

**Comment by nithinkolekar** [comment]
views exposed filter not working anymore #580
