### ISSUE TITLE
make, line lenghts

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#355]
Up until a few weeks ago, I was able to rebuild cleanly using make. Now I keep getting errors like ...

----- FILE  :  
drupalgap.js -----
Line 811, E:0110: Line too long (81 characters).
----- FILE  :  
menu.inc.js -----
Line 176, E:0010: Missing semicolon at end of line
----- FILE  :  
menu.js -----
Line 126, E:0110: Line too long (87 characters).
Line 127, E:0001: Extra space at end of line
Line 193, E:0110: Line too long (84 characters).
----- FILE  :  
views.js -----
Line 245, E:0110: Line too long (84 characters).
Found 6 errors, including 1 new errors, in 4 files (17 files OK).

Is there a way to set the line lengths longer or set some setting to allow jslint to allow it to make? I'm trying to test a patch for private files. Thanks!

**Comment by signalpoint** [comment]
@chrisschaub Yeah, I've been lazy on that. And that's why I created the makefile_lite, so you can get away with it like so:

```
cp makefile_lite makefile
make
```

Feel free to clean up the syntax errors ;) I think there is even a scrubber command that will do it autmotically.
