### ISSUE TITLE
Add entity type and bundle class names to page container div for CSS

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#358]
It'd be really nice for themeing purposes if we had the entity type and bundle listed as class names on entity page container divs, e.g.

```
<div id="node_123" data-role="page" class="node node-article"><!-- ... --></div>
```

Keep in mind this should be on the page container, not the internal div container used to inject the entity content on the pageshow entity load.

**Comment by signalpoint** [comment]
This is tricky because when the page container is added to the DOM, the entity bundle isn't known yet, i.e. node types aren't determined until the pageshow event. This means we'd have to dynamically inject the class names into the page container, and redraw the page (bad bad). It seems like the best we can do it get these handy class names on the internal div containter instead, darn.

**Comment by signalpoint** [comment]
We may just need to make one more internal div wrapper which will include the entity's bundle as a class name.

**Comment by jomarocas** [comment]
Hi @signalpoint is a good idea, i look that this implementation no working in edit node, appear always so, 

 `<div class="node ui-page ui-page-theme-a ui-page-header-fixed ui-page-footer-fixed ui-page-active" data-role="page" id="node_99" data-url="node_99" tabindex="0" style="padding-top: 43px; padding-bottom: 50px; min-height: 355px;">`

**Comment by signalpoint** [comment]
@jomarocas This is finally ready, a much needed feature indeed!

**Comment by jomarocas** [comment]
@signalpoint thanks for your contribution, i try to update to latest version to testing, thanks again
