### ISSUE TITLE
Drupal.user is 0

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#359]
So, in a hook_form_alter, I'm trying to interrogate Drupal.user ... but the uid is 0. And I'm logged in, can do logged in things. Is there a way to get the user data in form_alter? Too early in the process? Thanks.

-c

**Comment by signalpoint** [comment]
@chrisschaub The user data will be available in a hook_form_alter().

I just confirmed this, with a simple:

```
/**
 * Implements hook_form_alter().
 */
function my_module_form_alter(form, form_state, form_id) {
  try {
    dpm('my_module_form_alter');
    dpm(Drupal.user);
  }
  catch (error) { console.log('my_module_form_alter - ' + error); }
}
```

The only time Drupal.user isn't available is in the settings.js file, and during hook_install(). After that, the DOM is loaded and manipulated from there on out, so the Drupal.user object will always be available.

Maybe Ripple's Cross Domain Proxy needs to be disabled, I've seen it get confused with sessions sometimes.

Other than that, please provide more context about your form, or else I'm not sure what is happening.

**Comment by chrisschaub** [comment]
thanks, my bad

On Thu, Aug 28, 2014 at 8:46 AM, Tyler Frankenstein <
notifications@github.com> wrote:

> @chrisschaub https://github.com/chrisschaub The user data will be
> available in a hook_form_alter().
> 
> I just confirmed this, with a simple:
> 
> /**
> - Implements hook_form_alter().
>   */
>   function my_module_form_alter(form, form_state, form_id) {
>   try {
>     dpm('my_module_form_alter');
>     dpm(Drupal.user);
>   }
>   catch (error) { console.log('my_module_form_alter - ' + error); }
>   }
> 
> The only time Drupal.user isn't available is in the settings.js file, and
> during hook_install(). After that, the DOM is loaded and manipulated from
> there on out, so the Drupal.user object will always be available.
> 
> Maybe Ripple's Cross Domain Proxy needs to be disabled, I've seen it get
> confused with sessions sometimes.
> 
> Other than that, please provide more context about your form, or else I'm
> not sure what is happening.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/359#issuecomment-53721418
> .

## 

Christopher Schaub
http://chris.schaub.com
