### ISSUE TITLE
Variable scope

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#360]
I'm trying to figure out a scope issue with Drupalgap. Maybe it's just a javascript thing or an issue where form_alter and scope are colliding a bit. Here goes ...

When I have a hook form alter in my module that tries to lookup a user and set a form field default_value, it doesn't work within the scope of "success". It does work if I just move the line outside of the success callback. Then the default value gets set. Code like this:

```
// use profile address if no billing profile yet
if (empty(form.elements.billing_name_line.default_value)) {
  // get user profile info
  user_load(Drupal.user.uid, {
    async: false,
    success: function(result) {
      if (!empty(result.field_profile_state.und[0].value)) {
        //form.elements.billing_administrative_area.default_value = result.field_profile_state.und[0].value;
        form.elements.billing_administrative_area.default_value = 'IN';
        ...
```

Basically, load a user payment form and set some default billing values. I can set the administrative_area to Indiana by moving the last line outside of the user_load call. So, I know I'm running into a scope issue here. Since "form" is being passed it should be part of the scope for this function. My fear is that "result" is getting hoisted up and not available unless it's set outside the user_load function? 

The odd thing is that this exact example works fine with other function calls with success callbacks. I do the exact same thing with a custom service call and I can set form values within success and have it alter the form.

I can see the form object is updated in either case to have IN as the default_value, but it doesn't make it to the final form unless I move it outside user_load.

Any thoughts or hints are greatly appreciated.

**Comment by signalpoint** [comment]
@chrisschaub If you put a `dpm($form);` inside the success callback, does the form still exist?

**Comment by chrisschaub** [comment]
Yes, it's there. That's the maddening part. I can see and set it. But it doesn't stick after the alter is done.

**Comment by signalpoint** [comment]
@chrisschaub I think what is happening is that the user_load call (although it is set to sync) and subsequent success callback are not fired until after the form has already been rendered. So the alterations can't occur in the traditional way. Instead you'll probably have to use DOM manipulation to set the default value(s).

```
$('#my_form .my_input').val(my_default_value);
```

**Comment by chrisschaub** [comment]
Yes, that was it. The pagebeforeshow approach works.

**Comment by gs9999** [comment]
Aloha there tyler and chris,

using the above solution / example, $('#my_form .my_input').val(my_default_value); 

what was the value of .my_input?

or what is the .my_input value for the following element's default value?

  form.elements['name'] = {
      type: 'textfield',
      title: 'Your name',
      required: true,
     default_value: 'hello',
    };

**Comment by gs9999** [comment]
Aloha Tyler and Chris,

I was able to obtain the answer to the above question with the following process.

1. install iOS app that allows me to see the html source of a mobile app page.
2. find the 'id' element of the specific form <input> tag
3. then add the following DOM code snippet

document.getElementById("edit-jd-profile-edit-custom-form-firstname").setAttribute("value", "testing 123");

This accomplished the task for me that you were illuding to above.

Thanks,

GS
