### ISSUE TITLE
Add Icon to Header

### ISSUE THREAD

**Issue by Plabanm** [signalpoint/DrupalGap#365]
I want to add icon/Logo to the header bar beside title.
Cant think of any easy way..
Any Idea ?
Is there any way to add search from to any region ?
I tried to add on footer but disappears every time i come back to home page.

Thanks for helping me.
Cheers

**Comment by signalpoint** [comment]
You could try placing the `logo` block in the `header` region of your theme.

As for the search bug, please create a separate issue for that. I think I know why that is happening.

**Comment by Plabanm** [comment]
Please give me more details. I have tried the image adding procedure shown on doccumentation
http://www.drupalgap.org/node/163
Could not make it to work.

**Comment by signalpoint** [comment]
I've created a documentation page outlining how the logo works:

http://www.drupalgap.org/node/304

**Comment by Plabanm** [comment]
Thanks you this working fine.
just one issue.. is it possible to put 2 blocks side by side rather than one after another ?

cheers

**Comment by signalpoint** [comment]
@Plabanm that is up to you as the Theme developer. It can be done with custom CSS.
