### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#366]
When i turn on SSL and set my DrupalGap URL to use it, it get a CSRF error in the app. It's a real signed cert with a provisioned app. Any issues I should look into? Thanks.

**Comment by signalpoint** [comment]
@chrisschaub 

I haven't tried using an SSL cert with an app yet. Are you using SecurePages on your Drupal site? If so, I'd recommend tinkering with its settings (especially ones about redirection) to see if you can get it to work.

Also, definitely try some basic https services calls using e.g. FireFox Poster to make sure it is (or isn't DrupalGap's problem, i.e. maybe the Services module?).

**Comment by signalpoint** [comment]
I've successfully used SSL many times nowadays. I usually use it in conjunction with the securepages module, and have https on every page, including setting https in the `settings.js` file.
