### ISSUE TITLE
Release Help

### ISSUE THREAD

**Issue by Plabanm** [signalpoint/DrupalGap#368]
Hello

I am trying to release the app but not working. Building successfully but not not simulating.
I was developing in chrome/ripple. Its working fine there but when I took it to mac not working.
Giving me black on both iOS and android.

![screen shot 2014-09-12 at 03 05 47](https://cloud.githubusercontent.com/assets/4824797/4244450/842952e6-3a21-11e4-9d89-56cbad44b779.png)
![screen shot 2014-09-12 at 03 06 10](https://cloud.githubusercontent.com/assets/4824797/4244452/84546e68-3a21-11e4-96cc-2f26fdc5ac49.png)
![screen shot 2014-09-12 at 03 06 31](https://cloud.githubusercontent.com/assets/4824797/4244451/844f21b0-3a21-11e4-8318-6e47e9e84c6a.png)

What can be the reason. I could not find any documentation to release from ripple/chrome.
seems like I have to take them to local computer into Xcode or eclipse.
I have tried to go via phoneGap build same issue.. 

I need this to be simulated for my project.

Please help me. Thanks in advance.

**Comment by signalpoint** [comment]
@Plabanm you are correct, you need to take what you developed in Chrome+Ripple, and then install a PhoneGap environment on your local computer, e.g. xCode environment (iOS) or Eclipse environment (Android).

PhoneGap Build is a service (free I think) that will auto build your apps for you. I personally haven't tried it, but I know of others who have used PhoneGap Build with DrupalGap.

Before doing anything, it is important to make it through just the PhoneGap "Hello World" in your local development environment. Verifty that works properly, then drop DrupalGap on top of it.

What you are experiencing is the dreaded White Screen of Death issue: http://drupalgap.org/node/270

Please review all the information provided at the link above, and all issues listed within. An easy way to debug the WSOD issue is to use console.log() messages each step of the way through the DrupalGap bootstrap process:

```
drupalgap_onload();
_drupalgap_deviceready();
drupalgap_bootstrap();
// ...
```

That allows you to see how far it is making it before it crashes (for whatever reason(s)). See the DrupalGap developers guide for information on debugging DrupalGap core: http://www.drupalgap.org/node/224

FYI, AFAIK, at the time of writing this, DrupalGap hasn't been tested beyond PhoneGap 3.3.

**Comment by Plabanm** [comment]
Thank you for your reply.
Its working up to DrupalGapdev kit.
when I am putting my code this happening.

-------xcode log -----------------
<code> 2014-09-12 04:24:54.695 HelloWorld[88023:907] Finished load of: file:///Users/plabanmajumder/Library/Application%20Support/iPhone%20Simulator/6.1/Applications/FD17DA83-DAD7-4492-9940-1205F8A43B59/HelloWorld.app/www/index.html
2014-09-12 04:25:27.896 HelloWorld[88023:907] WARNING: drupalgap_entity_render_field - date_field_formatter_view() does not exist! (field_last_update)
2014-09-12 04:25:27.896 HelloWorld[88023:907] WARNING: drupalgap_entity_render_field - date_field_formatter_view() does not exist! (field_release_date)
2014-09-12 04:25:27.896 HelloWorld[88023:907] WARNING: drupalgap_entity_get_core_fields - Unknown anonymous comment setting (project): 0
2014-09-12 04:25:27.896 HelloWorld[88023:907] WARNING: theme_undefined() does not exist.
2014-09-12 04:27:36.737 HelloWorld[88023:907] THREAD WARNING: ['InAppBrowser'] took '1449.793945' ms. Plugin should use a background thread.
2014-09-12 04:28:05.324 HelloWorld[88023:907] WARNING: theme_() does not exist.
</code>

Sorry I know its too much.. But I am quiet helpless.
tried everything..it was working perfectly on chrome.!!

cheers

**Comment by Plabanm** [comment]
Lately this issue coming up on
eclipse consol

<code> [2014-09-12 06:08:44 - com.android.ide.eclipse.adt.internal.project.AndroidManifestHelper] Unable to read /Users/plabanmajumder/Desktop/APIZOOM/platforms/android/AndroidManifest.xml: org.eclipse.core.internal.resources.ResourceException: Resource is out of sync with the file system: '/APIZOOM/AndroidManifest.xml'.</code>

How can I fix this ?

**Comment by Plabanm** [comment]
Issue Fixed Working Fine Now
Problem was this line..
this line is not in ripple version...as i was developing in ripple/chrome I changed index.html
this is the only line was missing.. put it back working!!! 

link to cordova . js
![screen shot 2014-09-12 at 06 59 34](https://cloud.githubusercontent.com/assets/4824797/4245888/056910c4-3a42-11e4-9ba5-4b2d56523fc5.png)

Please update documentation.
Thanks for support.

**Comment by Plabanm** [comment]
Still seems to have problem with android.
Giving error on emulator ..

error: initializaing, cordova class not found.
where is the cordova.js ?

Please help me fix this.

cheers

**Comment by Plabanm** [comment]
also tried via PhoneGap build..
some how when all other app and browser getting connection
this app not getting connection!

**Comment by signalpoint** [comment]
@Plabanm 

The cordova.js file is generated when you run the PhoneGap CLI commands during your initial set up. It will be somewhere in the android folder that is automatically generated by the PhoneGap CLI. Copy that cordova.js file into your local PhoneGap's www folder (not the Ripple www folder).

The PhoneGap CLI should also have generated a default AndroidManifest.xml file. Problems with the AndroidManifest.xml file are unrelated to DrupalGap, and there are plenty of resources available (via Google) on how to understand and deal with that file.

Once you've sorted out the cordova.js and AndroidManifest.xml file problem(s), we still need to see the console.log() message during DrupalGap's initializiation (if you're still getting the WSOD).

Otherwise, from your console.log messages in this comment (https://github.com/signalpoint/DrupalGap/issues/368#issuecomment-55360141) it appears DrupalGap had loaded just fine, but it looks like you're missing the Date module inside your app.

Make sure you've installed the plugins required, via the PhoneGap CLI. This and all installation topics are covered here:

http://drupalgap.org/node/193

That being said, it is an open book, so if you see something in the documentation that can be improved, or updated, please do it while it is fresh in your mind. It's open source ;)

**Comment by Plabanm** [comment]
I am sooooo pissed.. uffffff...grrrrrrrrr..
sorry.

 Simple removing and adding platform and running it again worked.
<code>cordova platform rm android
cordova platform add android</code>
 this two simple thing took me 2 days... shame.

I will try and add to documentation later on. Project deadline coming up soon.

Thanks for all help and support.

**Comment by signalpoint** [comment]
@Plabanm thanks for following up. I feel your pain as well, I just struggled with an unrelated issue for about 10 days, and it turned out to be one line of code, doh!

**Comment by signalpoint** [comment]
@Plabanm will you please confirm which version of PhoneGap you are using on your local computer. I'm curious if it is the latest version, 3.5...?

**Comment by Plabanm** [comment]
Not quiet sure. Could not find out version number. But defiantly 3.X
