### ISSUE TITLE
White screen of death after splash screen (WSOD)

### ISSUE THREAD

**Issue by afcdotcom** [signalpoint/DrupalGap#370]
Hi,
1. I started a mobile app recently so I'm a newbie, everything seems to work fine in Chrome with Ripple Emulator, but after building it with phonegap, on my android device there is a white screen after  
   the splash screen. With a simple hello world text in index.html the app is running so the problem seems to be related to drupalgap.

You can find my app here: https://build.phonegap.com/apps/1097242 (I hope it's ok to post it).
1. Another problem I have is adding a custom class at my 401 page (because in css it's not working with #401 or .401). I tried this but it doesn't work:

'401': {
        title: '401 - Not Authorized',
        page_callback: 'system_401_page',
        options: {
            attributes: {
                'class': 'my_custom_class' 
            }
        }

I appreciate any ideas, thank you!

Regards,
Alin

**Comment by chrisschaub** [comment]
The makefile puts drupalgap.js in /bin ... but some build environments
(like Icenium) don't allow you to have stuff in /bin. So, drupalgap.js
never gets loaded. Just a thought.

-c

On Fri, Sep 19, 2014 at 11:28 AM, afcdotcom notifications@github.com
wrote:

> Hi,
> 1. I started a mobile app recently so I'm a newbie, everything seems
>    to work fine in Chrome with Ripple Emulator, but after building it with
>    phonegap, on my android device there is a white screen after
>    the splash screen. With a simple hello world text in index.html the
>    app is running so the problem seems to be related to drupalgap.
> 
> You can find my app here: https://build.phonegap.com/apps/1097242 (I hope
> it's ok to post it).
> 1. Another problem I have is adding a custom class at my 401 page
>    (because in css it's not working with #401 or .401). I tried this but it
>    doesn't work:
> 
> '401': {
> title: '401 - Not Authorized',
> page_callback: 'system_401_page',
> options: {
> attributes: {
> 'class': 'my_custom_class'
> }
> }
> 
> I appreciate any ideas, thank you!
> 
> Regards,
> Alin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/370.

## 

Christopher Schaub
http://chris.schaub.com

**Comment by afcdotcom** [comment]
Hmm and what you suggest I should try Chris?

Also now I'm getting a new error in Ripple Emulator, It says: 

XMLHttpRequest cannot load http://www.mywebsiteadress.com/?q=services/session/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:52647' is therefore not allowed access. 

But I don't see where is the problem as long as origin="*" should allow acces to all sources right?

**Comment by chrisschaub** [comment]
Did you set RemoteProxy to disabled in Ripple? Also, if I'm using a remote
database with local codebase, I invoke chrome with ...

/usr/bin/chromium-browser --disable-web-security

On Fri, Sep 19, 2014 at 2:36 PM, afcdotcom notifications@github.com wrote:

> Hmm and what you suggest I should try Chris?
> 
> Also now I'm getting a new error in Ripple Emulator, It says:
> 
> XMLHttpRequest cannot load
> http://www.mywebsiteadress.com/?q=services/session/token. No
> 'Access-Control-Allow-Origin' header is present on the requested resource.
> Origin 'http://127.0.0.1:52647' is therefore not allowed access.
> 
> But I don't see where is the problem as long as origin="*" should allow
> acces to all sources right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/370#issuecomment-56224323
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by signalpoint** [comment]
@afcdotcom Is your Drupal site running on your localhost, or is it running up on the Internet? If it is running on localhost, this would most likely explain the issue, as a compiled mobile app running on a device by default won't be able to access localhost. I'm sure throug some system admin trickery, you can expose your localhost to the outside world. But I'd recommend for simplicity just running your site on the Internet to test it against a compiled app.

Alternatively, if you're using PhoneGap Build (I personally haven't yet), make sure the config.xml file is present, and I haven't tested DrupalGap beyond PhoneGap 3.3 yet.

As @chrisschaub  mentioned, if you're just using Ripple, be sure to Disable the Cross Domain Proxy under Settings.

**Comment by afcdotcom** [comment]
@chrisschaub - Cross Domain Proxy is disabled otherwise it wouldn't worked at all using Ripple.
@signalpoint  - My drupal site is running on the internet, and my application is builded from a local folder.

I just tried again with the last default version of drupalgap: 7.x-1.0-rc3, the same error, but it's very strange because a few weeks ago everything worked well in the Ripple and my mobile device too, meanwhile I didn't do any changes to my website.

Any suggestions?

**Comment by afcdotcom** [comment]
About the error in Ripple - that was because chrome didn't started with --disable-web-security added.

The white screen after spash screen still there on my mobile device. Just builded the last version of drupalgap with phonegap 3.5.0 and the same.... 

The latest version of phonegap can cause the problem? - I think not, I tried with 3.3.0 - the same white screen, and as I mentioned in the first post with a simple text in index.html everything works.

**Comment by chrisschaub** [comment]
How are you building it? Manually or with a service?

On Mon, Sep 22, 2014 at 5:06 AM, afcdotcom notifications@github.com wrote:

> About the error in Ripple - that was because chrome didn't started with
> --disable-web-security added.
> 
> The white screen after spash screen still there on my mobile device. Just
> builded the last version of drupalgap with phonegap and the same....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/370#issuecomment-56352783
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by afcdotcom** [comment]
Using phonegap, there is any other way could I try?

**Comment by chrisschaub** [comment]
Try copying DrupalGap.js into the main docroot, its in bin my default. And
adjust the index.HTML.

**Comment by signalpoint** [comment]
@afcdotcom If @chrisschaub's latest recommendations don't work, then I would recommend stepping through the DrupalGap bootstrap process and printing messages to the `console.log()` each step of the way. You can modify the bin/drupalgap.js directly, or use the makefile to build it from the `src/` directory.

```
drupalgap_onload();
_drupalgap_deviceready();
drupalgap_bootstrap();
etc...
```

That should reveal to you what line(s) are crashing. And of course, make sure you installed the required cordova plugins via the command line interface.

**Comment by afcdotcom** [comment]
1. Firstly this is really incredible... it took me more than one week to discover that the problem was in index.html. I deleted the script line for cordova.js loading before drupalgap_onload() - I used the ripple.index.html content as tutorial said with missing that line. But I don't understand why this is mandatory for building with phonepag as long as there is no cordova.js file in my app root... how it could influence the app?
2. Secondly please help me finding a solution for my other problem with adding a class/id to the 401 page. (If it's better to open another issue ticket for that or my other problems in order to get an answer, I will understand, just let me know).
3. Finally, I need for anonymous users instead of homepage to appear the login form/page and I did it in my way changing 401 error page. Is it the right way or you know a better solution?

So in my_module.js I have this:

```
function my_module_menu() {
    var items = {
        homepage: {
            title: 'my title',
            page_callback: 'my_module_homepage',
            access_callback: 'my_module_homepage_access',
        } 
    };
    return items;
}

function my_module_homepage() {
    var content = {};
    content['my_intro_text'] = {
        markup: "<p>Hello this is my Homepage</p>"
    };
    return content;
}

function my_module_homepage_access () {
    try {
      if (drupalgap_user_has_role('authenticated user')){ return true; }  
      else return false;
    }
    catch (error) { console.log('my_module_welcome_access - ' + error); }
}
```

And in drupalgap.js I have this:

```
function system_401_page(path) {
  try { if (drupalgap_user_has_role('anonymous user'))   
        return drupalgap_get_form('user_login_form');    
        else
        return 'Sorry, you are not authorized to view this page.'; }
  catch (error) { console.log('system_401_page - ' + error); }
}
```

**Comment by signalpoint** [comment]
@afcdotcom Thank you for the kind words. To follow up on your questions:
1. The cordova.js file (last time I checked) must be loaded via the index.html file when compiling directly to a mobile device, or mobile device emulator. However, when using Ripple (AFAIK) the cordova.js file is automatically injected into the DOM for you via Ripple, and that is why the cordova.js file is not needed in Ripple.

This sounds like an important note (and possibly missing from the documentation). Did you have to manually copy the cordova.js file to your app's root directory when compiling to your device? Or you didn't need the cordova.js file at all when compiling to your device?
1. Please open a new ticket.
2. Check out the Force Authentication module: http://drupalgap.org/project/force_authentication

**Comment by afcdotcom** [comment]
@signalpoint Thank you for your answers. 

Regarding your question: no, I don't have the cordova.js file in my app's root directory, actually I don't have it at all, that's why I was so surprised phonegap is loading it somehow in the building process.

**Comment by signalpoint** [comment]
@afcdotcom Interesting, thank you for confirming, and thank you very much for the thorough debugging. I believe this may help many folks who have the WSOD issue. I've updated the documentation to reflect your findings: http://www.drupalgap.org/node/193
