### ISSUE TITLE
Change src/drupalgap.js to src/core.js

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#374]
Having bin/drupalgap.js and src/drupalgap.js is confusing.

**Comment by chrisschaub** [comment]
It would be great to make drupalgap.js right in the main root, not bin.
Then it would work with Telerik's Icenium which doesn't support /bin ... a
selfish request, I know!  :)

On Mon, Sep 22, 2014 at 8:12 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> Having bin/drupalgap.js and src/drupalgap.js is confusing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/374.

## 

Christopher Schaub
http://chris.schaub.com

**Comment by signalpoint** [comment]
Renamed to `src/dg.js` instead.
