### ISSUE TITLE
Adding a custom class or id to a menu item

### ISSUE THREAD

**Issue by afcdotcom** [signalpoint/DrupalGap#375]
I have to add a custom class to my 401 page (because in css it's not working with #401 or .401 you know...). 

I tried this with all variations possibles I think, but it doesn't work:

```
'401': {
  title: '401 - Not Authorized',
  page_callback: 'system_401_page',
  options: {
    attributes: {
      'class': 'my_custom_class' 
    }
}
```

I appreciate any ideas, thank you!

Regards,
Alin

**Comment by signalpoint** [comment]
@afcdotcom Thank you for pointing out this bug. I created a separate issue for the bug, and resolved it here: #376 

Grab the latest bin/drupalgap.js and either update the easystreet3 theme page.tpl.html file, or if you are using a custom theme, you must update your page.tpl.html to match the new syntax available here:

http://drupalgap.org/node/121

Once you have that done, you can use this example to add a custom class to the 401 page so you can style it:

http://drupalgap.org/node/210

I was able to successfully style it then using css like this:

```
.my_custom_class .ui-content {
  color: red;
}
```
