### ISSUE TITLE
Searching a JSON view feed...

### ISSUE THREAD

**Issue by mfuggle** [signalpoint/DrupalGap#379]
Is there a way of searching a JSON view. For example I have a list of 'match reports' and they relate to a number of different teams. They are allocated to teams using a taxonomy vocabulary, however I would like to display the view and have a search box at the top of the view which will allow the user to enter a value and use it as a filter to reduce the list.

Maybe there is another/better way of achieving the same outcome. I have seen somewhere that the use of the underscore.js library is a useful adjunct to JSON Views but I am not sure how to use it.

**Comment by mfuggle** [comment]
Perhaps I didn't use the right search criteria in the Docs since it looks as if this is possible with the Autocomplete with Remote Custom Data functions. I'll see if I can get that going...

**Comment by signalpoint** [comment]
@mfuggle Correct, the Autocomplete with Remote Custom Data should be the way to go with a feature like that. Let me know how it goes, thanks.

**Comment by mfuggle** [comment]
Actually I used the Autocomplete with Remote Views JSON. When I invoke the page I can enter a value and it displays a list of articles which comply with the filter. However when I click on an entry in the returned list it simply populates the search box with the title of the selected item. I was expecting it to display the node. I seem to have missed something.

**Comment by signalpoint** [comment]
@mfuggle Check out the "Handling Clicks on Items" section on this page: http://www.drupalgap.org/node/227

**Comment by mfuggle** [comment]
I am sorry to be a nuisance and I do appreciate your assistance

**Comment by signalpoint** [comment]
@mfuggle No worries, I enjoy supporting the project!

**Comment by narmnet** [comment]
hello my dear 

how can i make a filter search by Global: Combine fields filter  for view json of drupalgap
when make it not show me in my drupalgap i want to have got great searching in my drupal gap with multi field please help me !
