### ISSUE TITLE
image resizing

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#387]
So, I'd like to resize images to fit on a screen after they load. I can't seem to find a jquerymobile equivalent of

```
$(window).load
```

which runs after all dom elements are done rendering. I've tried pageshow and pageload, no dice. Any thoughts? The content including images is lazy loaded which is great but creates this issue.

**Comment by signalpoint** [comment]
@chrisschaub I think/thought this CSS has it covered:

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/drupalgap.css#L90

Maybe you'll need to use a style like that, but custom for your usage.

**Comment by chrisschaub** [comment]
Yeah, that works for width. But, I want to set image heights so they all
are in view. So, I need them to load or be on screen to dynamically adjust
them. Thanks!

On Mon, Oct 13, 2014 at 3:00 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> @chrisschaub https://github.com/chrisschaub I think/thought this CSS
> has it covered:
> 
> https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/drupalgap.css#L90
> 
> Maybe you'll need to use a style like that, but custom for your usage.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/387#issuecomment-58946381
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
Duh, vh measures save the day ...

 height: 25vh;

etc

Thanks and sorry for the dumb question.

On Mon, Oct 13, 2014 at 3:03 PM, Christopher Schaub chris@schaub.com
wrote:

> Yeah, that works for width. But, I want to set image heights so they all
> are in view. So, I need them to load or be on screen to dynamically adjust
> them. Thanks!
> 
> On Mon, Oct 13, 2014 at 3:00 PM, Tyler Frankenstein <
> notifications@github.com> wrote:
> 
> > @chrisschaub https://github.com/chrisschaub I think/thought this CSS
> > has it covered:
> > 
> > https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/drupalgap.css#L90
> > 
> > Maybe you'll need to use a style like that, but custom for your usage.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/signalpoint/DrupalGap/issues/387#issuecomment-58946381
> > .
> 
> ## 
> 
> Christopher Schaub
> http://chris.schaub.com

## 

Christopher Schaub
http://chris.schaub.com
