### ISSUE TITLE
Remove jQueryMobile Dependancy and Replace as a Plugin Option

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#39]
This started from an e-mail request:

"hi there tyler,

I found your drupal gap tutorial to be exactly what I needed, so thank you!

I'm looking to build several apps over the next few months based upon a
drupal backend and a backbone+phonegap based front end app. some but not all
of these projects will use jquery mobile.

I was wondering whether you'd ever thought of making the drupal gap API more
generic? I'm quite tempted to build upon your hard work but take jQm out of
the equation. it'd be great to hear what you think."

**Comment by signalpoint** [comment]
Actually, just last night I started tinkering with how to pull PhoneGap out of the equation and turn it into more of a plugin. The same will go for jQueryMobile someday. Learning from the past, now I'd like DrupalGap to be purely JS based and then have plugins for PhoneGap, jQM, Sencha, etc.

Right now the most evolved branch is here:

https://github.com/signalpoint/DrupalGap/tree/7.x-1.x-alpha

Soon it will be merged into this branch:

https://github.com/signalpoint/DrupalGap

It would be great if you would 'Star' and 'Fork' DrupalGap on GitHub. Then maybe we could start figuring out how to pull jQM out of the equation.

Unfortunately/fortunately jQM is used extensively right now, with very little PhoneGap involvement (only for device ready, connection tests and camera).

If jQM was out of the equation, what could handle making the Apps look nice though?

**Comment by Gys** [comment]
'If jQM was out of the equation, what could handle making the Apps look nice though?'
This should not be of Drupalgaps concern in my humble opinion...

Drupalgap seems a little too much, with functions for theming, forms, nodes, comments, etc, etc.
All those things can be handled with, for example, JQM or Phonegap. Or something else, like Intel XDK. Whatever the developer (or his client) wants.

Next to JQM and Phonegap, now the developer has to be familiar with Drupal as well, so it seems at a first glance. Maybe I am wrong ? But why have something like app/default.settings.js to be copied to app/settings.js ? That is a Drupal thing. I want my own system of settings (stored in a local db, btw).

I like a single file library that depends as little as possible on anything. I now use my own library, based on drupal.js, that handles the login and data with a Drupal site as backend. No other dependencies.

**Comment by signalpoint** [comment]
The DrupalGap 8 SDK (which also works with Drupal 7 websites) is now totally headless, there is no more jQuery Mobile under the hood for it, it is pure JavaScript. The DrupalGap 7 SDK will remain powered by jQuery Mobile, but know that the future is with the DrupalGap 8 SDK.

**Comment by mkinnan** [comment]
Will there​ be an upgrade tutorial on how to port DrupalGap 7 SDK to 8?

**Comment by signalpoint** [comment]
@mkinnan Yes indeed, I'll send out a newsletter when the beast is ready!

**Comment by mkinnan** [comment]
@signalpoint That's great! Thank you!
