### ISSUE TITLE
Failed Connection screen on android app

### ISSUE THREAD

**Issue by b14r** [signalpoint/DrupalGap#390]
I have checked all the troubleshout pages, my web site is running drupalgap well, my app is running ok in ripple in the remote server, i have built my app via phonegap website and eclipse build, but everytime I open my app on my phone the attach messages are shown for me.

someone has any ideia why?

![screenshot_2014-10-23-16-41-41](https://cloud.githubusercontent.com/assets/5417892/4758136/daa59af4-5adc-11e4-9c8e-64ff839a266b.png)
![screenshot_2014-10-23-16-41-34](https://cloud.githubusercontent.com/assets/5417892/4758135/daa3c4ae-5adc-11e4-88ca-2018e87fff4a.png)

**Comment by signalpoint** [comment]
@brunomontibeller  Set `drupalgap.settings.debug = true;` in settings.js, then run your app and watch the console.log() messages that are printed out via Eclipse LogCat.

Either way, we need that debug information to accurately debug this.

Also, don't forget to install the Network plugin for: org.apache.cordova.network-information

**Comment by b14r** [comment]
So, I did what asked me for, and the log is here: http://pastebin.com/UTpV7P61

I see some connection erros but I can't tell why they're happening!

**Comment by signalpoint** [comment]
@brunomontibeller - Search for `drupalgap` in the output, and typically information will be available:

```
drupalgap_check_connection - ReferenceError: Connection is not defined at file:///android_asset/www/bin/drupalgap.js:577
```

Did you install the Network plugin with the PhoneGap Command Line Interface (it is mentioned during the hello world)?

**Comment by b14r** [comment]
Yes, I did!

And I don't why this is happening, I tried the demo app on google store, and my website worked very well with this app.

**Comment by signalpoint** [comment]
@brunomontibeller Next you'll need to modify the `drupalgap_check_connection()` function in `bin/drupalgap.js` (or modify `src/drupalgap.js` and then use the `makefile` - preferred).

Each step of the way through that function, place a line like this:

```
console.log('A');
```

Then copy the line, replace A with B, then another line replace B with C, etc.... that way you can pinpoint what line of code is crashing.

It appears it will be the lines like this:

```
states[Connection.UNKNOWN] = 'blah';
```

For whatever reason(s), the Connection object isn't available in your Eclipse environment. Depending on if you are compiling directly to a device, or using the Android emulator, the way to solve it should be similar.

Of course verify your device/emulator actually has an internet connection.

**Comment by b14r** [comment]
I have no idea why, but it started to work!
I think I didn't install the network-information properly, but ok, thank you!
