### ISSUE TITLE
entity_load, single ids

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#393]
Ok, something is converting node/123 to node_123 -- and I'm doing anything like this in my code. And sometimes links work, sometimes they throw the "alert". in either case drupalgap_goto loads the correct intended url. It's just that the alert is very annoying. How about we change to a console.log because to the user, nothing is really wrong. I've been trying to track this down for a few days now, and I think there's a link bleed or race condition somplace in the core code. 

```
function entity_load(entity_type, ids, options) {
  try {
    if (!is_int(ids)) {
      // @TODO - if an array of ints is sent in, call entity_index() instead.
      console.log('entity_load(' + entity_type + ') - only single ids supported!');
      return;
    }
...
```

**Comment by signalpoint** [comment]
@chrisschaub Yikes, sounds awful. I've migrated this issue to jDrupal: https://github.com/easystreet3/jDrupal/issues/5

**Comment by signalpoint** [comment]
P.S. It will be a while before the next recommended jDrupal release is out, so it may be best just to manually patch your jdrupal*.js file(s) for now. Or grab the dev snapshot: https://www.easystreet3.com/jDrupal/download
