### ISSUE TITLE
How to refresh display

### ISSUE THREAD

**Issue by mfuggle** [signalpoint/DrupalGap#398]
What needs to be done to allow the user refresh the display to obtain the latest data?

**Comment by signalpoint** [comment]
@mfuggle Depends on what you mean by "obtain the latest data", please clarify.

Either way, this page is probably of interest: http://drupalgap.org/node/134

**Comment by mfuggle** [comment]
I'm thinking of wanting to see the latest results from a JSON feed if it has changed on the web.

**Comment by mfuggle** [comment]
The reload page is exactly what I want - thanks
