### ISSUE TITLE
Link to node displays Title but no other fields

### ISSUE THREAD

**Issue by mfuggle** [signalpoint/DrupalGap#399]
I do not understand what causes a link to display a full node. In the code below I intend to link to the attachment. However when I click on 'extra details' it displays the Title of the attachment (a Drupal node) but does not display any other fields. It also shows 'view' and 'edit' tabs and if I click on the 'edit' tab it displays the contents of the node.

What is it that will cause the display of other fields in the node? They are set to be displayed in the Drupalgap display in the Content Type.

```
/**
 * The row callback to render a single row.
 */
function mobile_notifications_notifications_list_row(view, row) {
  try {
    var attachment = '';
    if( row.Attachment.length > 0 ){
      attachment =  l('extra details', 'node/'+ row.Attachment);
    }
    content = '<td style="padding: 0px;"><div class="ui-body ui-body-a ui-corner-all">' + 
                '<h2>' + row.title + '</h2>' + 
                '<div>' + row.Message + '</div>' +
                '<div>' + attachment + '</div>' +
                '<p>' + '(Posted ' + row.Posted + ' ago by ' + row.name + ')' + '</p>' +
                '<hr>' +
                '</div></td>';

    return content;
  }
  catch (error) { console.log('mobile_notifications - ' + error); }
}
```

**Comment by signalpoint** [comment]
@mfuggle It depends on what type of fields you are trying to display. DrupalGap does its best to support most core fields, and popular contrib module fields. However all of them are definitely not supported.

Set `Drupal.settings.debug` to `true` in `settings.js` and then watch the JavaScript console log. There it will explain what fields are not supported.

FYI, you should place 'var ' in front of any variables you create in JavaScript, otherwise they will be added to the global scope, and can cause undesired results. I've updated your code above to reflect these changes.

**Comment by mfuggle** [comment]
Hi Tyler,

The message I get is shown in the attached screenshot and it states:

```
      WARNING: theme_undefined() does not exist
```

The fields in the content type are all supported fields so that's not 
causing any trouble but I am not sure where the theme gets defined.

```
/**
* The callback for the mobile_notifications page.
*/
functionmobile_notifications_notifications_page(){
try{
varcontent={};
content['mobile_notifications']={
theme:'view',
format:'table',
format_attributes:{
'border':'0px',
'cellpadding':'5px',
'cellspacing':'0px',
'width':'100%',
},
path:'mobile-notifications',
row_callback:'mobile_notifications_notifications_list_row',
empty_callback:'mobile_notifications_list_empty',
attributes:{
id:'mobile_notifications_list_view'
}
};
returncontent;
}
catch(error){console.log('mobile_notifications - '+error);}
}

/**
* The row callback to render a single row.
*/
functionmobile_notifications_notifications_list_row(view,row){
try{
varattachment='';
if(row.Attachment.length>0){
attachment= l('extra details','node/'+row.Attachment);
}
content='<td style="padding: 0px;"><div class="ui-body ui-body-a 
ui-corner-all">'+
'<h2>'+row.title+'</h2>'+
'<div>'+row.Message+'</div>'+
'<div>'+attachment+'</div>'+
'<p>'+'(Posted '+row.Posted+' ago by '+row.name+')'+'</p>'+
'<hr>'+
'</div></td>';

returncontent;
}
catch(error){console.log('mobile_notifications - '+error);}
}
```

**Comment by signalpoint** [comment]
@mfuggle Don't worry about the `WARNING: theme_undefined() does not exist`, that's unrelated.

What type of value is in `row.Attachment`? It it in integer, or an integer as a string? If yes, then it should navigate to the node page without issue.

The real question is, what types of fields are on your content type? But as you stated, there are no warnings output to the console regarding other fields. So that seems odd...

I'd suggest updating to the latest `bin/drupalgap.js`, and if you're developing in Chrome, please share your URL here and I'll take a look at the app real quick.

**Comment by mfuggle** [comment]
Hi Tyler,

That's kind of you - I'm a bit embarrassed that you'll see what limited 
capability I have.

The URL is www.quins.com.au/mobile

Cheers...

Martin Fuggle

Kew: 613 9817 1401
Deans Marsh: 613 5236 3306
Mobile: 614 0826 5586   martin@fuggle.com.au mailto:jmatthew@adaxa.com
www.fuggle.com.au http://www.adaxa.com
skype mfuggle

This email and any files transmitted with it are confidential. Any 
unauthorised use of the contents is expressly prohibited. If you have 
received this email in error please notify the sender via email 
immediately. Finally, the recipient should check this email and any 
attachments for the presence of viruses. Martin Fuggle accepts no 
liability for any damage caused by any virus transmitted by this email.

**Comment by signalpoint** [comment]
@mfuggle No worries, looks good to me!

I'm not sure what page I'm looking for though... I navigated around a bit and everything seems to be working displaying fine.

**Comment by mfuggle** [comment]
Have a look at Messages on the menu. On the first message there is an 
attachment called ‘extra details’. Clicking on that displays the title 
of the node but nothing else and I think it should display the content 
of the node. Clicking on the Edit tab displays the contents of the node 
but View does not.

## Cheers

Martin Fuggle

Kew: 613 9817 1401
Deans Marsh: 613 5236 3306
Mobile: 614 0826 5586   martin@fuggle.com.au mailto:jmatthew@adaxa.com
www.fuggle.com.au http://www.adaxa.com
skype mfuggle

This email and any files transmitted with it are confidential. Any 
unauthorised use of the contents is expressly prohibited. If you have 
received this email in error please notify the sender via email 
immediately. Finally, the recipient should check this email and any 
attachments for the presence of viruses. Martin Fuggle accepts no 
liability for any damage caused by any virus transmitted by this email.

**Comment by mfuggle** [comment]
Hi Tyler - didn't realise that unless you are logged on you cannot see 
any Messages at all! You can logon using a username and password that I will send separately and you will then be able to see the messages and the first one with an attachment link.

## Sorry...

Martin Fuggle

Kew: 613 9817 1401
Deans Marsh: 613 5236 3306
Mobile: 614 0826 5586   martin@fuggle.com.au mailto:jmatthew@adaxa.com
www.fuggle.com.au http://www.adaxa.com
skype mfuggle

This email and any files transmitted with it are confidential. Any 
unauthorised use of the contents is expressly prohibited. If you have 
received this email in error please notify the sender via email 
immediately. Finally, the recipient should check this email and any 
attachments for the presence of viruses. Martin Fuggle accepts no 
liability for any damage caused by any virus transmitted by this email.

**Comment by signalpoint** [comment]
@mfuggle Yeah that's a tough one, it isn't saying much about why it is happening. I'd recommend stepping through `drupalgap_entity_render_content()` with the `dpm()` function to see what is happening each step of the way: http://api.drupalgap.org/global.html#drupalgap_entity_render_content

**Comment by kuukua** [comment]
Hello Tyler, i am also having the same problem but my site is in my localhost. May i know how you solved mfuggle's problem

**Comment by signalpoint** [comment]
@kuukua Did you set your display modes? http://www.drupalgap.org/node/184

**Comment by kuukua** [comment]
I just tried it and it worked perfectly. u do not know how happy i am. Thanks so much

**Comment by sudhirlande** [comment]
I m new to drupalgap.
i have a menu, node links are given to the menu. but, it is not showing contents  and only shows its title of menu

**Comment by signalpoint** [comment]
@sudhirlande Please provide much more context (code, screenshots, explanation) about what you are doing if you need help.

**Comment by sudhirlande** [comment]
This is a screenshot. of its android app. in drupaldap

![about_us](https://cloud.githubusercontent.com/assets/10772308/6015781/1e0daff8-ab9f-11e4-96f9-7f4b27733495.png)

I have created a menu link named as about us. Its node id is node/3 on my drupal website.
so this page only shows the title of that page i.e About Us. But not showing the contents of a page.

plz give me solution for it.

following is the code. of 

setting.js

// Main Menu
drupalgap.settings.menus['main_menu'] = {
  options: menu_popup_get_default_options(),
  links: [
      {
      title:'About Us',
      path:'node/3',
      options:{
        attributes:{
          'data-icon':'grid'
        }
      }
    }
]
};

**Comment by signalpoint** [comment]
@sudhirlande http://drupalgap.org/node/184

**Comment by sudhirlande** [comment]
I have make it, But still not solved the issue 
This is screenshot of it 

![image](https://cloud.githubusercontent.com/assets/10772308/6041246/965a9918-ac48-11e4-9f59-5fb5a9923a7e.png)

**Comment by signalpoint** [comment]
@sudhirlande Are you using a multi lingual site?

**Comment by sudhirlande** [comment]
Yes 

![image](https://cloud.githubusercontent.com/assets/10772308/6056257/fc68db8c-acdb-11e4-9293-e41d0067f6de.png)

![image](https://cloud.githubusercontent.com/assets/10772308/6056243/c56f21ae-acdb-11e4-9fda-ce35f2289501.png)

**Comment by signalpoint** [comment]
@sudhirlande First, upgrade your Drupal site, and all of its contrib modules to the latest version. I can see from the screen shot there are some needed updates ;) Then please report back and we can debug the multi lingual problem (which is most likely why other field's on your nodes aren't showing up in the app).

**Comment by sudhirlande** [comment]
I Have make all the updates. but still contents are not displaying in drupalgap.

**Comment by signalpoint** [comment]
@sudhirlande Turn on debug mode in the settings.js file, then in a web browser, watch the JavaScript console log, and paste those results here. We need to get the URL the app is trying to use to fetch a node's JSON. For example, http://example.com/?q=drupalgap/node/123.json

**Comment by sudhirlande** [comment]
No Error

Following is setting.js
[DELETED]

**Comment by signalpoint** [comment]
@sudhirlande I don't need your settings.js file, I need you to turn on debug equal to true in settings.js, then copy/paste the JavaScript console log messages here. There won't necessarily be an error printed to the console log, and as I mentioned in my previous comment, we need the URL the app is trying to use to fetch the node's JSON.

**Comment by millionacrenest** [comment]
I'm having the issue discussed in this thread: Drupalgap display suite is set right but images aren't displaying on view node (they are displaying on edit node). My core and modules are up-to-date. Here's the URL my app is trying to use to fetch the node's JSON.

http://www.waworkersrights.com/?q=drupalgap/system/connect.json

**Comment by signalpoint** [comment]
@allisonmcentire DrupalGap doesn't officially support Display Suite (yet), so I'd recommend disabling Display Suite on the DrupalGap Display Mode, that should allow fields to display within the app.

**Comment by millionacrenest** [comment]
Thanks for the quick reply. I disabled the display suite module but the problem persists.

**Comment by millionacrenest** [comment]
Oh, sorry: the json is this: GET: http://www.waworkersrights.com/?q=drupalgap/node/121.json

**Comment by millionacrenest** [comment]
Could it be related to this in image.js? 
// @TODO - bug: the trailing slash on public and private is breaking images
    // that don't live in a sub directory in sites/default/files.
