### ISSUE TITLE
Add contrib module to force authentication before continuing to app front page

### ISSUE THREAD

**Issue by kochen** [signalpoint/DrupalGap#40]
Hey,
my Drupal side has little (to even none) functionality for guest users - very much like FB/Twitter etc. So I want to be able to make the user log in when the app first fires, and make sure he stays that way (unless the user intentionally chooses to logout).

the idea is to have the user log in, and save his user/pass (i.e in localstorage), and from there navigate as usual.
every page load, have a check to see if the session is still active, and if not, reconnect the user with the saved data.

is that possible?

UPDATE: This is a good candidate for a DrupalGap Contrib module.

**Comment by signalpoint** [comment]
Interesting idea. First, I must say that storing usernames and passwords in local storage is probably not a good idea. There has to be some other form of 'long' authentication mechanisms available in Drupal.

For starters though, you can add your own custom module in DrupalGap and declare a page via hook_menu(). Then set that page to be your app's front page in settings.js.

That page's callback function should check to see if the user is logged out, if they are show the login form, if they are logged in, let them see the normal front page:

function my_front_page_callback() {
  if (drupalgap.user.uid == 0) {
    return drupalgap_get_form('user_login');
  }
  else {
    return 'Hi, ' + drupalgap.user.name + ' you are logged in!');
  }
}

See this post in the Getting Started guide for more information on creating pages:

http://drupalgap.org/node/75

I am curious to learn more about long term login mechanisms, and definitely would stay away from storing user names and passwords in local storage.

Good news though, once you login to a Drupal site with DrupalGap, the session will remain active as long as Drupal thinks you are logged in.

In the long term, it would be cool to turn this into a DrupalGap contrib module, or to make it part of core and then you could specify some setting in settings.js, i.e. 'require_authentication' which would auto route the app to the login screen before continuing to the front page.

**Comment by signalpoint** [comment]
@kochen - This is now the first contributed module for DrupalGap, enjoy!

http://drupalgap.org/project/force_authentication

Clone the latest 7.x-1.x-alpha branch of DrupalGap to allow the module to work, or wait until the 7.x-1.4-alpha (or later) release of DrupalGap for compatibility.
