### ISSUE TITLE
Cutom Local Tasks

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#409]
Is there a way to setup custom local tasks with tabs for a custom path like:

courses/%
courses/online
courses/classroom

that way online and classroom would have tabs? It seems to only work if I stick a % sign in the arg 1 spot, but that yields some strange paths on the tabs. I know I'm missing something simple. Thanks!

**Comment by signalpoint** [comment]
@chrisschaub Did you try the techniques mentioned here (and in the sub pages)? http://drupalgap.org/node/294

**Comment by chrisschaub** [comment]
Sorry, I got it working! Thanks.
