### ISSUE TITLE
Add Google Maps Widget

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#410]
Now that we're placing maps in apps (http://www.drupalgap.org/node/497), let's make it even easier with a Google Map widget.

**Comment by signalpoint** [comment]
I've decided against this. Just use the docs for adding your own custom map. Each map is so different, I don't think it's worth trying to abstract this much further.

**Comment by DewaldHerbst** [comment]
Hi Tyler, https://www.drupal.org/project/geolocation has a pretty cool widget. Would be awesome to add lat and long values like this

**Comment by signalpoint** [comment]
@DewaldHerbst understood. For now, there is Geofield and Geofield GMap which do a pretty good job of providing an easy to use widget. http://drupalgap.org/project/modules

If anybody wants support for the geolocation widget, then I'll welcome pull requests, but I personally don't foresee needing it soon.
