### ISSUE TITLE
Views Expose Filter Not Visible 

### ISSUE THREAD

**Issue by kuukua** [signalpoint/DrupalGap#411]
I am using Drupalgap version 7.x-1.8 and i have walked through the tutorial on http://www.drupalgap.org/node/498 but my expose filter is not showing on my mobile application.
I have seen it appearing in the views preview as shown in the image attached to this post but it still does not reflect in the mobile app.
 Please, is there something i am not doing right?
![2](https://cloud.githubusercontent.com/assets/9804868/5103287/2fe1daa4-6fce-11e4-8dd6-f47cf7cdb1b1.JPG)

**Comment by signalpoint** [comment]
@kuukua This feature hasn't been officially released yet, therefore you need to upgrade the DrupalGap module and the SDK to the development versions to activate this feature: http://drupalgap.org/download
