### ISSUE TITLE
Calling field value in function theme_image

### ISSUE THREAD

**Issue by jharbertdev** [signalpoint/DrupalGap#412]
I added support for the EddyVergrubben Social Sharing Plugin making the following edits in drupalgap.js. When I click on image the native app allows me to share the image.  I am also trying to incorporate default hash tagging. But I can't get the drupal field to display.  I always get the error 
theme_image - TypeError: Cannot read property 'field_hashtag' of undefined.

I know I'm probably missing something very obvious. 

```
function theme_image(variables, entity_type, entity) {



  try {

    // Turn the path, alt and title into attributes if they are present.

    if (variables.path) { variables.attributes.src = variables.path; }
    if (variables.alt) { variables.attributes.alt = variables.alt; }
    if (variables.title) { variables.attributes.title = variables.title; }


    // Render the image.
  first ='<img  onclick="window.plugins.socialsharing.share(\'';
    middle = '' + entity.field_hashtag.und[0].value;  + '';
 end = '\', null, \'' + (variables.path) + '\', null)" ' + drupalgap_attributes(variables.attributes) + '  />';

return first + middle + end; 


  }
  catch (error) { console.log('theme_image - ' + error); }
}
```

**Comment by signalpoint** [comment]
@jharbertdev First, I wouldn't recommend hacking DG core. I'd recommend copying `theme_image()` and placing it in your custom theme, and renaming the function, for example:

```
function my_custom_theme_image(variables) {
  // copy DG core's theme_image() here and make necessary modifications.
}
```

That way when you upgrade DG core in the future, your customization won't break.

Second, DG core does not pass `entity_type` or `entity` to `theme_image()`, so both of those will always be undefined. Perhaps the entity info is bundled inside of `variables`, but I can't remember.

Use `dpm(variables);` to see what is inside of variables (it will be output to the console).

**Comment by jharbertdev** [comment]
So I assume when I add the custom function into say my_module.js it is suppose to override the core function?

**Comment by signalpoint** [comment]
@jharbertdev Close, you put the function in your custom theme's javascript file, not in a custom module's javascript file.

**Comment by jharbertdev** [comment]
Ok.  So just created a custom theme and I am overriding core from my_theme.js.    dpm doesn't show any fields.  How would I get what is in entity?

**Comment by jharbertdev** [comment]
Can I execute another function in the return of theme_image.  It always just return html- function drupal_gap....

**Comment by signalpoint** [comment]
@jharbertdev It sounds like you want DrupalGap core to pass along an entity to the theme() system, that was it is available inside of theme_\* functions.

You can run as many synchronous functions as you want inside a theme_ function, but no async functions (e.g. you can't load a node in it). You may be able to force a sync call to load a node, for example:

```
function my_custom_theme_image(variables) {
  var html = '';
  node_load(123, {
    async: false,
    success: function(node) {
      html += node.title;
    }
  });
  return html;
}
```

**Comment by jharbertdev** [comment]
How would I make DG core pass along an entity to the theme() system?

**Comment by signalpoint** [comment]
@jharbertdev Dig in there and understand the code ;)

**Comment by jharbertdev** [comment]
DG Core... are you referring strictly to drupalgap.js?

**Comment by signalpoint** [comment]
@jharbertdev DG core lives in the `src` directory, then we use the `makefile` to compile the entire `src` directory into a single `bin/drupalgap.js` file.

You can either dig into the `src` directory, and use the `makefile`, or just modify the `bin/drupalgap.js` file directly (not recommended). More info: http://drupalgap.org/develop

**Comment by jharbertdev** [comment]
Thanks for the help.
