### ISSUE TITLE
Translating Drupalgap

### ISSUE THREAD

**Issue by Zonzio** [signalpoint/DrupalGap#413]
Hi,

At the moment I'm making an Drupal site, which will be in Dutch. I'm using Drupalgap to make an app to go with this site, but I'll like the app to be in Dutch as well

I have looked around but haven't seen a way to translate Drupalgap. I could ofcourse just manually translate the string in the core files, but that would mean my translations would be lost when updating

So my question is, is there a way to translate Drupalgap? Or would I have to do this manually in the core files

**Comment by signalpoint** [comment]
@Zonzio this is becoming a very common feature request. Right now DrupalGap does not support multiple languages, and there is no way to translate. Here are some related issues:

https://www.drupal.org/node/2368435
#148 

It is quite a complex issue, and I am very much looking for someone(s) to help contribute to make this happen.

Essentially DrupalGap needs a t() function used everywhere in core, and then some kind of language file(s) (maybe even just JSON) to have the English string, and then the language code and translated string.

**Comment by Zonzio** [comment]
Ah, that's too bad

I'm not very experienced in module development (yet), but maybe I could somehow help if this feature were te be added, even if it just were to translate strings

Thank you for your time

**Comment by signalpoint** [comment]
@Zonzio What language code(s) are you looking to translate?

**Comment by Zonzio** [comment]
Dutch

**Comment by coolman7** [comment]
Hi Tyler,

I have a proposal for language translation:

I have implemented a simple function inside a new file called translate.inc.js for language translation. There would be better ways, but this is only a beginning. This method works for some text (for example works for Member since) and does not work for some text (for example does not work for Exit confirm dialogue), I don't understand why not working.

Anyway I need to modify all text messages in core files for t() functions, and I don't want to do this, because I don't want to loose updates. Is it possible to change text messages inside core files with t('text'). 

```
'<dl><dt>Member since</td></dt><dd>'
```

should be converted to:

```
'<dl><dt>'+t('Member since')+'</td></dt><dd>'
```

And you may define t function as empty like this if you don't want to define any translate function as a start:

```
function t(str) {
  return str;
}
```

Also it may be a good idea to create another file called includes/translate.inc.js and t function could be inside translate.inc.js file. With this way, people will not have to alter the other core files for language translation. they just need modify t function inside translate.inc.js file.

t function example:

```
function t(str) {
    switch (str) {
        case 'Member since':
            switch (Drupal.settings.language_default) {
                case 'tr': return 'Üyelik başlangıcı';
            }
            break;
        case 'Confirm':
            switch (Drupal.settings.language_default) {
                case 'tr': return 'Onay';
            }
            break;
        case 'OK':
            switch (Drupal.settings.language_default) {
                case 'tr': return 'Tamam';
            }
            break;
        case 'Cancel':
            switch (Drupal.settings.language_default) {
                case 'tr': return 'İptal';
            }
            break;
    }
    return str; 
}
```

There could be other methods to be developed for translation. We can discuss these methods later.

PS: If I am sure my efforts won't be wasted and they'll be pulled to main repository, I'll fork and change texts to t() function as much as I can. 

Thanks

**Comment by signalpoint** [comment]
@coolman7 Great start, thank you!

Yes, I think by starting with a basic `t()` function like you mentioned:

```
function t(str) {
  return str;
}
```

This could just go in `common.inc.js` for now. At that point, DrupalGap core could begin the tedious process of using `t()` everywhere there is text.

Then for the actual translation, I'd like to see individual language files for each language code, for example (in a new folder):

```
www/locale/tr.json
```

And would contain a JSON object

```
{
  'Member since': 'Üyelik başlangıcı',
  'Confirm': 'Onay',
  'OK': 'Tamam',
  'Cancel': 'İptal'
}
```

These language files would have to be loaded dynamically during the bootstrap according to settings.js language settings. The settings.js file will need to be expanded a bit, to allow for multiple locales:

```
drupalgap.settings.locale = {
  'tr': { }
  /* other language codes could go here */
};
```

Then during the bootstrap each language JSON would need to be loaded into scope.

```
// bootstrap...
if (typeof drupalgap.settings.locale !== 'undefined') {
  $.each(drupalgap.settings.locale, function(language_code, language) {
      var file_path = 'locale/' + language_code + '.json';
      drupalgap.locale[language_code] = JSON.parse('/* load file content */');
  });  
}
```

Then a call to t() would still be:

```
var foo = t('OK'); // default language
var bar = t('OK', [], [], 'en'); // specific language
```

Then `t()` could be expanded to something like:

```
function t(str) {
  var lang = arguments[3] ? arguments[3] : Drupal.settings.language_default;
  if (
    lang != 'und' &&
    typeof drupalgap.locale[lang] !== 'undefined' &&
    drupalgap.locale[lang][str]
  ) {  return drupalgap.locale[lang][str]; }
  return str;
}
```

If you take on this, your efforts will absolutely not be wasted, it would be a great contribution. I'm open to discussion on the best way to handle/represent individual language files. All are welcome to #drupal-drupalgap on IRC to chat about it.

**Comment by signalpoint** [comment]
@coolman7 check out the progress, we now have translation files!

https://github.com/signalpoint/DrupalGap/tree/7.x-1.x/locale

Next up, I'd like contrib and custom modules to be able to declare their own language files. For example:

```
app/modules/custom/my_module/locale/tr.json
```

Then I think we need a `hook_locale()` so modules can signal which language codes they are implementing:

```
function my_module_locale() {
  return ['tr'];
}
```

Then custom/contrib modules can provide their own translations separate from DrupalGap core:

```
{
  "Custom English string": "translation-goes-here"
}
```

Then DrupalGap bootstrap would need to invoke any implementors of this hook, load up their language files, then `extend` them into `drupalgap.locale` accordingly.

**Comment by coolman7** [comment]
As far as I understand, there still needs some work to have translation for drupalgap core or I just don't know exact steps to be done.

I just copied all files to my current project's src, bin and locale directories. And I added some new translations to tr.json file. And following is in settings.js file:

```
Drupal.settings.language_default = 'tr' 
```

But there is no translation I can see.

Do I need to do something else? Do I need to add or define following file to anywhere in my settings or custom modules?

```
app/locale/tr.json
```

**Comment by signalpoint** [comment]
@coolman7 Did you rebuild the `bin/drupalgap.js` file using `make` after updating the `src` directory?

There's also an update to the settings.js file: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/app/default.settings.js#L92

You may be able to use the GitHub interface to pull in the latest changes from this repo, to your repo. If not, you need to add this repo as a remote, then you can pull in the latest changes from 7.x-1.x. Copying changes manually makes GIT angry ;)

**Comment by coolman7** [comment]
make and adding locale in settings.js do the trick. Now it works for drupalgap core.

Thanks for great job.

I look forward for module translation.

**Comment by signalpoint** [comment]
@coolman7 you're welcome, thank you for igniting the `t()` initiative. Just a reminder that the `locale` folder is only for core translations. We'll soon allow module developers (app creators) to put translations for their customizations into their own app. Please continue to submit any core translations for the `tr` language code.

**Comment by coolman7** [comment]
I'll upload it, when I will finish it.

Is it possible to switch language to English, by changing this setting variable in a custom module like this?

```
Drupal.settings.language_default = 'en';
```

**Comment by signalpoint** [comment]
@coolman7 Yes, you can change the `default_language` in a custom module. Any pages already loaded in the app, will need to be reloaded, so consider calling `drupalgap_remove_all_pages_from_dom()`.

**Comment by coolman7** [comment]
This is great. I think we will have only one missing thing (texts in settings.js file) to have a complete multilingual application:

Like this one:

```
drupalgap.settings.loader = {
  loading: {
    text: 'Loading...',
    textVisible: true,
    theme: 'b'
  },
  saving: {
    text: 'Saving...',
    textVisible: true,
    theme: 'b'
  },
  deleting: {
    text: 'Deleting...',
    textVisible: true,
    theme: 'b'
  }
};
```

I hope We may have option to change them at runtime.

PS: I can change text with 

```
drupalgap.settings.loader.loading.text = 'sometext...';
```

**Comment by signalpoint** [comment]
@coolman7 Loader messages are now translated at run time.

**Comment by kinmenRP** [comment]
I don't know if this could be of any use, but did you know about this:

http://i18next.com/

It is a full-featured i18n javascript library for translating your webapplication. Runs in browser, under node.js, rhino and other javascript runtimes.
I don't have a clue about how it works, but maybe it can save you some time... Sorry if it's OT.

**Comment by signalpoint** [comment]
@kinmenRP Interesting. I don't think I would put that in DrupalGap core, but it looks like it could be an awesome contrib module for DrupalGap.

**Comment by kinmenRP** [comment]
Well, happy to know it was worth a look

**Comment by signalpoint** [comment]
@Zonzio it'd be awesome if you could start on the Dutch translations, see this page for more details: http://drupalgap.org/translate

**Comment by kinmenRP** [comment]
As you've noted I've added th IT translation: pls note that there're more translated text strings than in the the other 2 translations (32 so far), therefore for the next translations you can use that one as a template if you like. Let me know if I've missed any text string. I've translated "Spaces are allowed; punctuation is not allowed except for periods, hyphens, apostrophes, and underscores" too, but this doesn't work, maybe hardcoded somewhere...

**Comment by signalpoint** [comment]
@kinmenRP pull in the latest commit for the fix to translations on form element descriptions.

**Comment by signalpoint** [comment]
We now have support for contrib/custom modules to provide their own translations. See the docs for more details: http://drupalgap.org/translate

**Comment by coolman7** [comment]
I forgot to add t() to 'Add Picture' in entity module. I'll push it later.

**Comment by kinmenRP** [comment]
Just noted that in tr.json, after "Cancel": "İptal", there is no ","

**Comment by coolman7** [comment]
This is interesting. I pushed that code and in my files there is ",". 
It should be removed accidentally after I pushed.

**Comment by kinmenRP** [comment]
BTW, just as suggestion, wouldn't it be nicier if all the terms/sentences in the translation files could be in alphabetical order? So to easier find the desired text?

**Comment by coolman7** [comment]
I've already sorted them. It will be updated on next pull.

**Comment by kinmenRP** [comment]
good

**Comment by signalpoint** [comment]
@coolman7 @kinmenRP I've removed the extra "cancel" translation that was missing a comment.

**Comment by Zonzio** [comment]
@signalpoint Great to see it's now possible to translate DrupalGap! For now I've copied the it.json file and translated the strings to Dutch

**Comment by coolman7** [comment]
I want to change offline messages at these lines in system.js file.
Language is set in settings.js as following:

```
Drupal.settings.language_default = 'tr';
```

I added strings to tr.json file and build it. But they were not translated. Is there any way to translate strings in system.js?
Thanks

```
function system_offline_page() {
  try {
    var content = {
      'message': {
        'markup': '<h2>'+t('Failed Connection')+'</h2>' +
          "<p>"+t("Oops! We couldn't connect to")+":</p>" +
          '<p>' + Drupal.settings.site_path + '</p>'
      },
      'try_again': {
        'theme': 'button',
        'text': t('Try Again'),
        'attributes': {
          'onclick': 'javascript:offline_try_again();'
        }
      },
      'footer': {
        'markup': "<p>"+t("Check your device's network settings and try again.")+"</p>"
      }
    };
    return content;
  }
  catch (error) { console.log('system_offline_page - ' + error); }
}
```

**Comment by signalpoint** [comment]
@coolman7 you won't need to build/make to get the new translations to show up, and the translations should show up automatically. Try clearing your browser's cache, or you can overwrite the `page_callback` and make your own custom offline page: http://drupalgap.org/node/210

**Comment by kinmenRP** [comment]
Uff... for the hurry I've created a patch into the signalpoint repo instead of my own, with a new translation file which isn't complete yet. I didn't ask for a pull, but you can (should) delete that patch because it's not complete. Sorry for the mistake

**Comment by coolman7** [comment]
I have some problems with custom module translations. I did following steps but translatation did not work for my custom module:

0) I already added before to settings.js to get core translation which is working fine.

```
Drupal.settings.language_default = 'tr';
drupalgap.settings.locale = {
  tr: { }
};
```

1) Downloaded SDK 1.1 from http://drupalgap.org/download
2) Extract 7.x-1.1.tar.gz file and copy only src and bin directories to my existing project
3) modified index.html as this

```
<script type="text/javascript" charset="utf-8" src="bin/drupalgap-7.x-1.1.min.js"></script>
```

4) added following lines to my_module.js file

```
function my_module_locale() {
  return ['tr'];
}
```

5) Created app/modules/custom/my_module/locale/tr.json file as 

```
{
  "My settings": "Tercihlerim",
  "All deals": "Tüm fırsatlar",
  "Deals near me": "Yakın fırsatlar"
}
```

6) Changed texts in my_module.js as t('text') format.
7) build and run project 
But translation did not work for my_module. Did I forget something to do?

**Comment by signalpoint** [comment]
@kinmenRP no worries, submit a pull request whenever you're ready, thanks.

@coolman7 try stepping through the `drupalgap_load_locales()` function to make sure DrupalGap core is properly loading your custom language file: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/drupalgap.js#L617

**Comment by kinmenRP** [comment]
Pull request for Traditional Chinsese translation

**Comment by kinmenRP** [comment]
Hello. How can I provide transations for your custom mudules (for ex geofield?) Do I need to fork every project and create a json file by myself?

**Comment by signalpoint** [comment]
@kinmenRP Fortunately/unfortunately yes. There are more details on this topic here: http://drupalgap.org/translate

**Comment by kinmenRP** [comment]
I've already red it, but just to be sure, what I need to catch inside geofiled.js is just any 'title' and 'text' or is there anything else?

**Comment by signalpoint** [comment]
@kinmenRP Yup, there are just a handful of English strings in geofield.js, just wrap them in `t()` if they haven't been already, then implement the hooks and create the files mentioned in the doc.

**Comment by kinmenRP** [comment]
Ok, I've tried to do so. Can you give a look at https://github.com/kinmenRP/geofield and see if it is ok? As I've told you I don't know javascript, therefore I prefer to get a check before messing up everyting. The hook is at the bottom of js file. I've created a it.json translatio. I didn't test because first I need to understand why my core translation doesn't work in my app...

**Comment by signalpoint** [comment]
@kinmenRP Looks good. Just make some calls to `t()` on the Lat/Lon in `geofield_field_formatter_view()`.

**Comment by coolman7** [comment]
https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/drupalgap.js#L617
and drupalgap.js file from SDK 1.1 are not same. drupalgap_load_locales() starts at 607. line but file at github, starts at 617. 

Do you think my problem could cause because of that?

**Comment by signalpoint** [comment]
@coolman7 Yes, definitely. Please always use the latest `bin/drupalgap.js` file when testing out the latest and greatest features.

**Comment by coolman7** [comment]
Sorry. I forget to update my post. I found my mistake. I made a mistake in json file. I forgot to put a "," at the end of a line. json file is too strict and we should not make any mistake. It is hard to debug mistakes in json file. I'll use jsonlint.com next time I'll update json file.

**Comment by kinmenRP** [comment]
pull request for geofield module! Pls check it before accepting it.

**Comment by coolman7** [comment]
I wanted to translate "Wrong username or password." text. But it is not appear in source of drupalgap. Is it inside services module of drupal?

**Comment by signalpoint** [comment]
@coolman7 That is a message directly from the Drupal Forms API (which the Services module uses to perform its operations). You'll have to hook into Drupal some how to intercept and translate that message, perhaps by using a language code URL prefix (or other Drupal transliteration techniques).

I'm going to close this issue now, for future translation issues/requests, let's open individual issues for each.
