### ISSUE TITLE
Views exposed filter text input

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#414]
So, text fields, when you click the go or enter button on a phone cause the page to white screen. I think it's trying to reload the index.html. preventDefault doesn't work well either because the form is loaded after the page events fire.

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
