### ISSUE TITLE
invoke drupalgap_goto_preprocess in drupalgap_back()

### ISSUE THREAD

**Issue by g089h515r806** [signalpoint/DrupalGap#417]
drupalgap_back act the same function with drupalgap_goto, the different is is return previous page.
I want to hook in when page changed. "drupalgap_goto_preprocess" is the hook I want to choose, but it does not work with drupalgap_back(). 

```
/**
 * Change the page to the previous page.
 */
function _drupalgap_back() {
  try {
    drupalgap.back = true;
    history.back();
    // Invoke all implementations of hook_drupalgap_goto_preprocess().
    module_invoke_all('drupalgap_goto_preprocess', drupalgap.back_path);
    drupalgap_path_set(drupalgap.back_path);
    // Invoke all implementations of hook_drupalgap_goto_post_process().
    module_invoke_all('drupalgap_goto_post_process', drupalgap.back_path);
  }
  catch (error) { console.log('drupalgap_back' + error); }
}
```

Reference: https://www.drupal.org/node/2380207

**Comment by signalpoint** [comment]
@g089h515r806 Thanks, this makes sense. Will you please make a fork of the DrupalGap SDK and submit a Pull Request with this improvement?

**Comment by signalpoint** [comment]
The "post_process" has been added quite some time ago: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/includes/go.inc.js

It's now known as `hook_drupalgap_back`: http://api.drupalgap.org/7/global.html#hook_drupalgap_back

I'll close this for now, unless the need for a "pre_process" on the back event arises, then it should be pretty easy to add.
