### ISSUE TITLE
Exporting my App for to Eclipse

### ISSUE THREAD

**Issue by kuukua** [signalpoint/DrupalGap#420]
Hi Tyler,
I am new to Drupalgap but have worked my way into creating my first app but i will like to Export my app from the normal Ripple Emulator view to Eclipse so as to run the app in an Android emulator as well as getting the APK for my App.
I went through the steps in http://www.drupalgap.org/node/185 but it seems the folder am uploading to Eclipse isnt what is required. I strongly think i have missed my steps somewhere.
This is the link to my mobile app http://studgh.com/mobile-application/
please help me fix this because i am stacked

**Comment by kuukua** [comment]
Sorry, i mean Importing my App, not exporting. Dont know what i was thinking

**Comment by signalpoint** [comment]
Sorry for the delay in response. Compiling an app from the terminal and from Eclipse is now covered fairly well in the docs: http://docs.drupalgap.org/7/Compiling_a_Mobile_Application/Publishing_an_App_for_Android
