### ISSUE TITLE
Stuck after splash, need a manual push to get it rolling!

### ISSUE THREAD

**Issue by hadihadi** [signalpoint/DrupalGap#426]
Hi,
<b><i>Background Info:</b></i>

<pre>
     Dev Environment:
       phonegap –v: 4.1.2-0.22.9
       Platforms: android
       Plugins: camera 0.3.3, console 0.2.11, device 0.2.12, dialogs 0.2.10,
                file 1.3.1, geolocation 0.3.10, inappbrowser 0.5.3, network-information 0.2.13
       site: http://hadi.com.kw/d733
       modules: DrupalGap 7.x-1.8, Services 7.x-3.11, Geofield 7.x-2.3

       Building with CLI: phonegap build android
       Testing with CLI: phonegap serve + PhoneGap Developer App running on Galaxy Note 3
</pre>

<b><i>Issue:</b></i>
I get the splash screen followed with the loading progress icon twice then I get stuck with the splash. 

<b>When I change anything in index.html or drupalgap.js while everything is running</b> (e.g. adding console.log() to drupalgap.js), phonegap serve reloads everything automatically and the app works perfectly!! (<<-- the manual push!)

<b><i>Other Notes:</b></i>
1.Geofield loads fine
2.I did put few console.logs() in drupalgap_bootstrap() and it seems fine.
3.I do get a 404 on favicon.ico
4.If I remove the<pre> ... type="text/javascript" src="cordova.js"... </pre>from index.html nothing happens and nothing is loaded after the splash is displayed. Therefore, This line is required (I think) in my index.html.
5._Started mobile app recently so I'm a newbie_ :)
<br><br>
Any ideas much appreciated.

Regards

**Comment by signalpoint** [comment]
@hadihadi It appears you are using PhoneGap Build to compile the app, correct? I've never used the service, but I've heard it is necessary to have a config.xml file present. This file is normally included when using the PhoneGap Command Line Interface (CLI) to create a project, but we don't include it in the SDK since it is custom per project (I think).

Try using the CLI to create a project, then look through the project folder(s) for the config.xml file, and see what you can find.

**Comment by hadihadi** [comment]
@signalpoint 
1. I’m using the CLI command line “..>phonegap build android”  locally.
I’m NOT using the online services on “https://build.phonegap.com/”
2. config.xml file is there under my project directory on the same level of the www directory and I see some signs of its being used and loaded. 
Plz. note that I followed your guides on :
http://www.drupalgap.org/node/193 
http://tylerfrankenstein.com/code/build-mobile-app-geo-tag-photo
1. I think I miss-lead you (my mistake, I apologize for that). I believe that this is another case of the celebrated :) WSOD;<b> but with a twist</b> (I’ve inserted few greeting html statements in the index.html file and called it splash. but when I use ur original index.html  file we are back to WSOD, sorry ). 
   <br><br>
   <b> <i>The twist<i>: The app works <i> but not initially</i>.</b><br>
   I) After running  “phonegap serve” CLI command and connecting with the Phonegap App on my testing android mobile;  I get the loading progress icons twice then the WSOD.  
   While on the command line window, after the initial connection and loading messages I get a stream of :
   <pre> 200 /**api**/autoreload
   200 /**api**/autoreload
   ...</pre>

<b>to get the app working</b> while everything is running, I edit (e.g. insert  in) the index.html file then save it. Phonegap-serve will detect the change and reloads everything. 
After this the WSOD is gone and the app is rolling perfectly?!<br>
Sounds like phonegap CLI issue? Maybe!
I’m thinking of actually building and running it… this might get it resolved if it is a CLI issue.
->Should I use the https://build.phonegap.com/ to build it, install it and run it? or is there better alternative?

**Comment by signalpoint** [comment]
@hadihadi I typically use these commands to build and then deploy to my Android phone:

```
cordova build android
cordova run android
```

I've never tried the `phonegap` command, or PhoneGap Build, so I can't speak to their usage.

**Comment by signalpoint** [comment]
@hadihadi FYI, make sure this isn't the cause of the WSOD: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/UPGRADE.md#new-pagetplhtml-placeholder-token-required

**Comment by hadihadi** [comment]
@signalpoint 
Just installed the app directly on my testing mobile and <b>it worked flawlessly- <i>No WSOD</i></b>.
It appears to be “phonegap serve” CLI issue.<br/><br/>
Thank you for your superb work and help.
Kindest regards
Hadi
