### ISSUE TITLE
_drupalgap_back_exit() exits on both buttons(ok, cancel)

### ISSUE THREAD

**Issue by kiss-jozsef** [signalpoint/DrupalGap#428]
```
function _drupalgap_back_exit() {
    try {
      navigator.app.exitApp();
    }
    catch (error) { console.log('_drupalgap_back_exit - ' + error); }
}
```

exits the app even if on the confirmation popup you press the cancel button.

```
function _drupalgap_back_exit(button) {
  try {
    button === 1 ? navigator.app.exitApp() : '';
  }
  catch (error) { console.log('_drupalgap_back_exit - ' + error); }
}
```

by adding it like this with the button parameter which he gets from navigator.notification.confirm() we can check which button was clicked it has a numerical id.

**Comment by signalpoint** [comment]
@kiss-jozsef thank you for pointing this out. Will you please make a fork of this repository, make the changes above, commit them, then submit a pull request? That way you can be credited with the improvement to DrupalGap, thank you.
