### ISSUE TITLE
type error on creating comment

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#43]
When creating a comment, I get ...

drupalgap_goto - Type error:
'undefined' is not an object

Using IOS emulator, latest alpha with latest dev of drupal module. Clean install of latest drupal 7. The comment gets save, but the alert error happens. My settings.js has "dashboard" as the home screen.

**Comment by signalpoint** [comment]
@cschaub

I think this was related to some other issues. I am able to create comments on a node/123 type page in DrupalGap.

Are you able to create comments on a node page? Were you having the problems on a separate comment from page?

**Comment by signalpoint** [comment]
This should be all fixed up now, I was posting comments without issue earlier today. Re-open if problem persists.
