### ISSUE TITLE
Node Comment Form Disappears when Navigating Back and Forth Between Nodes.

### ISSUE THREAD

**Issue by czbaa** [signalpoint/DrupalGap#430]
Open "node/1" >back >open "node/2" >back > second time open "node/1", the node/1 comment form No Display. Just display the last open node's comment form.
Add {reloadPage:true} that is OK, but This will waste data traffic!

**Comment by signalpoint** [comment]
@czbaa Thanks for pointing this out. I think if you add a line here (https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/comment/comment.js#L167), like this:

```
form.id += '_' + comment.nid;
```

That should fix it. Will you please make a Fork of DrupalGap, change the code, test it out, then commit your code, push it up, and then submit a pull request with the fix?

**Comment by czbaa** [comment]
yes, fix the display, but other question, when comment form have image field first time open a node click the "take a photo" can not open camera, second time OK.

**Comment by signalpoint** [comment]
@czbaa Nice, I'm glad the first problem is fixed. Please open a separate issue for the new bug you found, thanks.

**Comment by signalpoint** [comment]
Fixed via #803
