### ISSUE TITLE
How to show Custom taxonomy/term/% Page on DrupalGap

### ISSUE THREAD

**Issue by rajesh-h** [signalpoint/DrupalGap#432]
Hi,
I need to change the default taxonomy/term/% view, on my drupalgap app I want to show only Article body.
I have created a custom view under drupalgap/taxonomy/term/% this outputs json view which has Message Body and its last updated date.

I have a cusom module writen in drupalgap to show the list of terms. this is my Home page on the app which is available at http://qmr-rajs.rhcloud.com/mobile-application/ (I use Ripple emulator to view this app) only logged in user can view the page Username - 123 password -123123 

``` jquery
/**
 * Implements hook_menu().
 */
function module_categories_menu() {
  var items = {};
  items['categories_view'] = {
    title:'Subscribed Products',
    page_callback: 'module_categories_articles_page'
  };
  return items;
}

/**
 * The page callback to display the view.
 */
function module_categories_articles_page() {
  try {
    var content = {};
    content['my_categories_list'] = {
      theme: 'view',
      format: 'ul',
      path: 'category-view', /* the path to the view in Drupal */
      row_callback: 'module_categories_articles_list_row',
      empty_callback: 'module_categories_articles_list_empty',
      attributes: {
        id: 'my_categories_list_view'
      }
    };
    return content;
  }
  catch (error) { console.log('module_categories_articles_page - ' + error); }
}

/**
 * The row callback to render a single row.
 */

function module_categories_articles_list_row(view, row) {
  try {
     /*return l(row.title, 'node/' + row.nid);*/
        return l(row.name, 'taxonomy/term/' + row.tid );
  }
  catch (error) { console.log('module_categories_articles_list_row - ' + error); }
}

/**
 *
 */
function module_categories_articles_list_empty(view) {
  try {
    return 'Sorry, no articles were found.';
  }
  catch (error) { console.log('module_categories_articles_list_empty - ' + error); }
}
```

This will show the page like this
![selection_004](https://cloud.githubusercontent.com/assets/6675921/5554872/c6df844e-8c4b-11e4-8bca-262f324a595a.png)
When I click on any Term say Term 1 I will get list of articles which are linked to this term with article title which is then linked to the article node page, The page shows like below,
![selection_005](https://cloud.githubusercontent.com/assets/6675921/5554874/055e777a-8c4c-11e4-83a2-22ed0765035e.png)
This is the expected behaviour ,
What I want to do here is , rather than showing list of article title with click option to node/%, I want to show the body directly of all related article one after another when a user clicks on any of the terms.
Sample like below
![selection_004](https://cloud.githubusercontent.com/assets/6675921/5554897/5e2fdf54-8c4e-11e4-8cd2-c2c72ab48392.png)
I have written a custom view which is available at http://qmr-rajs.rhcloud.com/drupalgap/taxonomy/term/8
Could you please help me how I can link this view to my app to show the body

**Comment by signalpoint** [comment]
@just10minutes You'll have to make a custom page in your app (e.g. my-custom-node/%) with page arguments (for the term id), and a pageshow handler. Then use the pageshow handler and argument to build a Views Render Array with your custom view, and have its row handler output the desired format.

**Comment by rajesh-h** [comment]
@signalpoint Thank you for your reply. I will try to do this and update in couple of hours.
