### ISSUE TITLE
When user register can not back front

### ISSUE THREAD

**Issue by czbaa** [signalpoint/DrupalGap#433]
When registering a new user, click on the submit button,   display  "loading..................", can not jump to the front page.

**Comment by signalpoint** [comment]
@czbaa What user registration settings do you have set on your Drupal site?

**Comment by czbaa** [comment]
Use logintoboggan module , setting "allow users to choose their initial password"..........

**Comment by signalpoint** [comment]
@czbaa Turn on debug mode in settings.js and watch the console.log() output, what does it say? It sounds like it is getting stuck, and possibly the service call isn't going through properly if passwords aren't being provided. Does the user registration form show the password field(s) properly? Have you installed the logintoboggan module in DrupalGap. Please answer those three questions, thanks.

**Comment by czbaa** [comment]
:+1: Thank you very much! 
1. the console.log() output : 
...
POST (ERROR): http://www.example.com/?q=foo/user/register.json - 200 - OK
SMTP -> ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)
<br />SMTP error: could not connect to SMTP host.
{"uid":"1111111","uri":"http://www.example.com/foo/user/1111111"}
..........
..........
Drupal.services.call - onload - SyntaxError: Unexpected token S
...
2.yes.
3.yes.

A solution I found is to turn off the SMTP module.

**Comment by signalpoint** [comment]
@czbaa Thank you for confirming.
