### ISSUE TITLE
Allow developer to choose apply exposed filter or not

### ISSUE THREAD

**Issue by vkudyushev** [signalpoint/DrupalGap#436]
It's be better to allow developer to choose apply exposed filter or not, because after upgrading to 7.x-1.0-rc4 some capabilities (like this https://www.drupal.org/node/2339997) isn't avalaible. So I'm need to downgrade... It's not critical, but in future it'll be better I think

**Comment by signalpoint** [comment]
@vadimk-design Sorry, I do not understand the issue here. Which capability isn't available anymore?

To enable/disable exposed filters on Views JSON, just add/remove the exposed filters from the Views' display.

**Comment by vkudyushev** [comment]
@signalpoint sorry, I really explaned without detailes. 
In my app there is a settings page, where users choose some options and this options are uses for filtering content in all application on all views pages. But in 7.x-1.0-rc4 release this way is broken and all filters work only on views page by exposed filters in dropdown list and not working by adding some "&my_expoed_filter=foo" to the url

**Comment by signalpoint** [comment]
@vadimk-design If you turn on debug mode in the settings.js file, and try to load the page in your app, what does the console.log() output for the URL that is being queried on your site? For example:

```
http://www.example.com/?q=my_view&my_expoed_filter=foo
```

What does that URL look like?

**Comment by signalpoint** [comment]
It's now possible to disable the display of exposed filters with a DrupalGap Views Render Array: http://docs.drupalgap.org/7/Views/Views_Exposed_Filters

```
content['my-view'] = {
  theme: 'view',
  exposed_filters: false,
  /* ... */
};
```
