### ISSUE TITLE
Custom Modules not being picked up

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#44]
I've trade all steps made a custom module, used the example module, tried including the dg_pro module but they arn't getting picked up by using this hook in settings.js 

drupalgap.modules.custom 

The syntax is all fine.

The module is fine as it works when I put it into the array thats in drupalgap.js

**Comment by scotthooker** [comment]
Ah ok. The module needs to be in a /custom/ folder. I think. Might patch the documentation as that confused me.

**Comment by signalpoint** [comment]
Thanks for reporting this.

For now, when creating custom modules, they are only recognized by DrupalGap core when placed inside this directory:

app/modules/custom

The drupalgap_modules_load() function needs to be improved to search recursively.

**Comment by scotthooker** [comment]
I don't think its a massive issue I just misread the documentation. It was misleading having the example module where it was and then I put it in the app folder but not inside a /custom/ folder. 

Basically I should have read the documentation! 

All good though brilliant module and framework. 

I'm taking notes as I develop this so will happily contribute to any documentation. 

Cheers,

S

**Comment by signalpoint** [comment]
We'll leave custom modules in the app/modules/custom folder.
