### ISSUE TITLE
override offline page

### ISSUE THREAD

**Issue by halmsx** [signalpoint/DrupalGap#446]
hi

just started with drupalgap. very excited to use it for my current project.

im aware of the issue https://github.com/signalpoint/DrupalGap/issues/258. right now i just need a quick solution. this is when opening the app 1st time or after it is closed.

when opening the app, if users are shown the splash page. then if offline, they will be shown the "offline" page. i want to override this and take users to another page.

is it possible to create a custom module with "!drupalgap.online" to override the default and display a different page? using hook_deviceready perhaps?

thanks in advance.

**Comment by signalpoint** [comment]
@halmsx See this page here: http://www.drupalgap.org/node/210

You can overide the page_callback (for any page), and customize it's output.

Use `drupalgap_check_connection()` instead of `!drupalgap.online`

**Comment by halmsx** [comment]
I saw the page earlier but couldnt it make out. Think i do now. Thanks!

**Comment by halmsx** [comment]
hi,

sorry for reopening this.

ive tried the link you gave. but it dont seem to do anything.

```
function thisMain_deviceready() {
  try {
    drupalgap.menu_links['offline'].page_callback = 'my_offline_page';
  }
  catch (error) {
    console.log('thisMain_deviceready - ' + error);
  }
}
```

i also tried the following, copied from _drupalgap_deviceready(), but not working either.

```
function thisMain_deviceready() {
  try {
    drupalgap_check_connection();
    if (!drupalgap.online) {
      drupalgap.menu_links['offline'].page_callback = 'my_offline_page';
      alert('is offline');
    } else {
      alert('is online'); // works if data is on
    }
  }
  catch (error) {
    console.log('thisMain_deviceready - ' + error);
  }
}
```

if i turn off all data, it still shows the default "Failed Connnection" page.

did i miss anything? thanks again.

**Comment by signalpoint** [comment]
@halmsx Do you have a module called `thisMain`? Is it enabled in `settings.js`? Is it located in `app/modules/custom/thisMain`? Do you have a function called `my_offline_page` in your module's .js file?

**Comment by halmsx** [comment]
wow.. that was fast... 

yes. if i have data on, alert('is online') is displayed.

**Comment by signalpoint** [comment]
@halmsx Please share all relevant code here, or use a service like pastebin to share it.

**Comment by halmsx** [comment]
hi

put it here >> http://pastebin.com/tnuhkQ63

the alert(connection) works if i turn on data. so the module is working fine.
![screenshot_2015-02-10-22-08-01](https://cloud.githubusercontent.com/assets/7524731/6128507/6f547fc2-b171-11e4-92c2-bff4f3e1c16a.png)

thanks.
