### ISSUE TITLE
Image not displaying in View

### ISSUE THREAD

**Issue by mfuggle** [signalpoint/DrupalGap#448]
I have a view which contains an image and some other fields. All fields display correctly other than the image field. When I inspect the element it shows as <img class="" src="[object Object]">. I had this working just fine but do not know what I have done to cause the problem. Any leads?

Cheers
Martin Fuggle

**Comment by signalpoint** [comment]
The latest (and first) recommended version of the Views Datasource module has been released recently. The module has changed the way it outputs an image field's JSON. A common use case is to get some image field URLs from a View JSON and display them the images. If you've done that in the past, you'll have to update your app's code to render a Views JSON row with the new syntax. It now bundles the path to the image within the `src` field inside your Views JSON:

# Old Way

```
function my_module_views_json_row(row) {
  return theme('image', { path: row.field_image });
}
```

# New Way

```
function my_module_views_json_row(row) {
  return theme('image', { path: row.field_image.src });
}
```

Vist the Drupal Admin UI for the View and click the "Preview" button, there you can see an example of the new JSON structure.
