### ISSUE TITLE
jQuery isn't working inside modules

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#449]
jQuery doesn't seem to be working inside of my_module.js files.  Not sure if it is drupalgap or jQuery Mobile.

example of what I am trying add at the bottom of my_module.js

```
$('#filter_results-button span').text();
```

I even tried doing this from the chromes console and nothing.  Very strange.

I am going to try creating a totally separate JS file, include it in the <head> of your index.html file, and perhaps jQuery will work from there.  I will let you know.

**Comment by ice423cube** [comment]
I was able to add a script tag to the index.html file and get jQuery to work.  I used the following code to get jQuery to run on the pageshow. Still haven't figured out how to do it inside the module.

```
(function ($) {
    $(document).on('pageshow',function(){
              //Do stuff on pageshow
    }); //end of pageshow                
}(jQuery));
```

**Comment by signalpoint** [comment]
@ice423cube What happens if you put this code in a separate JS file, and the include that JS file in the `head` of the index.html file? Does it still work?

I'm guessing the reason it doesn't work inside a module is that when DrupalGap is bootstrapping, it dynamically loads your module's JS file and adds it to the "page" on the fly.

**Comment by ice423cube** [comment]
Yep that works.  I can have the .js file live with the module and you just have to point the script tag in the head of your index.html file to point to that location.  It doesn't seem to care where it lives just as long as it isn't part of the my_module.js.

**Comment by signalpoint** [comment]
@ice423cube Good to know, I'd recommend that approach for now, so the index.html stays cleaner (easier for upgrades later).

**Comment by signalpoint** [comment]
Added documentation regarding this: http://www.drupalgap.org/node/531
