### ISSUE TITLE
Usage of Other Libraries?

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#45]
This originally was an e-mail thread between @uniquename and I talking about the possibility of using other Libraries to strengthen DrupalGap as a framework. Please feel free to comment with any of your thoughts, thanks!
# uniquename
- Being not a js jedi, I'm wondering that everybody talks about all that
  libraries from mustache to backbone to angular, and drupalgap is just built
  on jQM. What where your reasons to choose that way?
# signalpoint

A tough question... I've feared that I should have used some other libraries like backbone, node.js, angular, mustache, etc... but to be honest, I really still don't know much about them and I am at times stubborn and will just start coding :P The only reason I chose jQM was because jQuery is shipped with Drupal and I have much experience with it and it seemed like the right approach at the time. I am definitely open to hearing about/using other libraries, I just don't know which are the best and which can be used for this type of aplication.
# uniquename

hmm... same here, never used such libraries, just hear everybody talking about them. I mean backbone and require for example say, 
they help organizing code - that is already done in DG i guess 
they bring a router - thats done by modules/menu, or?

what i don't know, is what about a template engine, really just thinking loud, didn't look at this closer...
# uniquename
- recently I found some stuff saying, that jQM is not like ideal for
  phonegap, because it also carries a lot of browser releated stuff, hence
  becoming bigger and slower. Can you verify that?
# signalpoint

I can verify that jQM runs a bit slow inside of PhoneGap. I've always hated this fact and have tried many things to  increase performance. I am hoping it is simply that our current smart phones don't have the power to crunch all the javascript involved when using jQM. I've seen a little bit of Sencha in action (a jQM competitor, and it is even slower IMO). If you have any ideas on how to make this better I'd love to hear it. At this time I don't know of any alternatives, because without jQM, the Apps look really boring!
# uniquename

oh, is it that you just use it for ui, when i was playing with DG there where also some change_page things... what i remember...

well, somehow thats seems to a disadvantage from one level above, choosing phonegap over native app development
# uniquename
- can you recommend some good books about phonegap application?
# signalpoint

The only book I've seen is this one: http://www.amazon.com/jQuery-Mobile-Web-Development-Essentials/dp/1849517266/ref=sr_1_4?ie=UTF8&qid=1369832084&sr=8-4&keywords=jquery+mobile

And to be honest, it really just seems to follow the examples available on their website:

http://docs.phonegap.com/en/2.7.0/index.html
# uniquename

And also I like the idea of DG, because it's also really time to have a framework, that makes it easy to connect a cms to the app world.

**Comment by scotthooker** [comment]
underscore.js has been brilliant for working with views json

**Comment by signalpoint** [comment]
Closing this issue, since we're going to stick with jDrupal for nw.
