### ISSUE TITLE
Drupalgap after load and file transfer issues

### ISSUE THREAD

**Issue by kiss-jozsef** [signalpoint/DrupalGap#456]
Hello,
1.) Is there another hook similar to hook_deviceready() which has already loaded the Drupal.user object?

2.) I am using phonegap upload file(its custom entity so can't use the one in drupalgap) to save files on the server 

```
// Function gets called when pushing a button
function on_upload() {
  navigator.camera.getPicture(onPhotoURISuccess, onFail, {
    quality: 50,
    destinationType: Camera.DestinationType.NATIVE_URI,
    sourceType: Camera.PictureSourceType.PHOTOLIBRARY});
}

function onPhotoURISuccess(filePath) {
  window.resolveLocalFileSystemURI(filePath, function(fileEntry) {
    fileEntry.file(function(fileData) {
      var fileName = fileEntry.name;
      if (fileData.type.indexOf('image') !== -1) {
        filePath = fileEntry.nativeURL;
        fileName = fileEntry.nativeURL.substr(fileEntry.nativeURL.lastIndexOf('/') + 1)
      }
      var options = new FileUploadOptions();
      options.fileKey = 'file';
      options.fileName = fileName;
      options.mimeType = fileData.type;
      var params = {};
      params.description = 'Description field value from the form will come here now its random text';
      params.uid = 1; // hardcoded for testing
      params.request_id = 193; //hardcoded for testing
      options.params = params;
      var file_transfer = new FileTransfer();
      var resource_uri = Drupal.settings.site_path + '/drupalgap/mymodule_drupalgap_resources/save_file.json';
      file_transfer.upload(filePath, encodeURI(resource_uri), fileTransferSuccess, fileTransferError, options, true);
    });
  });
}
```

The problem is whenever i login to drupal in the drupalgap application, the file transfer will get a FILE_NOT_FOUND_ERR error, if i logout from drupal in the application then it works like a charm.

**Comment by signalpoint** [comment]
1. You can use http://api.drupalgap.org/global.html#hook_services_postprocess to do something immediately after the system connect, or you may be able to use http://api.drupalgap.org/global.html#hook_drupalgap_goto_preprocess to do something before the app goes to the front page.
2. Since this is a custom service resource declared in a custom Drupal module, and it appears you are making a custom call to the server (`file_transfer.upload()` who is this?), you'll need to pass along a header in the request with a key of `X-CSRF-Token` with a value that can be retrieved via a GET on `?q=services/session/token`. Check out this page (and sub pages) for more details about custom service calls, because jDrupal will automatically attach this header for you if you run through it: http://www.drupalgap.org/node/187

**Comment by kiss-jozsef** [comment]
1.)  http://api.drupalgap.org/global.html#hook_services_postprocess only works after someone login's for example. hook_deviceready is called then the loading activity appears then the drupalgap application frontpage i would need something that is called when the frontpage is fully loaded and the Drupal.user object is also loaded. ex. in https://github.com/signalpoint/push_notifications/ on deviceready register the new token for your device which gets called after user login , but if application is opened when clicked on notification nothing happens.

2.) i am using phonegap file and file-transfer plugins
the file_transfer.upload() is from var file_transfer = new FileTransfer(); this helps so in my custom resource i can get and save the file .
So in mymodule i can retrieve the uploaded file with file_get_contents($_FILES['file']['tmp_name']), if not using the file upload then in php i can't get the actual file with file_get_contents() or curl.
The issue only appears when i am logged in with a user for anonymous user it works.

**Comment by signalpoint** [comment]
1. If you need to act when the front page is loaded, use a `pageshow` event: http://www.drupalgap.org/node/154
2. Are you passing along the X-CSRF-Token header? You have to do that, or your custom service resource will reject any POST calls to it.

**Comment by kiss-jozsef** [comment]
Thanks, figured it out device ready was okay for me with some page events after that, still having some issues with file uploaded eaven after adding X-CSRF-Token header
options.headers = {'X-CSRF-Token':'value here'};
test with poster in firefox and after adding the token there it started working and reached the custom service. I am using mongo node entities thats why almost everything is called with custom service , the listing services and such are working only this has some issues.

**Comment by signalpoint** [comment]
@kiss-jozsef Please elaborate on any file issues.

**Comment by kiss-jozsef** [comment]
@signalpoint . i get a phonegap filetransfer error FileTransferError.FILE_NOT_FOUND_ERR if i try to use the file transfer upload function with a custom service.

```
function onPhotoURISuccess(filePath) {
  window.resolveLocalFileSystemURI(filePath, function(fileEntry) {
    fileEntry.file(function(fileData) {
      var fileName = fileEntry.name;
      if (fileData.type.indexOf('image') !== -1) {
        filePath = fileEntry.nativeURL;
        fileName = fileEntry.nativeURL.substr(fileEntry.nativeURL.lastIndexOf('/') + 1)
      }
      var headers = {
          "X-CSRF-Token": "1PiJTafCo8JNJyCN8m-3rzU0U7O5-9bsdhGOgGddFT4"
        };
      var options = new FileUploadOptions();
      options.fileKey = 'file';
      options.fileName = fileName;
      options.mimeType = fileData.type;
      options.headers = headers;
      var params = {};
      params.description = 'Description field value from the form will come here now its random text';
      params.uid = 1; // hardcoded for testing
      params.request_id = 193; //hardcoded for testing
      options.params = params;
      var file_transfer = new FileTransfer();
      var resource_uri = Drupal.settings.site_path + '/drupalgap/mymodule_drupalgap_resources/save_file.json';
      file_transfer.upload(filePath, encodeURI(resource_uri), fileTransferSuccess, fileTransferError, options, true);
    });
  });
```

if i change the resource_uri to for example :   var resource_uri = Drupal.settings.site_path + '/upload.php'; then it works.

FileTransferError.FILE_NOT_FOUND_ERR gets triggered eaven before it reaches the php side so no idea whats the issue.
Firefox Poster -> without the 'X-CSRF-Token' it gives CSRF validation failed , with it it returns what is in the function correctly.
Could you give me some advice how to debug effectivly because i have no idea and adb logcat is a mess.
Thanks again

**Comment by signalpoint** [comment]
@kiss-jozsef I'd recommend following the example here: http://plugins.cordova.io/#/package/org.apache.cordova.camera

To be honest this seems more like an issue with PhoneGap vs. Services module, than DrupalGap, since in no way is DrupalGap or jDrupal being utilized here, it's all custom JS trying to communicate with a custom Entity type, sorry.

**Comment by kiss-jozsef** [comment]
@signalpoint found the issue will post it so if someone else has the same issue no more searching for non existing errors.

change:

```
var resource_uri = Drupal.settings.site_path + '/drupalgap/mymodule_drupalgap_resources/save_file.json';
```

to:

```
var resource_uri = Drupal.settings.site_path + '/?q=drupalgap/mymodule_drupalgap_resources/save_file.json';
```

or there are some settings for apache with Overrwrite All, then I think it Pathauto will work when drupal site is accesed with ip.

Thanks for your assistance.

**Comment by signalpoint** [comment]
@khayong Excellent, thank you for the follow up.
