### ISSUE TITLE
CPU utilization 100%

### ISSUE THREAD

**Issue by davidyoung8906** [signalpoint/DrupalGap#47]
I repost the bug from https://drupal.org/node/1208216 because I haven't find appropriate solution:

I installed the module and followed the instructions on how to set the settings. I made "update interval" = 1 sec (who would want to wait longer to see a message?). After I navigate to the chat node I see CPU on the server going to 100%, and the access log shows a lot of messages ""POST /chatroomread.php HTTP/1.1" 404 57022". The server becomes unresponsive (CPU 100%), and the chat messages update on the screen is SEVERAL MINUTES!!

**Comment by signalpoint** [comment]
I'm sorry, I don't understand the problem here. The issue mentioned here is for the chat room module:

https://drupal.org/project/chatroom

Please specify what, if any issue you are experiencing with DrupalGap, thanks.

**Comment by signalpoint** [comment]
N/A
