### ISSUE TITLE
Webapp mode - Close popup menu - crashes app

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#471]
When i am going to close a popup menu it killing my app and dropping it back to the initialization screen but not initializing.  It isn't throwing any errors.  I am not sure if this is just a webapp thing?  It is also not every time.  Once in a blue moon it works fine.  

Close button Code:
`<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn ui-icon-delete ui-btn-icon-left ui-first-child">Close</a>`

Not sure if this is a known issue.  Just wanted to check to see if you have seen it.

**Comment by signalpoint** [comment]
Related issue: #459

**Comment by signalpoint** [comment]
Fixed.
