### ISSUE TITLE
upload image from app by using Drupalgap

### ISSUE THREAD

**Issue by teripak** [signalpoint/DrupalGap#473]
Hi,

I am trying to find ways to upload images in Drupalgap way but I couldn't find it.
I read an article here ( http://drupal.stackexchange.com/questions/103020/saving-file-to-drupal-site-using-drupalgap ) and there is your comment like below.

```
FYI, the latest version of DrupalGap now supports image fields, so you shouldn't have to write any custom code.  - answered May 22 '14 at 18:16  tyler.frankenstein
```

I am searching for any document on this but could not find it.

Is there a easy way to retrieve photos in the device's photo library and save it as a image filed of node in Drupal site?

Thank you.

**Comment by signalpoint** [comment]
@teripak This is currently possible in when you're in `phonegap` mode, but not yet possible when you're in `web-app` mode. For PhoneGap, make sure you installed the camera plugin using the Cordova CLI, because this feature only works when you've compiled to your device (and maybe through an official emulator, doesn't work through Ripple). As for web-apps, see this issue: #455 

Here's an example of the Image Field working properly: http://tylerfrankenstein.com/code/build-mobile-app-geo-tag-photo

**Comment by teripak** [comment]
It has been several days passed for our Lunar New Year's holiday here in Korea. Happy Lunar New Year Signalpoint and Drupalgap.

I have some issues regarding node. So I listed them all here and ??? mark is my question.
1. I am running drupalgap on apache+php+mysql on windows server.
2. I made a node (Article content type) with title, body and image. I is confused with below test scenario.
   1-1. create a node from web. as a default, file directory is field/image
   1-2. in the App, as you know, the default setting for file is as below.
       Drupal.settings.file_public_path = 'sites/default/files';
   1-3. In the App, goto menu > content > there is a node list. select a node which is created above.
       I can see content of the node. (title, body and image) then I click [edit] button, there is no Body field and no Image. ==> ???
   I realized through test for hours that if I change the file directory to blank (which mean it would be sites/default/files) then the image is displayed in Edit mode.
   I create another node from the App, in this case, there is no problem for image field.
   So I think below two path should be the same. Am I right ==> ???
   Drupal.settings.file_public_path = 'sites/default/files';
   file directory is '' (blank)
   1-4  There is no body field in Edit mode. I don't know why ==> ???
3. I add new field in Article content type to test entity reference.
   2-1. add a new field (test_tid) as a entity reference type above Body field.
   2-2. Target type: node
         Entity selection: Views: filter by entity reference view
     View used to select the entities: I selected one display name of views (I followed http://drupalgap.org/node/240 to create views)
    And [Save]
   2-3. Make it visible in the manage display setting for Drupalgap.
   2-4. I create an Article node from Web. no problem for far.
   2-5. in the App, goto the new node for view mode and I can see value of the value of entity reference field. 
   2-6. And suddenly, the body field is visible in Edit mode with no value. All article node has now Body field visible in Edit mode.  But there is no value in the Body field in Edit mode.  ==> ??? strange...
   2-7. And there is only Label for the entity reference field in Edit mode. no select box to select. ==> ??? I don't know what is wrong... Do I have to use autocomplete widget? but it is still not work.

Could you answer me above questions? sorry for the long inquiry.

**Comment by teripak** [comment]
I found a reason. I am running this site as a multi lingual site. When I save a node from Web, the language is English by default. in this case, the body and image field in Edit mode in the app is not shown. when I update the node as a language field to "Language neutral", everything is ok (except entity reference field).
In addition to, when I create a node from app, the node is created as a "Language neutral" by default.

Do you have a guidance to run a site as a multi lingual? 
I will post more here when I have something.

**Comment by teripak** [comment]
In the case of entity reference, I followed http://drupalgap.org/node/240 and I got below message when I put a letter in the entity reference field in Edit mode. (this field has a autocomplete widget)

```
           file:///android_asset/www/bin/drupalgap.min.js: Line 145 : _theme_autocomplete - TypeError: Cannot read property 'filter' of undefined
```

Fyi, I got json data successfully by using below URL
/drupalgap/my_articles_autocomplete/entityreference_1?title=f

![drupalgap_leo_03](https://cloud.githubusercontent.com/assets/3594627/6324041/13324d2c-bb77-11e4-815b-d805d1782694.jpg)
![drupalgap_leo_02](https://cloud.githubusercontent.com/assets/3594627/6324042/15b6156a-bb77-11e4-8639-e11d566a792b.jpg)

**Comment by signalpoint** [comment]
@teripak There is not much multilingual support at this time, it is hit and miss depending on your site, and the settings. I personally haven't had to do a multilingual site yet (nor for a client), so without contributions, it'll be a while before this feature works as expected.

For the autocomplete, did you follow the special instructions listed on www.drupal.org/project/drupalgap ? Also, update to the latest dev snapshot of the bin/drupalgap.js file. Once you do those things, adjust your field settings to "Basic" entity selection mode (aka you don't need a View for it).

In the future, please split these up into multiple issues, it is difficult to track when there are multiple issues listed within one issue, thanks!

**Comment by teripak** [comment]
I got it . I will post new issue for entity reference.  Please make it close for my multilingual issue. 
Thank you.
