### ISSUE TITLE
Option cancel exit of the app not work

### ISSUE THREAD

**Issue by geYdes** [signalpoint/DrupalGap#474]
Hi,

The 'OK' and 'Cancel' buttons perform the same function: exit the app.

Any solution?

Thanks!

**Comment by signalpoint** [comment]
@geYdes In what mode?

**Comment by signalpoint** [comment]
@geYdes Look at http://api.drupalgap.org/global.html#_drupalgap_back_exit at try to find a solution please by modifying the src/ code. First make a fork of DrupalGap if you haven't, thanks.

**Comment by geYdes** [comment]
@signalpoint I decided to upgrade to the latest stable version (7.x-1.0-rc5) and I found a new problem: the application doesn't start in phonegap mode (yes in web-app).

When you open the app on the mobile device it doesn't load.

I proceeded to uninstall the app in device, empty cache, etc.

What could be happening?

Thanks.

**Comment by geYdes** [comment]
In the 7.x-1.0-rc4 version work fine comment 3!

**Comment by signalpoint** [comment]
@geYdes If you found a new problem, please open a separate issue.

**Comment by geYdes** [comment]
@signalpoint It works fine!

Thanks!
