### ISSUE TITLE
App doesn't load with 7.x-1.0-rc5 version

### ISSUE THREAD

**Issue by geYdes** [signalpoint/DrupalGap#477]
@signalpoint I have updated to the latest stable version (7.x-1.0-rc5) and I found a new problem: the application doesn't start in phonegap mode (yes in web-app).

When you open the app on the mobile device it doesn't load.

I proceeded to uninstall the app in device, empty cache, etc.

What could be happening?

Thanks.

**Comment by signalpoint** [comment]
@geYdes Did you switch the mode to phonegap in settings.js?

Are you including the cordova.js file mentioned in cordova.index.html inside of your index.html file?

**Comment by geYdes** [comment]
@signalpoint The first that you indicate I had done already.

Now I've done what you indicate in second place and it works properly.

Thanks!
