### ISSUE TITLE
Clicking a link going to the current page

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#48]
If I click a link that links to the page im currently on I get a drupal_goto TYPERROR undefined.

Not sure why as if I'm not on the page it works ok. 

This is being called presumably from hook_menu as thats the link im clicking on, a link from my menu block.

**Comment by scotthooker** [comment]
// If the page is already in the DOM, remove it.
    if (page_in_dom) {
      // TODO - this is causing problems when you try to goto the same page
      // you are already on. E.g. node/%, then posting a comment, brings you
      // back to node/%, but since we remove the page from the dom here, then
      // try to add it again below, a jQM trigger event fails.
      $('#' + page_id).empty().remove();
      // This doesn't work.
      //$.mobile.changePage('index.html#' + page_id, {reloadPage:true});
    }

this is what breaks it.

**Comment by scotthooker** [comment]
Furthermore, if you go back to the page after visiting another the dom seems to duplicate the content? I end up with 2 pages.

What would be the easiest way for the pages to be reloaded every time you visit them? Rather than the current behaviour. I think that the drupal_goto should just return if the link is the current page.

**Comment by signalpoint** [comment]
Thanks for the hint @scotthooker, I've adjusted drupalgap_goto to just return if the link path is to the current page.

**Comment by signalpoint** [comment]
@scotthooker - Sorry, I just noticed you also mentioned that there are two instances of the same page on the DOM. I am curious how you were able to debug and see that?

Is that still an issue with this latest commit? If so, please let me know how that can be debugged, and I'll see to getting a patch ASAP. That sounds like a bad bug.

**Comment by scotthooker** [comment]
The latest commit is perfect in that if I click an existing link I don't get an undefined error.

However, as I navigate through my app pages in the following scenario.

I'm on index.html with a to a page defined in my hook_menu 
Click link to page 2 
When I'm on page 2 if I inspect index.html in my safari debugger I still see the original first page and its content albeit it not being visible. 

I.e. we don't remove it. 

This may have performance gains in that we only have to load the content and its already loaded if we navigate back to the page. Which is fine for static content. But there seems to be an issue if we navigate back to the page and are trying to load ajax content into it i.e. a view. 

Does that make sense? I'm not always the best at articulating issues. I'm pretty sure this is generic and not just in my scenario as I am not doing anything special and have tested it in a couple of different ways.

**Comment by scotthooker** [comment]
In terms of debugging I run the app in xcode and then open safari and in the developer tool bar I can inspect the iphone simulator and see the full page rendered html. 

My suggestion would be to .remove() any page that isn't the page you are going to. Or have some sort of hook where this could be done.

**Comment by scotthooker** [comment]
I see its trying to be done here...

```
var pages = $("body div[data-role$='page']");
var page_in_dom = false;
if (pages && pages.length > 0) {
  $.each(pages, function(index, page) {
    if (($(page).attr('id')) == page_id) {
      page_in_dom = true;
      return false;
    }
  });
}

// If the page is already in the DOM, remove it.
if (page_in_dom) {
  $('#' + page_id).empty().remove();
}
```

But I can't see that that works.

**Comment by scotthooker** [comment]
Ah I see. To clarify there isn't 2 instances of the same page. It's when I click onto another page the pages im coming from doesn't get removed. Thus I get some weird goings on when I navigate back to the page as all the jquery dynamic content building doesn't happen 2nd time round. Which will be an issue for people using views_datasource.

**Comment by signalpoint** [comment]
Now I remember why there was a need to re-load the current page. For example, when a comment is posted on a node, the node page needs to be reloaded. This new patch stops that reload from happening. So we need someway for drupalgap_goto() to let form submissions proceed with page reloads.

**Comment by signalpoint** [comment]
When clicking on a link to the page you are already on, drupalgap_goto() now prevents any page removal from the DOM, and prevents any $.mobile.changePage from happening. This means that when you click on a link to the page you are already on, it doesn't do anything, it just stays on the page. The exception is when a form submission is occuring, which now proceed with page reloads by using allowSamePageTransition in drupalgap_goto_generate_page_and_go().
