### ISSUE TITLE
Views exposed sort criteria

### ISSUE THREAD

**Issue by terotik** [signalpoint/DrupalGap#486]
Would be great to have the option to show views sorting criteria along the lines of exposed filters functionality. Are there plans to add this feature, or are there workarounds for the time being?

**Comment by signalpoint** [comment]
@terotic I don't have any plans to implement this anytime soon. Often times, features are implemented once a client requests them, or someone contributes to its resolution.

This sounds like a great feature though, and would be a great addition.

For the time being, you can build a Page Display for your View on your Drupal site, and take a look at the page and use the sorting feature. You'll then notice in your URL various query string parameters (? & etc) which show how to use the sort via URL. You could then use those URLs in your app to construct the feature.

**Comment by terotik** [comment]
@signalpoint Belated thanks for the reply. I will look into building the feature through views url parameters!

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
