### ISSUE TITLE
Ajax async issue

### ISSUE THREAD

**Issue by teripak** [signalpoint/DrupalGap#487]
I made a code to display user picture list as below. The problem is below ajax is not working as an async=false mode.
It is OK in Ripple, but not work in app.

```
offlineTeachersDIv = '<div class="offline-teachers">';
offlineTeachersDIv +=   '   <div class="mobile-h1">Offline teachers</div>';

ack = $.ajax(  
    {
        url: '/offline-teachers-m',
        type: "POST",
        data: ({}),
        async: false,
        dataType: "json",
            success  : function(data, status) {
            //console.log(data.nodes);
            offlineTeachersDIv += '<table><tr>';
            $.each(data.nodes, function() {
                $.each(this, function(k, v) {
                    image = {
                        path: drupalgap_image_path(v.user_picture_uri)
                    };
                    image_html = theme('image', image);
                    offlineTeachersDIv += '<td><div style="width:100px;">'+image_html+'</div></td>';
                });

            });
            offlineTeachersDIv += '</tr></table>';
        }
    }).responseText;

offlineTeachersDIv += '</div>';
console.log(offlineTeachersDIv);
```

In Ripple, I have to change one line (adding 'http://') as below then user pictures are displayed.
               path: 'http://'+drupalgap_image_path(v.user_picture_uri)

in App, there is no [table] tag in offlineTeachersDIv  variable when I check with console.log(offlineTeachersDIv);.
It seems that it is not working as a sync mode even I forced with "async: false,".

Could you find something wrong?

**Comment by teripak** [comment]
I found something. 
In Ripple, there was no error. Which means the ajax goes success function.
But in the app, the same code goes error function ( I add error function() to test and I realize that it went to error function).
I don't know why it is different and what is wrong so far.
Fyi,  the URL  "/offline-teachers-m"  returns json data successfully of cause.

**Comment by teripak** [comment]
Oh my.. There should have been added "Drupal.settings.site_path" in URL path.
Sorry. please just think someone was playing alone.

**Comment by signalpoint** [comment]
@teripak I'd recommend using jDrupal's (a dependency for DrupalGap) to build your Service calls. For example, I'm fairly certain you are missing the X-CSRF-Token header in your request. If you use jDrupal, that is taken care of automatically. See this page for more details: http://drupalgap.org/node/179

Now that you've added the site_path to your request, is it working properly?

**Comment by teripak** [comment]
Yes, it is working properly.
