### ISSUE TITLE
Custom service resource with args not working

### ISSUE THREAD

**Issue by days4** [signalpoint/DrupalGap#488]
when i am passing arguments it either display a parser error or  Unexpected end of input in the log
i am following drupalgap's tutorial for custom resource with args.
and also please anyone can tell me how to write drupalgap module for a custom service

**Comment by signalpoint** [comment]
@days4 That usually means your PHP code is returning an invalid JSON object, or there is a problem with your PHP code. Try just returning TRUE at first to verify your service is working properly, then try returning the argument to make sure it is being passed properly. Then step through with watchdog to verify each step of the way is working.

**Comment by days4** [comment]
@signalpoint  thanks for your quick response .i figured out the problem and now its working fine

**Comment by days4** [comment]
And all required resources are enabled on drupalsite
drupalgap function to access join and leave services is
------------------------------------------join--------------------------------------------------------------------------------
function og_user_groups_join(gid,options) {
  try {
    options.method = 'POST';
	options.path = 'og/' + gid + '/join.json';
	options.service = 'og';
	options.resource = 'join';
	console.log('join');
	console.log(options);
    Drupal.services.call(options);
  }
  catch (error) { console.log('og_user_groups join - ' + error); }
  }
--------------------------------------------leave--------------------------------------------------------
  function og_user_groups_leave(gid,options) {
  try {
    options.method = 'POST';
	options.path = 'og/' + gid + '/leave.json';
	options.service = 'og';
	options.resource = 'leave';
	console.log('leave');
	console.log(options);
    Drupal.services.call(options);
  }
  catch (error) { console.log('og_user_groups leave- ' + error); }
  }
calling functions are ---
for join og----

var join_args={
gid:187,
uid:312

};
og_user_groups_join(187,{
    
    data:JSON.stringify(join_args),
    success: function(result) {
	console.log(result[0]); 
	    }
});
to leave og ----------
var leave_args={
gid:187,
uid:312
};
og_user_groups_leave(187,{
    
    data:JSON.stringify(leave_args),
    success: function(result) {
	 
	console.log(result);
    }
});

**Comment by days4** [comment]
URL's Showing in log are-
--------------------------------------------------------leave-----------------------------------------------------------
 POST http://www.indiapredicts.com/?q=drupalgap/og/187/leave.json 404 (Not found : Could not find the controller.)
POST "http://www.indiapredicts.com/?q=drupalgap/og/187/leave.json".
-------------------------------------------------JOIN-----------------------------------------------------------------------
POST http://www.indiapredicts.com/?q=drupalgap/og/187/join.json 404 (Not found : Could not find the controller.)
POST "http://www.indiapredicts.com/?q=drupalgap/og/187/join.json".
