### ISSUE TITLE
DrupalGap OG unable to call join/leave services

### ISSUE THREAD

**Issue by days4** [signalpoint/DrupalGap#490]
i am working on an app which requires  og services 
when i try to use og_serrvices to retrive usergroups(subscribed by user) its working fine
but when i try to og_services join/leave it shows 404 (Not found : Could not find the controller.)
Url is POST http://www.indiapredicts.com/?q=drupalgap/og/187/join.json
And all required resources are enabled on drupalsite
drupalgap function to access join and leave services is

```
------------------------------------------join--------------------------------------------------------------------------------
function og_user_groups_join(gid,options) {
try {
options.method = 'POST';
options.path = 'og/' + gid + '/join.json';
options.service = 'og';
options.resource = 'join';
console.log('join');
console.log(options);
Drupal.services.call(options);
}
catch (error) { console.log('og_user_groups join - ' + error); }
}
```

--------------------------------------------leave--------------------------------------------------------

```
function og_user_groups_leave(gid,options) {
try {
options.method = 'POST';
options.path = 'og/' + gid + '/leave.json';
options.service = 'og';
options.resource = 'leave';
console.log('leave');
console.log(options);
Drupal.services.call(options);
}
catch (error) { console.log('og_user_groups leave- ' + error); }
}
```

calling functions are ---
for join og----

```
var join_args={
gid:187,
uid:312

};
og_user_groups_join(187,{

data:JSON.stringify(join_args),
success: function(result) {
console.log(result[0]); 
    }
});
```

to leave og ----------

```
var leave_args={
gid:187,
uid:312
};
og_user_groups_leave(187,{

data:JSON.stringify(leave_args),
success: function(result) {

console.log(result);
}
});
```

URL's Showing in log are-
--------------------------------------------------------leave-----------------------------------------------------------
POST http://www.indiapredicts.com/?q=drupalgap/og/187/leave.json 404 (Not found : Could not find the controller.)
POST "http://www.indiapredicts.com/?q=drupalgap/og/187/leave.json".
-------------------------------------------------JOIN-----------------------------------------------------------------------
POST http://www.indiapredicts.com/?q=drupalgap/og/187/join.json 404 (Not found : Could not find the controller.)
POST "http://www.indiapredicts.com/?q=drupalgap/og/187/join.json".

**Comment by signalpoint** [comment]
@days4 Please post this issue with the OG Services module instead.
