### ISSUE TITLE
How to retrieve current user's id in drupalgap 

### ISSUE THREAD

**Issue by days4** [signalpoint/DrupalGap#492]
Drupal.user.uid in my custom module returns 0, but if i place same code (Drupal.user.uid) in drupalgap.min to to check it returns required id

**Comment by signalpoint** [comment]
@days4 Where/when in your custom module are you trying to access the uid?

**Comment by days4** [comment]
I resolved it and Drupal.user.uid is returning right value ..Actually I was calling my function at wrong place .

But I need help on processing json object

I have response object but when I try to retrieve data using code

og_user_groups(32,
   {
    success: function(result) {
 int i;

 for(i=0;i<result.Object.length;i++)
 {

 console.log(result.Object[i].id);

```
}
```

 }

});

or 

og_user_groups(32,
   {
    success: function(result) {
 int i;

 for(i=0;i<result.length;i++)
 {

 console.log(result[i].id);

```
}
```

 }

});

it shows -  

-parsererror

-Unexpected identifier

Sent from Windows Mail

From: Tyler Frankenstein
Sent: ‎Monday‎, ‎02‎ ‎March‎ ‎2015 ‎17‎:‎20
To: signalpoint/DrupalGap
Cc: Anupam Awasthi

@days4 Where/when in your custom module are you trying to access the uid?

**Comment by days4** [comment]
I resolved it and Drupal.user.uid is returning right value ..Actually I was calling my function at wrong place .

But I need help on processing json object
I have response object but when I try to retrieve data using code
og_user_groups(32,
   {
    success: function(result) {
 int i;

 for(i=0;i<result.Object.length;i++)
 {

 console.log(result.Object[i].id);

```
}
```

 }

});

or 
og_user_groups(32,
   {
    success: function(result) {
 int i;

 for(i=0;i<result.length;i++)
 {

 console.log(result[i].id);

```
}
```

 }

});
it shows -  
-parsererror
-Unexpected identifier

**Comment by signalpoint** [comment]
@days4 Use github markdown on your code for assistance.

**Comment by signalpoint** [comment]
@days4 "-parsererror -Unexpected identifier" means you have a syntax error in your code.
