### ISSUE TITLE
How to get comments and comment form using hook_page_view_alter

### ISSUE THREAD

**Issue by clivesj** [signalpoint/DrupalGap#493]
When using [hook_node_page_view_alter_TYPE()](http://www.drupalgap.org/node/520) besides accessing the original node I also need the comments and comment_form.

Could you point me to a resource showing how this can be done. I think I have to load the comments and comments_form myself?

**Comment by signalpoint** [comment]
@clivesj Yes, you'll have to load the comments and the comment form yourself if you're using that hook. The best example is right in DrupalGap core inside the node_page_view_pageshow() function: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/node/node.js#L246

**Comment by clivesj** [comment]
Thanks Tyler,
I have posted a comment on the doc page. I managed to display the comment form but not the comments its self. I must be missing something obvious. Could you have a look when you have time. The post is intended to help others. I will update the code as as solved. Thank you

**Comment by signalpoint** [comment]
@clivesj You have to dynamically inject the comments from within the comment_index() success handler, not after the call to it (since it is an async call).

**Comment by clivesj** [comment]
Hi Tyler. I didn't succeed in retrieving the comments asynchronously. The new solution posted in the docs works now but looks a bit dirty. I am currently updating my JS skills and will come back to this later.
