### ISSUE TITLE
Remove previous page from DOM when drupalgap_goto() navigates to next

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#50]
When navigating around via drupalgap_goto, the previous page is left in the DOM. Once you navigate back to that previous page, it generates a new div for it in the DOM (so there are two identical divs) and the latter doesn't get its content set properly (because the first probably catches the content).

**Comment by scotthooker** [comment]
I actually think its an ordering issue. 

There isn't two identical divs once the page is loaded. There is some code in common.js that removes the identical div. However, this happens after the new page has run so your right the first div catches the content but then gets removed and replaced by the 2nd div.

I _think_ that is whats happening. If you point me in the direct of the page load code I'll attempt to right a patch. As I think this is the only major bug I've come across so far.

**Comment by scotthooker** [comment]
You may be able to fix this better than I can.

I've worked my way back through the code and tried putting tap in theme.js.inc

$(document).bind("pagebeforechange", function(e, data) {
  try {
    if (drupalgap.settings.debug) {
      console.log('pagebeforechange()');
    }
    if (typeof data.toPage === "string") {
      alert((data.toPage));
      var pages = $("body div[data-role$='page']");
      $.each(pages, function(index, page) {
        var page_id = $(page).attr('id');
        if (data.toPage == '#' + page_id) {
          alert('equal');
        } else {
          alert('not equal' + page_id);
          $('#' + page_id).remove();
        }

```
  });

  template_preprocess_page(drupalgap.page.variables);
  template_process_page(drupalgap.page.variables);
}
if (drupalgap.settings.debug) {
  // TODO - Is this log message getting hit twice on one page change?
  // If so, that's no bueno!
  console.log('pagebeforechange() - processed page');
}
```

  }
  catch (error) {
    alert('pagebeforechange - ' + error);
  }
});

Like so. Just to remove any old pages. However as soon as I try that I get a drupalgap undefined error and the whole thing goes bang.

**Comment by scotthooker** [comment]
Is there a way to put breakpoints and step through in phonegap? Trying to work back to see wheres the best place to remove the old page. Everywhere I try I get errors.

**Comment by signalpoint** [comment]
I believe that Ripple allows you to run PhoneGap App's in Chrome. That should then allow breakpoints in javascript by using Chrome's Inspector.

I haven't been able to successfully install Ripple (only tried once in Ubuntu).

You probably can use breakpoints in Safari to inspect the simulator, or no?

P.S. I shall get back to you soon on the code mentioned above.

**Comment by signalpoint** [comment]
@scotthooker - Will you please clarify what you mean here in this comment? 

https://github.com/signalpoint/DrupalGap/issues/50#issuecomment-19012587

**Comment by scotthooker** [comment]
Hi!

I gave up last night in the end. To clarify the comment.

What I was attempting to do is work my way back through the code to find an appropriate place to do $(#page_id).remove(); wrapped in an if statement that checks to make sure its removing the page you are coming from only if that page isn't the current page.

However, each time I do. Where ever I say .remove() on the page drupalgap_goto falls in to an error saying object is undefined.

**Comment by signalpoint** [comment]
With the commit mentioned above, drupalgap_goto() has been cleaned up (blocks of code moved to individual functions). It has been changed to not go anywhere if we are going to the path we are already on. The only exception is if we're doing a form submission we'll let the page rebuild becayse sometimes the page needs to be rebuilt (e.g. adding a comment to a node from a node view, goes back to the node view after submission) only remove the page is already.

I learned last night that $.mobile.changePage() needs at least one data-role="page" div element in the body to operate correctly (except on app startup, I think). So if we're trying to .remove() and then later a changePage(), that isn't going to work.

Using 'allowSamePageTransition' on the changePage works for form's submissions that then go back to the same page.

So at this point I'm not sure how to best handle removal of old pages, or if it is necessary. Perhaps drupalgap_goto() could be changed to just go back to the div already in the DOM during a page change, if the page is in the div, that seems like it could be a performance benefit. Some kind of garbage clean up would be necessary to make sure the DOM doesn't get too huge.

**Comment by scotthooker** [comment]
I think that will be perfect. The old pages won't get built up but that does all depend on how many pages you navigate off to. The pages get rebuild fine now so you don't end up with duplicates. 

I think other than nice performance related tweaks that cleans up all the issues.

**Comment by signalpoint** [comment]
We can't remove the page from the DOM when navigating to the next because jQM needs two pages in the DOM at the time $.mobile.changePage is called.

As each page is visited, it is added to the DOM, pages are removed the next time they are navigated to, so they can be rebuilt. If we navigate to the same page we're on, nothing happens, the app just stays where it is. If we navigate to the same page during a form submission, then the page is not removed from the DOM, and instead we use a allowSamePageTransition on the changePage call so the page can be revisited.

On the roadmap for DrupalGap is a comprehensive look at the way jQM pages are handled and to employ better caching and transitions.

I am going to close this issue since I think it will be best to leave the implementation where it is at for now. This means, that pages already visited will stay in the DOM, until the next time they are visited, at that time they will be removed and rebuilt.

As always, re-open if necessary.
