### ISSUE TITLE
og group subscribe unsubscribe button not showing

### ISSUE THREAD

**Issue by days4** [signalpoint/DrupalGap#501]
> hi i am developing an drupalgap app using drupalgap og module but subscribe and unsubscribe button is not displaying .(Group field displays undefined)
> its a radio field and display type selected for drupalgap is og_group_subscribe link
> my requirement is if a person is not subscribed to a group then it display subscribe button and if he had already subscribed  then it show unsubscribe button
> code that i tried is shown below
> 
> ```
> var user_id=0;
>      var entity_id=0;
>             var subscribe=0;
>                  var re;
>                      var res;
> ```
> 
> ```
> function og_ui_field_formatter_view(entity_type, entity, field, instance, langcode, items, display)
>  {
> user_id=Drupal.user.uid;
> entity_id=entity.vid;
> ```
> 
> _Retrieve all groups subscribed by user_

```
og_user_groups(user_id,{success:function(result)
{
      re=result.length;
```

_for all groups subscribed by user check current group is subscribed or not if subscribe set subscribe=1_

```
for(var i=0;i<re;i++){
if(entity_id==result[i].gid)
{
subscribe=1;
}
}
```

_if subscribed set unsubscribe button_

```
 if(subscribe)
{
 var element = {};
    $.each(items, function(delta, item) {
         element[delta] = {
          markup: theme(
            'button',
            { text: 'Unsubscribe'}
          )
        };
    });
    return element; 
 }
```

_otherwise set subscribe button_

```
else
{
var element = {};
    $.each(it, function(delta, item) {
          element[delta] = {
          markup: theme(
            'button',
            { text: 'Subscribe' }
          )
        };
    });
    return element; 

}

}});
   }
```

**Comment by signalpoint** [comment]
@days4 Please edit your post to include GitHub Markdown, that way I can easily read the code, thanks!

**Comment by days4** [comment]
> values of entity_type, entity, field, instance, langcode, items, display are 
> 
> ```
> entity_type=node
> ```
> 
> ```
> value of entity
> Object {vid: "5", uid: "1", title: "MY GROUP", log: "", status: "1"…}body: Objectchanged: "1425709085"cid: "0"comment: "1"comment_count: "0"content: "undefined<div class="body"><div><h3>Body</h3></div><p>vuhvuvuhhvyuvuyyyyyyyyyyyy</p>↵</div>"created: "1425709085"data: "b:0;"field_subscribe: Array[0]group_group: Objectgroup_register: Array[0]language: "und"last_comment_name: nulllast_comment_timestamp: "1425709085"last_comment_uid: "1"log: ""name: "Anupam"nid: "5"path: "http://localhost/drupal/node/5"picture: "0"promote: "1"rdf_mapping: Objectrevision_timestamp: "1425709085"revision_uid: "1"status: "1"sticky: "0"title: "MY GROUP"tnid: "0"translate: "0"type: "my_group"uid: "1"vid: "5"
> ```

**Comment by days4** [comment]
> this is my(**working**) fix for adding functionality for og_subscribe link in drupalgap og module 
> 
> ```
> function og_user_groups_join(options) {
>   try {
>       options.method = 'POST';
>     options.path = 'og/join.json';
>      options.service = 'join';
>     options.resource = 'og';
>     console.log('join');
>     Drupal.services.call(options);
>   }
>   catch (error) { console.log('og_user_groups_join - ' + error); }
>   }
>  function og_ui_field_formatter_view(entity_type, entity, field, instance, langcode, items, display) 
>   {
>   dpm(entity);
>      try {
>     var element = {};
>     var user_id=Drupal.user.uid;
>         var entity_id=entity.vid;
> // args for join
>     $.each(items, function(delta, item) {
>     var join_leave={uid:user_id,gid:entity_id};
>       var joinargs={
>                            data:JSON.stringify(join_leave),
>                       success:function(result){
>                       console.log(result);
>                       if(result.id)
>                       {
>                       alert('You Succesfully Subscribed this Group');}
>                       else if(result=='Already Subscribed'){
>                       alert(result);
>                       }
>                   }
>          };
>         var title = item.title ? item.title : item.url
>         console.log('title is::::'+title);
>         element[delta] = {
>           markup: theme(
>             'button',
>             { text: 'Subscribe', attributes:{onclick:og_user_groups_join(joinargs)}}
>           )
>         };
>     });
>     return element;
>   }
>   catch (error) { console.log('og_ui_field_formatter_view - ' + error); }
> }
> ```
> 
> **curresponding change in join function of og_services module is**
> 
> ```
> function _og_services_resource_user_join($gid, $uid) {  
>   $existing = og_get_group_membership($gid, 'user', $uid);
>     if ($existing) {
>      $label = og_label($gid);
>       return t('Already Subscribed');
>  }
>  $membership = og_membership_create('node',$gid,'user', $uid,'og_user_node',time(),1,'en');
>   if ($membership) {
>   entity_save('og_membership', $membership);
>    //$membership=entity_save('og_membership', og_membership_create('node',$gid,'user', $uid,'og_user_node',time(),1,'en'));
>     return $membership;
>     }
>  return services_error(t('Error creating membership for user with UID @uid for group ID @gid.', array('@uid' => $uid, '@gid' => $gid)), 404);
> }
> ```

**Comment by signalpoint** [comment]
@days4 Please make a fork of the OG module for DrupalGap on GitHub. Then you can add your code to your fork, commit it, push it, then submit a pull request to have your code merged into the main code repository. That is the most streamline way to do it, and then your account will be credited with the contribution.

**Comment by signalpoint** [comment]
Closing in favor of this issue: https://github.com/signalpoint/og/issues/2
