### ISSUE TITLE
Custom user fields are not shown in edit mode.

### ISSUE THREAD

**Issue by teripak** [signalpoint/DrupalGap#503]
Hi 
When I navigate path: 'user', I can see some fields in user profile.
When I press [edit] link,  It shows edit form like below.
"Lastname" field is shown. but there are some more custom fields in user profile.
How can I make other fields are included in this edit form?
![drupalgap_leo_user_profile](https://cloud.githubusercontent.com/assets/3594627/6661948/372ccd74-cbf8-11e4-97e9-a0b6089d50db.jpg)

below is how user profile set.

![drupalgap_leo_user_profile2](https://cloud.githubusercontent.com/assets/3594627/6661965/a4edd3bc-cbf8-11e4-8700-586829d3c7a1.jpg)

**Comment by signalpoint** [comment]
@teripak What type(s) of fields are they? You need to install (or implement) the corresponding contributed modules for DrupalGap for any contributed modules you'ave installed on your Drupal site.

**Comment by teripak** [comment]
Lastname, Firstname, Nickname are the same type as below.
But I don't know why only lastname is shown.

![drupalgap_userprofile_04](https://cloud.githubusercontent.com/assets/3594627/6667080/152fb1d4-cc2d-11e4-820d-a07df321a852.JPG)

**Comment by signalpoint** [comment]
@teripak That is very strange, they should all show up (the text field was one of the first fields supported). I'd recommending implementing `hook_form_alter()`, in a custom DrupalGap module, then inspecting it's elements with this line of code:

```
console.log(form.elements);
```

What does that reveal in the JavaScript console?

**Comment by teripak** [comment]
console.log(form.elements) shows as below.

WARNING: drupalgap_entity_render_field - i18n_field_field_formatter_view() does not exist! (field_gender)
drupalgap.min.js:192 
WARNING: drupalgap_entity_render_field - i18n_field_field_formatter_view() does not exist! (field_available_languages)
drupalgap.min.js:192
WARNING: drupalgap_entity_render_field - i18n_field_field_formatter_view() does not exist! (field_nationality)
drupalgap.min.js:192
WARNING: drupalgap_entity_render_field - location_cck_field_formatter_view() does not exist! (field_location)
drupalgap.min.js:213 drupalgap_field_info_instances_add_to_form - TypeError: Cannot read property '0' of undefined
VM25392:607 

####################################
Object {
    uid: Object, 
    name: Object, 
    mail: Object, 
    picture: Object, 
    og_user_node: Object…}
    current_pass: Object
    field_lastname: Object
    mail: Object
    name: Object
    og_user_node: Object
    pass_pass1: Object
    pass_pass2: Object
    picture: Object
    children: Array[0]default_value: Object
    id: "edit-user-profile-form-picture"
    is_field: false
    name: "picture"
    options: Object
    required: false
    title: "Picture"type: "hidden"
    value: "Add Picture"
    widget_type: "imagefield_widget"
    **proto**: Object
    submit: Object
    uid: Object
    **proto**: Object

####################################

**Comment by signalpoint** [comment]
@teripak `i18n_field_field_formatter_view()` indicates an attempt at loading a multi lingual field, which DrupalGap does not support, yet.

Also,  `location_cck_field_formatter_view()` is inside the Location module, so install it: http://drupalgap.org/project/location

**Comment by teripak** [comment]
I uninstalled i18n module on the drupal site and the related messages has gone.
but still the same status. only lastname field is visible.

below is a new log.
BTW, I have another question. is there a way to include and exclude fields in user or node edit built-in form?

GET: http://localhost:8080/?q=drupalgap/user/1.json
200 - OK
drupalgap_field_info_instances_add_to_form - TypeError: Cannot read property '0' of undefined

Object {uid: Object, name: Object, mail: Object, picture: Object, og_user_node: Object…}
Object {id: "user_profile_form", elements: Object, buttons: Object, options: Object, prefix: ""…}

image_field_widget_form - TypeError: Cannot read property 'field_name' of undefined
entityreference_autocomplete_path - TypeError: Cannot read property 'view_name' of undefined

**Comment by teripak** [comment]
I think something is weird in the drupalgap_field_info_instances_add_to_form().
I put dpm(f) in the function(in drupalgap.min.js) and it show as below.

Object {field_lastname: Object, field_firstname: Object, field_gender: Object, field_intro: Object, field_nickname: Object…}
field_available_languages: Object
field_firstname: Object
field_gender: Object
field_intro: Object
field_lastname: Object
field_location: Object
field_nationality: Object
field_nickname: Object
field_recommended: Object
field_teacher_level: Object
**proto**: Object
drupalgap_field_info_instances_add_to_form - TypeError: Cannot read property '0' of undefined

I don't know "Cannot read property '0' of undefined" message. I think it has a key to solve.

**Comment by teripak** [comment]
I guess I found the reason.

The entity[name][language][delta] could not find a property of language.
language_default() returns "und" and  entity.language has "en".
So entity["field_lastname"]["en"][0] returns error like "TypeError: Cannot read property '0' of undefined"

if I made a comment below line, it works fine.
EDIT: new users who are created after changing settings works fine. but existing user has still problem because they have "en" language code.

```
            //if (entity && entity.language) { language = entity.language; }
```

and I also found a reason for below error.

```
           image_field_widget_form - TypeError: Cannot read property 'field_name' of undefined
```

That's because below function has no "field" parameter (the third one).

```
          function image_field_widget_form(form, form_state, field, instance, langcode,  items, delta, element)
```

But I don't know how to deal with.

**Comment by teripak** [comment]
Please forget about above issues. They are messy to read.
I simply  re-write my 2 questions below.

I go to user/1/edit 

#1. I got below message.

```
       image_field_widget_form - TypeError: Cannot read property 'field_name' of undefined
```

That's because below function has no "field" parameter (the third one).

```
      function image_field_widget_form(form, form_state, field, instance, langcode,  items, delta, element)
```

#2. and I also got below.

```
        WARNING: _drupalgap_form_render_element() - location_cck_field_widget_form() does not exist for the "location" form element!
        WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.
```

Of cause I installed location contrib module and put it in the settings.js.

**Comment by teripak** [comment]
I think the bug report #280 is not applied to the latest drupalgap.js

```
          #280. Change drupalgap_entity_get_core_fields() to only include user...
```

When I modified the #280 manually, #1 question in above is solved.

**Comment by signalpoint** [comment]
@teripak The location module does not have `hook_field_widget_form()` implemented yet:

https://github.com/signalpoint/location/blob/7.x-1.x/location.js

It would need that hook implemented to support the Location field on entity edit forms. (there is better support for addressfield and geofield at this point if needed).

**Comment by signalpoint** [comment]
@teripak Great catch on finding that missing commit in #280 . I've added that commit back into 7.x-1.x, thank you!

**Comment by signalpoint** [comment]
@teripak Thank you for your 3rd comment on April 15th. I'm sorry this fix took so long, but I think it is finally fixed now with the latest commit.
