### ISSUE TITLE
Forward to homepage

### ISSUE THREAD

**Issue by hacioglu** [signalpoint/DrupalGap#504]
Hi,

First of all, thank you for the great work.

I have a responsive drupal website, i installed drupalgap and the sdk successfully. From what I see is drupalgap is for getting, nodes, and pages, ... as json from my drupal instalation. What I want is only to redirect my www.website.com/mobile-application to my www.website.com/index.php, so that I can compile my responsive site as a native app.
Is this possible?

Thank you

**Comment by signalpoint** [comment]
@hacioglu Nope, DrupalGap is used to build applications (mobile and web) for Drupal websites. What you describe isn't considered an application, and will likely be disallowed in the app store (Apple mostly). You may be interested in this module instead: https://www.drupal.org/project/mag

**Comment by hacioglu** [comment]
Wow, I have never received a response that fast

Thank you for ruining my dreams;.)

**Comment by signalpoint** [comment]
@hacioglu Well just think, now you can build an application instead of just mirroring a mobile website in a mobile app ;)
