### ISSUE TITLE
User login page needs a call to system connect

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#51]
If someone implements hook_deviceready and returns false (which cancels DrupalGap's default System Connect call) and then visits the user login page, logs in. Then reloads the app, and visits the login page again, they are technically logged in from Drupal's point of view, but DrupalGap still thinks they are anonymous.

**Comment by chrisschaub** [comment]
I think this is related. I get logged in, drupalgap seems to cache the successful login -- but I can't logout. It's happening  in Ripple and the IOS and Android simulator. I'm using the latest dev/alpha for drupal and the app code.

**Comment by signalpoint** [comment]
Are you running Ripple through the default proxy, or did you set up a local proxy?

**Comment by chrisschaub** [comment]
The default. I can see the login works on the drupal site. But the cookie never makes it back to ripple. Have you gotten around this?

**Comment by signalpoint** [comment]
@cschaub - This latest commit should be stable for compiling straight to a device and in emulators. I tested for both. I am still having trouble with Ripple though, the login works on the Drupal site like you said, but all subsequent calls go as anonymous in Ripple. I'm not sure about the cookie portion, there is more information here (https://drupal.org/node/2013781) that I am trying to gather about how to properly set the cookie, but it sounds like we don't have to do anything with the cookie. I think PhoneGap running on a device and in emulators takes care of the cookie for us, but I think Ripple (and possibly because it is running through a proxy) doesn't handle the cookie properly.

**Comment by chrisschaub** [comment]
So, I think the issue is using "localhost" on the app webserver end, along
with the csrf issue you referenced. If you use something like foo.dev, the
cookies used to work. It was working before the alpha phase, but I think
the real culprit is the services upgrade. I was using ripple against
foo.dev which talked to bar.dev on a virtual machine running drupal.
Digging more into this.

On Tue, Jun 11, 2013 at 10:48 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> @cschaub https://github.com/cschaub - This latest commit should be
> stable for compiling straight to a device and in emulators. I tested for
> both. I am still having trouble with Ripple though, the login works on the
> Drupal site like you said, but all subsequent calls go as anonymous in
> Ripple. I'm not sure about the cookie portion, there is more information
> here (https://drupal.org/node/2013781) that I am trying to gather about
> how to properly set the cookie, but it sounds like we don't have to do
> anything with the cookie. I think PhoneGap running on a device and in
> emulators takes care of the cookie for us, but I think Ripple (and possibly
> because it is running through a proxy) doesn't handle the cookie properly.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/51#issuecomment-19305622
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
For some reason, after upgrading the drupal module, services and the app, I
get a 404 no found on drupalgap/drupalgap_system/connect.json

And a bunch of csrf ereors in the console.

**Comment by signalpoint** [comment]
Thanks for the additional info, I'll try running Ripple on a site not running in localhost to see if the latest changes will work.

As for the latest upgrade, I'd try uninstalling the DrupalGap module on your Drupal site, then just installing a fresh one. Then visit admin/config/drupalgap to make sure the System Connect works OK.

I've noticed that sometimes when upgrading, the service resources can get messed up, so I'll usually disable/enable the drupalgap endpoint under services. Then if that doesn't work, I'll just uninstall drupalgap and re-install the module on the drupal site. I hope this helps!

The commit from yesterday (referenced above) should address the majority of the CSRF errors. Once you are sure your DrupalGap System Connect is working (not just the normal System Connect), the latest commit should be pretty good to go.

Let me know if you continue to have troubles, thanks!

**Comment by chrisschaub** [comment]
Ok, more info. In Ripple, the SetCookie is coming back in the response, but
it's not getting set in Chrome. The Ripple authors swear Ripple allows
cookies. I've tried various apache hacks to allow various headers to be set.

My drupal domain is foo.com. And I've set a 127.0.0.1 alias in /etc/hosts
to app.foo.com. So, Drupal tries to set a cookie for the domain
.foo.com(set in settings.php). The cookie looks correct.

I'm assuming there is some sort of browser restriction causing the cookie
to not be set.

I'm still getting errors like
Request header field X-CSRF-Token is not allowed by
Access-Control-Allow-Headers.
for ?q=drupalgap/drupalgap_system/connect.jsonhttp://myque.dev/?q=drupalgap/drupalgap_system/connect.json.
I've tried your suggestions, and Drupalgap seems to be functioning.

I can see Drupalgap geting the csrf token, the session id. And storing it.
But since the cookie is not set, Drupalgap thinks the user is logged in,
but no auth server requests succeed because the cookie is not there. The
emulators and devices must allow the cookie to be set.
- Chris

On Wed, Jun 12, 2013 at 5:29 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> Thanks for the additional info, I'll try running Ripple on a site not
> running in localhost to see if the latest changes will work.
> 
> As for the latest upgrade, I'd try uninstalling the DrupalGap module on
> your Drupal site, then just installing a fresh one. Then visit
> admin/config/drupalgap to make sure the System Connect works OK.
> 
> I've noticed that sometimes when upgrading, the service resources can get
> messed up, so I'll usually disable/enable the drupalgap endpoint under
> services. Then if that doesn't work, I'll just uninstall drupalgap and
> re-install the module on the drupal site. I hope this helps!
> 
> The commit from yesterday (referenced above) should address the majority
> of the CSRF errors. Once you are sure your DrupalGap System Connect is
> working (not just the normal System Connect), the latest commit should be
> pretty good to go.
> 
> Let me know if you continue to have troubles, thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/51#issuecomment-19360013
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
Ok, if you launch Chrome with

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
--disable-web-security

then cookies will work. The initial CSRF stuff goes away. But I do get a
CSRF violation on logout and viewing a full node. Login is now fine. So,
maybe the token is not getting passed everywhere? Also, shouldn't logout
call the actual logout service on the server side? It seems to just unset
the sessid vars locally.

On Thu, Jun 13, 2013 at 5:19 AM, Christopher Schaub chris@schaub.comwrote:

> Ok, more info. In Ripple, the SetCookie is coming back in the response,
> but it's not getting set in Chrome. The Ripple authors swear Ripple allows
> cookies. I've tried various apache hacks to allow various headers to be set.
> 
> My drupal domain is foo.com. And I've set a 127.0.0.1 alias in /etc/hosts
> to app.foo.com. So, Drupal tries to set a cookie for the domain .foo.com(set in settings.php). The cookie looks correct.
> 
> I'm assuming there is some sort of browser restriction causing the cookie
> to not be set.
> 
> I'm still getting errors like
> Request header field X-CSRF-Token is not allowed by
> Access-Control-Allow-Headers.
> for ?q=drupalgap/drupalgap_system/connect.jsonhttp://myque.dev/?q=drupalgap/drupalgap_system/connect.json.
> I've tried your suggestions, and Drupalgap seems to be functioning.
> 
> I can see Drupalgap geting the csrf token, the session id. And storing it.
> But since the cookie is not set, Drupalgap thinks the user is logged in,
> but no auth server requests succeed because the cookie is not there. The
> emulators and devices must allow the cookie to be set.
> - Chris
> 
> On Wed, Jun 12, 2013 at 5:29 PM, Tyler Frankenstein <
> notifications@github.com> wrote:
> 
> > Thanks for the additional info, I'll try running Ripple on a site not
> > running in localhost to see if the latest changes will work.
> > 
> > As for the latest upgrade, I'd try uninstalling the DrupalGap module on
> > your Drupal site, then just installing a fresh one. Then visit
> > admin/config/drupalgap to make sure the System Connect works OK.
> > 
> > I've noticed that sometimes when upgrading, the service resources can get
> > messed up, so I'll usually disable/enable the drupalgap endpoint under
> > services. Then if that doesn't work, I'll just uninstall drupalgap and
> > re-install the module on the drupal site. I hope this helps!
> > 
> > The commit from yesterday (referenced above) should address the majority
> > of the CSRF errors. Once you are sure your DrupalGap System Connect is
> > working (not just the normal System Connect), the latest commit should be
> > pretty good to go.
> > 
> > Let me know if you continue to have troubles, thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/51#issuecomment-19360013
> > .
> 
> ## 
> 
> Christopher Schaub
> http://chris.schaub.com

## 

Christopher Schaub
http://chris.schaub.com

**Comment by chrisschaub** [comment]
OK, ignore everything I said, I was off on many items. I just added a pull
request which fixes some of the issues I was having. You can debug with
Ripple as long as you setup a subdomain and use the --disable-web-security
option when launching Chrome, cookies get set. My pull request fixes an
CSRF issue with logout. There is still an issue with taxonomy, I'll try to
patch when I hear your feedback about this pull.

On Thu, Jun 13, 2013 at 7:34 AM, Christopher Schaub chris@schaub.comwrote:

> Ok, if you launch Chrome with
> 
> /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
> --disable-web-security
> 
> then cookies will work. The initial CSRF stuff goes away. But I do get a
> CSRF violation on logout and viewing a full node. Login is now fine. So,
> maybe the token is not getting passed everywhere? Also, shouldn't logout
> call the actual logout service on the server side? It seems to just unset
> the sessid vars locally.
> 
> On Thu, Jun 13, 2013 at 5:19 AM, Christopher Schaub chris@schaub.comwrote:
> 
> > Ok, more info. In Ripple, the SetCookie is coming back in the response,
> > but it's not getting set in Chrome. The Ripple authors swear Ripple allows
> > cookies. I've tried various apache hacks to allow various headers to be set.
> > 
> > My drupal domain is foo.com. And I've set a 127.0.0.1 alias in
> > /etc/hosts to app.foo.com. So, Drupal tries to set a cookie for the
> > domain .foo.com (set in settings.php). The cookie looks correct.
> > 
> > I'm assuming there is some sort of browser restriction causing the cookie
> > to not be set.
> > 
> > I'm still getting errors like
> > Request header field X-CSRF-Token is not allowed by
> > Access-Control-Allow-Headers.
> > for ?q=drupalgap/drupalgap_system/connect.jsonhttp://myque.dev/?q=drupalgap/drupalgap_system/connect.json.
> > I've tried your suggestions, and Drupalgap seems to be functioning.
> > 
> > I can see Drupalgap geting the csrf token, the session id. And storing
> > it. But since the cookie is not set, Drupalgap thinks the user is logged
> > in, but no auth server requests succeed because the cookie is not there.
> > The emulators and devices must allow the cookie to be set.
> > - Chris
> > 
> > On Wed, Jun 12, 2013 at 5:29 PM, Tyler Frankenstein <
> > notifications@github.com> wrote:
> > 
> > > Thanks for the additional info, I'll try running Ripple on a site not
> > > running in localhost to see if the latest changes will work.
> > > 
> > > As for the latest upgrade, I'd try uninstalling the DrupalGap module on
> > > your Drupal site, then just installing a fresh one. Then visit
> > > admin/config/drupalgap to make sure the System Connect works OK.
> > > 
> > > I've noticed that sometimes when upgrading, the service resources can
> > > get messed up, so I'll usually disable/enable the drupalgap endpoint under
> > > services. Then if that doesn't work, I'll just uninstall drupalgap and
> > > re-install the module on the drupal site. I hope this helps!
> > > 
> > > The commit from yesterday (referenced above) should address the majority
> > > of the CSRF errors. Once you are sure your DrupalGap System Connect is
> > > working (not just the normal System Connect), the latest commit should be
> > > pretty good to go.
> > > 
> > > Let me know if you continue to have troubles, thanks!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/51#issuecomment-19360013
> > > .
> > 
> > ## 
> > 
> > Christopher Schaub
> > http://chris.schaub.com
> 
> ## 
> 
> Christopher Schaub
> http://chris.schaub.com

## 

Christopher Schaub
http://chris.schaub.com

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.
