### ISSUE TITLE
Unable to load google map in web app

### ISSUE THREAD

**Issue by days4** [signalpoint/DrupalGap#513]
hi ,
i created an  native app using drupalgapthat has google map and working absolutely fine
but now i want to turn it as web app so i changed mode to web-app in settings
everything is working fine except map its not loading
is there anything else i have to change?
plese suggest

**Comment by signalpoint** [comment]
@days4 Did you remember to put the Google Maps JavaScript include in your index.html file? Clear your browser's cache. Also follow the instructions closely here: http://www.drupalgap.org/node/497

**Comment by days4** [comment]
thank you so much ....
i didn't included that api in my index file 
now it's  included and working very well
again thankyou so much @signalpoint
