### ISSUE TITLE
Xcode app stuck on splash screen

### ISSUE THREAD

**Issue by punchdone** [signalpoint/DrupalGap#514]
I have been able to get DrupalGap working as a mobile application, with Ripple and even with the DrupalGap iOS App.  For whatever reason, I am absolutely not able to configure an environment locally where my Xcode connects to my website (pantheon if that matters).  I have messed around repeatedly with Drupal.settings.site_path = '' thinking that was my problem.  Whatever I do, I still get the simple DrupalGap splash screen without the dashboard.  I want the dashboard, I need dashboard!  Help. . .

**Comment by signalpoint** [comment]
@punchdone Did you replace the index.html file with the contents of cordova.index.html?

**Comment by punchdone** [comment]
First, you are the man!  I didn’t know to do this (I must have missed it in the directions).  In my spare time, I was attempting to teach myself Swift but came across your Drupal MI Camp presentation.  You did an excellent job and inspired me to give the DrupalGap/PhoneGap approach a try.  It truly is awesome!  Now, I have my development environment setup and I can start trying to do some cool stuff.  

Second, we had lunch together in Austin.  Next time, I owe you dinner or at least a beer.  Thanks so much.

**Comment by signalpoint** [comment]
@punchdone excellent, good to hear. Please feel free to add this mention in the documentation on drupalgap.org where you may have missed it. This is a really common problem as of late, so I'd like to iron out this instruction step for folks.

And thanks for the kind words, and the reminder of Austin. I believe you were doing some IT stuff in relation to woodworks, if I recall correctly. Off to L.A. soon.

**Comment by punchdone** [comment]
Good memory.  I have built a very customized quotation, pricing and production tracking application for my Cabinetry & Millwork business in Drupal.  I have another larger manufacturer in Colorado also interested in using it as well.  Imagine if I could deploy an app as well.  With a co-founder, we are working on another project that this technology applies to—PunchDone.  Again, very impressive and I really appreciate your help.  If you are ever in the PNW.  

Scott

**Comment by punchdone** [comment]
And I will see if I can find where in the documentation your direction should be inserted.  Thanks.
