### ISSUE TITLE
how i can add bacground image in drupalgap front page

### ISSUE THREAD

**Issue by days4** [signalpoint/DrupalGap#521]
i want to add an image in background of my app's front page 
for that i made addition in drupalgap.css
file like this

```
 .my_class {
    position:relative;
  background: url(images/home.png) center center;
    width:100%;
    height:100%;

}
```

after that i made some corection in
my themes js file like this

```
content: {
          attributes: {

           'class': 'my_class',
            'role': 'main',

          }
        }
```

the image is displayed only in background of content not in full screen 
please help me to do so

**Comment by signalpoint** [comment]
@days4 I wouldn't recommend modifying drupalgap.css, instead use a custom CSS file.

You'll need to use a more specific CSS identifier to apply your background to the entire page, not just the content region. Modify index.html's splash page div as needed.

**Comment by days4** [comment]
to place an image in background of front page add this code in drupalgap.css file

```
#dashboard{
 position:relative;
  background: url(images/home.png) center center;
    width:100%;
    height:100%;
 }
```

here dashboard is your front page name
