### ISSUE TITLE
Using makefile and makefile_lite

### ISSUE THREAD

**Issue by coolman7** [signalpoint/DrupalGap#522]
Hello,
I forked 7.x-1.x. But it gave me compile errors. But I can compile without errors version 1.x-rc5. Is it possible to fork 1.x-rc5?

PS: I am a github newbie. If I'm asking stupid question, please forgive me :)

I get following errors on 7.x-1.x fork:

gjslint src/drupalgap.js src/includes/block.inc.js src/includes/common.inc.js src/includes/form.inc.js src/includes/go.inc.js src/includes/page.inc.js src/includes/region.inc.js src/includes/menu.inc.js src/includes/theme.inc.js src/includes/title.inc.js src/modules/comment/comment.js src/modules/contact/contact.js src/modules/entity/entity.js src/modules/field/field.js src/modules/file/file.js src/modules/image/image.js src/modules/menu/menu.js src/modules/mvc/mvc.js src/modules/node/node.js src/modules/search/search.js src/modules/services/services.js src/modules/system/system.js src/modules/user/user.js src/modules/taxonomy/taxonomy.js src/modules/views/views.js
----- FILE  :  /home/hirac/protected/Projects/cordova/drupalgap/src/includes/block.inc.js -----
Line 31, E:0210: Missing docs for parameter: "region"
Line 31, E:0210: Missing docs for parameter: "current_path"
Line 31, E:0210: Missing docs for parameter: "block_delta"
Line 31, E:0210: Missing docs for parameter: "block_settings"
Line 31, E:0210: Missing docs for parameter: "block_counts"
Line 29, E:0217: Missing @return JsDoc in function with non-trivial return
----- FILE  :  /home/hirac/protected/Projects/cordova/drupalgap/src/includes/go.inc.js -----
Line 71, E:0110: Line too long (106 characters).
Line 251, E:0214: Missing description in @deprecated tag
Line 253, E:0210: Missing docs for parameter: "path"
Line 252, E:0217: Missing @return JsDoc in function with non-trivial return
Line 359, E:0131: Single-quoted string preferred over double-quoted string.
Line 359, E:0001: Extra space after "function"
----- FILE  :  /home/hirac/protected/Projects/cordova/drupalgap/src/includes/page.inc.js -----
Line 47, E:0001: Extra space after "{"
Line 3, E:0217: Missing @return JsDoc in function with non-trivial return
----- FILE  :  /home/hirac/protected/Projects/cordova/drupalgap/src/includes/region.inc.js -----
Line 263, E:0210: Missing docs for parameter: "key"
Line 262, E:0217: Missing @return JsDoc in function with non-trivial return
----- FILE  :  /home/hirac/protected/Projects/cordova/drupalgap/src/modules/system/system.js -----
Line 167, E:0217: Missing @return JsDoc in function with non-trivial return
Line 188, E:0210: Missing docs for parameter: "path"
Found 18 errors, including 0 new errors, in 5 files (20 files OK).

Some of the errors reported by GJsLint may be auto-fixable using the script
fixjsstyle. Please double check any changes it makes and report any bugs. The
script can be run by executing:

fixjsstyle src/drupalgap.js src/includes/block.inc.js src/includes/common.inc.js src/includes/form.inc.js src/includes/go.inc.js src/includes/page.inc.js src/includes/region.inc.js src/includes/menu.inc.js src/includes/theme.inc.js src/includes/title.inc.js src/modules/comment/comment.js src/modules/contact/contact.js src/modules/entity/entity.js src/modules/field/field.js src/modules/file/file.js src/modules/image/image.js src/modules/menu/menu.js src/modules/mvc/mvc.js src/modules/node/node.js src/modules/search/search.js src/modules/services/services.js src/modules/system/system.js src/modules/user/user.js src/modules/taxonomy/taxonomy.js src/modules/views/views.js 
make: **\* [jslint] Error 1

**Comment by signalpoint** [comment]
@coolman7 For now, overwrite `makefile` with `makefile_lite`, then you can run `make`.

The lighter makefile isn't as strict about code documentation, so I use it for faster development.
