### ISSUE TITLE
Add "Toast" Message Feature

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#527]
It'd be nice to show a non intrusive message overlayed on the app screen. Example usage:

`drupalgap_toast('<p>Hello World!</p>');`

**Comment by d0t101101** [comment]
Great feature, but unfortunately this function currently seems to eat CPU indefinitely.  After loading a page which contains:

`drupalgap_toast('A message', 3000);`

Firefox & Chrome consume upwards of 20% CPU, and never returns to normal until the app is restarted.  This also fixed the sluggishness on my android build too!

This alternative works fine with no adverse side effects:

`drupalgap_set_message('A message', 'warning');`

.

**Comment by signalpoint** [comment]
@d0t101101 Yikes! Thank you for pointing this one out. I've pushed the fix for this and will update the docs to reflect more accurate usage of the toaster. http://drupalgap.org/node/207

**Comment by signalpoint** [comment]
As pointed out by @d0t101101, there are still some issues with this feature:

> I dug a little deeper into why the ui-loader animation doesn’t work sometimes on subsequent pages, and found that the problem starts once drupalgap_toast inserts ‘display:none’ into the HTML style tag. After this happens, it’s never cleared, hence ui-loaders stop working altogether!

Some useful articles on this:
- http://stackoverflow.com/questions/15292927/jquery-mobile-issues-first-time-user
- http://stackoverflow.com/questions/7420023/jquery-mobile-problems-getting-showpageloadingmsg-to-work-with-pagebeforeshow

**Comment by signalpoint** [comment]
Still having issues when using toast and then using jDrupal calls (which DG pre/post processes to show/hide the loader), then loader never shows back up.
