### ISSUE TITLE
drupalgap web app stuck on splash screen

### ISSUE THREAD

**Issue by Sunia88** [signalpoint/DrupalGap#550]
dashboard not load for my drupal website, web app just stuck on white screen with drupal icon, i have change the index.html --> cordova.index.html

**Comment by Sunia88** [comment]
where i can found web-app.index.html?

**Comment by signalpoint** [comment]
@Sanchiz DrupalGap out of the box supports web apps, so it should not get stuck on the splash screen in web-app mode when running in a modern browser.

If you're using cordova.index.html (in place of index.html), then make sure the cordova.js file has been copied to the root www directory of your app when running in PhoneGap/Cordova.

The web-app.index.html file no longer exists, it has been replaced by index.html file (by default). I've updated the documentation to reflect this.

**Comment by Sunia88** [comment]
where i can get cordova.js file?

**Comment by signalpoint** [comment]
@Sanchiz a simple Google search would yield many results for that... but you only need it if you are building a mobile app, and it is provided by the PhoneGap/Cordova install (aka platform add). This is all covered in the DrupalGap installation docs, please take the time to read through it. Good luck and happy coding!
