### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#56]
Is there somewhere I can begin to add to documentation. Such as helping to build up the getting started guide? 

I'm currently working through sessions (although not sure where to start). I need to be able see what user is logged in when I get a view via services (as I filter the view based on the user) but not sure how I would go about making the services call with the logged in user information. 

Stuff like this I think belongs in documentation as authentication will be a common use case. I'm happy to write it up if you tell me where I should post it after :)

**Comment by signalpoint** [comment]
Hey Scott,

Please check out:

http://www.drupalgap.org/get-started

There is quite a bit of information there already, but it could use some help that's for sure! By registering an account and logging in at drupalgap.org, the Getting Started Guide is available for authenticated users to make modifications and add new content (similar to drupal.org).

Feel free to add/edit anything you think is beneficial.

Thanks again for your contributions!
