### ISSUE TITLE
Classes for local tasks menu

### ISSUE THREAD

**Issue by terotik** [signalpoint/DrupalGap#561]
I'm trying to find a way to inject classes to local_tasks menu. 

Currently the local tasks menu div gets `id="node_1_menu_primary_local_tasks"` but this is not very useful for styling purposes as the id is different on every page. 

I have tried this in settings.js, but no joy:

`primary_local_tasks: {  
      options: {  
        attributes: {  
          class:'local-tasks'  
        }  
      }  
    }  
`

**Comment by signalpoint** [comment]
@terotic Does `primary_local_tasks: { attributes: { class:'local-tasks' } }` work?

**Comment by terotik** [comment]
@signalpoint Doesn't seem to work either. 
Still just getting an empty class attribute in local_tasks menu ul tag
`
<div id="node_1_menu_primary_local_tasks">
<ul class="">
<li>
...
`

**Comment by signalpoint** [comment]
@terotic whoops, I forgot to mention you need to wrap the word `class` in quotes or it won't work, like this: `'class': 'local-tasks'`. If that still doesn't work, try this:

`primary_local_tasks: { wrap: true, wrap_attributes: { 'class': 'local-tasks'  } }`

See here: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/menu/menu.js#L26

**Comment by terotik** [comment]
@signalpoint Hurrah, finally got it working. This is the correct syntax:

```
drupalgap.settings.menus['primary_local_tasks'] = {
      options: {
        wrap: true,
        wrap_options: { 
          attributes: {
            'class': 'local-tasks'
          }
        }
      }
};
```
