### ISSUE TITLE
{ InAppBrowser:true } is not working anymore.

### ISSUE THREAD

**Issue by zawlinoo** [signalpoint/DrupalGap#568]
I was using like this.
`l(node.name, 'node/' + node.nid, {InAppBrowser:true});`
it is going to external browser not inappbrowser. Will you please help me?
my inappbroswer version is ' cordova-plugin-inappbrowser 1.0.0 "InAppBrowser" '.

**Comment by signalpoint** [comment]
From the code, I don't see how that would be possible: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/includes/theme.inc.js#L357

You'll need to step through that function to see what is going on.

**Comment by zawlinoo** [comment]
i can't console.log on browser. Give me an error alert box which modules and theme.js are missing when i access from web browser. But it is working fine with the android console. Strange.

**Comment by zawlinoo** [comment]
![screen shot 2015-06-08 at 11 22 56 am](https://cloud.githubusercontent.com/assets/2246053/8028336/f8a58b5c-0dd0-11e5-9be1-20085aff261a.png)

it is showing correctly but always goes to browser.

**Comment by signalpoint** [comment]
@zawlinoo This sounds like an issue outside of DrupalGap then, it sounds more device specific vs. cordova vs. inappbrowser plugin, sorry.
