### ISSUE TITLE
cannot find ripple.index.html

### ISSUE THREAD

**Issue by benedict1986** [signalpoint/DrupalGap#570]
Hi, I am new to drupalgap and meet a problem. I could not find ripple.index. html. In the tutorial, I am asked to replace index.html by ripple.index.html, but I could not find the latter. Can anyone help? Thank you

**Comment by signalpoint** [comment]
@benedict1986 `ripple.index.html` no longer exists, you can use the `default.index.html` and switch the `mode` to `phonegap` in the `settings.js` file instead. What tutorial did you see a mention of `ripple.index.html` in?

**Comment by benedict1986** [comment]
Thank you. I will have a try.

**Comment by AdityaBhel** [comment]
https://www.youtube.com/watch?v=YUEDB68IdP8
here is the link
