### ISSUE TITLE
User already connected in a web app DrupalGap

### ISSUE THREAD

**Issue by lesonunique** [signalpoint/DrupalGap#571]
Hello,

I wish to make a connection between Drupal and my web app (in javascript). For this I use DrupalGap (jdrupal-7.x-1.2.js and drupalgap-7.x-1.0.js)

I get connected with user_login () and user_logout () but I can not test whether the user is already logged.

I see the cookie with Firebug but is HttpOnly so I can not get it.

Is there a solution for this (Get the session cookie or DrupalGap function)?

Thank you in advance.

Vincent

**Comment by signalpoint** [comment]
You're probably looking for the `system_connect()` function. Upon its `success` it will tell you if the user is logged in or not.

Note, DrupalGap automatically makes a call to `system_connect()` upon start up, then populates the `Drupal.user` object with the anonymous or authenticated user object.

In your case, first check the value of `Drupal.user`, it'll probably have what you need. If not, make a call to `system_connect()`.

Take a look at the `jDrupal` index.html for an example usage of `system_connect()`: https://github.com/easystreet3/jDrupal/blob/7.x-1.x/index.html

**Comment by lesonunique** [comment]
Hello,

Thank you very much, this is exactly what I wanted.

A second question: with the function user_load I can log into my user with the login, but not with the mail of the user (unlike drupal).

Is it possible to authorize the connection to the email?

Thank you.

Vincent

**Comment by signalpoint** [comment]
@lesonunique Drupal does not let you login with an e-mail address by default, only contrib modules (aka Login Toboggan) allow such a feature.

**Comment by lesonunique** [comment]
Hello,

I have a problem with system_connect (): when the request is made, it is blocked:

" Blocage d'une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://www.lesonunique.com/?q=drupalgap/system/connect.json. Raison : jeton « content-type » manquant dans l'en-tête CORS « Access-Control-Allow-Headers » du canal de pré-vérification des requêtes CORS. "

So I tried to use CORS Drupal module with these settings:
    \* | \* | POST, GET, PUT, DELETE | Content-Type, X-csrf-token | true

Now the query executes but always returns the user as anonymous.

```
    system_connect({
        success:function(result){
            console.log("Test user connect");
            console.log(result);
            console.log(result.user.roles);
            if (result.user.roles[1] == "anonymous user")
            {
                console.log('Anonyme');
            }
            else
            {
                console.log('Connecté');
                console.log('Hi, ' + result.user.name + '!');
            }
        },
        error:function(xhr, status, message) {
            console.log('Error system_connect');
        }
    });
```

How to fix it? Thank you in advance.

Vincent

**Comment by signalpoint** [comment]
@lesonunique This seems like an unrelated issue, please don't post multiple issues in one issue thread. Make sure `session authentication` is checked under your Services endpoint settings.

**Comment by lesonunique** [comment]
Yes session_authentification is checked. Do create a new issue for this problem?
When I put my web-app in the same website server, it not work when I launch the application on lesonunique.com/newappli but it work on www.lesonunique.com/newappli ...

**Comment by signalpoint** [comment]
@lesonunique Make sure the `site_path` variable contains www (or not) in your settings.js file, that will dictate whether you can access the app over www or not. That's a server configuration problem, as I have the same problems on many servers. I think the solution is to always resolve the user to the www, similar to visiting drupal.org, you are redirected to https://www.drupal.org
