### ISSUE TITLE
Angular JS

### ISSUE THREAD

**Issue by coolman7** [signalpoint/DrupalGap#578]
I've read from the link below, new version of SDK will be based on angular JS. jquery mobile will be dropped or both of them will be used at the same time?

http://drupalgap.org/angular

**Comment by signalpoint** [comment]
@coolman7 jQuery Mobile will be dropped in favor of Angular JS. The 7.x-1.x branch of DrupalGap is the jQuery Mobile branch, and it will continue onward (similar to Drupal 6, DrupalGap 1.x has some cool features, is production ready, but has some design pitfalls that need to be overcome with a complete overhaul, aka DrupalGap 2.x).

I personally am very excited about the 7.x-2.x branch of DrupalGap which is powered by Angular, and will be focusing my personal resources towards that.

jQM and Angular JS won't be used at the same time, they'll be used separately. With the Angular JS version, you'll be able to choose a front end design framework like Bootstrap or Ionic.

**Comment by chrisschaub** [comment]
Definitely a vote for Ionic. I just built an app with it, very solid and
really responsive. And Pouchdb + Websql + Couchdb, fun stuff.

On Sun, Jul 5, 2015 at 9:02 AM, Tyler Frankenstein <notifications@github.com

> wrote:
> 
> Closed #578 https://github.com/signalpoint/DrupalGap/issues/578.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/578#event-348033285.

## 

Christopher Schaub
http://chris.schaub.com

**Comment by coolman7** [comment]
React is getting stronger and widely used. While changing framework, is it better to switch React instead of Angular?
