### ISSUE TITLE
Question about Events

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#58]
Just wondering if I should create a custom module to register events for pageshow, and pageinit? Or just hang them in a custom js file directly from index.html. Appreciate your thoughts.

**Comment by signalpoint** [comment]
I'd place them in a custom module so they won't get tangled up with DrupalGap core files. You can register jQM page events for specific pages via hook_menu(). Check out node_menu() in node.js for an example of how to attach a jQM page event to a page defined by hook_menu(). For example, this attaches the node_page_pageshow() function to the pageshow event on the 'node' page (shows a simple list of recent nodes):

/**
- Implements hook_menu().
  */
  function node_menu() {
  // ...
  var items = {
    'node':{
      'title':'Content',
      'page_callback':'node_page',
      'pageshow':'node_page_pageshow',
    },
  };
  // ...

**Comment by signalpoint** [comment]
I've added a page with more information about events in the Getting Started Guide: http://drupalgap.org/node/116

**Comment by chrisschaub** [comment]
One thing about this. I've noticed that, since LIVE has been deprecated in favor of ON, things are a bit different. Live used to be ok with handling elements that come and go via ajax -- it would just rebind as the pageshow fires, or even pageinit. ON is stickier.

For example, if you have a #search div that you want to show hide based on a click, you can't put that in a pageshow within Drupalgap, or even a custom module. It needs to be loaded when then main index.html gets loaded to really fire consistently. You can get it to fire once, but then it won't fire again. I've tried pageinit, pageshow, pagecreate ... and others are having similar issue. 

Just mentioning this because I tried to put all of my event handlers into a custom Drupalgap module. The more global ON event handlers needed to be in a javascript file, included from index.html. This might be that Drupalgap including pages might be just after they need to be? Not sure, but the behaviour was really consistent.
