### ISSUE TITLE
text view expose filter

### ISSUE THREAD

**Issue by roozbehzand** [signalpoint/DrupalGap#582]
when add expose filter on body field .
the text box is not show for filter

**Comment by signalpoint** [comment]
duplicate: #580

**Comment by roozbehzand** [comment]
when you fix expose filter with latest release of Views

On Tue, Jul 7, 2015 at 6:46 PM, Tyler Frankenstein <notifications@github.com

> wrote:
> 
> duplicate: #580 https://github.com/signalpoint/DrupalGap/issues/580
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/582#issuecomment-119236185
> .

## 

Tel      : +98 2122566686
Mobile : +98 9121013730
Email  : Roozbeh.Zand@gmail.com
