### ISSUE TITLE
Any idea how to implement private messages?

### ISSUE THREAD

**Issue by coolman7** [signalpoint/DrupalGap#585]
I want to read, reply and send private messages from drupalgap app. I guess we need services integration with privateemsg module.

There is a discussion at drupal site and they have a patch:
https://www.drupal.org/node/433780#comment-10034435

Is that enough to make privatemsg module for drupalgap?

**Comment by signalpoint** [comment]
@coolman7 Yes, the services wrapper for privatemsg would be enough to get started. Talk to @ptmkenny , he may have made progress on this.

**Comment by coolman7** [comment]
How can I talk with him? I think github has no private message system.

**Comment by signalpoint** [comment]
@coolman7 I've tagged him in this thread earlier, so he should've received a notification already.

**Comment by coolman7** [comment]
Ok. So I'll wait for reply.
Thanks

**Comment by ptmkenny** [comment]
I'm sorry to say I haven't made any progress on this yet.

The main thread for Privatemsg services on d.o is here:
https://www.drupal.org/node/433780

There was also a sandbox (https://www.drupal.org/sandbox/deminy/2413647)
but this is now in the form of a patch in the thread above (#71).

**Comment by signalpoint** [comment]
@coolman7 This module is now available for DrupalGap! https://github.com/signalpoint/privatemsg
