### ISSUE TITLE
How can i show the pager in my app?

### ISSUE THREAD

**Issue by zaoanx** [signalpoint/DrupalGap#587]
I follow this guide(http://www.drupalgap.org/node/251) to add the pager,but it seems useless.
This is my drupal configuration:
![image](https://cloud.githubusercontent.com/assets/10852297/8585738/e42434f2-2618-11e5-80db-5297f4d69992.png)
and the code snippet of my app:
![image](https://cloud.githubusercontent.com/assets/10852297/8585829/141a2454-261a-11e5-8b34-a5186d96e136.png)

**Comment by signalpoint** [comment]
@zaoanx try removing the custom `id` and `data-filter` attributes, and of course make sure you have at least 5 nodes, and are running the latest version of everything (up to date Drupal, DrupalGap module, DrupalGap SDK). Any luck with that?

**Comment by zaoanx** [comment]
@signalpoint it doesn't work.
i remove <code>data-filter</code> attribute, and sure that i have more than 5 nodes, and running the newer version than the guide doc use.
i think maybe my drupal website have the wrong configuration but i'm not sure that.
i have just use drupal and drupalgap for a week.thank you for your help :+1: .

![image](https://cloud.githubusercontent.com/assets/10852297/8587385/33161c06-262d-11e5-8430-c37f135cb7ac.png)
![image](https://cloud.githubusercontent.com/assets/10852297/8587387/455eacfc-262d-11e5-9c04-6c4b94554178.png)
![image](https://cloud.githubusercontent.com/assets/10852297/8587392/52d8b5c6-262d-11e5-8275-3e2aa66e51c3.png)

**Comment by signalpoint** [comment]
With the latest version of everything, and following these examples http://drupalgap.org/node/234 & http://drupalgap.org/node/219 - the pager is working properly.

I see from your code sample you aren't specifying a `path` in your Views Render Array, you should have a path, or else it won't work at all.
