### ISSUE TITLE
Print flag/unflag Links in Views

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#588]
How are flag/unflag links displayed in views pages? I have tried a few different things without success:

flag_flag('bookmarks', row.nid)

flag_is_flagged('bookmarks', row.nid)

flag_create_link('bookmarks', row.nid)

**Comment by signalpoint** [comment]
@mkinnan The `flag_entity_post_render_content()` function is in charge of displaying flags on node view pages. Will you please elaborate on what you mean by `views pages`?

**Comment by mkinnan** [comment]
By `views pages` I am referring to having a JSON view that I want to display as a table:

```
var html =
  '<td>' + rowtext + '</td>' +
  '<td>' + display flag/unflag link here + '</td>';
return html;
```

I tried the following to display the links, but gives me _undefined_ for the flag column.

`flag_entity_post_render_content(entity, entity_type, bundle)`
`flag_entity_post_render_content(row.nid, 'node', 'article')`
`flag_entity_post_render_content(row.nid)`
`flag_entity_post_render_content(entity)`

**Comment by signalpoint** [comment]
@mkinnan You'll probably want to try something like this when rendering the flag link in your `row_callback`:

```
theme('flag', {
  fid: row.fid,
  entity_id: row.entity_id,
  action: 'flag', // 'flag' or 'unflag'
  text: t('Flag'),
  entity_type: row.entity_type,
  bundle: row.bundle
});
```

**Comment by mkinnan** [comment]
I thought printing a flag was similar to standard Drupal, so I am unclear on this in DrupalGap... I am assuming this is wrong:

```
var html =
  '<td>' + rowtext + '</td>' +
  '<td>' + flag_entity_post_render_content(row.nid, 'node', 'article') + '</td>';
return html;
```

In the view I created in Drupal, one of the fields I have outputted via JSON is whether the node has been flagged ... and have the _output format_ set to 1/0. So, where do I put the theming when _flagged == 1_ and when _flagged == 0_ ?

**Comment by signalpoint** [comment]
@mkinnan Correct, do _not_ use `flag_entity_post_render_content()` in a Views row callback, it is not at all meant for that. Instead use the `theme('flag', ...)` I describe earlier.

**Comment by mkinnan** [comment]
Ok, I have the flag links visible but nothing happens when clicking them.

What's interesting is that when viewing a node in the app, DrupalGap is pulling the flag/unflag image checkboxes that I have implemented on the main website.

```
if (row.nodeflagged == 1) {
  flagthislink = theme('flag', {
    fid: row.fid,
    entity_id: row.entity_id,
    action: 'flag', // 'flag' or 'unflag'
    text: t('Flag'),
    entity_type: row.entity_type,
    bundle: row.bundle
  });
} else {
  flagthislink = theme('flag', {
    fid: row.fid,
    entity_id: row.entity_id,
    action: 'unflag', // 'flag' or 'unflag'
    text: t('UnFlag'),
    entity_type: row.entity_type,
    bundle: row.bundle
  });
}

var html =
  '<td>' + rowtext + '</td>' +
  '<td>' + flagthislink + '</td>';

return html;
```

**Comment by signalpoint** [comment]
@mkinnan Well your `row` JSON object needs to contain the `fid` (aka the flag id), the `entity_type` (e.g. `node`) and the `bundle` (e.g. my `my_content_type`). If you know all of these values, you can just send them along manually instead.

**Comment by mkinnan** [comment]
Yes, I am using the latest dev version of flag to pass the `fid` through the JSON view. I am printing the output in the table in the app to ensure the values are being passed. I was passing the other variables via JSON, but have hardcoded them instead. I can click the flag/unflag links, but the only thing that happens is highlighting around the box. I know I am just missing something, but just can't figure out what.

```
if (row.nodeflagged == 1) {
  flagthislink = theme('flag', {
    fid: row.fid,
    entity_id: row.nid,
    action: 'unflag', // 'flag' or 'unflag'
    text: t('UnFlag'),
    entity_type: 'node',
    bundle: 'thread'
  });
} else {
  flagthislink = theme('flag', {
    fid: row.fid,
    entity_id: row.nid,
    action: 'flag', // 'flag' or 'unflag'
    text: t('Flag'),
    entity_type: 'node',
    bundle: 'thread'
  });
}

var html =
  '<td>' + row.nid + '</td>' +
  '<td>' + row.fid + '</td>' +
  '<td>' + flagthislink + '</td>';

return html;
```

![untitled](https://cloud.githubusercontent.com/assets/13283396/8642077/1dd0f94a-28dc-11e5-8360-9a20926b2d77.png)

**Comment by signalpoint** [comment]
@mkinnan Set `debug` to `true` in `settings.js`, and step through the `_flag_onclick()` function to see what is going on. Also watch the Network tab in your browser for Internet activity.

**Comment by mkinnan** [comment]
All variables are being passed to `_flag_onclick`. It appears

```
var flag = flag_load(fid);
```

in `_flag_onclick` always returns NULL regardless of whether the fid is an integer (_flagged nodes_) or 0 (_unflagged nodes_).

**Comment by mkinnan** [comment]
In the function `flag_load(fid)` there is `fid` and `_fid`. If I log both those values, `fid` is the id of the flag where as `_fid` is the id of the flag type (e.g., bookmarks). When I have this:

```
    dpm("DEBUG flag_load 2 = " + fid + "-" + _fid);
```

before the `if (fid == _fid) {` line in `flag_load`, then here is the output I get when I click the unflag link once:

```
DEBUG flag_load 2 = 392-2
DEBUG flag_load 2 = 392-3
DEBUG flag_load 2 = 392-4
DEBUG flag_load 2 = 392-5
DEBUG flag_load 2 = 392-7
```

where the 2,3,4,5,7 values for `_fid` are my different flag types (e.g., bookmarks). So, the _if_ clause will always be _false_. Am I looking at this correctly?

**Comment by signalpoint** [comment]
@mkinnan A flag ID in the 3 hundreds seems unreasonable, unless you've created 300+ flags ;)

Are you sure that is the correct value to be passing?

**Comment by mkinnan** [comment]
I have 300+ flagged items ... across 6 different flag types (e.g., bookmarks). It seems the correct value to be passing in the theme() function is the ID number of the flag type, not the ID number of the flagged item :)

 I'll need to tinker to see if my implementation above for `if (row.nodeflagged == 1) { }` is the correct way to display the flag because it doesn't switch when the flag link is clicked.

Hopefully when I get this all figured out right, I'll create another tutorial page on drupalgap.org.

**Comment by signalpoint** [comment]
@mkinnan Do a `console.log(drupalgap.flag);`, what does that output?

**Comment by mkinnan** [comment]
When `console.log("DEBUG drupalgap.flag = " + drupalgap.flag);` is placed first in the `flag_load(fid)` function, I get:

```
DEBUG drupalgap.flag = [object Object]
```

**Comment by signalpoint** [comment]
@mkinnan The console log can't print a string and an object and the same time, you must separate the logs. Do this instead:

```
console.log("DEBUG drupalgap.flag");
console.log(drupalgap.flag);
```

**Comment by mkinnan** [comment]
Here is the output and I expanded Object 5 since that is the one this flag is for.

![image](https://cloud.githubusercontent.com/assets/13283396/8688558/d2fa2cc2-2a5a-11e5-9e4f-abe8696d1a7e.png)

**Comment by mkinnan** [comment]
I am wondering if the theme display is correct ... because the attributes of the `theme('flag'), {}` should get populated from the option variables already being passed in `drupalgap.flag`. I don't understand why I need to tell the theme function to use a specific text to display (e.g., 'Flag This') when the text is already stored (_flag.options.flag_short_).

**Comment by signalpoint** [comment]
@mkinnan when I originally built this, it was in about 2-3 hours for a sponsored client, so I will let you take it from here. Please consider forking the DrupalGap Flag module and adding these improvements you are discovering, and submit a pull request.

**Comment by signalpoint** [comment]
@mkinnan There's now some helper functions to do this included with the flag module for DrupalGap, see the README: https://github.com/signalpoint/flag/blob/7.x-1.x/README.md#views-render-array-row-quick-links-for-flags
