### ISSUE TITLE
node_load needs to be changed to async

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#59]
The node_load function is synchronous right now, this is no good. It needs to be converted to async and be ready for a success and error callbacks

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.

**Comment by eliataylor** [comment]
is this possible with loading Drupal Views via Render Array (http://www.drupalgap.org/node/219)?

**Comment by signalpoint** [comment]
@taylormadetraffic I'm not sure I entirely understand you, so maybe. Drupal Views via a Render Array are fetched asynchronously, so yes.

If that doesn't clarify your question, please open a new issue, thanks.

**Comment by eliataylor** [comment]
Yeah, my mistake. I see it is indeed asynchronous. I was basically trying to innerHTML the Drupal View into the my content div, without changing pages. I starting to think that's not even a great idea now so will play around a bit more. Thanks

**Comment by signalpoint** [comment]
@taylormadetraffic That should also be possible if you fetch the View manually (http://www.drupalgap.org/node/222). Also, instead of using innerHTML, I'd recommend:

```
var my_html = '<p>Hello World</p>';
$('#my_container').html(my_html).trigger('create');
```
