### ISSUE TITLE
Change Homepage per Role Type

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#590]
Where is the best place to set the home page per role type? For anonymous users, I want them to see a default page of text (e.g., some about info and register links). For authenticated users, their homepage should be a feed of new content (via JSON views).

Is this something that can be done in settings.js?

**Comment by signalpoint** [comment]
@mkinnan I usually do this in the `page_callback` and/or the `pageshow` callback. Something like this:

```
var content = {};
if (Drupal.user.uid == 0) {
  content['randy_random'] = {
    markup: '<p>You are not logged in!</p>'
  };
}
else {
  content['authenticated_andy'] = {
    markup: '<p>Hello ' + Drupal.user.name + '!</p>'
  };
}
return content;
```
