### ISSUE TITLE
How to implement views infinite scroll?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#594]
How do you implement views_infinite_scroll:
https://github.com/signalpoint/views_infinite_scroll

I have my format as `ul` on my function page ... 

I read the referenced link: http://stackoverflow.com/a/24728709/763010

Do I need to configure my view on the main site in a specific way?

**Comment by signalpoint** [comment]
@mkinnan You should just have to turn on the module in DrupalGap as usual, and make sure your Views Render Array's path Drupal View is set up for paging.

**Comment by mkinnan** [comment]
When I enable views_infinite_scroll and add pagination to a view, I see next/previous buttons at the top of the page ... but no scrolling to the next page when I scroll to the bottom of the page. When I scroll down to the buttom of the page, nothing happens until the last row is reached ... and I see the following error in the console log (Ripple Emulator):

```
Uncaught ReferenceError: _views_embed_view_options is not defined
```

Here is the JSON views output for **MINI** pager and **FULL** pager:

```
"view" : {
  "name" : "drupalgap_my_bookmarks",
  "display" : "default",
  "path" : "admin/structure/views/nojs/preview/drupalgap_my_bookmarks/default",
  "root" : "nodes",
  "child" : "node",
  "pages" : 2,
  "page" : 0,
  "count" : 36,
  "limit" : 25
}
```

Here is the JSON views output for **LITE** pager (https://www.drupal.org/project/views_litepager) which doesn't show any content because limit is 0 for some reason. I am guessing this is a view_litepager issue?

```
"view" : {
  "name" : "drupalgap_my_bookmarks",
  "display" : "default",
  "path" : "admin/structure/views/nojs/preview/drupalgap_my_bookmarks/default",
  "root" : "nodes",
  "child" : "node",
  "pages" : 1,
  "page" : 0,
  "count" : 0,
  "limit" : 0
}
```

**Comment by signalpoint** [comment]
@mkinnan Try updating to the latest `bin/drupalgap.js` file and the latest dev snapshot of the drupalgap module.

**Comment by mkinnan** [comment]
Updated drupalgap module and the entire DrupalGap application development kit ... which fixed the problem. Thanks!
