### ISSUE TITLE
menu for specific page

### ISSUE THREAD

**Issue by Sunia88** [signalpoint/DrupalGap#595]
can i make menu on navigation region for certain page, maybe using block on navigation region?, i think i can make it using the same implementation on  primary_local_tasks: { } blok, but i am not understand it yet, is it posible?

**Comment by signalpoint** [comment]
@Sunia88 yes, block visibility rules and/or custom access callback should do the trick:
- http://drupalgap.org/node/168
- http://drupalgap.org/node/168#access_callback
