### ISSUE TITLE
Running ./drupalgap dl geofield results in error when installing on Mac OS

### ISSUE THREAD

**Issue by wildfeed** [signalpoint/DrupalGap#598]
Charless-MacBook-Pro:DrupalGap-7.x-2.x cnovick$ sudo ./drupalgap dl geofield
Password:
./drupalgap: line 149: cd: app/modules: No such file or directory
--2015-07-28 21:13:18--  https://github.com/signalpoint/geofield/archive/7.x-1.x-angular.zip
Resolving github.com... 192.30.252.131
Connecting to github.com|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/signalpoint/geofield/zip/7.x-1.x-angular [following]
--2015-07-28 21:13:18--  https://codeload.github.com/signalpoint/geofield/zip/7.x-1.x-angular
Resolving codeload.github.com... 192.30.252.147
Connecting to codeload.github.com|192.30.252.147|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-28 21:13:19 ERROR 404: Not Found.

unzip:  cannot find or open 7.x-1.x-angular, 7.x-1.x-angular.zip or 7.x-1.x-angular.ZIP.
rm: 7.x-1.x-angular: No such file or directory
mv: rename geofield-7.x-1.x-angular to geofield: No such file or directory
Downloaded geofield to app/modules/geofield
Charless-MacBook-Pro:DrupalGap-7.x-2.x cnovick$

**Comment by signalpoint** [comment]
@wildfeed upon closer inspection, I see that I forgot to push that branch for geofield. I've pushed it now, and if you try again it should work.

**Comment by wildfeed** [comment]
...and it does!

Thanks
