### ISSUE TITLE
What is DrupalGap/drupalgap/ ?

### ISSUE THREAD

**Issue by lefnire** [signalpoint/DrupalGap#6]
The README says to copy & edit `DrupalGap/pages/*` & `DrupalGap/services/*`. Just out of curiosity after playing with the codebase a bit- how can we (or _should_ we) utilize `DrupalGap/drupalgap`, and especially `DrupalGap/drupalgap/services/` in our projects?

**Comment by signalpoint** [comment]
I assume you are trying out the new 7.x-2.x branch.

The README should say to copy DrupalGap/pages/\* and DrupalGap/scripts/*
(not DrupalGap/services). Eventually the DrupalGap/drupalgap directory will
go away. I haven't evolved this branch enough yet to get rid of it, and to
tag it for a ready release.

So, really the directory is not needed in the 7.x-2.x branch, but for older
versions it is still needed.

On Tue, Jan 8, 2013 at 2:29 PM, Tyler Renelle notifications@github.comwrote:

> The README says to copy & edit DrupalGap/pages/\* & DrupalGap/services/_.
> Just out of curiosity after playing with the codebase a bit- how can we (or
> *should_ we) utilize DrupalGap/drupalgap, and especially
> DrupalGap/drupalgap/services/ in our projects?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/6.

## 

Regards,
Tyler Frankenstein

http://www.tylerfrankenstein.com

**Comment by lefnire** [comment]
Got it. Indeed using 7.x-2.x, so I'll ignore that directory then. Thanks!

On Tue, Jan 8, 2013 at 2:36 PM, Tyler Frankenstein <notifications@github.com

> wrote:
> 
> I assume you are trying out the new 7.x-2.x branch.
> 
> The README should say to copy DrupalGap/pages/\* and DrupalGap/scripts/*
> (not DrupalGap/services). Eventually the DrupalGap/drupalgap directory
> will
> go away. I haven't evolved this branch enough yet to get rid of it, and to
> tag it for a ready release.
> 
> So, really the directory is not needed in the 7.x-2.x branch, but for
> older
> versions it is still needed.
>

**Comment by signalpoint** [comment]
Cool, thanks for checking out the bleeding edge branch ;)

Please checkout the DrupalGap API (only compatable with the new 7.x-2.x branch) for more helpful information:

http://easystreet3.com/drupalgap-api

**Comment by signalpoint** [comment]
Removed the deprecated DrupalGap/drupalgap directory from the 7.x-2.x branch.
