### ISSUE TITLE
edit standar page drupalgap

### ISSUE THREAD

**Issue by Sunia88** [signalpoint/DrupalGap#600]
![issue2](https://cloud.githubusercontent.com/assets/11264819/9002212/be624876-3793-11e5-92e5-3c03d7fb4100.png)
can i change the basic node page on the sdk?, im trying to edit on src\modules\node\node.js to remove the "Create content" button, but when i run it on the emulator, it still appears

**Comment by signalpoint** [comment]
@Sunia88 you shouldn't hack DG core, but if you have to, you need to run the makefile to rebuild the src/ directory into the bin/drupalgap.js file. Otherwise you can alter existing pages: http://www.drupalgap.org/node/210
