### ISSUE TITLE
button in a menu region

### ISSUE THREAD

**Issue by bmason** [signalpoint/DrupalGap#602]
I am trying to create a menu item that behaves like a button:  execute some js when pressed

I tried

 {  title: 'English',
        path: '',
      options: {

```
    attributes: {
       'onclick': "Drupal.settings.language_default='th'; drupalgap_goto('hello_world', {reloadPage:true});",
      'class': 'ui-btn-right'
    }
  }
}
```

**Comment by signalpoint** [comment]
@bmason Try setting your onclick handler to just the name of a function:

`onclick: 'foo_bar();'`

Then add that function's implementation to your module's JS file, that should work.

**Comment by bmason** [comment]
Tyler

I could not get that to work.

my next harebrained scheme was to use a path with arguments:

```
{  title: 'English',
```

   path: 'set_language/und',
      options: {

```
    attributes: {
```

//       'onclick': "setLanguage();",
          'class': 'ui-btn-right'
        }
      }
    },

```
items['set_language'] = {
title: 'Fab Card',
page_callback: 'set_language'
```

  };

hoping the und would be treated as an argument to set_language

no luck so far  :(

On Sat, Aug 1, 2015 at 8:49 PM, Tyler Frankenstein <notifications@github.com

> wrote:
> 
> @bmason https://github.com/bmason Try setting your onclick handler to
> just the name of a function:
> 
> onclick: 'foo_bar();'
> 
> Then add that function's implementation to your module's JS file, that
> should work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/602#issuecomment-126917031
> .

## 

Brian Mason

m +66870633580

[image: logos.png] http://myally.asia

[image: italogo.jpg] http://itassociates.com

[image: Rodans.jpg] http://rationalisthuman.com

[image: linkedin.jpg] http://th.linkedin.com/pub/brian-mason/4/16b/151/

[image: fblogo.jpg] http://facebook.com/smalltalkman

[image: bmasonsm.jpg]

**Comment by signalpoint** [comment]
@bmason right click on your menu link when is rendered, then click "inspect element". What html is output for your button? Please share it here.

**Comment by bmason** [comment]
@tyler

I only run the app in debug mode on an Android device now.

I have not been able to migrate the menu back to the web.

I am ok with the current configuration.

On Mon, Aug 3, 2015 at 8:32 PM, Tyler Frankenstein <notifications@github.com

> wrote:
> 
> @bmason https://github.com/bmason right click on your menu link when is
> rendered, then click "inspect element". What html is output for your
> button? Please share it here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/signalpoint/DrupalGap/issues/602#issuecomment-127234317
> .

## 

Brian Mason

m +66870633580

[image: logos.png] http://myally.asia

[image: italogo.jpg] http://itassociates.com

[image: Rodans.jpg] http://rationalisthuman.com

[image: linkedin.jpg] http://th.linkedin.com/pub/brian-mason/4/16b/151/

[image: fblogo.jpg] http://facebook.com/smalltalkman

[image: bmasonsm.jpg]
