### ISSUE TITLE
auto apply filter on views exposed filter

### ISSUE THREAD

**Issue by stvx** [signalpoint/DrupalGap#603]
Does drupal gap currently support auto submit on views exposed filter?

**Comment by signalpoint** [comment]
@stvx I can't remember if I added that or not, if I did it should listen to the "auto submit" checkbox in your View's exposed filter settings.

**Comment by stvx** [comment]
Well seems like that feature is not supported yet

**Comment by signalpoint** [comment]
@stvx In the past I've used form alteration to attach event listeners to the inputs of an exposed filter form in the app, then when its value changes, simulate a click on the apply filters button (that I hide via css).

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
