### ISSUE TITLE
Contact Form: 401 - Not Authorized

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#604]
Contact Form is viewable for only user 1 on my drupalgap app.

Permissions are set for all users including anonymous to access Contact Form.

Contact form is visible on main website for all user roles.

Suggestions on what I may be missing?

Here is my code snipped in `drupalgap.settings.menus['main_menu']`

```
{
  title:'Contact',
  path:'contact',
  options:{
    attributes:{
      'data-icon':'info'
    }
  }
}
```

![image](https://cloud.githubusercontent.com/assets/13283396/9028822/f265edac-3942-11e5-895a-3c7e73aad7a7.png)

**Comment by signalpoint** [comment]
@mkinnan As long as they have this permission: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/contact/contact.js#L13

It should work. Try flushing Drupal's caches, and/or rebuilding the user permissions. If not, set debug to true in the settings.js file, and watch the console.log() output for more details.

Additionally use `console.log(Drupal.user);` to inspect the user account object, and verify that their correct roles and permissions are bundled within.

**Comment by mkinnan** [comment]
Cleared cache. Rebuilt permissions. Debug=true.

I don't see any error messages ...

Here's what I am seeing with console.log(Drupal.user);

![image](https://cloud.githubusercontent.com/assets/13283396/9075400/85c70420-3ad1-11e5-942d-20f6fe905078.png)

That's weird that UID = 0.

**Comment by mkinnan** [comment]
If I change the user's role to **administrator**, the user can access the form. Otherwise, user get's a 401. 

![image](https://cloud.githubusercontent.com/assets/13283396/9151489/67868e84-3dc1-11e5-8a9c-a22de0830dd4.png)

**Comment by mkinnan** [comment]
Fixed ... removed all user roles from contact form, saved, rechecked the boxes again, saved ... and it works now.
