### ISSUE TITLE
Help text for fields. 

### ISSUE THREAD

**Issue by stvx** [signalpoint/DrupalGap#605]
Hi, 
I wanted to create help texts in drupalgap for forms from the drupal website,  Is that possible?

**Comment by signalpoint** [comment]
@stvx Yes, use the `description` property on your form elements:

form.elements['foo'] = {
  type: 'textfield',
  title: 'Foo',
  description: 'Foo this, foo that'
};

**Comment by stvx** [comment]
Thanks, works like a charm.
