### ISSUE TITLE
What 'theme' to use for custom JSON pages?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#608]
I wrote a Drupal module that is on my main website. When you visit a specific URL, it outputs JSON data ... just like with JSON output from a view except for the last part of the JSON data with the 'view' information:

```
"view" : {
  "name" : "drupalgap_my_bookmarks",
  "display" : "default",
  "path" : "admin/structure/views/nojs/preview/drupalgap_my_bookmarks/default",
  "root" : "nodes",
  "child" : "node",
  "pages" : 2,
  "page" : 0,
  "count" : 36,
  "limit" : 25
}
```

In my drupalgap module, I have the following:

```
function my_module_customjson_page() {
  try {
    var content = {};
    content['my_customjson'] = {
      theme: 'view',
      format: 'ul',
      path: 'customjson', /* the path to the view in Drupal */
      row_callback: 'my_module_customjson_list_row',
      empty_callback: 'my_module_customjson_list_empty',
    };
    return content;
  }
  catch (error) { console.log('my_module_customjson_page - ' + error); }
}
```

In order for my custom JSON page to work in drupalgap, I have to add that JSON "view" information to the end of my JSON output for my custom page. Is this the right thing to do? Or do I need to change the `theme` to something else besides **view**

**Comment by signalpoint** [comment]
The `theme: 'view'` means use a Views Render Array, which only works with the Views datasource module, it does not work with custom page callbacks up on Drupal's side. You'll have to use a pageshow callback in your app, then make a custom call via $.ajax or http://www.drupalgap.org/node/154, then process your results and manually render the results and inject them into a page.
