### ISSUE TITLE
Back button on iOS

### ISSUE THREAD

**Issue by coolman7** [signalpoint/DrupalGap#613]
I tried to export one of my app that I designed for Android to iOS platform. I noticed that there are some problems:

1) Because there is no hardware back button on iOS devices, but android phones have back button, and designed the app for android, I realize I didn't put any back button on my app for iOS. 

What should I do? Should I put a back button on both android and iOS app? Or should I put back button only iOS? What is the common sense about this back button problem? 

2) My app tries to use all screen on iOS including notification bar. Look at the picture. How can I get rid of this problem?

Thanks

![ios-bestvoiprate2](https://cloud.githubusercontent.com/assets/11715129/9520650/a8931d42-4cd1-11e5-82e6-3a78a3a2c3f8.jpg)

**Comment by signalpoint** [comment]
@coolman7 I always design the app with a "soft" back button so it always shows up in the app (for both Android and iOS).

As for the iOS status bar, you'll need this plugin: http://devgirl.org/2014/07/31/phonegap-developers-guid/
