### ISSUE TITLE
views_litepager fails on views with 'display all items' in views module

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#615]
Should the following section of code:

```
if (
  (results.view.count == 0 && !views_litepager_present) ||
  (views_litepager_present && results.view.pages == null)
) {
```

be changed too ... adding the `!` to the 3rd line :

```
if (
  (results.view.count == 0 && !views_litepager_present) ||
  (views_litepager_present && !results.view.pages == null)
) {
```

Below are the views information ...    

A view with 'display all items':

```
"view" : {
  "name" : "subscriptions",
  "display" : "default",
  "path" : "admin/structure/views/nojs/preview/subscriptions/default",
  "root" : "nodes",
  "child" : "node",
  "pages" : null,
  "page" : null,
  "count" : 11,
  "limit" : null
}
```

A view with 'lite pager' enabled:

```
"view" : {
  "name" : "subscriptions",
  "display" : "default",
  "path" : "admin/structure/views/nojs/preview/subscriptions/default",
  "root" : "nodes",
  "child" : "node",
  "pages" : 1,
  "page" : 0,
  "count" : 0,
  "limit" : 0
}
```

And for comparison, a few with 'mini pager' enabled:

```
"view" : {
  "name" : "subscriptions",
  "display" : "default",
  "path" : "admin/structure/views/nojs/preview/subscriptions/default",
  "root" : "nodes",
  "child" : "node",
  "pages" : 2,
  "page" : 0,
  "count" : 11,
  "limit" : 10
}    
```

**Comment by signalpoint** [comment]
@mkinnan If you add that `!` to the condition in the `bin/drupalgap.js` file, does that fix it for you?

I'd have to dig in and test it again, but I recall having to check for that `null` because without it, it was crashing.

**Comment by mkinnan** [comment]
Adding the exclamation mark fixed all the views with 'display all items' ... all the views with lite_pager still work fine. I have been running the modification in my app for a week now with no issues ...

... except there is an issue (related? separate?) when a returned JSON view has 0 rows ... the _list_empty function is not called and I get a blank area instead of my empty function text.

**Comment by signalpoint** [comment]
@mkinnan If you disable/uninstall the views lite pager module, is the `pages` value still `null` for the "display all items" Views JSON?

**Comment by mkinnan** [comment]
The pages are still `null` when the lite pager module is disabled in the main drupal website.

**Comment by mkinnan** [comment]
Finally got things figured out and resolved all my issues:

```
  (results.view.count == 0 && !views_litepager_present) ||
  (views_litepager_present && results.view.pages == null && results.view.count == 0 )
```

**Comment by tolesolo** [comment]
@mkinnan I was spend 2 days, why when I use litepager (with only 3 content only), the page is showing no result error (empty array)
yes, thank you, your solution fixed that

**Comment by mkinnan** [comment]
@tolesolo Glad the solution worked for you too!

**Comment by signalpoint** [comment]
Thanks @mkinnan and @tolesolo I shall take your word for it, I've committed it to core. FYI, if either of you are interested in implementing the `@TODO`s mentioned in the above commit, that'd be awesome.
