### ISSUE TITLE
How to (exposed) filter in custom views?

### ISSUE THREAD

**Issue by coolman7** [signalpoint/DrupalGap#616]
Views Exposed Filters explained this page:
http://drupalgap.org/node/498

And this page says: 
Please note, the Views Exposed Filters in DrupalGap is designed to work in conjunction with Views Render Arrays (it's of course possible to build your own forms and construct your own URL parameters to filter your Views, this feature is meant to simplify that entire process in a dynamic way).

But I don't use Views Render Arrays. So how can I use exposed filters? Is there any small example snippet to start working?

Currently I'm using image format and I use a custom list_row function to display the results.

Thanks

```
function my_module_devices_page() {
  try {
    var content = {};
    content['devices'] = {
      theme: 'view',
      pager_pos: 'bottom',
      format: 'image',
      path: 'mobile/devices',
      row_callback: 'my_module_devices_list_row',
      empty_callback: 'my_module_devices_list_empty',
      attributes: {
        id: 'my_module_devices'
      }
    };
    return content;
  } catch (error) { console.log('my_module_devices_page - ' + error); }
}
```

**Comment by signalpoint** [comment]
@coolman7  If you're using `theme: 'view',`, then you're using a Views Render Array. So your code above, is definitely a Views Render Array. The link you mentioned above is the most up to date documentation for exposing filters in DrupalGap. If the filter isn't working, then chances are DrupalGap doesn't support it yet. If you set `debug` to `true` in the `settings.js` file, then watch your browser's JS console log message, DG will inform you of any unsupported exposed filters you are trying to use.

**Comment by coolman7** [comment]
I just want to filter by taxonomy term list. Here is the console log:

```
drupalgap_region_render_zone - TypeError: Cannot read property '_prefix' of undefined
drupalgap-7.x-1.2.min.js:157 _drupalgap_region_render_zone - TypeError: Cannot read property '_suffix' of undefined
jdrupal-7.x-1.3.min.js:30 GET: http://.../?q=mobile/devices&page=0
jdrupal-7.x-1.3.min.js:31 200 - OK
jdrupal-7.x-1.3.min.js:30 GET: http://.../?q=mobile/devices&&page=0
jdrupal-7.x-1.3.min.js:31 200 - OK
jdrupal-7.x-1.3.min.js:30 GET: http://.../?q=mobile/devices&&&page=0
jdrupal-7.x-1.3.min.js:31 200 - OK
jdrupal-7.x-1.3.min.js:30 GET: http://.../?q=mobile/devices&&page=0
jdrupal-7.x-1.3.min.js:31 200 - OK
jdrupal-7.x-1.3.min.js:30 GET: http://.../?q=mobile/devices&&&page=0
jdrupal-7.x-1.3.min.js:31 200 - OK
```

**Comment by coolman7** [comment]
By the way, I'm using SDK version 7.x-1.1. Should I use latest snapshot of SDK?

**Comment by signalpoint** [comment]
@coolman7 7.x-1.1 should have support for taxonomy term list exposed filters, you could try 7.x-1.2 though, or the latest dev snapshot. I have a client whose app uses taxonomy term reference exposed filter on a listing of nodes.

**Comment by coolman7** [comment]
I could not make it. So I decided to implement it in a different way. I created a "Filter" page which is a form and includes all filters as select lists. But in this case I need to hide "Apply Filters" button at the views page. How can I hide this button?

**Comment by signalpoint** [comment]
@coolman7 You could just use CSS to set a `display: none;` on it. Otherwise a `hook_form_alter()` may be able to remove the submit button. Use `dpm(form);` in `hook_form_alter()` to inspect what alterations will be available.

**Comment by coolman7** [comment]
@signalpoint CSS solution seems to be simpler. Which CSS item should I set a `display: none;` ?
Thanks

**Comment by signalpoint** [comment]
@coolman7 use your html inspector in your browser's development tools to identify the appropriate css selector. This is CSS 101, and you should have that complete before building html5 mobile apps ;)

**Comment by coolman7** [comment]
I didn't realize I can inspect the code generated by web-app by browser's inspector tool until you mentioned that in this post. I tried to debug with ripple half an hour and had no result. Such a waste of time. I can identified in a few minutes with this method. So I added this code module's css file and Apply filters button removed.
Thanks

```
#edit-views-exposed-form-submit {
  display: none;
}
```

**Comment by signalpoint** [comment]
@coolman7 Excellent, that is good news. I remember my excitement the first time I saw Ripple, and new about the html inspector, great stuff indeed. I actually don't even use Ripple much any more, it seems faster just use web-app mode with Ripple disabled (i.e. just open it in any browser).
