### ISSUE TITLE
Checking for body

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#62]
In modules/services/node.js ...

``` Javascript
if (node.body.length != 0) {
  node.content = node.body[node.language][0].safe_value;
}
```

will fail if your node does not have a Body. Something like ...

``` Javascript
function isEmpty(value) {
  return (typeof value === "undefined" || value === null || value == '');
}
```

could be used to test for empty instead, maybe. I know, thedailywtf.com material for sure, but testing for empty in javascript is a pain! Happy to make a pull request if you agree. This one might be more of an issue with Drupal 7 since Body is optional.

**Comment by signalpoint** [comment]
I agree. This will be a good function to have around. I'd also recommend (if it doesn't already) to make isEmpty() return true if you pass it an empty array. Thanks again for the pull request offer, looking forward to it!
