### ISSUE TITLE
Log out of app not working correctly

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#621]
I did a series of tests ensuring to clear all cache each time:
Drupalgap module 7.x-1.13
Drupalgap Dev Kits  7.x-1.1 and 7.x-1.2

With dev kit 1.1, the logging in and out work just fine. When I use 1.2, logging in and logging out isn't working right.

When you first log in, the loading comes up:

![login1](https://cloud.githubusercontent.com/assets/13283396/9648380/4bbea0e0-51a5-11e5-82a1-6b7bccf26b87.png)

then the loading goes away (v 1.1 and v 1.2) and comes back, but the 'LOGIN' header is now gone with v 1.2:

![login2](https://cloud.githubusercontent.com/assets/13283396/9648385/5975fe72-51a5-11e5-997b-efb58a4ca9ba.png)

Then after logging out, the user menu still shows user is logged in with v 1.2:

![logout1](https://cloud.githubusercontent.com/assets/13283396/9648390/60f935ba-51a5-11e5-8e1f-bf8d2264e3a4.png)

Then when you click on main menu, you get error:

![logout2](https://cloud.githubusercontent.com/assets/13283396/9648423/a7e4f144-51a5-11e5-8a69-002e78112d3d.png)

**Comment by mkinnan** [comment]
Did another test ... the 1.1 dev kit with the latest drupalgap.js file DOES NOT WORK.

**Comment by mkinnan** [comment]
Updated previous comment because I forgot to enable drupalgap.js file in index.html.

To confirm, enabling the latest drupalgap.js file causes the issue outlined in the first post.

**Comment by signalpoint** [comment]
@mkinnan I've just tested login/logout with the latest `bin/drupalgap.js` file, and everything is working fine. The logout mechanism in jDrupal has not been changed for a very long time: https://github.com/easystreet3/jDrupal/commits/7.x-1.x/src/services/services.user.js

Similarly the logout mechanism in DrupalGap doesn't appear to have been touched since October of last year. I'd recommend setting `debug` to `true` in the settings.js file, and watching the javascript console log (and the network tab) in your browser's development tools. That should yield some information about what is going on during the server calls for login/logout. This sounds like an issue with session authentication up on Drupal's side, or possibly with your host.

**Comment by signalpoint** [comment]
@mkinnan P.S. Be careful when using your Drupal site and developing the app in the same browser, they both share the same cookies, so if you login/logout with one, the other can become confused unless they are restarted.

**Comment by mkinnan** [comment]
Regardless of enabling drupalgap.js, I am seeing the issue going from dev kit 1.1 to 1.2.

If I take dev kit 1.1 and test login/logout, everything works great. If I use the drupalgap-7.x-1.2.js file from dev kit 1.2 with dev kit 1.1 (enabling in index.html), then I get the logout issues described above.

There are no error messages in console log.

I only use Chrome+Ripple for app development. Firefox for website development.

Where else can I look to debug what ever is going on?

**Comment by mkinnan** [comment]
I set up a new Drupal installation at a new domain with only the modules required to get drupalgap working. I then used the drupalgap configuration (admin/config/services/drupalgap) to install the dev kit. It installed version 1.2. I am still seeing the logging in/out issue above.

**Comment by mkinnan** [comment]
Please verify these are the issues I think I tracked down:

(1) The issue with the LOGIN bar disappearing is a result of going from **jquery.mobile-1.4.2.min.js** to **jquery.mobile-1.4.5.min.js**.

(2) The issue with logging out seems to be the result of the function `drupalgap_remove_page_from_dom`. If I take **drupalgap-7.x-1.2.js** (which has the logout issue) and replace with the `drupalgap_remove_page_from_dom` function code in **1.2** with that from **1.1**, logging out works fine.

**Comment by mkinnan** [comment]
I forgot to mention that there are 2 functions with the same **drupalgap_remove_page_from_dom** name in **bin/drupalgap.js**. I am referring to the 2 function in my previous comment:

Function 1

```
function drupalgap_remove_page_from_dom(page_id) {
  try {
    $('#' + page_id).empty().remove();
  }
  catch (error) { console.log('drupalgap_remove_page_from_dom - ' + error); }
}
```

Function 2

```
function drupalgap_remove_page_from_dom(page_id) {
  try {
    var current_page_id = null;
    if (typeof arguments[2] !== 'undefined') { current_page_id = arguments[2]; }
    else { current_page_id = drupalgap_get_page_id(drupalgap_path_get()); }
    var options = {};
    if (typeof arguments[1] !== 'undefined') { options = arguments[1]; }
    if (current_page_id != page_id || options.force) {
      $('#' + page_id).empty().remove();
      delete drupalgap.pages[page_id];
      // We'll remove the query string, unless we were instructed to leave it.
      if (
        typeof _dg_GET[page_id] !== 'undefined' &&
        (typeof options.leaveQuery === 'undefined' || !options.leaveQuery)
      ) { delete _dg_GET[page_id]; }
    }
    else {
      console.log('WARNING: drupalgap_remove_page_from_dom() - not removing ' +
        'the current page (' + page_id + ') from the DOM!');
    }
  }
  catch (error) { console.log('drupalgap_remove_page_from_dom - ' + error); }
}
```

**Comment by mkinnan** [comment]
I am still having issues with the `drupalgap_remove_page_from_dom` function. In the latest dev version of **drupalgap.js**, it seems the logout issue I was having above is working fine. But reloading my homepage is not. I have a function to display different content to to anonymous users vs authenticated users. I use an `if (Drupal.user.uid == 0) {} else {}`. When the user logs in, it still shows the anonymous user content. I have to click the home page menu link again and then it shows the authenticated user content. So, copying the `drupalgap_remove_page_from_dom` from the older .js file solves the problem.

My guess is there is something else that is the culprit and not necessarily the `drupalgap_remove_page_from_dom`. But changing out that function solves the issue, so that is what I am going with for now.

**Comment by mkinnan** [comment]
I had reloadPage: true set in my slide menu link block, but I had to add it to the hook_menu item instead. Now everything seems to work fine.

**Comment by jomarocas** [comment]
this is update in version of drupalgap?

**Comment by jomarocas** [comment]
or how can apply all related for a simply patch for try, i have same problem

**Comment by mkinnan** [comment]
@jomarocas ... did you try downloading the latest development version of the Drupalgap SDK?

**Comment by jomarocas** [comment]
@mkinnan thanks, sorry i dont see the latest version, i see is update, thanks

**Comment by mkinnan** [comment]
https://github.com/signalpoint/DrupalGap/archive/7.x-1.x.zip
