### ISSUE TITLE
How to execute code after Loading screen?

### ISSUE THREAD

**Issue by coolman7** [signalpoint/DrupalGap#622]
I want to execute a code once every time app starts. I tried to put that code to deviceready eventlistener but it is too early. Drupal user is not logged in at that moment. 

I want to execute that code after Loading splash disappears. Which hook or eventlistener should I implement?

Thanks

**Comment by signalpoint** [comment]
I'd recommend adding a `pageshow` handler to your app's front page, that'll allow you to execute code after the app's front screen is shown. More info: http://www.drupalgap.org/node/154
