### ISSUE TITLE
hardware back button while on splash screen results in WSOD

### ISSUE THREAD

**Issue by coolman7** [signalpoint/DrupalGap#624]
Is it possible to add 3rd line to drupalgap_back() function? Without this line, if a user presses hardware back button while in splash screen, application drops to a white screen shows a message like this:
{header}{content}{footer}

```
function drupalgap_back() {
  try {
    if ($('.ui-page-active').attr('id') == '_drupalgap_splash') return;
...
}
```

PS: I didn't want to deal with git repository for just 1 line of code. :)
Thanks

**Comment by signalpoint** [comment]
@coolman7 Thanks, I've added this to core.
