### ISSUE TITLE
drupalgap phonegap stuck on splash screen

### ISSUE THREAD

**Issue by weiChiang** [signalpoint/DrupalGap#630]
I have read all the issues and answers of topics related to this problem that I can find, but none of them helps.

My setups are as follows:
Drupal: 7.39, 2015-08-19
drupalgap: 7.x-1.13+6-dev
cordova: 5.3.1

The outcomes are:
.../mobile-application in web-app mode runs on desktop chrome.
.../mobile-application in phonegap mode runs on desktop chrome only when ripple is enabled.
web-app mode apk works on Android mobile.
phonegap mode apk hangs on the splash page.

I have also copied config.xml to the Android www directory, but it makes no differences.

Any help will be greatly appreciated.   Thanks.

**Comment by signalpoint** [comment]
@weiChiang Try using the contents of `cordova.index.html` for your `index.html` file. You may or may not need to add the inclusion of the `cordova.js` file in your `index.html` file, and you may or may not have to copy the platform's `cordova.js` file into your app's `www` directory. Also set the mode in `settings.js` to `phonegap`. All of this is covered here: http://drupalgap.org/node/193

**Comment by weiChiang** [comment]
Thanks for your response,  Tyler.

I have cordova.js line inserted at the end of the body section of the index.html.
Whether cordova.js is in the www directory or not, it makes no differences.
setting.js is set to phonegap for the mobile App;  when it is set to web-app, all works OK.

My drupal site uses https, I wonder if this would cause any trouble.

**Comment by signalpoint** [comment]
@weiChiang No, the https should be fine. Check out how to use `adb shell logcat | grep 'Web Console'` to see the console log in a compiled application, that will provide more information: http://drupalgap.org/debug

**Comment by weiChiang** [comment]
Running it on an emulator and I saw the message:
Connection to the server unsuccessful (file:///android_asset/www/index.html)

In my index.html file, it loads the google map api script.

This page, http://stackoverflow.com/questions/15535382/application-error-is-a-directory-file-android-asset-www-index-html,  provides a number of solutions.  The one that works for me is by replacing the index.html file with a dummy one which loads main.html and renames the original index.html to main.html

Thanks for your pointers, Tyler.

**Comment by signalpoint** [comment]
Stuck on the splash screen when compiling an app? Just a reminder to get this into your `index.html` file:

```
<!-- Load PhoneGap (Cordova) -->
<script type="text/javascript" src="cordova.js"></script>
```

I just wasted a few hours on this, and I'm the creator of DrupalGap, doh!
