### ISSUE TITLE
Views Exposed Filter List Sorting

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#631]
The first time the exposed filter list is presented to the user, it is in reverse (Z-A) sort. After a user clicks a term and the view updates, the sort list is no longer sorted and becomes random. Console log still shows the terms in order, reverse order though. Where would I look to debug?

**Comment by signalpoint** [comment]
@mkinnan The views_exposed_form() function controls how it is built:

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/views/views.js#L110

Essentially it calls functions with a name like `[module-name]_views_exposed_filter()` to handle the assembly of each field/filter that is being exposed. Search for `_views_exposed_filter()` on the API to see example implementors, and to find the one that is currently in charge of your filter(s).

http://api.drupalgap.org/

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
