### ISSUE TITLE
external link need support

### ISSUE THREAD

**Issue by tolesolo** [signalpoint/DrupalGap#632]
```
content.callcenter = {
  theme: 'button_link',
  text: 'Call Center 08.1234.1234.1234',
  path: 'tel:+618123412341234',
  attributes: {
    'data-icon': 'phone'
  },
  options: {InAppBrowser: true}
};
```

when i use this button (external link), it's open default browser first and then open call dialer.

How to make that link to open direct to call dialer without open the browser first?

Is there a way to support link tag like tel or emailto in the button's path?

NB: tried internal link too

**Comment by signalpoint** [comment]
@tolesolo Try this instead:

```
content.callcenter = {
  theme: 'button_link',
  text: 'Call Center 08.1234.1234.1234',
  path: null,
  attributes: {
    'data-icon': 'phone',
    href: 'tel:+618123412341234'
  }
};
```

This is borrowed from the DrupalGap Telephone module's telephone_field_formmater_view() function: https://github.com/signalpoint/telephone/blob/7.x-1.x/telephone.js

**Comment by tolesolo** [comment]
@signalpoint thanks, its work, i think this will work with other link tag too, like mailto:, sms: market:
