### ISSUE TITLE
Directory where Application kit is installed

### ISSUE THREAD

**Issue by weiChiang** [signalpoint/DrupalGap#633]
If the user chooses a name other than "mobile-application" when installing the application kit (via the link Web Wervices ---> DrupalGap),  the application kit will be installed successfully but the widget to install DrupalGap module disappears.

I suggest to change the following line in in the drupalgap_sdk_form () 
      `if (file_exists('mobile-application')) {`
      to
     `if (file_exists($dir)) {`

as show in the following snippet.  This way the user can name the directory differently.

```
function drupalgap_sdk_form($form, &$form_state) {
  global $base_url;

  // Check installation status.
  $installed = variable_get('drupalgap_sdk_installed', 0);
  $dir = variable_get('drupalgap_sdk_dir', 'mobile-application');
  if (!$installed) {
    // Many existing sites will already have the mobile-application directory in
    // use, let's auto detect that.
    ////if (file_exists('mobile-application')) {
    if (file_exists($dir)) {
```

**Comment by signalpoint** [comment]
@weiChiang Thanks for pointing this out, I've updated the code (and in one extra spot): http://cgit.drupalcode.org/drupalgap/commit/?id=db63e68
