### ISSUE TITLE
error when user login

### ISSUE THREAD

**Issue by tolesolo** [signalpoint/DrupalGap#634]
I got this warning error in my drupal's logs
![error](https://cloud.githubusercontent.com/assets/14232358/10058652/d7ab7822-6270-11e5-87f4-48deb7e256d8.png)

and this is the line rdf_mapping
![error2](https://cloud.githubusercontent.com/assets/14232358/10058766/5e8d4690-6271-11e5-8f06-2f945d17561f.png)

I don't know why and when this error appear. but I think unset is not working.

**Comment by signalpoint** [comment]
@tolesolo Thanks for pointing this out, I've updated the drupalgap.module file to accommodate this: http://cgit.drupalcode.org/drupalgap/commit/?id=3c9466e

Download the latest dev snapshot of the drupalgap module for the fix.

**Comment by signalpoint** [comment]
@tolesolo Actually this commit will probably fix yours: http://cgit.drupalcode.org/drupalgap/commit/?id=30d126d

Either way, download the latest dev snapshot of the drupalgap module.
