### ISSUE TITLE
Json response string being truncated

### ISSUE THREAD

**Issue by weiChiang** [signalpoint/DrupalGap#635]
The json response string get truncated with "cordova run"  command (as well as Android Studio run); but it is OK using Ripple.  Are there any configuration parameters to be set up to prevent the truncation under cordova?

Thanks.

**Comment by signalpoint** [comment]
@weiChiang I don't understand, please elaborate. i.e. what json response string? Is this for DrupalGap 7.x-1.x?

**Comment by weiChiang** [comment]
Sorry being so terse.

I'm using 
cordova 5.3.1

**Comment by weiChiang** [comment]
Sorry being so terse.

I'm using cordova 5.3.1 and drupalgap 7.x-1.13+8-dev (2015-Sep-24)
The original index file is renamed as main.html; and it is replaced with the following code snippet:

```
    <script>
        window.location='./main.html';
    </script>
```

Instead of getting the front page as shown below under ripple, I got a white screen when using cordova to build and run.
![screen shot 2015-09-25 at 10 17 02 am](https://cloud.githubusercontent.com/assets/6695439/10090147/1a0a5cf2-636f-11e5-853e-3081cbcd44f8.png)

I have put some logs in jdrupal.js.  Below is part of the output.  Not sure if the truncate happened at the server side or the client side. 

I don't know any android development tool that can set breakpoints in the javascript files to ease the debugging process.  Any pointers are very much appreciated.  Thanks.

# 

09-24 20:44:10.684 1030-1030/com.example I/chromium: [INFO:CONSOLE(267)] "app/modules/pathfix/pathfix.js", source: file:///android_asset/www/jdrupal-7.x-1.3.js (267)
09-24 20:44:10.864 1030-1030/com.example I/chromium: [INFO:CONSOLE(16)] "themes/easystreet3/easystreet3.js", source: file:///android_asset/www/bin/drupalgap-7.x-1.2.min.js (16)
09-24 20:44:11.344 1030-1076/com.example I/X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-24 20:44:12.114 1030-1030/com.example I/chromium: [INFO:CONSOLE(1215)] "POST: https://192.168.0.17/nippy/?q=drupalgap/system/connect.json", source: file:///android_asset/www/jdrupal-7.x-1.3.js (1215)
09-24 20:44:12.384 1030-1030/com.example I/chromium: [INFO:CONSOLE(1226)] "200 - OK", source: file:///android_asset/www/jdrupal-7.x-1.3.js (1226)
09-24 20:44:12.384 1030-1030/com.example I/chromium: [INFO:CONSOLE(1235)] "responseText length = 42212", source: file:///android_asset/www/jdrupal-7.x-1.3.js (1235)
09-24 20:44:12.444 1030-1030/com.example D/dalvikvm: GC_FOR_ALLOC freed 198K, 12% free 4334K/4888K, paused 55ms, total 59ms
09-24 20:44:12.464 1030-1030/com.example I/chromium: [INFO:CONSOLE(1236)] "responseText = {"sessid":"8NFqQ_ZxrV3WmOWS_RGPznuIS0gejTinnJSNK0eYjVY","session_name":"SSESS79ab384034baf70d2d3ad4fca6c1e2fe","user":{"uid":0,"hostname":"192.168.0.17","roles":{"1":"anonymous user"},"cache":0,"timestamp":1443141852},"remote_addr":"192.168.0.17","date_formats":{"short":{"Y-m-d H:i":{"type":"short","format":"Y-m-d H:i","locales":[],"locked":"1","is_new":false,"dfid":"1","language":null},"m/d/Y - H:i":{"type":"short","format":"m/d/Y - H:i","locales":["en-us"],"locked":"1","is_new":false,"dfid":"2","language":null},"d/m/Y - H:i":{"type":"short","format":"d/m/Y - H:i","locales":["en-gb","en-hk","en-ie","el-gr","es-es","fr-be","fr-fr","fr-lu","it-it","nl-be","pt-pt"],"locked":"1","is_new":false,"dfid":"3","language":null},"Y/m/d - H:i":{"type":"short","format":"Y/m/d - H:i","locales":["en-ca","fr-ca","no-no","sv-se"],"locked":"1","is_new":false,"dfid":"4","language":null},"d.m.Y - H:i":{"type":"short","format":"d.m.Y - H:i","locales":["de-ch","de-de","de-lu","fi-fi","fr-ch","is-is","pl-pl","ro-ro","ru-ru"],"locked":"1","is_new":false,"dfid":"5","language":null},"m/d/Y - g:ia":{"type":"short","format":"m/d/Y - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"6","language":null},"d/m/Y - g:ia":{"type":"short","format":"d/m/Y - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"7","language":null},"Y/m/d - g:ia":{"type":"short","format":"Y/m/d - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"8","language":null},"M j Y - H:i":{"type":"short","format":"M j Y - H:i","locales":[],"locked":"1","is_new":false,"dfid":"9","language":null},"j M Y - H:i":{"type":"short","format":"j M Y - H:i","locales":[],"locked":"1","is_new":false,"dfid":"10","language":null},"Y M j - H:i":{"type":"short","format":"Y M j - H:i","locales":[],"locked":"1","is_new":false,"dfid":"11","language":null},"M j Y - g:ia":{"type":"short","format":"M j Y - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"12","language":null},"j M Y - g:ia":{"type":"short","format":"j M Y - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"13","language":null},"Y M j - g:ia":{"type":"short","format":"Y M j - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"14","language":null}},"medium":{"D, Y-m-d H:i":{"type":"medium","format":"D, Y-m-d H:i","locales":[],"locked":"1","is_new":false,"dfid":"15","language":null},"D, m/d/Y - H:i":{"type":"medium","format":"D, m/d/Y - H:i","locales":["en-us"],"locked":"1","is_new":false,"dfid":"16","language":null},"D, d/m/Y - H:i":{"type":"medium","format":"D, d/m/Y - H:i","locales":["en-gb","en-hk","en-ie","el-gr","es-es","fr-be","fr-fr","fr-lu","it-it","nl-be","pt-pt"],"locked":"1","is_new":false,"dfid":"17","language":null},"D, Y/m/d - H:i":{"type":"medium","format":"D, Y/m/d - H:i","locales":["en-ca","fr-ca","no-no","sv-se"],"locked":"1","is_new":false,"dfid":"18","language":null},"F j, Y - H:i":{"type":"medium","format":"F j, Y - H:i","locales":[],"locked":"1","is_new":false,"dfid":"19","language":null},"j F, Y - H:i":{"type":"medium","format":"j F, Y - H:i","locales":[],"locked":"1","is_new":false,"dfid":"20","language":null},"Y, F j - H:i":{"type":"medium","format":"Y, F j - H:i","locales":[],"locked":"1","is_new":false,"dfid":"21","language":null},"D, m/d/Y - g:ia":{"type":"medium","format":"D, m/d/Y - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"22","language":null},"D, d/m/Y - g:ia":{"type":"medium","format":"D, d/m/Y - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"23","language":null},"D, Y/m/d - g:ia":{"type":"medium","format":"D, Y/m/d - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"24","language":null},"F j, Y - g:ia":{"type":"medium","format":"F j, Y - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"25","language":null},"j F Y - g:ia":{"type":"medium","format":"j F Y - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"26","language":null},"Y, F j - g:ia":{"type":"medium","format":"Y, F j - g:ia","locales":[],"locked":"1","is_new":false,"dfid":"27","language":null},"j. F Y - G:i":{"type":"medium"

09-24 20:44:12.504 1030-1030/com.example I/chromium: [INFO:CONSOLE(1238)] "result = undefined", source: file:///android_asset/www/jdrupal-7.x-1.3.js (1238)

**Comment by signalpoint** [comment]
@weiChiang I would not recommend navigating away from index.html, DrupalGap has never been tested outside of that. Why are you using main.thml?

**Comment by weiChiang** [comment]
Thanks for you response.  It was done that way because of the connection
problem per issue #630.

**Comment by weiChiang** [comment]
I downgraded cordova to 5.1.1 and used min version of javascripts in the index.html file.  The connection and the above mentioned problems disappeared.
