### ISSUE TITLE
yesterday & today cann't compile

### ISSUE THREAD

**Issue by tolesolo** [signalpoint/DrupalGap#636]
Hi Tyler,

Thank you for the last commit of drupalgap module. Its work perfectly.

I had another issued.
It was started since yesterday, but the day before yesterday & a week ago was worked fine

This is the screenshot result using adobe today
![error3](https://cloud.githubusercontent.com/assets/14232358/10085654/8fe2335e-6334-11e5-8253-eea1048b7b44.png)

and I see the log, there is an error while compiling plugin inappbrowser 
![error4](https://cloud.githubusercontent.com/assets/14232358/10085655/8fec7670-6334-11e5-891c-5fb920a85325.png)

but i see the api's cordova.inappbrowser nothing change since a long time.

why this happen yesterday only and not before.

Thank you

NB: I use this gap:plugin name="org.apache.cordova.inappbrowser"  at my config.xml

but if I use this gap:plugin name="org.apache.cordova.inappbrowser" source="npm" , compiling no error, but I'm not sure that plugin was installed.

**Comment by signalpoint** [comment]
@tolesolo I wouldn't consider this a DrupalGap issue, as this is a "level up" the stack in PhoneGap land. You can verify the inappbrowser is working properly by creating a link like this: http://drupalgap.org/node/524

**Comment by tolesolo** [comment]
@signalpoint yes tyler, i'm sorry, that was changed version phonegap from cli-5-1-1 to cli-5-2-0, so some of the plugins were not supported yet at that moment (23 september). After patient a little while, the compiler is working again.
