### ISSUE TITLE
Visit previous page - no go

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#64]
So, if you view a content list, click on a node, hit back button and then try to re-visit that node ... nothing happens. You can view nodes once, not twice. I tested with the default easystreet3 theme along with my custom one.

**Comment by signalpoint** [comment]
This commit (https://github.com/signalpoint/DrupalGap/commit/2e6b120857636e7c4888514ab9c6fb560782dd0c) adds an event listener to the back button via PhoneGap. This issue is now resolved.
