### ISSUE TITLE
App restarts in iOS when switching to a different app and going back

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#640]
I have links in my app that open in a browser window. After clicking a link (which opens a browser), I go back to the app and upon doing so my app restarts. This only happens with iOS ... not Andriod. Are there any ways to fix this?

**Comment by signalpoint** [comment]
@mkinnan Have you tried the system browser? http://drupalgap.org/node/524

**Comment by mkinnan** [comment]
I am currently using the system browser to open links as described in the link. 

When I am in my app, I will click a link that takes me to the system browser and opens the link. When I am done reading the info at the link, I go back to the app and continue where I left off in the app. This is how it works when the app is run on Andriod. 

On iOS, clicking a link in my app and having it open in the system browser works just fine. The problem is that when I go back to my app, the app restarts and goes back to the homepage of my app. Thus losing the place where I left off in the app. 

----- Original Message -----

**Comment by mkinnan** [comment]
I use configap to build my config.xml ... and I use Adobe Phonegap Build for compiling my Andriod, iOS, and Windows apps.

In the configap program, you need to uncheck the 'Exit on Suspend' box ... see image below. Thus, in the config.xml file, that parameter should be set to false ... fixing my problem.

`<preference name="exit-on-suspend" value="false" />`

![capture](https://cloud.githubusercontent.com/assets/13283396/10235891/acf5623a-685d-11e5-9573-0d221db44d79.PNG)
