### ISSUE TITLE
Menu Buttons Acting Strange in iOS

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#642]
When I touch the top buttons (see pic below) in my app in iOS, the menus comes up and quickly disappear. Then when I touch it again it stays up. Has anyone else had this happen in iOS?

![capture1](https://cloud.githubusercontent.com/assets/13283396/10260501/d7298d2a-6933-11e5-8837-e5ef90ca4fb7.PNG)

**Comment by signalpoint** [comment]
@mkinnan Are you using popup menus? http://drupalgap.org/node/264

Or slide menus? http://www.drupalgap.org/node/530

Although the popup menu is the default style that comes with DrupalGap, I'm pretty much deprecating their usage in all apps I work on these days. Instead I prefer the slide menus, and will be releasing future versions with that as the default menu style.

**Comment by mkinnan** [comment]
Slide menus appear to work just fine in iOS compared to the popup menu. Since you are deprecating popup menus, then I would consider this to be closed.
