### ISSUE TITLE
how to dynamically populate select list in a form

### ISSUE THREAD

**Issue by days4** [signalpoint/DrupalGap#647]
hello,
i am making a custom form where i want to populate a select list option's based on a custom service call. In dupalgap how i can do that. Also how can i access my form based on link formats like this-

```
myform/%/add/%
```

thanks

**Comment by signalpoint** [comment]
To populate the select list dynamically:
- leave the select list options empty in your form builder function
- attach a `pageshow` handler to the `hook_menu` item that displays your form
- in the `pageshow` implementation, make the custom service call to Drupal: http://www.drupalgap.org/node/187
- in the success callback for the call to Drupal, iterate over the results and append them to the empty select list using jQuery and jQuery Mobile APIs.

As for `myform/%/add/%` path with arguments, there is a bug in DG core that doesn't process the args properly. The workaround is to always place your arg placeholders at the end of the path in your `hook_menu` item, like so:

`myform/add/%/%`
