### ISSUE TITLE
Drupal.services.call - error - TypeError: Cannot read property 'toUpperCase' of undefined 

### ISSUE THREAD

**Issue by gireeshscs** [signalpoint/DrupalGap#658]
i am getting an error while submitting form values to drupalgap custom service call

**Comment by signalpoint** [comment]
@gireeshscs That means you are trying to call `toUpperCase` in JavaScript on a variable that is undefined.

**Comment by gireeshscs** [comment]
Hi Tyler,

Thank you for your response. I am not calling any toUpperCase in javascript.
I am using below method 

  Drupal.services.call(fname, lname, email, phone, city, state,{
    method: 'POST',
    path: 'person_dg_resources/addperson.json',
    success: function(result) {
      alert(result);
    }
});

when i click on submit button i am getting 
Drupal.services.call - error - TypeError: Cannot read property 'toUpperCase' of undefined

errorin console

can you tell why this error is coming.

Thanks,
Gireesh
