### ISSUE TITLE
login session not persisting

### ISSUE THREAD

**Issue by gireeshscs** [signalpoint/DrupalGap#663]
Hi There,

I am facing an issue with login session, Logging is happening through drupalgap logintoboggan. But Drupal.user.name getting undefined value. The drupalgap site_path using basic drupal site(https) having  initial login and subsequent login for accessing the site. could you please suggest any solution for this.

Thanks in advance,
Gireesh

**Comment by signalpoint** [comment]
@gireeshscs Try this:

```
ini_set('session.cookie_lifetime',  2000000);
```

Sorry for the late reply. More info here: https://www.drupal.org/node/590832

**Comment by gireeshscs** [comment]
Hi Frank,

Thank you for your reply. i have already resolved the issue.

Thanks,
Gireesh

**Comment by signalpoint** [comment]
@gireeshscs Thank you for the follow up. Out of curiosity, how did you solve the issue?

**Comment by gireeshscs** [comment]
Issue related to my drupalgap service functionality. I have enabled the session from the service set up.
