### ISSUE TITLE
image upload issue

### ISSUE THREAD

**Issue by gireeshscs** [signalpoint/DrupalGap#665]
Hi

I am using a custom drupalgap form with file field ,and i am saving image to public pathuing file_save.
Images are uploading but when taken in browser it got corrupted.can you help me to resolve this issue. I am pasting code here.

```
 var file = $("input[type=file]")[0].files[0]; 
      //alert(file.name);
     // exit;
    alert(form_state.values['image']);  
     // var file= form_state.values['image'];
     //alert( form_state.values['image']);
      var form_data = new FormData();                  // Creating object of FormData class
    form_data.append("file", file);

          var d = new Date();
      var image_file_name = Drupal.user.name + '_' + d.valueOf() + file.name;
      // Build the data for the file create resource. If it's private, adjust
      // the filepath.

      var file = {
        file: {
        //$("input[type=file]")[0].files[0];  
          file: form_state.values['image'],
          filename: image_file_name,
          filepath: 'public://' + image_file_name
        }
      };
      if (!empty(Drupal.settings.file_private_path)) {
        file.file.filepath = 'private://' + image_file_name;
      }
      // Change the loader mode to saving, and save the file.
      drupalgap.loader = 'saving';
      processed_an_image = true;

      var profile_img_uri = 'public://' + image_file_name;
      //
//  var profile_img = 1;

      file_save(file, {
         async: false, 
        //data: data,    
        //method: 'POST',
    //  path: 'drupalgap/file.json',
            success: function(result) {
              try {
              //alert(result.fid);
              var fid=result.fid;
              //alert(profile_img_uri);

                // Set the hidden input and form state values with the file id.
                //var element_id = drupalgap_form_get_element_id(new_upload_image, form.id);
                $('input#fid').val(result.fid);
                //form_state.values['new_upload_image'][lng][0] = result.fid;
                //if (options.success) { options.success(); }
               console.log('success');
              }
              catch (error) {
                console.log('_image_field_form_process - success - ' + error);
              }
            }
        });
```

Thanks in advance,
Gireesh

**Comment by signalpoint** [comment]
You need to base 64 encode your image, I _don't_ think this line is going to work:

```
file: form_state.values['image'],
```

DG doesn't yet fully support custom file elements on forms, so some custom implementation is needed here.

**Comment by gireeshscs** [comment]
Hi Tyler,

Thank you for your reply. I am using a custom form with file field. I have tried all possibilities. Image is uploading to sites/default/files folder and fid also getting. filename and url are saved in database. 
But when we take the file in browser not displaying. i am attaching my url
http://mylance.co.in/drumobileapp/sites/default/files/dgimages/admin_1447939589206kid4.jpg

Can you tell me why this happening.

Regards,
Gireesh

**Comment by signalpoint** [comment]
You need to base 64 encode the image, that is most likely why it is corrupt. Replace `form_state.values['image']` with a base 64 encoded image, and it'll work.

**Comment by gireeshscs** [comment]
Hi Tyler,

Thank you for your reply. I have tried that option please see my code

  if (typeof FileReader !== "undefined") {
        var container = document.getElementById(containerid),
            img = document.createElement("img"),
            reader;
	   
        container.appendChild(img);
        reader = new FileReader();
        reader.onload = (function (theImg) {
            return function (evt) {
		  // $("#base64").val(evt.target.result);
		   // fname=file.name;
		     var d = new Date();
		     var image_file_name = Drupal.user.name + '_' + d.valueOf() + file.name;
		    var data = {
			file:{
			file:evt.target.result,
			filename:image_file_name,
			filepath:'public://dgimages/'+image_file_name
			}
		};
		    
		 Drupal.services.call({
		 data: JSON.stringify(data),	
	 	 mimeType:"image/jpeg", 		
    method: 'POST',
    path: 'file.json',
//file:file,
async:false,
success:function(result){
	alert(result.fid);
//form_state.values[name] = result.fid;
}
});

**Comment by gireeshscs** [comment]
I have added

```
  // Create Base64 Object
```

var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){var t="";var n,r,i,s,o,u,a;var f=0;e=Base64._utf8_encode(e);while(f<e.length){n=e.charCodeAt(f++);r=e.charCodeAt(f++);i=e.charCodeAt(f++);s=n>>2;o=(n&3)<<4|r>>4;u=(r&15)<<2|i>>6;a=i&63;if(isNaN(r)){u=a=64}else if(isNaN(i)){a=64}t=t+this._keyStr.charAt(s)+this._keyStr.charAt(o)+this._keyStr.charAt(u)+this._keyStr.charAt(a)}return t},decode:function(e){var t="";var n,r,i;var s,o,u,a;var f=0;e=e.replace(/[^A-Za-z0-9+\/\=]/g,"");while(f<e.length){s=this._keyStr.indexOf(e.charAt(f++));o=this._keyStr.indexOf(e.charAt(f++));u=this._keyStr.indexOf(e.charAt(f++));a=this._keyStr.indexOf(e.charAt(f++));n=s<<2|o>>4;r=(o&15)<<4|u>>2;i=(u&3)<<6|a;t=t+String.fromCharCode(n);if(u!=64){t=t+String.fromCharCode(r)}if(a!=64){t=t+String.fromCharCode(i)}}t=Base64._utf8_decode(t);return t},_utf8_encode:function(e){e=e.replace(/\r\n/g,"\n");var t="";for(var n=0;n<e.length;n++){var r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r)}else if(r>127&&r<2048){t+=String.fromCharCode(r>>6|192);t+=String.fromCharCode(r&63|128)}else{t+=String.fromCharCode(r>>12|224);t+=String.fromCharCode(r>>6&63|128);t+=String.fromCharCode(r&63|128)}}return t},_utf8_decode:function(e){var t="";var n=0;var r=c1=c2=0;while(n<e.length){r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r);n++}else if(r>191&&r<224){c2=e.charCodeAt(n+1);t+=String.fromCharCode((r&31)<<6|c2&63);n+=2}else{c2=e.charCodeAt(n+1);c3=e.charCodeAt(n+2);t+=String.fromCharCode((r&15)<<12|(c2&63)<<6|c3&63);n+=3}}return t}}

```
  var file = {
    file: {
    //$("input[type=file]")[0].files[0];  
      file: Base64.encode(form_state.values['image']),
      filename: file.name,
      filepath: 'public://dgimages/' + file.name
    }
  };
```

But Still persist same issue .

**Comment by gireeshscs** [comment]
Hi Tyler,

Can you help me what is causing the issue with image upload everything is working fine. no errors but image is not displaying. i am passing file parameters to file_save as  
  var file = {
        file: {
        //$("input[type=file]")[0].files[0];  
            file: someimage,
      //    file: Base64.encode(image_file_name),
          filename: image_file_name,
          filepath: 'public://dgimages/' + image_file_name
        }
      };
this is my base64 encode image data data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxQSEhQUExQUFhUXGBwYGBgXGBUXGBgdGhYYFxcVGBgYHCggGBolHRUUITEiJSkrLi4uFx80ODMsNygtLiwBCgoKDg0OGxAQGywkICQsLDQvLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLP/AABEIAKgBLAMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAADAAIEBQYBBwj/xAA/EAABAwIEAwYDBwQBAwQDAAABAgMRACEEEjFBBVFhBhMicYGRMqGxBxQjQsHR8FJicuHxM0OCRJKishUWF//EABkBAAMBAQEAAAAAAAAAAAAAAAABAwIEBf/EACwRAAICAgECBQMEAwEAAAAAAAABAhEDITESQQQiUWHwE3GBMpGx4RRS0UP/2gAMAwEAAhEDEQA/APE6VE7hXKklQSef0oHQ/DYYrIAFLFueKNk2A8qOwspStZ1HhHmTeobqpJNZV2N6Q00XDqAULTQzTmudNiRLxL6RIR/PKoM11RrlCVA3Y9FOfTXCuwFdUbCmZGt601OtIa09oXoGOeFgabNWLHBX3U5m2lqTe4Fj5E6+lQcThltKyuJUg8lAj60upMOloFtTSacoU2mAhXRXKegXoAmYdPhJFNeAUkEa71zDPBKVVNw/DXlJzIZWUkahJP8AzWdXsdXwViVQCOdNCvnUhbcrUDaBoQQfY0KIitCOIsRRVDcUGpmEUATItFCQWRCLUynuLknrSSySCoAwNTQBMwOEBbcWr8otVfMmp7bZKb+cc6Y1h8xuDHTbqaAIy1CBFDooRra1MRE3oGNSmir+H1qd9wJSpSbpTaec1GWiyhvb050mCALRTSLVZL4cW2u8VEHTzqsSabTQjgp7djTKcKAJOIRJCtAajLMmnKcMRQ5oG2SsRjCs3sOQoC0QJ2rhFdQJtzNLgLsk4wwhsRr4j7AVFItVlxz/AKkCISAmBtUAaUo8DnyM0tRsoCSDZVoomCSkkSQL70TiqgpzwxFhP60XsSWiEqwFuZ/b6H3rikEAHmJHoSP0rry5M7aDyFhrRFgSBySB6xmPzUaYASbCnqFDoqnJjpTENUN6n9neGnFYplkWzrAJ5DVR9gahRY1O7PcS+7Ylp+JyKkgakaED0JrL4dDR7PjuJowZSgIsISlPwyNLE0LHN4TGJKFBB3KSRmTO4IuPMVXdsMbh8Th0upUSnXp5KE1XcJ4gHmwF4RIAFnkAJHuokqFri9csqrZ1Ri+3cx3aHsuvCv5FqhoyUORNuRA/MLfWqN5iFFIIMHXSet69L4pi2IQHnV4hOiGG9FGCPinNuRqBFZvGYtts50hCFLkJaw4Hh6LcgyRN4pwzSfz5/wAHLBFe3z57mcGD0PiiLmAI56ny1p4wYgeO52iQPVJNXHCx3ilrfcdQuAQ4ZyAKiJMRuLHnWl4Y220vusay0+haSWcQlKfFaSmR+a3yNEs7i6+f2OPh01fz+ip7G9m0kfeHhKR/007KP9ZnUVsH+PIatYgQm0EzvE2iqrF4zvA22yrIlKoKSPEEpMj/ACAiYHKs72lbKHE5QcuWUmVeIk3Nxr0iswn17fI5YujXYu+O4QY4fhgFwTlIABJ/oV0NYByxgjSxH1FbDsU8oLzKWIAm5gjp1FZztC6l195xA8CnFEep19dfWuiD7HNlS5K9Ik+dJ9zlXBpb2oRqpII3c1b4fGhDZQQLk36VTJor5FudK3Y0XGIxXfEZSlCUAADc1EdfgETbQxVcU/6rhGlN0w4J2Jx6ShKEJtvPOozKLFZ0G3M0xDdwKTqpsNB/JpD92TF8RJaDYsJk9aJw/BKU2tYBtrVZNTRjVtpCUkgKEnrTT3sz9h/FOJrcAQbITomoJbI+tFT4zmVoNetJ1xSzNDdsEiPXUmllpwaJMC9AUMNKlSoAIBXWyRf28660L/zlTnhEJ5UgQ3EOlSsx1IE+cX+c10xtQl7eX705Bgmgb5H21pyUeAn09NzSaElKedr6eZ6DWi4lmDrGw6jne4HnQwS1ZHwzYJk/CkZj15J9SQPWhKUSSTqTJ9dakvQE5eZkx0kJH1PqKjFNAjhFOFImkKYHV0iK6L1pOzvZVT6C8ue65AgE9QTasTmoK2ahBzdItvs+wS3G3s2ctQISVeHqcpF/MVcdoMSju04VtfgWQlMRmSTYpPP+Haq/hXFwGu5w6lJU1bvD4UpTP5tUqPSKr8PxAYbGd49mfUJCW5EyqI6SRcxMWFcTUsmS3+Ed6ccePWy8e7OKWtLLSMrSEgOLRqQRmUlTqvh2lIkmbkWqtxfEQpxTOHaHdtpMuRYQk/CPlM3rbYni6m8LAIBfWGgQk+ErSVOK84kX38qzZwxPeSogAbRBJBAQBuEiDPOp5nGL+fv7lPDdUk38+3sVHAu9S6MN3C1tHwzEmCZCuUaCK2/ZrsiG3+472G1SVYZ5J5SFsKO4NyAT1rLcOQ9hsrqXZIdaQhJgBSe8Aid5Ctf7TXpfHsSoF4hPera7t1tAUEkK5BW0hKpvpNEUpNv4/cWWTilH4vYxHabhreGxTSYuCcpIvaZyn8xg/DRuMcNaxzaU5iggyFAXnTfWoXa7tOxxVnCq/wCk93uRyJPcqM5DI1BIFx15VZY/s++2G3G1JLsfiJJOVZi6gTJBOtSyR+m1umVxTWRNNGG47w95ptwJBUEHKtWQ3TE5hsBzPWsr3seVerr4gHm14bFAsqUnKcxIBEyYUDfQV5t2g4b93dKAVFP5VFJAV5Heu7w+Xq8suTh8Ti6X1LgrU611YuabRVpj1rqs5ByEQJV6dTXCkqvTXDMUiuwAoGFRAAkz0ob6p00rrRsTTkNwMx0GnWka5O4a0nf+fOgLX7U56mBNNGX6HKO8ZCOcR86ARUxtMNhUXBgUmNAnTAyjbXqaTJimqSZk1wmgOGPFwelCB9KK2m/SmOog0A/UfKDrM08IgARNDSkAGdasGMehKQIrLbXBWCT5dAMEQl1MiRr0IjSgYheZRVzrrS4UAbQYvt50Ot9yHYT6dPIUKjYnUf4j6U/BNJKpX8CRKuvJA6k28pO1C4G+SQiW0gj41C3MJO/rHt51GaRmVBMSbnkNSfrSeeK1lR35aDkB0Aj2p6zAnc29Nfnb2oAC67Kidtug2HtFIA0008m9MQ1SbTSaVT1EHz+tcyxrSALhG860gDU7V6ZxvEBnBpQgJC1AIAgi5sIgRvzrF9lMKc+cwEzEn5xzr0nthgWVYBSlEShGcKA3jwg+vKuebudeh0w8sL9TB8dUELwuEQgJSChxcmSVn4gSbGINXvZp99DrikMskvqzNqdCgmQmEoDgBIWqLAgCSLzVb2uwxL+CdSrMHWPBqbpSfzXkkkVL7PcQSrCpZU0pBQmFKXMKuT4UZgZj83MVOTcYKS/JSKU5uL/BDd7TYh1amnS2MwLgCJTlWhBUQpKjKTAKdtqtOE48OIJ2n2/1VF2u4iX1sNzmU2DK1fEc0QkqiSABqeZo2DbW0ImxF/WpZoqcU+5fw7cJNdjWcPZYdcCnSEoaSp06R4ADodSItUF/t26+4oYZDakOSA2qVPOECEpKQbSBYCRzOtZriozNm8aA+pg1oeEvH7uw2zlZyoyrKEgLcJPiKljxEHkDWIdOOFs3khLJPXoD7U/eMSO5CcKBhsiloYQchWBK2y4IEiYyj3FTftaxTjKcGtsrQYJkEj8qfCdah9pscWMAtv7u61KghCipOQ2spsp6JmKv/tC4MXmeGMgypTiE6Xju5WqNLATetRblJSktb/gjOopxi9mc7QcQChgXnWiELgqIIKlHlGpG+ta7i/Dkv4YiEFJSYiJFrWNqzf2zYcMqwjSQDGgkg2gQBoAeYrVcMUk4NJQVIMQpLgBKTyO/rNZnCoJoccrcmmeEdxCiDsSPbenWJmrXtFh1N4heZKQoyQUyEqBPxQdDVWpoxOxr0YytWcUo02gbqQLDWhKFPSZo7KLSda1dGKs4ykBMnempdBsdNP8AdPXeY20AoKWyTFIfHAsUAFGNKFRbSZ0phitIyxAe9S8SSmE8q5hWgJUdE6dTQnlEmTqazyzXCOBR1rqTuaaUU9tVrimCGkxTnTmAJ1FJSIvTELvNAP0EQAL60I05RptNGWe/dvOwTWMUp1rK0+gaCIXFwFDn1614U4iFERodK+qncLkHhTnNyVnc6k+teTce7YtYdAZYw7JcCQlTmUKvlEkfSTyNOXqxRTekeXvsKmyVGw0BOwtanYoZcrY2uo81EX9BoPInervEY5xAkrUcx8CEmEkkeJZ/xn3I5VTNuqFgQZ1gSf8A3GsdRXo3ySeH8BdeUkICTJgeNAMwTubC2ptWjc+zfiKhmDCSOQWk25Cs9i38qQjU/EoEkm+g8MaCD/5GiYPiz7Ed24+2JEZFZflNLq9gePsmM4v2dxOHV+Kw4j/xJHoRaq5xJEZkkeYI+taxr7Qce3ALqlj+l0Nr9fhke9cxX2ivuwHmMK6B/U3f3BFaTJyg13/kySjlMwPrTe9561oeLdslOoKG8Ph2M3xKbSc56An4fS9ZkUxI2XY4AiABJuVKgwNwkbVpu2Tyl4RQjwAAAQZnmP3qt+zThgWFqMmLW0EnSef6VtHWWlEtLTPIG8k7dTXKv1s6pvyIxnFmkjg2BeCpWysRG0quOtRMbxFRQl12U50BQRlEFOiCVaqWRrylIq27ZJUywMIUiXSVJCY8NxluT51lcZhHUBAxBUVZRObQJT4W0JI0tc1aSTgSxNrJaGcLR3jpWTc7fKtBjUnLH6fKo3ZdCA4EOQhS7t5goBxMycq9JkxvpV/xDh4SlS3nWmkAxmJKvJISIk+tcWVeY9HFfTaMc0FKVF8pN7EwOdhWy4GylKBnIABuo2CRrmPSx12qt4MpKkOrSB3afCHLgOGVZiM35QMuo1nlVrwDEhT6GwUFKyUBQWCU2lObzuI6DnUc1t1RbFJKLdlitDODUf8A8rhXVoccztrRLzCQAMoKQbEXvEkG+kC54djW8bxRl4OJS000ruG7hayqMzxTaEwQBNS8My+yssOKL2FcbMB3L+EoWKJAgtqBMWtppFYfB9l0cPf++4l8AIJU002SYTNhJuUgGIAtXZGKo8tybdsX284cqfYd1QkFKvCqBJBkn9Kv+FuJ+5tCZBiJMyI2VqR5/Ku4t3CcYZltyFDqQRzSpO41quw3D14YtsBzwAaEAidUkEaT0pTScafYeN1KzA9tW+6eiSU6gHaeXT9qo88pOwmPlWw+0xCUuAHUjMOhgAj1gGsS4jwgzrtVcX6EGR+ZjGU3MUguAfY0XKctgZi5qLrarEXoIwYzKHL602THU/SpGHbhKs3mOtc7rwyDpqKVjUWBfjwxy+ddwzeY9BrXO6MVJX4EADVWpov0FW7YN8kgRYcqACakOtZYzGZGlR5vQglyEWJimk2iioEmBvTHG4MG3nQNruMUq8TNMUm9PJA61wuXpmWcKd6bakTXKZk99+1Lt0rDFOFZhLqx4yDPdo0iNlET6V4YglRgT4iAPW0n3qQvELdccedUVLUFKUTcyq1/f5VzhQEqUdhYcybfSaU5WUhGqQ7HplxQUqEpMDqBYUsIoGYT4ECVc1bJR6mJ6A0ziy8zhAH5iPn9KLifwkJaSDmN1HmrQewt6msm3y6/chIWUkxcwZP6D1rrZyklV1bCdPOjts5bAZlnr8PtTsSx3SbfErf9qVrgag0r9Pn7kJ5wk316UwC005Tca1IfahNbtIl0t22Q6cnWk0qDMA+YBHsasMFjY1meSAhoeqkpzHyt502ZW2eh/ZavIysk2Urw8rXJsOWvoNa1YcN3YQIughJUR1J5m9eQsdoHEqT8MAjbOYmYzOlRHpXqCcQ4pDalarAy2KlAkaNpJuRzsABqK5ulqRd8FJjmnsQ6rvX3ypSoS2yUtBNvCFKRmCpF/EtJiSAYpMYJbQyJU5mEBILefD63TngrWbq3BN7Wq4c4w03mT4YR8ZtlHPMq2Yn0T5kGaDjnFhlD/iKwCEwSFCfyp/pmxUbGLWmBSrIp0zSYDhLTzBYfabyGSjKlxCmlWlSM6RF1A68+VU7HZr7zii3iXAtvDmQAFAuZkJgrEmBbaZvUHsI9iHO/K1KUTBywVKAM6mfDJ5naprvZPENE4nDqDbx8RuSlQJ0VmMEkgiD8jFZcUiinKnXfksO0LDaFISnCsLQBlQkvlKRrfKpsbeelRMDiQ0vOpvBpSQAUtnvT4cysxMBLUAkydieVLjbfERCwQhEePuySP8gldgDJBB560Dsk/wDeHAp0rS+2CFESnOAfjAFiUkzMaKHJU4cFyP6jWjU9ouJKQhoZVHvIF5UgDaVIM32MEVheOoRipBCyQoic64kAarSHAg6WWlOlejjgUYgOocUEkeJuQpBP9SR+RX+MAg+Yq1TgmVGcqQSdQADOmtJSoTVnjPY7hK28QlxPfNIAlRJbcQobZXEkBQ8hW9RDi86TMm2kHp0nXzqV2lxKGUqSgJSrlACVbkEaXBO29ZXstxJJccb8QTBVBMwQZlJJ+RJ0mb05XJWENMqvtQcQp1vXNkuD5/welYhtIKk+pitT2gbcxqs7KFLUjMhYTeCNDHIj9ag4LstjVf8ApndIEgCPc1TGmojk1ZR4p4hQA/LQm1eOSLVb43sjjG1QphwE8hI9xQcRwR9CQVNODzSap2McsjtZlZrUIgZepOlFXmQkG4NRr6/y9JGrDpdJERM/pQ3nZUDsNqehspkxtQ2VAAyLmgXPI91sTY3i9DU1H70cLSNppwG5FqVm+lMA0CAVW86GoFQkmrVTaFIiDE67U9nDtCBmMb2rPWP6d6KvC4YEKJMHYUJTUa69Kt3W2DITmprMTCUggbmxo6+4fSXBXN4cbgnpXSpI2omNURqmKAmOlbW9mGqdBcU1lSQSCSqZG4i31qTAbbjVRE+Ww/Wht+MoR+aMwO0k2T0kR603FqJKwBPiCB6eG3r9aT3pmk0toNg2YcccNwgmJ57fv6UIGZdV1iRqelT+JkIQsJ5nzKifEf0HQVWx+GmfhGv6Cldmq6f5OYcEJKryogD56UXEXdSNgJ/5o2LcBDaBy/2PpUYqJcWQNjSTvY2uldP2/wCgMQMyrbmnLVKQOVvOuOJkC3U0u7vP0rZLdv3Asp3pyFQrpScRlPnXHOe9a5McFrh8alChkTlv8ZCVuD/EGEp89RzrRYLtQpSC34syrBSlFSjNvGo/FN7QBYWrGoVIqRh6nKJaLstePJcCktp/6aYVAuVKi61ncyNNAKgYHjJTZZJSBYQDudZItfrppVxgMdlTDolP9QGvmaj4vgCXVZmTE6iPpSjkXDFPC+UaTsx2vawyAA3mB8SiNZzfDcXVCZOgEivQEdrWSYEkBWQnlqJv5D3rwTiHCXmJKkqCR+bb/VF4fxlSSAo+GwMdN6JRvaMLTpnvA7RIcQvu0AxAMxdJB8MaGNflWPxXCFqcaLBQlbeZwkHKcmhbAnQyfKuYXhrimErZcOX4gRBB5TzFTcJw/M4CuUEpKTBMctetq51kXYu8ToOeNqwyD3pK0yAcuoCpylMbAiemccqiNYvGOytJyrSowR8LiNULH90RI3HUVpnOGMqyrVAyEJOwMGwPPWjBF8qAIGhGkbfIkelNzRhRM1jlDEeF4EL3IPsfS4rC8fWrBYiWlidQBqOR5V62jhYDua5P77V5D9pjOXFkADQTAi9Zw5OvJXYpkgo47Nz9imKLqsQrukgFQNoAJOojbnpvXrKXUgeJv2NeRfZyPumHZWqB3yvIxFiTXrpb0lUgiQb11Ypxk2kc2WDjTfcTX4hMJkf3a+9Vz+HBOluRAqw7opM5iJ5GKY+wTcab8zVKJGP4z2Hw2KMuNweaTl+lUTn2R4c/9x0J5Wn3NeiFtQ0qYhxJ+JGn9MzTpAmzzv8A/luCUgJKnQRvmvWT7RfZS62ZwziXE/0qsr0O9e1LybLkeUH1oRSPOlSHbPmPiXCHcMoJeQpCjoD/AC9Q31kwSK+nOIcGaegutJXGhUmY9aq8f2VwrpBWykkCBaIHpS6TfWeA4V0lBi5nSNKjvydLEaivdcL2AwaFEhsmdiowPKg437PMEtJAStBJnMFEnyvtS6HZp5VVHjWGSUpJB8RFNeeUowQJjavT3vsqRnTD6wjeQCqOhqYPsswxNn3E9TlP6Uuh3ZpZVR48pIV8RJimEJr2d77H0JScuISZ0JA/Slwj7KWQ3+OM65N0kgRtRFN6FKcaPIMLAU44fyCB6CAfcCuh6UJc/MDERbMbd57SfOKctolsJkAqPiP9o1V/NYpzjaQUZR4RsdYiATG+9Zb7lFF8fOQHFEGybyVGOt6LxNA7pIn+bqpnFT4wP6t+k/rp71JfZJQNCBpWW6o2o9TkQsamC2fK/tSKIcVG4tXeJNHKFctacog5Fen7U09GWvM/wAYTqK4QYiDIuPKjsjK6AdDvUjiLBEHcfSm5boFC4/YrlpzA9KjE1PSIVrY8ufKg4tu8gVtPsSnHVjMIJVHOrdvAHUXqnaPK1anhTwU0PQEcqlnk4q0X8NGMtM7gmlRGUK/tVYenWp+BQylUghlf9K/hmRcaW8qWDcyrufL+RV8y228ClaZkQbAxtblXnzy098HorDa0ELQWjI4kqQsXKfEgjW+4PKKymL7FpcC1sLAMnKj8oj8vMT1rQO9k1iV4V9bV5CZlG22oqEnjbmGcQMe0U7d+3oReyhvVMU5f+bv2OfLCL1NfkzvBuP4rhq0oWlQbmS2rcTBKT717RwlbWKZS42UkKAI6aGDGh0rMcQ7MM8TQl0LkBPgUg2MwYO88wawPDsTiuE4qFZgkHxJ1StBtmA3ItpeqSjHMrWpHPcsbrlHtL+CyiF5YUb6j6mrPCYVKEBKdhrUDhHFG8S2m4WFCx1BqyU4lAvYaftXPbrZp8kV8ZUk779a8N41hXcdxBSG8yoVEKJ8Im+t4r2LjXGgyhagkmBJgpnzA3rG/ZvgHHsS9xBwQlchO0318oi9bwXBObDJ5molt2gbDX3RlANiIEKIgJvfatjwvEqU2BJ8No1rHYx7vuJpQASGkFR5Amw3/AJFaBjFlhzN+U2UP1rOHN9PIr78lMmL6mNpcovSo8zRA+YubcqosR2oamMqj1AFAc7TtpjwKMmPCCT7AV6f+RifDPPfh8qXBpUYqPypPmaYnEH+kE+dRsM+hYBSf3+dGCRVeSPBwun+kVxKCdh9KM3l3MU7PHOgCMSsaEj3ioy8/MmrNRMaioi7mLedIYFtShvRTiFEfl9qks4TOPCAfWnnhiuQpi2QSonlXZ6TUg4IjX9KGpiNz7UACnpHrXMyv4TRUtfy1LuT1oA+cuJpLZQkQdM/kPy/OT18qS2iViNOf0qLikKFnEqBBkhQIM/yamtEKHhkHUfsK55po74NMHj8KVoNxmbSVjqARmA983oaNgXCW78qIXSyFOmcyQUiIuXBEcrJKj6U3hY/CSbx6TrvU5vylMarI69DmITmSUmqppBgoO1/nV2pOwFV+LYnoRoaWOXYeaF7IWcq/yTVonGodSBHj61AxDMQr+etceYMBaf8AmqNKRKLlGwq0iCk6Try6VBnY0RTkjkbz+tBSqa3FUTnJM5oZq4w7RIlsxp61Trq04I+Rb+a0sv6bRrA11Uy0++EAZxlI3+dW3D+MtpykrG5NxPzNVePZC1R09qO3wdtQAUkH5elcE1ja2elH6idRNhgOMsxm71I9RtrRUdocG+e7WtpY5Ejy0O9Y9HBsOn/tpnU728jVmxhmiB4EERpAIHpXO4Y1tWUrJL9VF9heBKw6u+4a4ADdWHUZac/xP5FdandpeFIx2H7zu1IebBORQGYGLoIFlAjlrtVBh2mW1AtlTagZ/DJSDzlOh9q1OG4uFKSsagZVAkDMNfcbeZ51WOT1f5OTJga2kYPs26cGhS0Sppari8tHe240nQ16GeIoU2CtQiJJ2g6X5VFPD2u/JEQ8NvhURNyNJg+0cqgcaY7plSQkZTaNfO3z9OtVfmZFaRm+2eLU7iEMMqnPCFRBiTzG159elbrEYpvh+CCVkJCEQJFlHlaqbsb2V7pw4hyMxskagJP/ABUfigVxXEnCQQyyr8VQ/MoEgBJ8vrWmk6XZGbfPcl/ZvgFFtzEOjxuqJF5EbZSdiIrQY1oXKoirhnDBltKBokADyAtesR2h4sHHhh0zAErIP/x9b1x5Y9c7OrE60VWDcecU5lSe6BISrSRzE60fAvlDkGfWrFGICYbTMn0gc6BisqlZTdetpJHWir7F+rVNl22+kqCTlN7A29jrPlV8lM8/51rM8EWgnK5dW2Ya8iOtaEOHaPnXqeEbcNnj+LilPQSnJVagyaRP8vXWcxOYcSQRAnnNMThAq6SPM7/tUXNXEuWtI96QWEhSTcm3KuKcVMlR96Yp6RcqNNSgczQA9SZ1NdyUIpTzNIZOaqACoRH/ADRg0s3vUWBzPqRXUrjRah5GgCj4hwRl9KlPIaVslSwNt5OkmfSs9xPs5h+4WtnDJQUpJzStIBFoSkfEZ52jnWxYaaEQmY0KvERbYmTuag8baCW1QUgOKQlQmIKnEpzR63rTV8hGVcGYZ7CM4hDiFF1vI5Agg+IJTmPiBkSbdKb/APoCmwlCHgoEH405dOZTP0rU9nMMpIstKkuuOqBzgmyzCjJ/MBtyFc7WhYShpB/EeUUAgjwoj8Re2ggA8yKi8cWqZaOaUZWjAJ7OvlJUlGZIUUhSSIOUwSmblOt6psThyD4kkEWggj5G9e0YXDZEgCEgCMtoEWAseVqa9gEOiFoSof3AHSo/4/odC8X/ALI8T+7yn4Ymq7DlTawhQknT/Ve5L7M4cgjukjyt7Vk+KfZoFOBxD7ib/CpIVHSQR9KccUlaYSzwdNcnmPEMGpCp2PKoTWsV6J2i7E4kJJbHe/42Psd6x+E4E+FeNtSSNiINbi2o3IxOKlPyEF0UbhJhVGx2DKQMwIM1MwOHBSUxcXFZlNdJuEH9QscE7K51Plbzq4W1pt8v1iqfBMKQRz3gVbJWL++ledl50epi42Fdat59fXf196hl0xG/833oxXNgdOf0I9a6+kaJtz3i1TWuSr3wRkEzr9P5tUpt5ROttwPrUVbGUDrbkZ/TSkFRY6/z51ukybZoMPjimLzBkTqDpInzqY/ilq/EEKUL5VaHy2H+qoGnrbWvvTnMURJkaVlWnozKMWtl7i+1CnmSjDt/ifCpMwUcz/cNdKvex3DG8I14VZlqhS5MkqOtefcAMFSzGZZm0286vm8URdKikjl/uqSyNaRzrw6as1vaHiwabUpSrAbajzHLyrB9lsEpSnH1BQK1EgGSco0gnWn451K1pLpK8uaBJCfEIMjQ1YscZaQIAi2ltY286Sar7j6JRK7B8RSrGYhs2ypTBNhpf51adkk5ULeWZ71RUkG/g0SfUAH1rzTimPWvFurCS0VDLBkkzYac62eDxjjDDZcEFKQCjew0Fdn0lWjjeVvTNTxF1sgZwByO49qjYDtT3S8jiitGyh8Q8+dU+Ew7rv4z5grAKGxogcjzVUDjawiwTBFyRy3JNT6ZQfVEpFxmumR6hh8e258C0HyIn1GtGPQ14u5xNDajF4trVxwrtY/HgKiOSr/Wrx8U680SUvB/6yPTyDXCD1rDYXt8SqFsgkbpJB9iKveH9qW3VBJSpBO5iPrVlnxvVkH4bIuxeEetOBvXUGkSP5FWIA1Eb+2/yrqiDaKfFNUJoAYsCuJjnXVJimlX8vQAU4BKIjQ7beYqo7c4ZQwaygkqCm8sayXUxHWlSpdTo1WxYzh7uGwyY/7aQYMapFxPW49aBwwd8FYgzCiA3pIQhQ/+ywT1tSpUS4SBepfAje/yphcSFACApXTWIvr5UqVDEg3pTgOdKlQB3J0qLieHJV8SQR/cAaVKkaKbHdi8K8fE0B/iSPlpWdxv2Wpgll9aTsHAFD3SAR7GlSrLSo0pNOzM43geMwcd6gqbmApJzJ8zF0jzApzb03Ij2pUq4PEQSej1PC5ZSWyQiNR/P5NHbZ3Py+tKlXFLR3x2MfSSkCAf3E0D7sVHMZuPp/xSpUJ0hSVsWQpn5G/Lf6+lQnVE2uee9KlVYvuRkSWMSUkAp5jlpRMRjFjUgDpelSp0rQk2RO8BOpnrXEqJVcab86VKtNUK7LNlsKKDkCim4zRIPQ1YcXacXC1NFITe5FzoCCna1KlVcEnwcviYpbI6+PgLAWY+hJgC/Sm8XecCVhzIAUlKEpN1k/mNrASfO1KlXTNKjkg9mJbYJgjU2j96t2WnxCGk+I68kjdSjyrtKs0nyVcmuCwUwA/KbkAJNoBO5B32q5fJbLZUg+I5RAvMTf2pUqk8ab2bWWUVo1PAuMFctqspIEE/mBFr71cBR6GlSrtwu47OPMkpaCGeQ9SP0NJSeYA/nnSpVQlQk9f0pSnlPr/uu0qAP//Z

Can you help i am sitting for this 3 days.

Thanks,
Gireesh

**Comment by gireeshscs** [comment]
i have resolved this issue by strip down the data:image/jpeg;base64, from the encoded string
