### ISSUE TITLE
drupalgap_item_list_populate error

### ISSUE THREAD

**Issue by ghost** [signalpoint/DrupalGap#67]
DrupalGap-7.x-1.x-alpha

Error - When I try to add comments or create a new node

index.html
drupalgap_item_list_populate - Error: cannot call methods on listview prior to initialization; attempted to call method 'destroy'

Node gets created on server

(via Xcode 4.6.3 and running on iPhone 4S -  Cordova 2.7.0 - not using ripple)

**Comment by ghost** [comment]
Was this one solved?

**Comment by signalpoint** [comment]
Not yet, the node should be created successfully, and any comments should also post without a problem. We're still having problems with the listview init/destroy when reloading the same page.
