### ISSUE TITLE
Entity reference - Label view not showing

### ISSUE THREAD

**Issue by pierpa68** [signalpoint/DrupalGap#673]
Hi,

I'm trying to show a field of type "entity reference" with a view datasource. I followed the instructions for building the entity reference and page views and the content shows perfectly in edit mode.

I've selected the "label" formatter in drupalgap display with link to the content.

The resulting HTML is:

```
<a href="#" onclick="javascript:drupalgap_goto('undefined/1238');" class="ui-link ui-btn ui-shadow ui-corner-all" data-role="button" role="button"></a>
```

that is an empty button linking to wrong url. The entry has a title and is "node/1238" .

The logging console show a message: `entity_primary_key_title - unsupported entity type (undefined)`
The JSON segment relative to the field: {und: [{target_id: "1238"}]}

Any guess?

Many thanks

**Comment by signalpoint** [comment]
First, the DrupalGap Display Mode is in no way connected to the JSON delivered by Views Datasource. The Display Mode only affects `node/%` pages, while you decide what is rendered when working with Views JSON.

**Comment by pierpa68** [comment]
Of course you are right, I reported the information about the datasource for completeness as it uses a view to power the field. 
The JSON segment above is the content of my entityreference field as returned for the node/%:

http://127.0.0.1/devcarpe/?q=drupalgap/node/1242.json

returns

```
field_esercizio: {
  und: [
    {
      target_id: "1238"
    }
   ]
},
```

As you can see, it doesn't containt the "title" and "entity_type" elements as requested in the procedure
entityreference_field_formatter_view:

```
case 'entityreference_label':
            var text = item[entity_primary_key_title(item['entity_type'])];
            if (display.settings.link == 1) { // Display as link.
              element[delta] = {
                theme: 'button_link',
                text: text,
                path: item['entity_type'] + '/' + item['target_id']
              };
            }
```

Hope this helps

**Comment by signalpoint** [comment]
@pierpa68 please read about GitHub markdown and how to better style your comments, I've fixed your comment with markdown. I've also added markdown to your original issue comment, I can now see the code you were referring to, which makes more sense now.

That being said, thank you for the thorough debug/context about the situation. I'd recommend placing a:

```
console.log(item);
```

... in the `entityreference_field_formatter_view()` and seeing what's inside of it to debug further, as it looks like it's having a hard time figuring out the bundle of the entity type (node/content type, other?).

**Comment by pierpa68** [comment]
@tyler: Sorry for the bad style, I'm new in github!

Here is what's in console for the 

`console.log(item)`

```
Object {target_id: "1238"}
```

In drupal the object to be shown is a node.

Thanks a lot

**Comment by pierpa68** [comment]
@tyler: Hi, I've gone further in debugging for solving the problem and may have found the cause: the default mode for my entity_reference field is hidden, so the following piece of code (from drupalgap_entityrefence.module) goes wrong:

```
 // Add the target entity type, bundle, and title/name/subject/etc to the
    // result set.
    foreach ($instances as $field => $instance) {
      if (!isset($instance['display']['default']['module'])) { continue; }
      $module = $instance['display']['default']['module'];
```

In fact, the `['module']` element of the array doesn't exists for `default`:

```
[field_esercizio] => Array
        (
            [default_value] => 
            [description] => Scegli quale degli esercizi che gestisci è responsabile per l'evento che stai generando
            [display] => Array
                (
                    [default] => Array
                        (
                            [label] => above
                            [type] => hidden
                            [weight] => 11
                            [settings] => Array
                                (
                                )

                        )

                    [drupalgap] => Array
                        (
                            [label] => hidden
                            [type] => entityreference_label
                            [weight] => 2
                            [settings] => Array
                                (
                                    [link] => 1
                                    [colorbox_node_link] => 
                                    [colorbox_node_classes] => 
                                    [colorbox_node_width] => 600
                                    [colorbox_node_height] => 600
                                )

                            [module] => entityreference
                        )
```

Shouldn't be better to use

```
 if (!isset($instance['display']['drupalgap']['module'])) { continue; }
      $module = $instance['display']['drupalgap']['module'];
```

instead which, in my case, seems to work?

Hope this helps

**Comment by pierpa68** [comment]
@signalpoint Is the druaplgap module for drupal also on github? I could push my fixing for this issue also, if you like.

**Comment by signalpoint** [comment]
@pierpa68 Nice catch, this definitely looks like a bug. I do not have the DG drupal module on github (yet?), so for now I happily accept d.o patches: https://www.drupal.org/project/drupalgap/git-instructions

**Comment by pierpa68** [comment]
@signalpoint Thanks, patch pulled.

**Comment by signalpoint** [comment]
This was later fixed in an issue on d.o with the DrupalGap module.
