### ISSUE TITLE
ReferenceError: device is not defined after upgrade

### ISSUE THREAD

**Issue by ntym4ek** [signalpoint/DrupalGap#679]
I had working web-app.
Looking for fixing logout issue https://github.com/signalpoint/DrupalGap/issues/621 I made kit upgrade from 7.x-1.2 to 7.x-1.3 by https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/UPGRADE.md and DrupalGap Module from 7.x-1.13 to 7.x-1.14
After all I got next issue: "_drupalgap_deviceready - ReferenceError: device is not defined" on drupalgap.js:233 in console log.
How can I fix both issues?

**Comment by ntym4ek** [comment]
Fixed "device is not defined" issue with replacing in index.html "bin/drupalgap.js" to "bin/drupalgap-7.x-1.3.js".
But original issue of logout bug still not fixed. 
Anyone has ideas?

**Comment by signalpoint** [comment]
@ntym4ek Thanks for reporting this. I've just now fixed the device not defined issue. Please open a separate issue if you're having problems with logout.
