### ISSUE TITLE
Add Support for Views Exposed Filters with a Node Title

### ISSUE THREAD

**Issue by rpayanm** [signalpoint/DrupalGap#684]
In my View I have a exposed filter (Title of node), but in the DrupalGap App I see a select instead of text input:

![selection_052](https://cloud.githubusercontent.com/assets/6087454/11726391/7084033a-9f4c-11e5-8001-43eb304a73ae.png)

In the console I have this:

![selection_053](https://cloud.githubusercontent.com/assets/6087454/11726473/d36d3ac0-9f4c-11e5-944a-ebaadb14e0c4.png)

Her my code:

``` javascript
function mypage_page() {
  try {
    var content = {};
    content['mypage_list'] = {
      theme: 'view',
      pager_pos: 'bottom',
      format: 'ul',
      format_attributes: {
        'data-inset': 'true',
      },
      path: 'mypage_list',
      row_callback: 'mypage_list_row',
      empty_callback: 'mypage_list_empty',
      attributes: {
        id: 'mypage_list_view',
      }
    };
    return content;
  }
  catch (error) {
    console.log('mypage_page - ' + error);
  }
}
```

How I can fix that ?

Greetings.

**Comment by signalpoint** [comment]
@rpayanm The views exposed filter form builds itself here: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/views/views.js#L147

I never got a chance to add support for node titles, so it would need to be implemented somewhere in there, probably around here: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/views/views.js#L215

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
