### ISSUE TITLE
Access denied when the app try connect to site

### ISSUE THREAD

**Issue by rpayanm** [signalpoint/DrupalGap#686]
Hello,

I build my app for android platform:

![selection_055](https://cloud.githubusercontent.com/assets/6087454/11907868/680e60d8-a5a5-11e5-81da-8a648128661e.png)

I was installed in my android phone, but when I open it, begin loading and show me:

```
Unable to Connect
Failed connection to http://....... - <!DOCTYPE html PUBLIC "-//W3C//DTD........
```

and show me the complete output of a page `Access Denied` of my site.

However, I can navigate fine into my site http://......./mobile-application like anonymous user.

What am I doing wrong? How I can fix it that?

Thank you.

**Comment by signalpoint** [comment]
@rpayanm Have you installed the network plugin? Is your Drupal site on the Internet, or on localhost?

**Comment by rpayanm** [comment]
I follow [this tutorial](http://docs.drupalgap.org/7/Compiling_a_Mobile_Application/Preparing_PhoneGap/Installing_PhoneGap) and I installed this plugins:

```
cordova plugin add org.apache.cordova.console org.apache.cordova.device org.apache.cordova.dialogs org.apache.cordova.file org.apache.cordova.inappbrowser org.apache.cordova.network-information
```

And my site is in Internet and my phone is connected to Internet, even when I open the app the error what it show me is the full output (plain text) of a page of "Access Denied" of the site, that is, there communication between both.

**Comment by signalpoint** [comment]
@rpayanm I'd recommend placing some alert() messages inside the drupalgap bootstrap process, that way you can identify when the code fails.

**Comment by rpayanm** [comment]
@signalpoint I move the code outside of drupal hosted folder:
Before:
/var/www/mydrupal/mobile-application

After:
/var/www/mobile-application
1. I launched Google Chrome from a terminal with a flag to disable this security feature for prevent the "Cross Site Request Forgery" error: `google-chrome --disable-web-security`.
2. I go to http://localhost/mobile-application and show me the seem error on the app, here the console output:
   ![selection_060](https://cloud.githubusercontent.com/assets/6087454/11935549/6ecaab7e-a7d6-11e5-8ccf-fd4daf630f5d.png)

----- Full output of a page of Access Denied -----
And a little below:
![selection_061](https://cloud.githubusercontent.com/assets/6087454/11935553/71a41cf4-a7d6-11e5-862e-72d03e7447cd.png)

And show me this:
![selection_058](https://cloud.githubusercontent.com/assets/6087454/11934824/5fec99ea-a7d2-11e5-9097-0aac510a61b0.png)

Then I follow this steps:
1. Open FireFox
2. Log out of your Drupal site.
3. Open Firefox Poster Plugin
4. Make a POST to http://mydrupal.local/?q=drupalgap/system/connect.json

And and everything is ok:
![selection_059](https://cloud.githubusercontent.com/assets/6087454/11935234/c4d09f76-a7d4-11e5-9fea-221be675642b.png)

Please you can suggesting something?

Thank you.

**Comment by rpayanm** [comment]
Oh man, I almost went crazy. I already knew how to solve the issue.

I check my logs (admin/reports/dblog) and:
![selection_061](https://cloud.githubusercontent.com/assets/6087454/11942442/943a4008-a804-11e5-90b0-5a7833442cad.png)

The "problem": [seckit module](https://www.drupal.org/project/seckit).

Specifically (admin/config/system/seckit):
![selection_060](https://cloud.githubusercontent.com/assets/6087454/11941654/42aa0610-a7ff-11e5-886e-a267b4fcc9be.png)

When I uncheck this, everything work like a charm.
I think it's less safe place, What I could put in "Allow requests from" for keep this checked?

Thank you for you support.

**Comment by signalpoint** [comment]
@rpayanm Thank you for the follow up. Yes, there are many contrib modules out there that can interfere with each other when you least expect it.
