### ISSUE TITLE
Problem loading locales

### ISSUE THREAD

**Issue by pierpa68** [signalpoint/DrupalGap#689]
Hi,

I'm trying to use 'it' language on my webapp, but it doesn't seem to work. I've set 

`Drupal.settings.language_default = 'it';`

as well as 

```
drupalgap.settings.locale = {
    it:{ } 
};
```

but the messages are always in english language.

After some debugging I made it working changing the `function drupalgap_file_exists(path)` function:

```
jQuery.ajax({
      async: false,
      type: 'HEAD',
      dataType: 'text',
      url: path,
      success: function() { file_exists = true; },
      error: function(xhr, textStatus, errorThrown) { console.log('Err='+textStatus); }
    });
```

It was necessary to put the `dataType: "text"` element overwise a 'parserror' is thrown due to the empty response of the call with 'HEAD' method as "json" type is automatically guessed by jQuery.

In the jQuery documentation it says:
_"The JSON data is parsed in a strict manner; any malformed JSON is rejected and a parse error is thrown. As of jQuery 1.9, an empty response is also rejected; the server should return a response of null or {} instead. (See json.org for more information on proper JSON formatting.)"_

Hope this helps

**Comment by signalpoint** [comment]
@pierpa68 Thank you very much for thourougly debugging this. If you could please create a pull request, I'd be happy to merge in your code and credit you as the contributor!

**Comment by pierpa68** [comment]
Hi,

I've just tryed pushing modification (via `git push` on my pc) but got

```
Username for 'https://github.com': pierpa68
Password for 'https://pierpa68@github.com': 
remote: Permission to signalpoint/DrupalGap.git denied to pierpa68.
fatal: unable to access 'https://github.com/signalpoint/DrupalGap/': The requested URL returned error: 403
```

What should I do?

Sorry, I'm new to github, but like learning!

**Comment by signalpoint** [comment]
@pierpa68 First make a Fork of the DG repo, then clone your fork. Then you can git add/commit/push up to your forked clone of the repository, then on the github UI, you can click to create a pull request from your repo to mine, and it will send it to me.

**Comment by pierpa68** [comment]
@signalpoint Thanks. It seems have worked now.
