### ISSUE TITLE
Views exposed filter doesn't work if field is term reference using list mode

### ISSUE THREAD

**Issue by pierpa68** [signalpoint/DrupalGap#691]
Hi,

I've made a view with a term reference field as exposed filter.
It works ok if I use the autocomplete mode but not using select list.

Debugging in the browser I can see that in first case (autocomplete, working) the generated url is:

``http://127.0.0.1/devcarpe/?q=esercizijson&field_categoria_esercizio_tid=Servizi&page=0`

while setting the display mode as select list (and choosing the same value as before) the url becomes 

`http://127.0.0.1/devcarpe/?q=esercizijson&field_categoria_esercizio_tid=13&page=0`

In the taxonomy the id=13 is related to term 'Servizi'.

Any guess?

**Comment by ericjgruber** [comment]
Did you ever get an answer for this?

**Comment by pierpa68** [comment]
@vml-egruber not yet, but 'll go to look at the source in next few days.

@signalpoint Any guess on where should I look at?

**Comment by signalpoint** [comment]
@pierpa68 Here's the code that is making it happen: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/taxonomy/taxonomy.js#L916

The quickest workaround would be to use this hook to fix the query string before it goes out: http://api.drupalgap.org/7/global.html#hook_services_preprocess

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
