### ISSUE TITLE
Google maps display problem

### ISSUE THREAD

**Issue by pierpa68** [signalpoint/DrupalGap#692]
Hi,

there seem to be a problem with google maps both creating them in `pageshow` function and using geofield_gmap module: the zoom controls are shown wrong and the dragging of the map shows new areas as gray background. See attached example.

Trying to solve the problem, it seems to be related to the drupalgap.css file here:

```
/**
 * Images
 */

/**
 * Don't let images stretch out of their parent container in the main content
 * div. Ignore google images.
 */ 
div[role="main"] img,
div[role="banner"] img,
#_drupalgap_splash_content img {
  width: auto !important;
  width: 100%; 
  max-width: 100%; 
  max-height: 100%;
}
```

In fact it doesn't ignore google images at all!

I solved adding

```
div[role="main"] .gm-style img {
  max-height: unset;
  max-width: unset;
}
```

to my module css, but this should be addressed in drupalgap.

HTH

![temp2k9](https://cloud.githubusercontent.com/assets/16143949/12063119/6f144164-afa9-11e5-893a-5637d841d459.jpg)

**Comment by signalpoint** [comment]
@pierpa68 thank you. Yes, this has been a long standing issue/annoyance. I went ahead and dropped your CSS into drupalgap.css: https://github.com/signalpoint/DrupalGap/commit/8051a7de4f528d7095e4af08629b3ef46f3bd7f0

I don't have a chance to test it right now, but it looks good, thank you!
