### ISSUE TITLE
Mobile Notifications When New Content is Created in Organic Groups

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#693]
I currently have organic groups for a website. When new content gets posted to a group for which a user is a member, I want the user to be notified on their phone that their is new content in one of their groups. I don't quite understand how the push notifications to a phone work ... but if I want to go down that path to add that functionality, what are the recommended Drupal/Drupalgap modules required?

**Comment by signalpoint** [comment]
@mkinnan I believe we had sorted this out through a verbal discussion sometime after this issue was posted. In closing, Push Notifications is the way to go and the recommend modules are:

http://drupal.org/project/push_notifications
http://drupalgap.org/project/push_notifications
