### ISSUE TITLE
Only One Exposed Filter is Working and No Hierarchy

### ISSUE THREAD

**Issue by BilalSukkarieh** [signalpoint/DrupalGap#694]
Hello ! 
 I gave up on this, when I try to expose two taxonomy filters as select or auto-complete ONLY THE FIRST ONE WORKS WHILE THE OTHER IS A USELESS EMPTY LIST, plus when the taxonomy exposed has hierarchy ONLY THE PARENT TERMS ARE RETRIEVED. 
thanks in advance for any help
![1](https://cloud.githubusercontent.com/assets/12585373/12166618/b1f64bde-b540-11e5-815e-0a5f4c8ff36e.png)

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
