### ISSUE TITLE
Event handlers for 'live' should be changed to 'on'

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#7]
Most event handlers should be change to 'on' instead of 'live'.

Live is being deprecated and seems to cause strange behavior (double loads, etc).

**Comment by lightsurge** [comment]
I might have just got lost in the troubleshooting but I'm sure I found that even with converting these functions from live() to on() there was still some weirdness, until I put them within the pageshow() functions as $(this).on(selector, function( etc 

If you don't find that it'd be interesting to know.

**Comment by lightsurge** [comment]
Actually, quite possibly I lost my way in troubleshooting, I'll test your way tomorrow.

**Comment by lightsurge** [comment]
Tested and pageshow events still showed the same back-n-forthness

**Comment by signalpoint** [comment]
Yeah, I am still experiencing the same back-n-forth with 'on' instead of click. Please let me if you make any progress on figuring out why this is happening. I am still trying to figure it out, thanks.

**Comment by lightsurge** [comment]
I can only fix it by unbinding the pageshow handler (I ended up putting the unbind inside whatever dynamic injection is happening i.e. datasource etc. on success) so that it works like .one()
