### ISSUE TITLE
Forms API has no 'weight' on elements

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#70]
The DrupalGap Forms API does not make use of the 'weight' that can be applied to elements to set their order in the form.

DG also needs to respond to the weights that are specified on the "Manage fields" page for the entity type.

**Comment by chrisschaub** [comment]
Ok, need to tackle this one. Any suggestions before I dig in?

**Comment by signalpoint** [comment]
@cschaub Take a look at drupalgap_entity_render_content() in entity.js, which has a concept of field display weights. Essentially you just first need to render each form element and hang onto their HTML, then afterwards extract their weights, sort them, then append each rendered element to the html string.

I believe this should all happen in the _drupalgap_form_render_elements() function in form.inc.js
