### ISSUE TITLE
Mobile Application Development Kit on a separate server?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#700]
Does the SDK have to installed on drupal server? Or can I deploy it on a additional web server?

**Comment by signalpoint** [comment]
@luxio If you're running a web application or headless Drupal site, then yes the SDK will be installed on the same server, and same domain as the Drupal website.

If you're building a mobile application, the SDK will be included within the compiled application, and the Drupal site will remain online.

**Comment by luxio** [comment]
Thanks for the prompt reply. I have deployed the SDK on a new web server, because the configuration of the my drupal web server won't deliver the html files in the sdk directory. But when trying to test the DrupalGap App with Ripple, I get an js error message:

```
Failed connection to http://example.com  - Bad Request: Bad Request
```

example.com is my drupal server. Do you hink deploying the SDK on the Drupal Web Server will fix this error?

**Comment by signalpoint** [comment]
Use FireFox Poster to test is Services System Connect is actually working: http://tylerfrankenstein.com/user/4/code/drupal-services-examples

**Comment by luxio** [comment]
After deploying the SDK on the Drupal Webserver it works. Thanks for helping.
