### ISSUE TITLE
Set Field Value Using hook_form_alter

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#704]
I have a field for determining if the node is a group, it is a boolean checkbox with a value of 0/1. I am trying to automatically set the value to 1 (checked) using hook_form_alter, but I'm having trouble getting it to work. What am I missing?

```
function my_module_form_alter(form, form_state, form_id) {

  console.log(form);

  if (form.id == 'node_edit' && form.bundle == 'group') {

    form.elements['group_group']['und'][0]['item'].value = "1";
    form.elements['group_group']['und'][0]['item']['value'] = "1";
    form.elements['group_group']['und'][0]['item']['default_value'] = "1";
    form.elements['group_group']['default_value'] = "1";
    form.elements['group_group'].value = "1";
    form.elements['group_group'].default_value = "1";
    form.elements['group_group']['und']['0']['item'].value = "1";
    form.elements['group_group']['und']['0']['item']['value'] = "1";
    form.elements['group_group']['und']['0']['item']['default_value'] = "1";

  }
}
```

Below is the console.log output for creating a node:
![new-node](https://cloud.githubusercontent.com/assets/13283396/13025723/b38061ea-d1cb-11e5-894d-7e5df3139bea.jpg)

Below is the console.log output for editing a previously saved node with the box checked:
![existing-node](https://cloud.githubusercontent.com/assets/13283396/13025726/c6071e62-d1cb-11e5-9b34-ea3d3bcae2cf.jpg)

**Comment by signalpoint** [comment]
@mkinnan Try one of these:

```
form.elements['group_group']['und']['0']['default_value'] = "1";
form.elements['group_group']['und']['0']['default_value'] = 1;
```

Either way, it'd be best to see the console output for `form.elements['group_group']` inside the alter hook.

**Comment by mkinnan** [comment]
I tried the above ... no go ... so made numerous different combinations without the **item** setting. This worked:

```
form.elements['group_group']['und']['0'].value = 1;
```

Thanks for pointing me in the right direction!
