### ISSUE TITLE
Link Module Fields - How to open in system browser?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#705]
I have several 'link' fields for a content type. No matter what setting I use on the field configuration on the website, I cannot get the links to open in the system browser in the app. They only open in the inappbrowser. Thoughts on how to get the links to open in the system browser? Do I need to use hook_form_alter to rewrite the output of the field from a basic link to 

```
var html = bl('example.com', null, {
    attributes: {
      onclick: "window.open('http://example.com', '_system', 'location=yes')"
    }
});
```

**Comment by signalpoint** [comment]
The link module for DG is hard coded to open in app browser: https://github.com/signalpoint/link/blob/7.x-1.x/link.js#L136

Ideally there is some type of setting up in Drupal on the field instance that would let us distinguish between what type of browser to open it in. The the field formatter view hook in the link module would just need to be slightly expanded to support a system browser: http://docs.drupalgap.org/7/Pages/Navigating_Pages/External_Links

**Comment by pierpa68** [comment]
@mkinnan I managed to do so using `hook_entity_post_render_content` and, in function body:

```
var $newhtml = $('<div/>').html(entity.content);
$newhtml.find('.field_www a')
                   .attr('onclick', function(i,v) {
                                       return v.replace(/_blank/g,"_system");
                                       });
entity.content = $newhtml.html();
```

HTH

**Comment by mkinnan** [comment]
Here is what I ended up having to do. I noticed that when **href="#"** is before the **onclick** the links open within browser/app. I had to remove **href="#"** to get links to open in system browser.

This opens in system browser:
`<a onclick="window.open('http://www.drupalgap.org', '_system', 'location=yes')" data-role="button" class="ui-link ui-btn ui-shadow ui-corner-all" href="#" role="button">drupalgap.org</a>`

This opens in app:
`<a href="#" onclick="javascript:window.open('http://www.drupalgap.org', '_system', 'location=yes');" class="ui-link ui-btn ui-shadow ui-corner-all" data-role="button" role="button">drupalgap.org</a>`

The code I used:

```
function my_module_entity_post_render_content(entity, entity_type, bundle) {
  try {

    var $newhtml = $('<div/>').html(entity.content);

    $newhtml.find('.field_group_website a').attr('onclick', function(i,v) {return v.replace(/_blank/g,"_system");});

    $newhtml.find('.field_group_website a').attr('onclick', function(i,v) {return v.replace('javascript:',"");});

    $newhtml.find('.field_group_website a').attr('onclick', function(i,v) {return v.replace(';',"");});

    // entity.content = $newhtml.html();

    string = $newhtml.html();

    var string_1 = string.replace('href="#"','');
    // console.log(string_1);

    entity.content = string_1;

    // console.log(entity.content);

  }

  catch (error) {

    console.log('my_module_entity_post_render_content - ' + error);

  }
}
```

**Comment by mkinnan** [comment]
Last reply has been working with no know issues for over a year.
