### ISSUE TITLE
How to set the default value of an entityreference field in the node edit form

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#709]
How can I set a default value of an entityreference field in the node edit form via hook_form_alter()?

Would it be possible to change the type of an entity reference field to hidden an set the the default value with a `default_value`attribute?

**Comment by signalpoint** [comment]
#704 duplicate.

**Comment by luxio** [comment]
I looked at #704 but I could not manage to set the default value for a my entityreference field. I have tried different variants, e.g.:

```
form.elements['field_reldated_task']['und']['0'].item = {target_id : 1598};
form.elements['field_reldated_task']['und']['0'].default_value = '1598';
form.elements['field_reldated_task']['und']['0'].value = '1598';
form.elements['field_reldated_task'] = {
    und: [
        { target_id: 1598 }
    ]
};           
```

but without success. Here is the output of `console.log(form.elements['field_reldated_task']);`

![screen shot 2016-02-15 at 19 53 26](https://cloud.githubusercontent.com/assets/1497217/13057641/d8a30a96-d41d-11e5-8085-e228bf0ea275.png)

What am I doing wrong?

**Comment by signalpoint** [comment]
Ok, to set the default value, I've confirmed the `default_value` approach works, but it is misleading due to this bug: #712

**Comment by mkinnan** [comment]
To set the value of a field and then hide it, like adding an event to a specific group:

```
  form.elements['og_group_ref']['und']['0'].default_value = 12345;
  form.elements['og_group_ref'].access = true;
  form.elements['og_group_ref'].prefix = '<div style="display: none;">';
  form.elements['og_group_ref'].suffix = '</div>';
```
