### ISSUE TITLE
How to synchronous load a node in hook_form_alter?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#713]
I want to wait in hook_form_alter until a node is loaded:

```
function hole_form_alter(form, form_state, form_id) {
    try {

            var task_title = 'undefined';
            // get task title
            node_load(task_nid, {
                async: false,
                success: function(node) {
                    task_title = node.title;
                    console.log('node_load - ' + task_title );
                }
            });

            console.log('task_title: ' + task_title);
           ....
```

The `console.log('task_title: ' + task_title);` is called before `console.log('node_load - ' + task_title );`. Shouldn't `async: false;` in `node_load()`prevent this?

**Comment by signalpoint** [comment]
@luxio The short answer is, you can't.

The long answer is, you need to attach an inline pageshow handler to the `suffix` of your form using hook form alter: http://docs.drupalgap.org/7/Pages/Page_Events/Inline_JavaScript

Then in your pageshow handler load the node, when then node is loaded then use jQuery to inject the values into the DOM: `$('#foo).val(node.title);`

**Comment by luxio** [comment]
Why can't I just use jQuery within the node_load success function to inject the values in into the DOM.

Is there any reason, why to use the pageshow handler for this?

**Comment by signalpoint** [comment]
@luxio I suppose you could use jQuery in the success handler to modify the DOM, we just can't modify the `form` object in the success handler.

**Comment by luxio** [comment]
Thanks. Using  jQuery in the success handler works.
