### ISSUE TITLE
Pass Data From Node Page to a New Node Create Form

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#716]
I have a content type _group_. When viewing the _group_ node, I want to have a button link to create an event in this group. Is there a good way to pass the group information to an _event_ new node form and populate the _select group_ field? hook_form_alter can populate and hide the field on the _event_ new node form, but I'm not sure the best way to get the info from the node group to the new node form.

**Comment by signalpoint** [comment]
@mkinnan You're probably looking for query strings: http://docs.drupalgap.org/7/Pages/Navigating_Pages/Query_Strings

**Comment by mkinnan** [comment]
That's what I was looking for. Thanks.
