### ISSUE TITLE
Entity Reference - Can't remove values from node edit

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#717]
If you have an entity reference field with a cardinality greater than 2 ...

Create a node and add values for both autocomplete boxes of the field. Save node.

Go back to edit node and delete out one of the values for the field. Click save.

Both values are still displayed and when you go back to edit the node the value has been repopulated with the value that was deleted.

**Comment by signalpoint** [comment]
https://github.com/signalpoint/entityreference/commit/de7f7211539f204f5ed9d9bd287ecb0f30fd43b2
