### ISSUE TITLE
Entity Reference - Select list widget on node edit form

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#719]
When creating a new content type that has an entity reference field with widget type as _Select List_ does not provide a box on the edit form to select a list values. The _autocomplete_ widget works, so this is most likely a feature request.

**Comment by signalpoint** [comment]
https://github.com/easystreet3/jDrupal/commit/4544454d3076410a4c276e7d8da8e271c9d67e0a

**Comment by signalpoint** [comment]
https://github.com/signalpoint/entityreference/commit/c2c68490eedf492edaf8b55d347e216c653bfe9a
