### ISSUE TITLE
Add support of modules with minified js file.

### ISSUE THREAD

**Issue by Digeridoo** [signalpoint/DrupalGap#724]
Currently, the following structure of modules in settings.js does not support minified js files (with suffix ".min").

`Drupal.modules.custom["my_module"] = {name: "my_module"};`

Here, `{name: "my_module"}` is quite rediculous and useless (except case when module name is different to module directory name). My proposition is: change `{name:"my_module"}` to `{file:"my_module(.js)?"}`. Or, if you still want to use name in some cases, then add new directive "file" where I can set a full filename (i.e. mymodule.js or mymodule.min.js).

The main idea of changes is add support full or minified module file according to Drupal.settings.debug.

```
Drupal.modules.custom['my_module'] = {
    file: Drupal.settings.debug ? 'my_module.js' : 'my_module.min.js'
};
```

or

```
Drupal.modules.custom['my_module'] = {
    file: Drupal.settings.debug ? 'my_module.full.js' : 'my_module.js'
};
```

or

```
Drupal.modules.custom['my_module'] = {
    debugfile: my_module.full.js';
};
```

Or somehow in another way.

**Comment by signalpoint** [comment]
@Digeridoo thank you, this is a great idea. This feature would need to be added to `drupalgap_load_modules()`: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/dg.js#L296

I personally would like this _optional_ syntax:

```
Drupal.modules.custom['my_module'] = {
    file: 'my_module.min.js'
};
```

Then if the `file` property is present, the system could just look to load that file when loading the module, otherwise if it isn't present, then the system would just default to loading `my_module.js`.

**Comment by Digeridoo** [comment]
@signalpoint great, thanks.

**Comment by signalpoint** [comment]
@Digeridoo Here's the syntax I went for:

```
Drupal.modules.custom['my_module'] = {
    minified: true
};
```

Then it will automatically load `app/modules/custom/my_module/my_module.min.js` instead. Also, thank your for your suggestion on using the ternary operator as well, that will still be possible if you'd like.

```
Drupal.modules.custom['my_module'] = {
    minified: Drupal.settings.debug ? false : true
};
```

**Comment by Digeridoo** [comment]
@signalpoint Excellent! Thank you.
