### ISSUE TITLE
problem when using two views in the same app

### ISSUE THREAD

**Issue by 1nf1n7y** [signalpoint/DrupalGap#727]
hi . 
i am using drupalgap  7.x-1.3 version . when i create two views in the same time . it doesn't work correctly.
the following steps describe the problem:
when show the first view . it work fine.
when show the second view i got a white empty page.
when I return to the the first view i got the result of the second view.
[screenshots.zip](https://github.com/signalpoint/DrupalGap/files/140289/screenshots.zip)

**Comment by signalpoint** [comment]
@ahmedbarwary Thank you for reporting this. It would be more helpful if you could provide your `page_callback` code, and your console.log output, thanks.

**Comment by ahmedbarwary** [comment]
The console log and the page_callback for both views modules in the the attachment.
[console_log_page_callback.zip](https://github.com/signalpoint/DrupalGap/files/142160/console_log_page_callback.zip)

**Comment by 1nf1n7y** [comment]
The console log and the page_callback for both views modules in the the attachment.
[console_log_page_callback.zip](https://github.com/signalpoint/DrupalGap/files/142160/console_log_page_callback.zip)

**Comment by signalpoint** [comment]
@ahmedbarwary Next time, please just paste the code here... it's much faster to scan than downloading, extracting, opening. Thanks.

Anyways, you need to use a unique `id` attribute on each View, because as you navigate pages stay in the DOM, so the second page loads and then injects its View contents into the first pages view.

**Comment by 1nf1n7y** [comment]
thank you very much @signalpoint  . the problem solved by using unique id attribute.
