### ISSUE TITLE
Add hook_menu_alter

### ISSUE THREAD

**Issue by Digeridoo** [signalpoint/DrupalGap#735]
There is no way to alter the menu. Maybe, it does not exists by some serious reason. If not, please add such hook.

**Comment by signalpoint** [comment]
@Digeridoo There isn't that hook exactly, but there is one that can accomplish the same thing for now:
- http://docs.drupalgap.org/7/Menus/Altering_Existing_Menu_Links
- http://api.drupalgap.org/7/global.html#hook_deviceready

**Comment by Digeridoo** [comment]
Oh, I have missed it in docs. Thanks.

I have seen (in the source code) the possibility to modify menu directly using **drupalgap.menu_links**. I thought that it "private" variable which shouldn't be touched :) Maybe, it will be good to have hook_menu_alter. And it will be similar to drupal api. But it is not important now, since we have a way described in docs.
