### ISSUE TITLE
How to prevent order of nodes loaded by a view

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#736]
I'm want to print a list of nodes. The nids of the nodes are generated by a view.

Here is my code:

```
function my_module_node_page_view_alter_task2(node, options) {
        var build = {};
        // build task
        build['task'] = {
            theme: 'my_module_node',
            node: node
        }

        build['task_submissions'] = {
            markup: '<div class="task-submissions"></div>'
        }

        var path_to_view = 'll-rest-task-submission-nodes/' + node.nid;
        views_datasource_get_view_result(path_to_view, {
            success: function (data) {
                if (data.nodes.length > 0) {
                    var items = [];
                    $.each(data.nodes, function(index, object){
                        var submission = object.node;
                        node_load(submission.nid, {
                            success:function(node){
                                var $output = theme('my_module_node', { node: node } );
                                $('.task-submissions').append($output);
                            }
                        });
                    });
                }
            }
        });

        options.success(build);
}
```

The nodes are loaded async, so the order is not the same order as in view result. Do you have an advice to solve this?

**Comment by signalpoint** [comment]
@luxio I would not recommend loading multiple nodes like this, instead I'd use a single call to node_index() after I set aside all the node ids retrieved from the view. You would need this patch to be able to multi load entities: https://www.drupal.org/node/2601764 - the patch would be needed until it gets rolled into the Services module

**Comment by luxio** [comment]
Thanks. I will try this. I thought about using node_index(), but I did not used it because it didn't return the full entity. Thanks for your great and **prompt** support.

**Comment by luxio** [comment]
Do you mean something like this:

```
        // get submissions
        var path_to_view = 'll-rest-task-submission-nodes/' + node.nid;
        views_datasource_get_view_result(path_to_view, {
            success: function (data) {
                if (data.nodes.length > 0  ) {
                    var submissions = [];

                    for (var i = 0, l = data.nodes.length; i < l; i++) {
                        submissions.push(data.nodes[i].node.nid)

                    }

                    // get node submissions
                    var query = {
                        parameters: {
                            'type': 'post',
                            'nid': submissions,
                        },
                        'pagesize': 100,
                    };

                    node_index(query, {
                        success:function(nodes){
                            console.log('nodes -', nodes);
                            var $output = '';
                            for (var i = 0, l = nodes.length; i < l; i++) {
                                $output = theme('liveloop_node', { node: nodes[i] } );
                                $('.task-submissions').append($output);
                            }
                        }
                    });

                }
            }
        });
```

**Comment by signalpoint** [comment]
@luxio Yes, except do `'nid': submissions.join(','),` to make it a comma separated list of node ids.

**Comment by luxio** [comment]
I have applied the patch in https://www.drupal.org/node/2601764 to load multiple entities. 

The result does not contain the `content` property of the node, which `node_load()` delivers. Is there a way to receive also the `content` property which node_index()?

**Comment by signalpoint** [comment]
@luxio Yes, pass each individual node to: http://api.drupalgap.org/7/global.html#drupalgap_entity_render_content

`drupalgap_entity_render_content('node', nodes[i])`

**Comment by luxio** [comment]
Thank's. It's working. 👍

**Comment by luxio** [comment]
I have still a question. The topic of this issue was "How to prevent order of nodes loaded by a view?"

Now using index() the nodes does not come in the order of the nids of the view (submissions). Is there a way to prevent the order of the nids?

**Comment by signalpoint** [comment]
@luxio What do you want to order it by? Post date descending, updated date descending, etc, ?

**Comment by luxio** [comment]
In the view they are sorted by `Updated/commented date (desc)`.

**Comment by signalpoint** [comment]
Add this to your index query object:

```
query.options.orderby = { changed: 'desc' };
```

**Comment by luxio** [comment]
This would sort them after the change timestamp.  The sort option  `Updated/commented date (desc).` in views would check both, the `changed` and the `last_comment_timestamp` property. If there is no way of keeping the order of the nid array passed to index(), I will have to write my own sort function in js.
