### ISSUE TITLE
How to wrap text for views _list_row?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#737]
When you create a view page:
http://docs.drupalgap.org/7/Views/Displaying_a_View/Views_Render_Array

text typically goes off the right side of the screen if it is longer than the width of the screen. How do I wrap the text?

**Comment by signalpoint** [comment]
@mkinnan What does your row_callback function look like?

**Comment by mkinnan** [comment]
I want to wrap the comment body text so is readable. I am trying to create a list of comments for a node.

```
function my_module_comments_list_row(view, row) {
  try {
    var html = '<table><tr><th width="50px"><img src="' + row.picture.src + '" alt=""/></th><th style="font-size:15px">' + row.author + '<br /><i style="font-size:10px">' + row.postdate + '</i></th></tr>' + 
    '<tr><td colspan="2">' + row.body + '</td></tr>' +
    '</table>';

    return html;

  }

  catch (error) { console.log('my_module_comments_list_row - ' + error); }
}
```

**Comment by signalpoint** [comment]
@mkinnan What if you wrap the `row.body` in a paragraph tag inside the td?

**Comment by mkinnan** [comment]
Still doesn't work

![comments](https://cloud.githubusercontent.com/assets/13283396/13376330/b6b250a6-dd76-11e5-8b9c-7f7c9d19136f.PNG)

**Comment by mkinnan** [comment]
The issue is the theme selected to render the content. Here is my workaround:

Display your view manually:
http://docs.drupalgap.org/7/Views/Displaying_a_View/Manually_Display_View

Add this function to your custom module (it could probably using some better coding):

```
function theme_unformatted_list(variables) {
  try {
    var type = 'text';
    var html = '';
    html += '<' + type + ' ' + drupalgap_attributes(variables.attributes) + ' style="list-style-type:none">';
    if (variables.items && variables.items.length > 0) {
      for (var index in variables.items) {
        if (!variables.items.hasOwnProperty(index)) { continue; }
        var item = variables.items[index];
        html += '<li>' +  item + '</li>';
      }
    }
    html += '</' + type + '>';

    return html;

  }

  catch (error) { console.log('unformatted_list - ' + error); }

}
```

Modify the **theme** of the **my_module_articles_page** to reflect **unformatted_list**.

Do something like this for the **pageshow** function:

```
function my_module_articlecomments_pageshow(thenodid) {
  var path_to_view = 'dg-comments/' + thenodid;
  views_datasource_get_view_result(path_to_view, {
      success: function (data) {
        if (data.comments.length > 0) {
          var items = [];
          $.each(data.comments, function(index, object){
              var comment = object.comment;

              if (empty(comment.picture.src)) {
                var userpic = 'http://example.com/sites/default/files/styles/thumbnail__40x40_/public/pictures/picture-default.jpg?itok=JzApsZvs';
              } else {
                var userpic = comment.picture.src;
              }

              items.push(

                '<table class="commentrow"><tr><th width="50px"><img src="' + userpic + '" alt=""/></th><th style="font-size:15px">' + comment.author + '<br /><i style="font-size:10px">' + comment.postdate + '</i></th></tr>' + 
                '<tr><td colspan="2">' + comment.body + '</td></tr>' +
                '</table>'                

              );
          });
          drupalgap_item_list_populate('#my_articlecomments_list', items);
        }
      }
  });
}
```

And you could get comments displayed like:

![comments-2](https://cloud.githubusercontent.com/assets/13283396/13382684/207706d2-de38-11e5-9e61-7cb9b71cf3b1.PNG)

**Comment by mkinnan** [comment]
So, I closed prematurely. I had a specific view loaded as my homepage to make refreshing easier. When I view comments (via a button link on each node), I am not getting any comments returned.

I have noticed this error:

`drupalgap_item_list_populate - Error: cannot call methods on listview prior to initialization; attempted to call method 'refresh'`

**Comment by mkinnan** [comment]
To wrap the text, use CSS `word-wrap: normal`.
