### ISSUE TITLE
file_entity_field_formatter_view - ReferenceError: media_field_formatter_view is not defined

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#746]
I have the media module installed and I'm trying to show a an image in a file field. I have set the format to `Rendered file` and the view mode to `Default`.

I'm getting an error:

```
file_entity_field_formatter_view - ReferenceError: media_field_formatter_view is not defined
```

The `file.js` module calls `media_field_formatter_view()`. Do I have have to create the `media_field_formatter_view()` function myself in a custom module?

**Comment by signalpoint** [comment]
@luxio Sounds like you don't have the media module included in the settings.js file...? The media_field_formatter_view() function should at least get fired if the module is loaded properly. https://github.com/signalpoint/media/blob/7.x-1.x/media.js

**Comment by luxio** [comment]
Yes, you are right.

I have looked at the [module page](http://www.drupalgap.org/project/modules?field_project_core_tid=All&field_project_sandbox_value=All), but the media module was not listed there.

**Comment by signalpoint** [comment]
@luxio Thank you for pointing that out, I've added it to the list: http://drupalgap.org/project/media

The module doesn't really do much, I think I just forward it along to other formatters for now.
