### ISSUE TITLE
Form values are not cleared

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#749]
I have modified the `node_edit` form with `hook_form_alter()`.

When I create a 2nd node, the form items values are prefilled with the values of the 1st node, I have created. 

Do I have to clear the from / values after submitting.

**Comment by signalpoint** [comment]
@luxio You shouldn't have to, I believe DG removes the form from local storage after submission. It sounds like the actually page holding the form is still in the DOM. So you could call http://api.drupalgap.org/7/global.html#drupalgap_remove_page_from_dom or http://api.drupalgap.org/7/global.html#drupalgap_remove_pages_from_dom in a custom success handler attached to the form, or use the reloadPage option when navigating users back to the content creation form: http://docs.drupalgap.org/7/Pages/Reloading_Pages

I guess DG should be smart enough to remove a node/add/\* page from the DOM, but I guess it isn't. If it isn't, then we could mark this as a bug. But for now, I'm sure there are some programmable ways around it.

**Comment by luxio** [comment]
Thank you. If I reload the page using `hook_menu()` the form is cleared.
