### ISSUE TITLE
Nodes Viewed by User Not Being Recorded in Database

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#753]
I have noticed that when viewing a node in an app, it does not appear to get recorded in the history table that the user has viewed the node.

I am currently implementing this in my app to change the color of the node titles in my view (http://docs.drupalgap.org/7/Views/Displaying_a_View/Views_Render_Array/Other_Views_Render_Array_Examples/Node_has_New_Content) as a means to show nodes with new content. When I click on a node in the app and then go back to my view, the text color should change but it doesn't. When I click on the node in the drupal website, then go to the view in the app it shows there is new content because it was already viewed. 

Doing that views title color change is the only way I noticed views not appearing to be recorded as 'viewed' ... that and confirming a lack of entries in the history table.

**Comment by jomarocas** [comment]
is possible for views cache, when i disable this, the node in the views appear instantly
and try yo use attributes "reload: true" when you use the app for reload a url

```
Drupal.settings.cache.views = {
  enabled: false,
  expiration: 100,
};
```

**Comment by mkinnan** [comment]
The issue isn't views, but with Drupalgap not recording the user visiting a node into the history table. It's a feature that does not exist at this time.

**Comment by signalpoint** [comment]
What core/contrib module provides this feature in Drupal?

**Comment by mkinnan** [comment]
I thought this was a core component that was built in by default? It should be eaay to find by just searching in all Drupal files for keyword 'history' to see which files are used ...

**Comment by mkinnan** [comment]
Finally got around to looking at this. It is the **node** module in core that has the following:

```
// Update the history table, stating that this user viewed this node.
node_tag_new($node);
```

which calls this:

```
/**
 * Updates the 'last viewed' timestamp of the specified node for current user.
 *
 * @param $node
 *   A node object.
 */
function node_tag_new($node) {
  global $user;
  if ($user->uid) {
    db_merge('history')
      ->key(array(
        'uid' => $user->uid,
        'nid' => $node->nid,
      ))
      ->fields(array('timestamp' => REQUEST_TIME))
      ->execute();
   }
}
```

how difficult is this to implement into drupalgap?

**Comment by signalpoint** [comment]
@mkinnan In a custom Drupal module, you should be able to do this:

```
/**
 * Implements hook_services_request_postprocess_alter().
 */
function my_module_services_request_postprocess_alter($controller, $args, &$result) {
  if ($controller['callback'] == '_node_resource_retrieve') {
    node_tag_new($result);
  }
}
```

**Comment by mkinnan** [comment]
Gave that a shot ... didn't appear to work for me.

**Comment by mkinnan** [comment]
It appears to work now. Thanks! Not sure what the issue was yesterday.
