### ISSUE TITLE
Error on Creating New Users

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#754]
Cannot create new users using the lastest versions of jdrupal, drupalgap sdk, etc.

`drupalgap.js:3868 _drupalgap_form_submit_response_errors - SyntaxError: Unexpected token <
drupalgap.js:13851 user_services_postprocess - SyntaxError: Unexpected token <`

**Comment by signalpoint** [comment]
What data is being posted? You can find that in the Network tab, and find the entry that is POSTing to /drupalgap/user/register.json

This issue may be related: https://www.drupal.org/node/2686047

**Comment by mkinnan** [comment]
I don't have any extra user fields. Network tab:

![network](https://cloud.githubusercontent.com/assets/13283396/13764886/66768696-ea11-11e5-8aa8-d14cbecfedb0.PNG)

**Comment by mkinnan** [comment]
Website log errors:

`Warning: array_merge(): Argument #1 is not an array in field_default_extract_form_values() (line 36 of /var/www/html/modules/field/field.default.inc).`

`Recoverable fatal error: Argument 2 passed to drupal_array_get_nested_value() must be an array, null given, called in /var/www/html/modules/field/field.default.inc on line 38 and defined in drupal_array_get_nested_value() (line 6787 of /var/www/html/includes/common.inc).`

Both **Location: drupalgap/user/register.json**

**Comment by mkinnan** [comment]
![more](https://cloud.githubusercontent.com/assets/13283396/13765445/c636f642-ea16-11e5-9af2-d669564e89c9.png)

**Comment by mkinnan** [comment]
![more-error](https://cloud.githubusercontent.com/assets/13283396/13766712/9a77596a-ea21-11e5-9edc-be5233b56e91.PNG)

**Comment by utsunomiyajp** [comment]
I have the same error after upgradeing Drupal core to 7.43.
The error was not solved evern after updated latest drupalgap-7.x-1.x-dev 2016-Mar-09.

**Comment by signalpoint** [comment]
Well the jDrupal user registration unit test is passing fine. Here's the example POST data:

`{name: "QCT2ZuEytx", mail: "IFzXfSnNNq@example.com", pass: "ZSWst2cI3R", pass2: "ZSWst2cI3R"}`

Please share the data that is being POSTed by the app, you can get that by clicking on the `?q=drupalgap/user/register.json` in the `Network` tab, then scrolling down to the `Request Payload` section.

**Comment by mkinnan** [comment]
![payload](https://cloud.githubusercontent.com/assets/13283396/13798626/9fd4b57e-ead5-11e5-8c60-2ffc1204b64b.PNG)

**Comment by mkinnan** [comment]
`{"name":"demo","mail":"demo@example.com","conf_mail":"demo@example.com","pass":"mypa$$","pass2":"mypa$$"}`

**Comment by mkinnan** [comment]
Looking at the function that is triggering an error in the **field.default.inc**:

```
function field_default_extract_form_values($entity_type, $entity, $field, $instance, $langcode, &$items, $form, &$form_state) {
  $path = array_merge($form['#parents'], array($field['field_name'], $langcode));
  $key_exists = NULL;
  $values = drupal_array_get_nested_value($form_state['values'], $path, $key_exists);
  if ($key_exists) {
    // Remove the 'value' of the 'add more' button.
    unset($values['add_more']);
    $items = $values;
  }
}
```

var_dump($path) reveals there is nothing and is NULL.

var_dump($form)
`string(18) "user_register_form"`

var_dump($form['#parents'])
`string(1) "u"`

var_dump($field)

```
array(16) {
  ["settings"]=>
  array(4) {
    ["handler"]=>
    string(2) "og"
    ["handler_submit"]=>
    string(14) "Change handler"
    ["handler_settings"]=>
    array(3) {
      ["behaviors"]=>
      array(1) {
        ["og_behavior"]=>
        array(1) {
          ["status"]=>
          bool(true)
        }
      }
      ["target_bundles"]=>
      array(0) {
      }
      ["membership_type"]=>
      string(26) "og_membership_type_default"
    }
    ["target_type"]=>
    string(4) "node"
  }
  ["entity_types"]=>
  array(0) {
  }
  ["translatable"]=>
  string(1) "0"
  ["storage"]=>
  array(5) {
    ["type"]=>
    string(17) "field_sql_storage"
    ["settings"]=>
    array(0) {
    }
    ["module"]=>
    string(17) "field_sql_storage"
    ["active"]=>
    string(1) "1"
    ["details"]=>
    array(1) {
      ["sql"]=>
      array(2) {
        ["FIELD_LOAD_CURRENT"]=>
        array(1) {
          ["field_data_og_user_node"]=>
          array(1) {
            ["target_id"]=>
            string(22) "og_user_node_target_id"
          }
        }
        ["FIELD_LOAD_REVISION"]=>
        array(1) {
          ["field_revision_og_user_node"]=>
          array(1) {
            ["target_id"]=>
            string(22) "og_user_node_target_id"
          }
        }
      }
    }
  }
  ["foreign keys"]=>
  array(1) {
    ["node"]=>
    array(2) {
      ["table"]=>
      string(4) "node"
      ["columns"]=>
      array(1) {
        ["target_id"]=>
        string(3) "nid"
      }
    }
  }
  ["indexes"]=>
  array(1) {
    ["target_id"]=>
    array(1) {
      [0]=>
      string(9) "target_id"
    }
  }
  ["id"]=>
  string(1) "7"
  ["field_name"]=>
  string(12) "og_user_node"
  ["type"]=>
  string(15) "entityreference"
  ["module"]=>
  string(15) "entityreference"
  ["active"]=>
  string(1) "1"
  ["locked"]=>
  string(1) "0"
  ["cardinality"]=>
  string(2) "-1"
  ["deleted"]=>
  string(1) "0"
  ["columns"]=>
  array(1) {
    ["target_id"]=>
    array(4) {
      ["description"]=>
      string(28) "The id of the target entity."
      ["type"]=>
      string(3) "int"
      ["unsigned"]=>
      bool(true)
      ["not null"]=>
      bool(true)
    }
  }
  ["bundles"]=>
  array(1) {
    ["user"]=>
    array(1) {
      [0]=>
      string(4) "user"
    }
  }
}
```

**Comment by utsunomiyajp** [comment]
I solved this problem updating Services module 7.x-3.13 to 7.x-3.14. Sorry for bothering.

**Comment by signalpoint** [comment]
@utsunomiyajp No problem, thank you for sharing your solution.

**Comment by mkinnan** [comment]
Confirmed updating services fixed the issue.
