### ISSUE TITLE
Error: not removing the current page (node_add_article) from the DOM!

### ISSUE THREAD

**Issue by max1020** [signalpoint/DrupalGap#776]
this warning shows up in Xcode when adding an article with the default app using v 1.15 and drupal 7.43: 

`WARNING: drupalgap_remove_page_from_dom() - not removing the current page (node_add_article) from the DOM!`

I tried it with iPhone 5 and iPhone6 on the simulator.

The node is correctly created in drupal, but there is no redirection or success message shown after the node has been posted. One can also not navigate through the app anymore and is stuck on the node_add page.

EDIT: in the browser and with Chrome Ripple enabled it works just fine.

**Comment by signalpoint** [comment]
@max1020 Will you please describe your content type(s) and field(s) involved here?

I'd recommend connecting the Safari debugger to the simulator, then watching the Network tab. That'll reveal to you the POST call that is made to `?q=drupalgap/node.json`, to properly debug this we would want to know the `JSON` data that is being posted, to the server, and what response and http status codes are returned from the server.

As for the warning about not removing the current page, this means someone (maybe DrupalGap core under certain circumstances) is explicitly trying to remove the current page from the DOM, which isn't possible AFAIK with jQuery Mobile.

**Comment by max1020** [comment]
@signalpoint 

Thanks for the feedback. It was just an article using default DrupalGap. I didnt make any changes to the default DrupalGap app.

I have tried it anew (downloading DrupalGap, creating dummy phonegap app, building and running) on the device (iPhone 4) now and it works. It also works on the simulator like a charm. 

I don't know what was causing the issue the last time - as the node has been created on the backend. The response codes were OK. I close the issue.
