### ISSUE TITLE
How to render views results obtained by a custom search form

### ISSUE THREAD

**Issue by puidu** [signalpoint/DrupalGap#778]
Hi,
I'm absolutely new to the world of drupalgap and not very handy with jQuery.
I have following problem. I have a form that based on submitted values tray to get a filtered remote json views. Let me show the code:

in the hook_form_submit I have

```
var pclass = form_state.values['property_class'];
        var location = form_state.values['location'];  
        var path = 'search_results/'+pclass+'/'+location;
        drupalgap_goto(path, {reloadPage:true});
```

then in the hook_menu

```
items['search_results/%/%'] = {
            title: 'Property in Italy',
            page_callback: 'italy_main_search_result_page',
            pageshow: 'italy_main_search_result_pageshow',
            options:{
                reloadPage:true
            },
            page_arguments: [1,2]
        };
```

The function italy_main_search_result_pageshow get the remote filtered views and returns the results. 

The problem is that all works fine just for the first submission, but from the second submission on I get a "Sorry, the page you requested was not found".

Looking at the documentation here http://docs.drupalgap.org/7/Views/Views_Exposed_Filters I read that it's possible to have a custom form to filter a views, but I didn't found the way to do that.

Could you please suggesst how to proceed or adding an example in the guide?

Thank you in advance

**Comment by signalpoint** [comment]
@puidu Do a `console.log(path);` in the submit handler to make sure you're actually putting values in the path. What are those values?

**Comment by puidu** [comment]
@signalpoint  thank you for your reply. 

The console.log(path) returns correct values every time I submit the form. Example values are 'search_results/16511/13011', 'search_results/all/13011', 'search_results/16511/all', 'search_results/all/all'. Whatever is the first submission/path works correctly and returns the appropriate results. From the second on, I get the message I sent in my previous post.

Note. The "all" parameter is used as exception on conditional filter on my view, while numbers are taxonomy term IDs.

With just one parameter passed to the hook_menu ( items['search_results/%'] ) all works fine.

It seems that from second time on, the app isn't able to match the path in the menu as it was previously associated with another.

**Comment by signalpoint** [comment]
@puidu Please share your implementation of `italy_main_search_result_page()`.

**Comment by puidu** [comment]
@signalpoint thanks.
Here it is

```
function italy_main_search_result_page(pclass,location) {
    var content = {};
    content['search_properties'] = {
        theme: 'jqm_item_list',
        title: 'Property Results',
        items: [],
        options:{
            reloadPage:true
        },
        attributes: { id: 'property_list'+pclass+location }
    };
    return content;
}
```

and 

```
function italy_main_search_result_pageshow ( pclass , location ) {
    var path_to_view = 'app/property/search/' + pclass + '/' + location;
    views_datasource_get_view_result( path_to_view, {
    success: function (data) {
           if (data.nodes.length > 0) {
                                     var items = [];
                                     $.each(data.nodes, function(index, object){
                                            var node = object.node;
                                            items.push(
                                                       l(node.title, 'node/' + node.nid)
                                                       );
                                            });
                                     drupalgap_item_list_populate('#property_list' + pclass + location, items);
                                     }
                                     }
                                     });
}
```

**Comment by puidu** [comment]
@signalpoint Sorry for the lack of indentetions, I wasn't able to let it work here

**Comment by signalpoint** [comment]
@puidu That all looks fine, maybe try a Views Render Array instead: http://docs.drupalgap.org/7/Views/Displaying_a_View/Views_Render_Array - using the same technique as you did above by appending a unique id with the pclass and location.

But if I understand correctly, when you add the second page argument to the path, then the page itself doesn't even work in DrupalGap.

**Comment by puidu** [comment]
Exactly, the problem is not the way I render the results, but the fact that the second time I call the url 'search_results/%/%' with different parameters from the ones used the first time, the path "isn't recognised".
My question is: is my approach correct? I mean, is it correct to filter view results in this way, using the drupalgap_goto into the _hook_form_submit or there is a better "approach"?
If you want I can send the entire module file via email.

**Comment by puidu** [comment]
@signalpoint did you have occasion to take a look? Do you think the behaviour I detected is a sort of bug?

**Comment by signalpoint** [comment]
@puidu Here's a technique to utilize Input Widgets as custom filters to auto refresh a Views Render Array using Contextual filters: http://docs.drupalgap.org/7/Views/Views_Contextual_Filters - thus simulating the rendering of views results with a custom form

In regards to the routing of `search_results/%/%`, admittedly the DrupalGap 7 router baked over jQuery Mobile is insufficient and very touchy, I've had best results utilizing only single `%` parameters with my paths. The DrupalGap 8 router is a total rewrite and much more flexible. DrupalGap 8 (with the help of a DrupalGap 8 contrib module called `d7`) can be utilized alongside a Drupal 7 website.
