### ISSUE TITLE
Bug in drupal_load_locales function

### ISSUE THREAD

**Issue by KerZoli** [signalpoint/DrupalGap#790]
Hello!

I created my own custom module in drupalgap and created a romanian language file for translation, but I always got undefined for language key when the file was loaded in drupalgap_file_get_contents(). 

I checked the drupalgap_load_locales function, and I think I found the problem:

on line 545: var language_code = languages[i];

I think it should be var language_code = languages[j];

Tested the changes and language file loads properly know without problems.

**Comment by signalpoint** [comment]
@KerZoli thank you!
