### ISSUE TITLE
drupalgap_goto_generate_page_and_go error

### ISSUE THREAD

**Issue by mattshoaf** [signalpoint/DrupalGap#793]
This is seemingly random, but I'm wondering if anyone else has been able to narrow it down. Occasionally drupalgap_goto() fails with the error logged as:

> drupalgap_goto_generate_page_and_go - TypeError: Cannot read property 'contentWindow' of undefined jdrupal-7.0.4.min.js:1

**Comment by signalpoint** [comment]
@mattshoaf I haven't ever seen that one before. I just did a quick search through the entire source code for both DrupalGap and jDrupal, and there is not a single line with `contentWindow` in it.

Does `contentWindow` appear in your custom code anywhere? If so, that's a likely suspect. If not, it sounds like jQuery Mobile might be struggling to do something. Without more context about being able reproduce this type error, it's going to be very difficult to debug.

**Comment by mattshoaf** [comment]
You're right, I just did a search through my code folder, `contentWindow` is used throughout jQuery, and I have one call to it to stop a youtube video from playing on page transitions.

Thanks

Edit for anyone else that runs into this: it looks like it drupalgap removes all the pages from the DOM after a user logs in (at least that's the case with my app, it's a custom login form so I can't be sure if that's typical for drupalgap). There is a dynamic function that was built looking for an iFrame id, jQuery can't find the ID anymore on page changes after it's removed. Wrap it in an if and it's good to go.
