### ISSUE TITLE
Multiple image fields don't UPDATE

### ISSUE THREAD

**Issue by soketes** [signalpoint/DrupalGap#797]
Hi, Im trying the last weeks about this, I have a node type with various single imagefields, when I upload this images for first time, upload well. BUT... when I try to update a node that have any image previously uploaded don't update (and don't upload) the new image.

**Comment by signalpoint** [comment]
@soketes Please share the JSON data you are POSTing to create the node, then also share the JSON data you are PUTting to update the node. Without that and console log information, I will not be able to help debug this.

**Comment by soketes** [comment]
Hi tyler,

When I trying to resolve this issue, I see that the function: _image_field_form_process skip the empty fields without value:  if (!image_phonegap_camera_options[name][0]) { break; } but it does the function skip all the fields. Example

I have a Image field with selected image (call it imgF_1)

Another image field called without selected image  (imgF_2)

Another  Image field with selected image (call it imgF_3)

When I save only imgF_1 its saved.

I resolve this with:
if (!image_phonegap_camera_options[name][0]) { continue; } (it's working)

Its possible that the problem in "Multiple image fields don't UPDATE" be this:
if (form_state.values[name][lng][0] != '') { break; }

to:

if (form_state.values[name][lng][0] != '') { continue; }

thanks

**Comment by soketes** [comment]
I try this: if (form_state.values[name][lng][0] != '') { continue; } and its working!!!

Multiple image fields don't UPDATE #797 SOLVED

Regards

**Comment by signalpoint** [comment]
@soketes thank you for pointing this out. I've committed the fix you identified.
