### ISSUE TITLE
Function only called the first time

### ISSUE THREAD

**Issue by max1020** [signalpoint/DrupalGap#798]
Hello,

I am using drupal module 1.15 and drupalgap 7.0.1 (in bin folder). I just added a menu link and the custom module called "main" below. 

On the iOS simulator (tried iPhone4S, iPhone5, iPhone6) the console.log('inside main_hello_world') function inside main_hello_world_page() is only called the first time i click the menu link for that page. When I click another menu link and access this page via the menu link, there is no console.log entry anymore so it looks as if the function is not called anymore.

```
 function main_menu() {
   try {
    var items = {};
    items['hello_world'] = {
    title: 'Hello DrupalGap',
    page_callback: 'main_hello_world_page'
    };
    return items;
}
catch (error) {  console.log('main_menu - ' + error); }
}

function main_hello_world_page() {
try {
    console.log('inside main_hello_world');
}  
 catch (error) { console.log('main_hello_world_page - ' + error); }
}
```

Here the log from Xcode:

```
2016-05-25 10:19:32.687 Name of App[3171:62921] 200 - OK
2016-05-25 10:19:40.257 Name of App[3171:62921] inside main_hello_world (only called the first time)
2016-05-25 10:19:48.770 Name of App[3171:62921] GET: http://capps-testdrupal.rhcloud.com/?q=drupalgap/taxonomy_vocabulary.json
2016-05-25 10:19:49.122 Name of App[3171:62921] 200 - OK
```

Any ideas?

**Comment by signalpoint** [comment]
@max1020 Thank you for the detailed description. By default, pages are left in the DOM as you navigate around the app, so when you revisit them they are already loaded. There are definite pros/cons to this Multi Page Application approach (DrupalGap 8 will be a Single Page Application).

If you'd like pages to be rebuilt upon navigating, I'd recommend reading up on reloading pages: http://docs.drupalgap.org/7/Pages/Reloading_Pages

**Comment by max1020** [comment]
@signalpoint Many thanks for the explanation. great documentation, btw!
