### ISSUE TITLE
How to target/style the user edit page?

### ISSUE THREAD

**Issue by max1020** [signalpoint/DrupalGap#800]
I would like to remove the page title from the user page. I can target an individual node page titles (172 in the example) like below in a custom CSS file.

But for the user profile the div_id's are dynamic/user dependent (e.g. user_1) and this approach does not work. Any ideas?

```
h1#drupalgap_page_title_node_172 {
display: none;
}
```

**Comment by signalpoint** [comment]
@max1020 You can remove the `name` placeholder from the `user-profile.tpl.html` file in your theme. Or (maybe) use `hook_entity_view_alter()` in your custom DG module, to remove the `name` render array from the build object.
- https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/themes/easystreet3/user-profile.tpl.html
- http://api.drupalgap.org/7/global.html#hook_entity_view_alter

Or with the latest dev version of the SDK, you can use CSS:

```
.user-view h2:first-child {
  display: none;
}
```

**Comment by max1020** [comment]
@signalpoint: Many thanks for the info!
