### ISSUE TITLE
Comment Form Disappears on Nodes

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#803]
In **settings.js**, global caching is set for 60 seconds. Nodes are set to have comment form displayed.

I view node A and see the comment form. Then I view node B and see the comment form. I go back to view node A and the comment form is gone. Go back to node B and the comment form is gone there too. I wait 60 seconds, and then node form comes back after viewing the node again.

This doesn't happen in Ripple Emulator, but it happens in Android (and probably iOS). No error log messages are happening from USB debugging.

**Comment by signalpoint** [comment]
@mkinnan Try adding this to comment.js in DG core: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/comment/comment.js#L167

```
// Append the node id the comment form id.
form.id += '_' + comment.nid;
```

Try placing it directly after those default values are set. Rebuild the bin/ files, and give that a shot.

**Comment by mkinnan** [comment]
That works ... but, the text a user enters into the comment form stays and isn't cleared out when the comment is saved.

**Comment by signalpoint** [comment]
@mkinnan Oops, one more spot we need:

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/comment/comment.js#L256

Add the underscore and node id to the end of the jQuery selector on that line.

**Comment by mkinnan** [comment]
That appeared to work. Thanks!

**Comment by signalpoint** [comment]
@mkinnan Awesome, please submit a pull request if you get a chance, that'll be a big improvement.
