### ISSUE TITLE
After posting comment on node, the comment is not shown on the node and navigating back to the node results in page failing to render

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#81]

**Comment by signalpoint** [comment]
https://github.com/signalpoint/DrupalGap/issues/88

**Comment by amitsedai** [comment]
This issue persists even now. After posting comment in the node, loading... popup shows but then stops.

**Comment by signalpoint** [comment]
Now, navigating back to the node, the page no longer fails to render. But the new comment doesn't show up in the listing, and the old form values from the previously posted comment are still in the form.

#180 is related to this issue.

**Comment by signalpoint** [comment]
This has been fixed.
