### ISSUE TITLE
node_load i need the response later of success

### ISSUE THREAD

**Issue by jomarocas** [signalpoint/DrupalGap#811]
Hi @signalpoint 

i try this function and many more to get the result of node. when i make node_load, but alwys the value of handleData is null; why the response no success if when i make in console.log(tmp) appear all log of node, thanks

```
//first function
    var handleData = function () {
      //var tmp = NULL;
      return node_load(id.nid, {
        async: false,
        success:function(node){
          tmp = node;
        }
      });
  //return tmp;
    }();

//second function
```

**Comment by signalpoint** [comment]
I wouldn't recommend using `false` for `async`, instead use synchronous callbacks like so:

```
var handleData = null;
firstFunction();

function firstFunction() {
  node_load(123, {
    success: function(node) {
      handleData = node();
      secondFunction();
    }
  });
}

function secondFunction() {
  alert(handleData.title);
}
```

**Comment by jomarocas** [comment]
excuse me @signalpoint 

why node() function?

and same no working for me, i explain what i want to make if is possible more simply.

 i want edit my custom form, make a edit form, but for this i need use the fields that i send in a drupal node, but this custom module no need used, then i need load all values of node and print this values in a custom form.

i use a hook menu for send values of nid. and this is my custom form

```

      var node_elements = null;
      function firstFunction(id) {
        node_load(id.nid, {
          success: function(node) {
            console.log('in the success load');//console.log(handleData);
            ajaxCallBack(node);
          }
        });
      }

      function ajaxCallBack(retString){
        console.log('enter to ajaxCallBack');
        node_elements = retString;
        console.log('value of' + node_elements);
      }
    });


function custom_module_medicamentos_form_edit(form, form_state, id) {
  try {

    console.log('first enter');
    firstFunction(id);
    //var result = handleData();
    console.log('later of first function'); 
    console.log(node_elements);

}
```

later of this this is the logs

```
[phonegap] [console.log] first enter
[phonegap] [console.log] later of first function
[phonegap] [console.log] null
[phonegap] [console.log] custom_module_medicamentos_form_edit - ReferenceError: node is not defined
[phonegap] [console.log] _drupalgap_form_elements_set_defaults - TypeError: Cannot read property 'elements' of undefined
[phonegap] [console.log] image_form_alter - TypeError: Cannot read property 'entity_type' of undefined
[phonegap] [console.log] _drupalgap_form_elements_set_defaults - TypeError: Cannot read property 'elements' of undefined
[phonegap] [console.log] drupalgap_form_local_storage_save - TypeError: Cannot read property 'id' of undefined
[phonegap] [console.log] in the success load
[phonegap] [console.log] enter to ajaxCallBack
[phonegap] [console.log] value of[object Object]
```

then i look that go to node load and no enter to success and no save the values or no enter first to firstFunction()

thanks if any help for this

**Comment by signalpoint** [comment]
@jomarocas Try using an empty `div` in your `page_callback`, then in your `pageshow` callback, load the node using async true, then inject the html results of `drupalgap_get_form('my_custom_form', node)`  into that waiting div. This will deliver the fully loaded node to your form builder function, then you can build the form as necessary.

**Comment by jomarocas** [comment]
@signalpoint sorry tyler but you can give me an example.

i try to make something like that, but later of inject html im lost, how inject the html of drupal_get_form in the empty callback

```
    items['medicaments-edit/%'] = {
      title: t('Medicaments'),
      'page_callback': 'custom_module_medicamentos_form_edit_empty',
      'page_arguments': [1],
      'pageshow': 'custom_module_medicamentos_form_edit_pageshow',
      options:{
        reloadPage:true,
      }
    };


function custom_module_medicamentos_form_edit_empty(nid){
  return '<div id="my-div-' + nid + '"></div>';
}

function custom_module_medicamentos_form_edit_pageshow(nid){
  node_load(nid, {
    success: function(node) {
      var html = drupalgap_get_form('custom_module_medicamentos_form_edit', node);
      $('#my-div-' + nid).html(html).trigger('create');
    }
  });
}

function custom_module_medicamentos_form_edit(form, form_state, node) {
  alert('node is available in my form builder! ' + node.title);
}
```

**Comment by signalpoint** [comment]
@jomarocas I've updated your comment above with the correct syntax to use.

**Comment by jomarocas** [comment]
Oh yes, thanks @signalpoint  working perfectly, nice example, and close the issue

**Comment by signalpoint** [comment]
This is even easier now, see the examples here:
- http://docs.drupalgap.org/7/Entities/Rendering_Entities
- http://docs.drupalgap.org/7/Entities/Editing_Entities
