### ISSUE TITLE
Order of Comments on Nodes

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#815]
Comments on nodes are ordered newest to oldest.

When adding a new comment it gets added at the bottom of the comments. This comment doesn't get moved to the top of the comments until cache is cleared.

Is this the desired behavior?

How would i change comments to be oldest to newest?

**Comment by signalpoint** [comment]
@mkinnan https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/comment/comment.js#L252

We can see here it appends it to the list. This function would need to be expanded to take a look at the comment settings on the content type in question, then either append/prepend it accordingly. The settings are probably buried somewhere in the System Connect JSON results. If not, we'd want to have that data sent back along with the System Connect results.

**Comment by mkinnan** [comment]
I don't follow on the System Connect JSON results ...

Where is the query that is pulling the comments for the node coming from?
`http://example.com/?q=drupalgap/comment.json&parameters[nid]=1234`

Can't I just switch a _DESC_ to _ASC_ in the query order somewhere?

**Comment by mkinnan** [comment]
Any suggestions on where to change order of comments?

**Comment by signalpoint** [comment]
@mkinnan You can add a sort to the query using this: `options[orderby][created]=asc`

**Comment by mkinnan** [comment]
Thanks!! Here's how I implemented:

```
function my_module_services_preprocess(options) {

  try {

    if (options.service == 'comment') {
      options.path += '&options[orderby][created]=asc';
    }

  }

  catch (error) { console.log('hook_services_preprocess - ' + error); }

}
```

**Comment by signalpoint** [comment]
@mkinnan Nice, thanks for sharing. You may want your `if` statement to be more specific i.e. `&& options.resource == 'index'`, otherwise the path will change for _all_ comment resources (create, retrieve, update, delete and index, etc).

**Comment by mkinnan** [comment]
Thanks for the suggestion!!!

**Comment by mkinnan** [comment]
Updated code for future reference to others:

```
function my_module_services_preprocess(options) {

  try {

    if (options.service == 'comment' && options.resource == 'index') {
      options.path += '&options[orderby][created]=asc';
    }

  }

  catch (error) { console.log('my_module_services_preprocess - ' + error); }

}
```
