### ISSUE TITLE
Access Denied for Uploading Images via an Image Field

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#818]
I have an image field for a node. The **Field visibility and permissions** settings are selected as _public_. User 1 can upload an image no problem. However, any other user gets 'Access Denied' error via USB debugging compiled Android app.

`POST: http://example.com/?q=drupalgap/file.json - 403`
`Access denied for user mkinnan`

The user can upload an image no problem via the website interface.

Where else are permissions set?

**Comment by signalpoint** [comment]
@mkinnan There are some Services permissions on the permissions page, something like `save binary file`, etc.

**Comment by mkinnan** [comment]
The permissions to enable for users is `Save file information`. Thanks!

![permissions](https://cloud.githubusercontent.com/assets/13283396/16675042/e00f2080-447a-11e6-936c-1503b8f71f1b.PNG)
