### ISSUE TITLE
DrupalGap config is blank except for hello world

### ISSUE THREAD

**Issue by croxis** [signalpoint/DrupalGap#827]
For Drupal 8 (I know it isn't production ready, I'm making an issue anyways :) ) step 5 of Compiling a mobile application reads

> If you built a web app, you can click the "download" link on your Drupal site under "Configuration -> Web services -> DrupalGap". Extract the contents of this download into PhoneGap's www directory so it overwrites many of the files that come with PhoneGap's test app

However said page is blank.

Also the cordova plugin commands do not work as printed, the v7 documentation has the updated command.

**Comment by signalpoint** [comment]
@croxis I've updated the D8 docs as you suggested for the cordova plugins: http://docs.drupalgap.org/8/Compiling_a_Mobile_Application/Preparing_PhoneGap/Installing_PhoneGap - thank you for pointing this out.

This still needs work in regards to the module's config page in D8.
