### ISSUE TITLE
DrupalGap does not check to see if session still exists. 

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#83]
If I manually delete my session (which I was testing as I haven't made my logout page yet!) then drupalgap still things I'm logged in.

There should be a check on every page request/ bootstrap process to check the session along with its connection status I guess.

**Comment by signalpoint** [comment]
@scotthooker I know this is an old issue, just wanted to follow up...

I believe the whole System Connect feature is pretty stable now and that will report accurate user ids when the app is loaded. I don't think it would be wise to make a system connect call on every page request, that will add tons of potential calls to the server.

So if a session gets deleted manually from the Drupal DB, jDrupal will need to be intelligent enough to understand that, and then clear out the Drupal.user object.

**Comment by scotthooker** [comment]
Yes all appears to be working correctly now :)
