### ISSUE TITLE
Hot to use custom theme function for theming the comment in comment_services_postprocess?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#830]
How can I use my own theme function for theming the comment in `comment_services_postprocess()`?

**Comment by signalpoint** [comment]
If you're custom theme's machine name was `foo`, then you'd make `foo_comment` to override the themeing of the comment in `comment_services_postprocess`.

**Comment by luxio** [comment]
Perfect. Thanks.
