### ISSUE TITLE
Wildcards in Menu Links

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#832]
Is it possible to have wildcards in menu links:

```
drupalgap.settings.menus['group_menu'] = {
  links:[
    {
      title: 'Directory',
      path: 'mypath/%'
    },
    {
      title: 'Attending',
      path: 'mypath/*'
    },
    {
      title: 'Created',
      path: 'mypath...'
    }
  ]
};
```

I have links with wildcards working already in `hook_block_view` but want to move some of those links to menus in **settings.js** to create this:

![menu](https://cloud.githubusercontent.com/assets/13283396/17198109/e05782f2-542f-11e6-980b-cd96549c439c.PNG)

I have tried a variety of different wildcard combinations and configurations, but cannot get anything to work.

**Comment by signalpoint** [comment]
@mkinnan Nope, sorry. This is the exact reason I never use menu links created in the settings.js file anymore. Instead, I like to build a custom block to simulate a menu. This is a much better approach, because the `Drupal.user` object will have been initialized and you can easily place things like a user id in the path (this is not possible at all with settings.js). Here's the docs: http://docs.drupalgap.org/7/Menus/Menus_with_Dynamic_Links

**Comment by mkinnan** [comment]
I was thinking that was the case ... but was having trouble with block menus getting links to display ...

With blocks, how do I get the links to print underneath the header like in the image above? I've tried a few different things like the code below, but cannot get any links to print.

```
  case 'my_panel_block_groupmenuitems':

    var items = [];

    items.push(bl('Groups Joined', 'dg-groupsjoined/' + Drupal.user.uid, {
        attributes: { },
        reloadPage:true
    }));
    items.push(bl('Groups Created', 'dg-groupscreated/' + Drupal.user.uid, {
        attributes: { },
        reloadPage:true
    }));
    items.push(bl('Groups', 'findgroups', {
        attributes: { },
        reloadPage:true
    }));

    // Finally theme the menu.
    content += '<div ' + drupalgap_attributes(attrs) + '>' +
      '<!-- panel content goes here -->' +
      theme('jqm_item_list', { items: items }) +
    '</div><!-- /panel -->';

  break;
```

**Comment by mkinnan** [comment]
Nevermind ... the block of text above works just fine and I can recreate menu links like the image no problem.
