### ISSUE TITLE
DrupalGap does not scroll to the newly inserted comment

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#834]
After a new comment is created, it is inserted at the bottom of the comment container. Then it scrolls to the first comment instead to the newly inserted comment.

**Comment by luxio** [comment]
#835

**Comment by luxio** [comment]
pull request: #835

**Comment by mkinnan** [comment]
Tested on Ripple Emulator and Android. Thanks for this!

**Comment by signalpoint** [comment]
@luxio Thank you for this, much appreciated! @mkinnan Thank you for the test on this.
