### ISSUE TITLE
How to move a field's help text (description) between the label and input element(s)?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#836]
What would be the best way to Move field's help text (description) between the label and input element(s).

**Comment by signalpoint** [comment]
@luxio We could render something right here to place html between the form element title (aka label) and its first (or only) item. The code would go right around here: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/includes/form.elements.inc.js#L310

Can you think of a property name we could use here similar to Drupal? https://api.drupal.org/api/drupal/developer%21topics%21forms_api_reference.html/7.x

I thought about `field_prefix`, but that isn't quite the equivalent. Maybe we need to invent our own property here, e.g. `title_suffix` :

```
form.elements.foo = {
  title: t('Name'),
  type: 'text',
  description: t('Enter your name'),
  title_suffix: '<span>...</span>'
};
```

Thoughts?

**Comment by luxio** [comment]
Hi,

there is a Drupal Module for that called [Form element layout](https://www.drupal.org/project/fel). They use `description_display`:

> `#description_display`: Where the `#description` should be rendered relative to its `#children`. Can be `before` or `after`. Default is `before` for fieldsets and `after` for the rest.

**Comment by signalpoint** [comment]
@luxio Hmmm, well I think we could bake this into DrupalGap core, so how about we call it `description_position` and it'll default to `below`, but can be changed to `above`... thoughts?

**Comment by luxio** [comment]
Why not give it the same name as in  Form element layout module : `#description_display`?

**Comment by signalpoint** [comment]
@luxio That's fine. `before`, `after` and `none` sound like appropriate options.

**Comment by mkinnan** [comment]
Was this ever put into Drupalgap? I tried the following and it didn't work for me ...

    form.elements['field_data_body'] = {
      type: 'textarea',
      title: t('Group Description'),
      description: '<p><i>Describe your group</i></p>',
      description_display: 'above'
      required: true,
      default_value: node.field_data_body
    };

**Comment by luxio** [comment]
@mkinnan I don't think so.

**Comment by mkinnan** [comment]
https://github.com/signalpoint/DrupalGap/pull/900

**Comment by signalpoint** [comment]
@mkinnan Thank you for taking the reigns on this. I merged in your code, and then did some touch up on it. I decided to use `before` and `after` instead of `above` and `below`.

- `before`
- `after` (default)
- `none`

As an example, this would work:
```
form.elements['field_data_body'] = {
  type: 'textarea',
  title: t('Group Description'),
  description: '<p><i>Describe your group</i></p>',
  description_display: 'before'
  required: true,
  default_value: node.field_data_body
};
```

**Comment by signalpoint** [comment]
https://github.com/signalpoint/DrupalGap/commit/766ec5b214bcd21257118fd01addb03e33093c01
