### ISSUE TITLE
user_load yields 'undefined'

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#841]
I am following the example for user_load:
http://docs.drupalgap.org/7/Entities/Users

```
var load_account = user_load(1, {
    success:function(load_account) {
      alert("Loaded user " + load_account.name);
    }
});
console.log('--- load_account ---');      
console.log(load_account);
```

The alert gives the correct username, but the console.log message returns 'undefined'.

I'm trying to pass the loaded user account to the avatar module to load specific avatars.

**Comment by signalpoint** [comment]
@mkinnan user_load is an asynchronous call, so `load_account` will only become available inside the `success` callback.

**Comment by mkinnan** [comment]
Just to complete an example for others in the future:

```
  user_load(1, { success:function(account) {

    console.log('--- load_account ---');      
    console.log(account);

    var load_avatar = theme('avatar', { account: account });

    // this works
    console.log(load_avatar);


  } });

  // this does not work
  console.log(load_avatar);
```
