### ISSUE TITLE
Services call backs asynchronous?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#842]
Are call backs from creating custom services _asynchronous_ just like **user_load**? Thus, only stuff can be done inside the success function and suffers just like **user_load**?
https://github.com/signalpoint/DrupalGap/issues/841

**Comment by signalpoint** [comment]
@mkinnan Yes, all services in jDrupal and DG are asynchronous on the client side, and should typically be followed by the success function, because all code after the call will execute before the call even goes out.
