### ISSUE TITLE
How to create a button in the sub-header region

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#847]
I'm trying to add a button in the sub-header with this code:

```
function my_module_menu() {
  var items = {
   ...
    'edit' : {
        title: 'Edit',
        page_callback: 'my_module_edit_page',
        region: {
          name: 'sub-header',
          options: {
            attributes: {
              'class': 'ui-btn-right'
            }
          },
          }
        }
   ...
```

I'm getting an error: `drupalgap_menus_load - TypeError: Cannot read property 'links' of undefined`.

What is my mistake?

Would it be possible to add dynamically add a button in the sub-header  by code in the page callback itself?

**Comment by signalpoint** [comment]
@luxio Maybe the region name is `sub_header`...?

I typically don't add buttons anywhere to the UI via hook_menu(). I know I had programmed that feature long ago, but I don't know if it is working well anymore. Typically I'll use a http://docs.drupalgap.org/7/Regions/Region_Zones , in combination with http://docs.drupalgap.org/7/Blocks http://docs.drupalgap.org/7/Blocks/Imitating_Menus_with_Blocks or http://docs.drupalgap.org/7/Menus/Menus_with_Dynamic_Links

**Comment by luxio** [comment]
Thanks a lot. Works great.
