### ISSUE TITLE
How to create an edit form for a custom entity

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#849]
I am able to show custom entities by using the way described at [Rendering Entities](http://docs.drupalgap.org/7/Entities/Rendering_Entities).

The example at [Rendering Entities](http://docs.drupalgap.org/7/Entities/Editing_Entities) shows how to create a completely new form. Is there a way to create an initial form with the fields of the entities, similar to rendering an entity with `drupalgap_entity_render_content()`?

**Comment by signalpoint** [comment]
@luxio There's now this page in the docs: http://docs.drupalgap.org/7/Entities/Editing_Entities

You can use jDrupal functions like entity_load(), entity_save() and entity_delete() along with it.

You'll also need to implement something like:

```
function [my_entity_machine_name]_primary_key() {
  return 'id'; // The column name of the primary key
}
```

This helps jDrupal know what the primary key is.

From that point you can have a full entity delivered to your form builder function (which is how I wish I would've built DrupalGap from the start, but it's been a learning process). Unfortunately/fortunately you have to then build your own widgets and submission handlers, which is good for customization, but bad cause there is work to do.

**Comment by luxio** [comment]
Thanks. Doesn't I have to use  `drupalgap_field_info_instances_add_to_form('[my_entity_machine_name]', bundle, form, entity);` to have all entity fields included in the form?

**Comment by signalpoint** [comment]
@luxio I think you should be able to use that function, I've never tried it outside of DrupalGap core's forms though. The only problem would be, the System Connect call only returns core entity types, so up in Drupal you'd have to hook into the System Connect call and supply more entity/bundle/info/instance data.

**Comment by luxio** [comment]
> you'd have to hook into the System Connect call and supply more entity/bundle/info/instance data.

Yes, I have done this already, it's a one liner. This step is also neccessary  to use `drupalgap_entity_render_content()`to render custom entities.

**Comment by signalpoint** [comment]
FYI, jDrupal can now utilize Services Entity to support all entity types (core and custom): https://github.com/signalpoint/jDrupal/issues/60
