### ISSUE TITLE
How to make Drupal.settings.site_path configurable?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#850]
I would like to make `Drupal.settings.site_path` configurable by using a  configuration settings form.

When `Drupal.settings.site_path` is empty dg throws the error

`No site_path to Drupal set in the app` 

and the settings form is not loaded. Is there a way to show a settings form before a system connect call?

**Comment by signalpoint** [comment]
@luxio We can take the `Verify site path is set` code block (https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/dg.js#L193), and move it below the `Device is ready, let's call...` code block (https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/dg.js#L202):

That'll be a safe change for everyone. Then in your app, you can implement this hook to take over the startup procedure: http://api.drupalgap.org/7/global.html#hook_deviceready

With that hook, you can use `drupalgap_goto()` to send them to your configuration settings form, then after you set the `site_path` in the submit handler, you can continue the normal bootstrapping by calling (https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/dg.js#L233):

```
system_connect(_drupalgap_deviceready_options());
```

The `facebook` module has a good example of taking over the startup procedure, and then continuing as usual after doing some special stuff: https://github.com/signalpoint/facebook/blob/7.x-1.x/facebook.js#L18

**Comment by luxio** [comment]
Thanks. 

If I use   `drupalgap_goto('my_settings_form)` in `hook_deviceready()` dg still goes to the front page and not the the settings form? 

Any ideas why?

**Comment by signalpoint** [comment]
@luxio In your `hook_deviceready()`, are you setting `Drupal.settings.site_path` to your config form?

**Comment by luxio** [comment]
I have added the site path to my login form. I have attached a custom submit handler to the login form:

```
/**
 * Implements hook_deviceready().
 */
function my_module_deviceready() {
  try {
    if (Drupal.settings.site_path == 'undefined') {
      drupalgap_goto('user/login', {reloadPage:true});
      return false;
    }
  }
  catch (error) {
    console.log('my_module_deviceready - ' + error);
  }
}


function my_module_user_login_submit(form, form_state) {
  var submitted_sitepath =  'https://' + form_state.values.my_module_site_path ;
  if (submitted_sitepath != Drupal.settings.site_path ) {
    variable_set('my_module', form_state.values.my_module_site_path);
    Drupal.settings.site_path = 'https://' + form_state.values.my_module_site_path;
    system_connect(_drupalgap_deviceready_options());
  }
}
```

This seems to work. The only problem ist that sometimes system_connect call is slower than the user login call. Can I add an success closure to the `system_connect()`, in which the `user_login_submit()`handle is called, so that he user login happens **after** a successful system connect. 

```
POST: https://example.com/?q=drupalgap/user/login.json
POST: https://example.com/?q=drupalgap/system/connect.json
```

**Comment by signalpoint** [comment]
@luxio Try using this hook too: http://api.drupalgap.org/7/global.html#hook_services_postprocess

```
function my_module_services_postprocess(options, result) {
  if (options.service == 'user' && options.resource == 'login') {
    Drupal.settings.site_path = 'https://' + variable_get('my_module', 'example.com');
    system_connect(_drupalgap_deviceready_options());
  }
}
```

That'll allow the user login to finish first. Or you can use a `hook_form_alter()` and completely override the user login form submit handler.

**Comment by luxio** [comment]
I thought I had to do the `system_connect()` before the user login call? So can I do a a user login without having done the system_connect() first?

**Comment by signalpoint** [comment]
@luxio Yes you're right, you'd want to do the System Connect before the User Login call (in case they are already logged in).

It sounds like you need to override the submit handler for the user login form, then use the custom submit handler to set the site path, make the system connect call, then manually log them in (if they aren't already).

**Comment by luxio** [comment]
Thanks. It works.
