### ISSUE TITLE
Support for Computed Field

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#851]
I have entities with computed fields.

On the website, the fields are recalculated each time the entity is viewed and shows the latest (and correct) information.

In the app, the fields are not recalculated each time the entity is viewed and shows old information. Re-saving the entity or clearing the cache forces the app to clear 'something' and then the computed field is correct. However, this defeats the purpose of having a computed field.

**Comment by signalpoint** [comment]
@mkinnan A number of things could be going on here...
1. If Computed Field is triggered by the Viewing of a node, it's likely the retrieval of a node via the Services module (for DrupalGap) doesn't trigger this process
2. Just a reminder that once you visit a node in the app, that node's page remains in the DOM unless you navigate to the page again using the `reloadPage` option.
3. If entity caching is enabled in DrupalGap, it may hold stale Computed Field data. (navigating to a page with `reloadPage` set to `true` will force a reload of the entity's cache via jDrupal)

Thoughts?

**Comment by mkinnan** [comment]
@signalpoint ... I believe it is a Services issue. I am using reloadPage and entity caching is disabled.

When I visit a node:

```
http://example.com/?q=drupalgap/node/1234.json
```

I can see all the fields. I then change some things such that the computed field will be something new. On the website, I can see the computed field is something new. However, when I visit the drupalgap node URL above it is still showing the old computed field data. Editing and resaving the node on the website then causes the computed field to show updated data on the drupalgap node URL.

Will it be easy to add support for computed field?

**Comment by signalpoint** [comment]
@mkinnan So you need the computed field to re-compute itself upon a Services node retrieval (i.e. simulating a node page view in DrupalGap)?

**Comment by mkinnan** [comment]
@signalpoint Yes. I need the computed field to update each time someone views an entity (e.g., node, comment) in drupalgap. And it would be ideal for this to be server side doing the query update instead of in the app.

**Comment by signalpoint** [comment]
@mkinnan I would use [hook_services_request_preprocess_alter()](http://cgit.drupalcode.org/services/tree/docs/services.alter.api.php?h=7.x-3.x#n13) in a custom _Drupal_ module to programatically trigger the re-computation of the field(s). Then the fresh data should be delivered to the app. As for actually re-computing the data programmatically, I'm not sure on that one, never tried it. But I'd start [here](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8&client=ubuntu#q=drupal%20recompute%20computed%20field).

**Comment by mkinnan** [comment]
@signalpoint I couldn't get that hook to work. Instead, I created a Services callback that passes the UID. The callback then deletes all the cache the user has authored. This probably isn't an ideal approach, but it does work.
