### ISSUE TITLE
Not all comments being displayed on nodes

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#852]
I have a node with 24 comments. Only 20 comments are being displayed. Where is the setting to increase more? Node edit is set to 50. The built-in drupalgap view is set for all comments.

**Comment by mkinnan** [comment]
The JSON URL being shown in Ripple Emulator is

```
http://example.com/?q=drupalgap/comment.json&parameters[nid]=2167&options[orderby][created]=asc
```

and that is only showing 20 comments even though the node has 26 comments. Is there some hidden Services setting for returning only 20 comments? I'll try to take a look the SQL query logs next to see if there is a LIMIT clause.

**Comment by signalpoint** [comment]
@mkinnan The quick workaround is:

```
drush vset services_comment_index_page_size 100
```

This will allow 100 comments to be indexed, instead of the default 20 set by Services.

Other than that, DrupalGap doesn't automatically respect node comment page size settings.

**Comment by mkinnan** [comment]
@signalpoint That works. Thanks!

Is there a plan for DrupalGap to respect node comment page size settings?

**Comment by signalpoint** [comment]
@mkinnan Good to hear.

> Is there a plan for DrupalGap to respect node comment page size settings?

Almost all improvements to DrupalGap core come out of the needs from financially sponsored work these days. That fortunately/unfortunately uses up most of my development time. Other than that, I sure do like pull requests should anyone want to tackle any improvements ;)
