### ISSUE TITLE
Removing certain pages from the DOM after navigating away

### ISSUE THREAD

**Issue by ApsGitAdmin** [signalpoint/DrupalGap#853]
Hi,

I have a series of Vimeo embeds coming from my nodes in my app, but since they're just embedded videos when you navigate away from them, they continue to play since they still exist in the DOM, are any of the Page Events triggered after a page has been navigated away from? I know that I can use drupalgap_remove_page_from_dom, but to do that I'd need to fire the action after I navigate away or there's drupalgap_remove_pages_from_dom, but I only really want to remove my video nodes, and not everything.

Is this possible?

Cheers

**Comment by signalpoint** [comment]
@ApsGitAdmin these hooks will help:
- http://api.drupalgap.org/7/global.html#hook_drupalgap_goto_post_process
- http://api.drupalgap.org/7/global.html#hook_drupalgap_goto_preprocess

I use them to stop YouTube players when navigating away.

**Comment by ApsGitAdmin** [comment]
Awesome, thank you, I've managed to make it work, I don't know if this is how you'd do it, but just for future help, I wrote a 'pageshow' event for when users landed on my video page which set a variable to drupalgap_get_page_id, then using hook_drupalgap_goto_post_process I checked whether or not that variable was empty, and that the path wasn't the video page itself, and if it wasn't, it meant that they have navigated away from it, and then I used drupalgap_remove_page_from_dom(my_variable) to remove it from the DOM.

Don't know if this is how you made it work, but now it's successfully removing the video pages from the DOM only
