### ISSUE TITLE
Why is the node loaded in comment_services_postprocess()?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#861]
Why is the node of the comment loaded in `comment_services_postprocess()` at https://github.com/signalpoint/DrupalGap/blob/c49acc0399128648780737ca8692a6634fc17e4b/src/modules/comment/comment.js#L247 ?

Couldn't we load the comment directly?

**Comment by signalpoint** [comment]
@luxio I think I did that so the latest node (and comment count) would be loaded into the app.

**Comment by luxio** [comment]
I see. Thanks.
