### ISSUE TITLE
Multiple Views Expose Filter

### ISSUE THREAD

**Issue by ghost** [signalpoint/DrupalGap#863]
When I add multiple expose filter into views, drupalgap show first expose filter items, but others expose filter select options not display.

How can i figure it?

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
