### ISSUE TITLE
Map Search Result

### ISSUE THREAD

**Issue by igenroot** [signalpoint/DrupalGap#872]
I'm having a problem displaying map. Right now i want to do search function and from search result will display marker for each item on map. I have created custom search form and the form sends paramater to drupal view to populate search result based on the given user filter option. The issue is, the map only displays data for the selected user filter options for the first time it loads. And when user make changes to the filter option, the search result does not load map and map data. To get map and map data, the user has to refresh the page. Is there any solution for this?

**Comment by signalpoint** [comment]
@igenroot It is definitely possible, I've done it in a few apps. Please share some of your code, particularly the page_callback and any form builder, validation and submission functions for further assistance.

**Comment by igenroot** [comment]
For your reference

`function my_module_menu() {
  try {
    var items = {};
    items['search/%'] = {
    title: 'Search Item',
      page_callback: 'my_module_map',
      pageshow: 'my_module_map_page',
      page_arguments: [1],
      options:{reloadPage:true,reset:true}

    };
    items['my_module_searchingform_page'] = {
      title: 'Search Item',
      page_callback: 'drupalgap_get_form',
      page_arguments: ['my_module_searching_form']
    };


function my_module_searching_form(form, form_state) {
  try {

    form.elements['s_club'] = {
      type: 'select',
      options: {
        All: 'All Club',
        6564:	'Arsenal',
        6706:	'Chelsea',
        6932:	'Manchestar United',
        7264:	'Manchestar City',
        7377:	'Liverpool',
      },
      default_value: 'All'

    };
    form.elements['submit'] = {
      type: 'submit',
      value: t('Search')
    };
    return form;
  }
  catch (error) {
    console.log('my_module_searching_form - ' + error);
  }
}


/**
 * Define the form's submit function.
 */
function my_module_searching_form_submit(form, form_state) {
  try {
        var state = form_state.values['s_country'];
        var path = 'search/'+country;
        drupalgap_goto(path, {reloadPage:true,reset:false,});

  }
  catch (error) { console.log('my_module_searching_form_submit - ' + error); }
}`


`/**
 * The map page callback.
 */
function my_module_map(country) {
  try {
    var content = {};

    var map_attributes = {
      id: 'my_module_map',
      style: 'width: 100%; height: 320px; margin-top: 1em;'
    };
    content['map'] = {
      markup: '<div ' + drupalgap_attributes(map_attributes) + '></div>'
    };
    
    return content;
  }
  catch (error) { console.log('my_module_map - ' + error); }
}


/**
 * The map pageshow callback.
 **/
function my_module_map_page(state) {
  try {

      navigator.geolocation.getCurrentPosition(

      // Success.
      function(position) {

        // Set aside the user's position.
        _my_module_user_latitude = position.coords.latitude;
        _my_module_user_longitude = position.coords.longitude;

    var path = 'map-search&location_tid='+country;

     // Build the lat lng object from the user's position.
        var myLatlng = new google.maps.LatLng(
          _my_module_user_latitude,
          _my_module_user_longitude
        );

        // Set the map's options.
        var mapOptions = {
          center: myLatlng,
          zoom: 5,
          mapTypeControl: true,
          mapTypeControlOptions: {
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
          },
          zoomControl: true,
          zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL
          }
        };

        // Initialize the map, and set a timeout to resize properly.
        _my_module_map = new google.maps.Map(
          document.getElementById("my_module_map"),
          mapOptions
        );
        setTimeout(function() {
            google.maps.event.trigger(_my_module_map, 'resize');
            _my_module_map.setCenter(myLatlng);
        }, 500);

    // Call the server.
    views_datasource_get_view_result(path, {
        success: function(data) {


          // Iterate over each spot, add it to the list and place a marker on the map.
          var items = [];
          $.each(data.nodes, function(index, object) {

              // Render a nearby location, and add it to the item list.
              var row = object.node;

              // Add a marker on the map for the location.
              var locationLatlng = new google.maps.LatLng(row.latitude, row.longitude);
              var marker = new google.maps.Marker({
                  position: locationLatlng,
                  map: _my_module_map,
                  data: row
              });
              // Inject it into the container.


          });
          drupalgap_item_list_populate('#location_results_list', items);

        }
    });
  },
   // Error
      function(error) {

        // Provide debug information to developer and user.
        console.log(error);
        drupalgap_alert(error.message);

        // Process error code.
        switch (error.code) {

          // PERMISSION_DENIED
          case 1:
            break;

          // POSITION_UNAVAILABLE
          case 2:
            break;

          // TIMEOUT
          case 3:
            break;

        }

      },

      // Options
      { enableHighAccuracy: true }

    );
  }
  catch (error) { console.log('_my_module_map_button_click - ' + error); }
}
`

**Comment by igenroot** [comment]
This is the code for your understanding

```
function my_module_menu() {
  try {
    var items = {};
    items['search/%'] = {
    title: 'Search Item',
      page_callback: 'my_module_map',
      pageshow: 'my_module_map_page',
      page_arguments: [1],
      options:{reloadPage:true,reset:true}

    };
    items['my_module_searchingform_page'] = {
      title: 'Search Item',
      page_callback: 'drupalgap_get_form',
      page_arguments: ['my_module_searching_form']
    };


function my_module_searching_form(form, form_state) {
  try {

    form.elements['s_club'] = {
      type: 'select',
      options: {
        All: 'All Club',
        6564:   'Arsenal',
        6706:   'Chelsea',
        6932:   'Manchestar United',
        7264:   'Manchestar City',
        7377:   'Liverpool',
      },
      default_value: 'All'

    };
    form.elements['submit'] = {
      type: 'submit',
      value: t('Search')
    };
    return form;
  }
  catch (error) {
    console.log('my_module_searching_form - ' + error);
  }
}


/**
 * Define the form's submit function.
 */
function my_module_searching_form_submit(form, form_state) {
  try {
        var state = form_state.values['s_club'];
        var path = 'search/'+state;
        drupalgap_goto(path, {reloadPage:true,reset:false,});

  }
  catch (error) { console.log('my_module_searching_form_submit - ' + error); }
}
```

```
/**
 * The map page callback.
 */
function my_module_map(state) {
  try {
    var content = {};

    var map_attributes = {
      id: 'my_module_map',
      style: 'width: 100%; height: 320px; margin-top: 1em;'
    };
    content['map'] = {
      markup: '<div ' + drupalgap_attributes(map_attributes) + '></div>'
    };

    return content;
  }
  catch (error) { console.log('my_module_map - ' + error); }
}


/**
 * The map pageshow callback.
 **/
function my_module_map_page(state) {
  try {

      navigator.geolocation.getCurrentPosition(

      // Success.
      function(position) {

        // Set aside the user's position.
        _my_module_user_latitude = position.coords.latitude;
        _my_module_user_longitude = position.coords.longitude;

    var path = 'map-search&location_tid='+state;

     // Build the lat lng object from the user's position.
        var myLatlng = new google.maps.LatLng(
          _my_module_user_latitude,
          _my_module_user_longitude
        );

        // Set the map's options.
        var mapOptions = {
          center: myLatlng,
          zoom: 5,
          mapTypeControl: true,
          mapTypeControlOptions: {
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
          },
          zoomControl: true,
          zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL
          }
        };

        // Initialize the map, and set a timeout to resize properly.
        _my_module_map = new google.maps.Map(
          document.getElementById("my_module_map"),
          mapOptions
        );
        setTimeout(function() {
            google.maps.event.trigger(_my_module_map, 'resize');
            _my_module_map.setCenter(myLatlng);
        }, 500);

    // Call the server.
    views_datasource_get_view_result(path, {
        success: function(data) {


          // Iterate over each spot, add it to the list and place a marker on the map.
          var items = [];
          $.each(data.nodes, function(index, object) {

              // Render a nearby location, and add it to the item list.
              var row = object.node;

              // Add a marker on the map for the location.
              var locationLatlng = new google.maps.LatLng(row.latitude, row.longitude);
              var marker = new google.maps.Marker({
                  position: locationLatlng,
                  map: _my_module_map,
                  data: row
              });
              // Inject it into the container.


          });
          drupalgap_item_list_populate('#location_results_list', items);

        }
    });
  },
   // Error
      function(error) {

        // Provide debug information to developer and user.
        console.log(error);
        drupalgap_alert(error.message);

        // Process error code.
        switch (error.code) {

          // PERMISSION_DENIED
          case 1:
            break;

          // POSITION_UNAVAILABLE
          case 2:
            break;

          // TIMEOUT
          case 3:
            break;

        }

      },

      // Options
      { enableHighAccuracy: true }

    );
  }
  catch (error) { console.log('_my_module_map_button_click - ' + error); }
}

```

**Comment by signalpoint** [comment]
@igenroot This line of code here is a problem:

```
var path = 'map-search&location_tid='+country;
```

In `my_module_map_page`, that `country` variable will be undefined, so the path to the View will not work as expected.

**Comment by igenroot** [comment]
`var path = 'map-search&location_tid='+state;` 
I already update this code and other too. The view work properly but the map only first time it load but when i do another search the map does not load.

Screenshot 1st search
![Image of First](http://i65.tinypic.com/ri80og.png)

Screenshot 2nd search
![Image of Second](http://i64.tinypic.com/2vis5c8.png)

**Comment by signalpoint** [comment]
@igenroot Your map `id` will need to be unique across each page. Try appending the `state` value to it:

```
    var map_attributes = {
      id: 'my_module_map_' + state,
      style: 'width: 100%; height: 320px; margin-top: 1em;'
    };
```

Then wen you select the map, also use the `state` value:

```
        _my_module_map = new google.maps.Map(
          document.getElementById("my_module_map_" + state),
          mapOptions
        );
```

**Comment by igenroot** [comment]
@signalpoint Thanks for you help. Right now my map display issue already fixed

**Comment by signalpoint** [comment]
@igenroot Good to hear, please share your resolution if you can.
