### ISSUE TITLE
How to prevent scrolling above the header?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#873]
Is there a way to keep the header at the top of the screen when the user scrolls above the top:

![iphone](https://cloud.githubusercontent.com/assets/1497217/19680335/8f86018e-9aa5-11e6-8fda-750b8a96ae61.jpg)

**Comment by signalpoint** [comment]
@luxio That I do not know. I've noticed this behavior as well, but only on iOS. After some brief research, others seem to be looking for a solution as well. This one stands out with potential:

http://stackoverflow.com/a/14213250/763010

**Comment by luxio** [comment]
Activating this setting in config.xml 

`<preference name="DisallowOverscroll" value="true" />`

worked for me.
