### ISSUE TITLE
Drupal Gap Commerce Stripe Module

### ISSUE THREAD

**Issue by tennist** [signalpoint/DrupalGap#882]
I am trying to download and use this module, but the link for it is broken.  Does anybody have the ability to fix this issue?

**Comment by signalpoint** [comment]
@tennist The Drupal module and the corresponding DrupalGap module are located here:

- https://www.drupal.org/project/commerce_drupalgap_stripe
- https://github.com/signalpoint/commerce_drupalgap_stripe

**Comment by tennist** [comment]
@signalpoint Sorry I was not specific, I have the modules for my website, but need the contrib module for my app.  The link to the contrib module is broken

http://drupalgap.org/project/commerce_drupalgap_stripe

**Comment by signalpoint** [comment]
@tennist Thank you for pointing that problem out, I have fixed the page: http://drupalgap.org/project/commerce_drupalgap_stripe

**Comment by tennist** [comment]
Thank you!
