### ISSUE TITLE
Allow loader spinning icon to be toggled on or off

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#884]
I'd like to be able to suppress the loader from showing on a particular jDrupal call, this isn't possible.

**Comment by signalpoint** [comment]
Here's a simple usage example that will temporarily hide the spinner so you can make a network call in the background, without interrupting the user with the "loading..." icon. Once your call is on `success`, then turn the loader back on, for example:

```
// Temporarily disable the spinner icon.
drupalgap_loader_enable(false);

my_module_service_call({
  success: function(result) {

    // Turn the spinner back on for the next caller.
    drupalgap_loader_enable(true);

    // Everything was OK, do some custom code now
    // ...

  },
  error: function(xhr, status, msg) {

    // Turn the spinner back on for the next caller.
    drupalgap_loader_enable(true);

    // Alert the user to the problem.
    drupalgap_alert(msg);

  }
});
```

**Comment by mkinnan** [comment]
@signalpoint I'm having a bit of trouble getting this to work. I want to disable loader for a node_save but I get `uploadUserLocation - ReferenceError: my_module_service_call is not defined`. Do I need to create a custom service for this to work?

    function uploadUserLocation() {
      try {

        var data_to_save = { ... };
      
        // Temporarily disable the spinner icon.
        drupalgap_loader_enable(false);
      
        my_module_service_call({
          success: function(result) {

            // Turn the spinner back on for the next caller.
            drupalgap_loader_enable(true);
      
            // save node
            node_save(data_to_save, {
              success: function(result) {
                // do nothing
              }
            });
      
          },
          error: function(xhr, status, msg) {

            // Turn the spinner back on for the next caller.
            drupalgap_loader_enable(true);

            // Alert the user to the problem.
            drupalgap_alert(msg);

          }
        });  
      
      }
      catch (error) { console.log('uploadUserLocation - ' + error); }
    }

**Comment by signalpoint** [comment]
@mkinnan 

> uploadUserLocation - ReferenceError: my_module_service_call is not defined

This literally means it can't find the `my_module_service_call` function, so either it doesn't exist, it is not being loaded, or there is a syntax error in that module's file(s) preventing it from properly loading.

**Comment by signalpoint** [comment]
@mkinnan Now that I read your question a bit closlier, I think this is what you're looking for:

```
function uploadUserLocation() {
  try {

    var data_to_save = { ... };
  
    // Temporarily disable the spinner icon.
    drupalgap_loader_enable(false);
  
        // save node
        node_save(data_to_save, {
          success: function(result) {
            // Turn the spinner back on for the next caller.
            drupalgap_loader_enable(true);
          },
          error: function(xhr, status, msg) {
            // Turn the spinner back on for the next caller.
            drupalgap_loader_enable(true);
          }
        });
  
  }
  catch (error) { console.log('uploadUserLocation - ' + error); }
}
```

**Comment by mkinnan** [comment]
@signalpoint That seems to be working. I had tried something I thought was similar but it still popped up for a split second. I'll report back if I encounter and strange behavior. Thanks for adding in this feature!

**Comment by mkinnan** [comment]
@signalpoint I had forgot to re-enable the function that contained the node_save. The loader pops up for a split second and then quickly disappears using the above code. It's as if the re-enabling of the loader is happening before the save function has actually completed.
