### ISSUE TITLE
Howto reload a page when calling drupalgap_back()

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#885]
I have a page, where the previous page should be reloaded when then user clicks on the back button. 

`drupalgap_back()` does not seem to evaluate the `reloadPage`option.

What is the best way to achieve this? Removing the previous page from the dom? Or replacing the `drupalgap_back()`button with `drupalgap_goto()`?

**Comment by signalpoint** [comment]
@luxio There's a "Back to the Future" helper function for this: http://api.drupalgap.org/7/global.html#drupalgap_back_2tf

```
drupalgap_back_2tf();
```

Does that work for you?

**Comment by luxio** [comment]
Thanks for the prompt reply.

`drupalgap_back_2tf();` was exactly what I was looking for.

How could I save the vertical position of the page and jumpt to this position again, after the page has been reloaded? Or is there another way to jump to specific id on a page, after the page (and e.g. nodes) has finished loading?

**Comment by signalpoint** [comment]
@luxio I'm not sure about recording the vertical position on the page,, but to jump to a spot you can use: http://api.drupalgap.org/7/global.html#scrollToElement

Example usage in DG core:

```
scrollToElement('#' + container_id + ' #' + comment_container_id(comment.cid), 500);
```

Func args:
```
src/dg.js:1544:function scrollToElement(selector, time, verticalOffset) {
```

**Comment by luxio** [comment]
Thanks. If I have page where nodes are inserted asynchronously and I want to scroll to a certain id, I have to check for the id in `node_load` success callback and then scroll to the id? Or is there an event called when inserting something in the dom, where I can listen for and then scroll to the id as soon as the id is inserted in the dom?

**Comment by signalpoint** [comment]
> I have to check for the id in node_load success callback and then scroll to the id

@luxio Yes.

**Comment by luxio** [comment]
Thanks for your help.
