### ISSUE TITLE
DrupalGap Commerce Stripe Module

### ISSUE THREAD

**Issue by tennist** [signalpoint/DrupalGap#886]
I tried to create this issue on the Stripe Module repository, but it doesn't have an area to do so.  

The stripe payment gateway has a new version of API than what is reported in the setup instructions for this DrupalGap module.  The new Stipe API is used by the current Stripe Payment Gateway module in Drupal and it is not possible to have both API's on a single site.  Step 3 of the setup instructions for the DrupalGap Module need to be updated to read version 3.23.0.  The payment.inc file for the drupal module "Commerce DrupalGap Stripe also needs 3 revisions for the new Stripe API.  The changes are as follows:

Line 31 needs to be changed to \Stripe\Stripe::setApiKey($settings['secret_key']);
Line 35 needs to be changed to 'source' => $data['stripe_token'],
Line 40 needs to be changed to $response = \Stripe\Charge::create($c);

I will also note these change requirements on the thread for the module as well.

**Comment by signalpoint** [comment]
@tennist Thank you for pointing out the closed issue queue, I've opened it up and migrated the issue here: https://github.com/signalpoint/commerce_drupalgap_stripe/issues/1
