### ISSUE TITLE
Settings Page with Widgets

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#887]
For a user to change settings like mobile notifications in my app, they have to go to My Account, then click Edit, then toggle the boxes, then click save.

If I wanted to create a new page called "Notification Settings" with checkboxes:
http://docs.drupalgap.org/7/Widgets/Checkbox_Widget

how do I code it so that when the user toggles the checkbox it automatically updates the setting (aka the field) for the user?

**Comment by signalpoint** [comment]
@mkinnan You'd set up a `change` handler on the checkboxes, and in its callback make a call to `user_update()` to update the new notification settings (if those settings are actually part of the user object, I'm not sure).

It's probably something like this:

```
$('#my-checkbox').on('change', function() {
  console.log('Do something now that the checkbox has changed');
});
```

**Comment by mkinnan** [comment]
@signalpoint Where do I place the change handler? Just inside my page callback?

**Comment by mkinnan** [comment]
Still not sure where to place the change handler ... I've also tried a few different change handlers ...

    function my_module_user_settings_page() {
      try {
        
        $('#my_checkbox').on('change', function() {
          console.log('Do something now that the checkbox has changed');
        }); 

        $('#my-checkbox').on('click', function() {
          console.log('Do something now that the checkbox has changed');
        }); 
        
        $('#my_checkbox').click(function(){
          console.log('Do something now that the checkbox has changed');
        });    
            
        $('#my_checkbox').change(function(){
          console.log('Do something now that the checkbox has changed');
        });    
       
        
        var content = {};
        content['my_checkbox'] = {
          theme: 'checkbox',
          attributes: {
            id: 'my_checkbox'
          }
        };

        var info = 1;
        if(info == 1) { content['my_checkbox'].attributes.checked = 'checked'; }
        
        content['my_checkbox_label'] = {
          theme: 'form_element_label',
          element: {
            title: 'Enjoy Pizza?',
            attributes: {
              'for': 'my_checkbox'
            }
          }
        };
        
        return content;    
        
      }
      catch (error) { console.log('my_module_user_settings_page - ' + error); }
    }

**Comment by mkinnan** [comment]
@signalpoint This works ... any issues with doing it this way?

    function my_module_user_settings_page() {
      try {
        
        var content = {};
        
        content['my_intro_text'] = {
          markup: "<script>$(':checkbox').change(function() { console.log('Do something now that the checkbox has changed'); alert('Clicked'); })</script>" 
        };    
        
        content['my_checkbox'] = {
          theme: 'checkbox',
          attributes: {
            id: 'my_checkbox'
          }

        };

        var info = 1;
        if(info == 1) { content['my_checkbox'].attributes.checked = 'checked'; }
        
        content['my_checkbox_label'] = {
          theme: 'form_element_label',
          element: {
            title: 'Enjoy Pizza?',
            attributes: {
              'for': 'my_checkbox'
            }
          }
        };
        
        return content;    
        
      }
      catch (error) { console.log('my_module_user_settings_page - ' + error); }
    }

**Comment by signalpoint** [comment]
@mkinnan In this case I'd attach an attribute to my form element to handle the particular event:
```
content['my_checkbox'] = {
      theme: 'checkbox',
      attributes: {
        id: 'my_checkbox',
        onchange: 'foo_bar(this)'
      }
    };
```
And a handler to take care of business:
```
function foo_bar(checkbox) {
  alert($(checkbox).attr('id') + ' was clicked');
}
```

**Comment by mkinnan** [comment]
@signalpoint That works! Thanks!
