### ISSUE TITLE
Add reloadPage option to drupalgap_goto() so pages already in the DOM can be forced to rebuilt

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#89]

**Comment by chrisschaub** [comment]
Also, allow the rebuild option for the menu links defined in settings.js. I need to be able to set some of my menu paths to always rebuild and replace the page.

**Comment by scotthooker** [comment]
Menu items are no longer being rebuilt so any dynamic content that is triggered to be displayed once you have already viewed the page the page cant be rebuilt.

**Comment by chrisschaub** [comment]
Its really an issue on user login and register pages. The should always
check if he user is logged in. But other pages, content teasers being added
to a view... maybe destroying certain pages before loading will do the
trick.

**Comment by scotthooker** [comment]
I have a "cart" for a lack of a better word that users add things to from other pages. This page needs to refresh to load the new content each time the user navigates to it. 

How do I destroy a page in the dom before viewing? reloadPage doesn't work in its current state and even so I can't apply that to the hook menu

**Comment by signalpoint** [comment]
Ok, the reloadPage option now works in various places. Using this option will remove the page from the DOM, if it is in the DOM, then let the page rebuild itself. Check out this page for examples on how to use reloadPage:

http://drupalgap.org/node/134

@scotthooker - menu item links can now have the reloadPage option attached to them, check out the link above for example to use in settings.js.

@cschaub - as for the user login and registration pages (and others that should always be rebuilt), do you think we should have a reloadPage option that can be attached to menu link items defined via hook_menu()? That way modules declaring pages via hook_menu() can decide if the page should use reloadPage, or not (default is to not use it).

**Comment by chrisschaub** [comment]
Thanks for doing this work! So, I've been testing a bit. I'm setting the reloadPage option in my menu links. It's not setting the reloadPage option within the onclick code. My link becomes:

``` javascript
<a onclick="javascript:drupalgap_goto('user');" class="account ui-link" reloadpage="true">Account</a>
```

**Comment by scotthooker** [comment]
"- as for the user login and registration pages (and others that should always be rebuilt), do you think we should have a reloadPage option that can be attached to menu link items defined via hook_menu()? That way modules declaring pages via hook_menu() can decide if the page should use reloadPage, or not (default is to not use it)."

Is the most flexible and proper way forward

**Comment by chrisschaub** [comment]
I think Tyler's latest commit attempts to do this. I think it just has a bug, or maybe I do. Trying to step through it now. He allows you to generally add reloadPage as an option to theme_link, and in your menu links.

**Comment by scotthooker** [comment]
e.g.

'menus': {
        'main_menu': {
            'links': [
                {'title': 'Scores', 'path': 'link', 'options': {reloadPage:true}, {'attributes': {'class': 'bt-link', 'data-icon': 'bt-foobar'}}},

```
        ],
    },
```

}

**Comment by scotthooker** [comment]
I'll give it a run through later haven't had chance to test it yet.

**Comment by chrisschaub** [comment]
Yeah, it works with a slight patch.

https://github.com/signalpoint/DrupalGap/issues/105

**Comment by signalpoint** [comment]
@cschaub - will you please send me the code you were using for this comment? (https://github.com/signalpoint/DrupalGap/issues/89#issuecomment-21407099)

Were these menu links in your settings.js file?

UPDATE - nevermind, I see your code example here: #105

**Comment by scotthooker** [comment]
I tested both before and after that comment using the code in the latest version of theme.inc.js with my menus defined in settings.js

**Comment by signalpoint** [comment]
@scotthooker - you grabbed the latest version of common.inc.js too, right?

**Comment by scotthooker** [comment]
Yep. Everything in the includes directory :) 

But I see you updated that comment now ;) the patch in 105 works for me :)
