### ISSUE TITLE
Updating User Fields

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#890]
I'm working on a function to update a user field. However, I am noticing unexpected behavior. When I perform a `user_update` within `user_load`, all the field values get reset to the field's default value. So, if I have 6 fields (all on/off) that are defaulted to be on (checked), then when I perform a `user_update` all 6 fields get set as on (checked) even though the user has all the values as off (unchecked). Additionally, my console.log() is not being displayed. Here is how I am doing the `user_load`:

    function user_settings_enable_email_notifications() {
 
      user_load(Drupal.user.uid, { success:function(account) {

        user_update(account, { success:function(account) {
          
          console.log('--- user_update ---');
          
        }});    

      }});  
      
    }

**Comment by signalpoint** [comment]
@mkinnan Yes this can happen and is pretty much a side effect of the Services module using the dang Forms API during CREATE and UPDATE.

I'll typically massage the `account` object before calling `user_update`, so that the object is only updating the necessary data.

```
var account = {
  uid: 123,
  field_foo: { und: [ { value: 'bar' } ] }
};
user_update(account);
```

If I *need* to user `user_load` prior to the call (similar to your example), then I'll delete things off the `account` object to cleanse it before save.

```
delete account.field_foo;
```

**Comment by mkinnan** [comment]
@signalpoint That would be ideal to use the __var account__ approach since all I am trying to do is update one user field. I have this but it gives an error on `user_update`:

    function user_settings_enable_email_notifications() {
      var account = {
        uid: 89,
        field_enable_email_notifications: { und: [ { value: 1 } ] }
      };
      user_update(account);
    }

---

    services_resource_defaults - TypeError: Cannot read property 'service' of undefined
    jdrupal.js:2035 entity_update - TypeError: Cannot read property 'service' of undefined

**Comment by signalpoint** [comment]
@mkinnan I didn't include it in my code, but you need to pass along the `options` object to react to the update:

```
user_update(account, {
  success: function(result) {
    console.log(result);
    // Do something...
  },
  error: functuion(xhr, status, msg) { drupalgap_alert(msg); }
});
```

**Comment by mkinnan** [comment]
@signalpoint Thank you! I'm getting closer, but something is still acting strange. The default value for the field is 0 (off). I'm sending the value 0. Yet, it still ends up getting a value of 1 (on) ... as viewed on the website user settings.

    function my_module_user_settings_page() {
      try {
        
        var content = {};
        
        content['enable_email_notifications'] = {
          theme: 'checkbox',
          attributes: {
            id: 'enable_email_notifications',
            onchange: 'user_settings_enable_email_notifications()'
          }
        };

        content['my_checkbox_label_1'] = {
          theme: 'form_element_label',
          element: {
            title: 'Enable Email Notifications',
            attributes: {
              'for': 'enable_email_notifications'
            }
          }
        };
        
        var een = Drupal.user.field_enable_email_notifications.und['0']['value'];
        if(een == 1) { content['enable_email_notifications'].attributes.checked = 'checked'; }

        return content;    
        
      }
      catch (error) { console.log('my_module_user_settings_page - ' + error); }
    }

---
    
    function user_settings_enable_email_notifications() {

      var account = {
        uid: 625,
        field_enable_email_notifications: { und: [ { value: 0 } ] }
      };
      
      user_update(account, {
        success: function(result) {
          drupalgap_toast('<p>Updated!</p>', 1000);
        }
      });  
      
    }

**Comment by signalpoint** [comment]
@mkinnan In Drupal, if the field is powered by a checkbox, then it's little tricky with Services. I can't remember the exact syntax, but you may need to send `null` instead of `0`, or perhaps just sending the empty `[]` for the `und` value, or maybe sending `null` here instead of the array. You'll have to try a few of them, I forget which one sticks, but it is most likely not zero, because of course it couldn't be that easy, right?

**Comment by mkinnan** [comment]
@signalpoint Of course it's not that easy, lol :) I'll write up a tutorial page on a settings page once I hopefully get something to work :-/ I think there will be an audience for that capability. Here's what worked for unchecking the box:

    field_enable_email_notifications: { und: null }

One issue resolved and another encountered ... caching?

- uncheck the box in ripple emulator app
- in my `user_settings_enable_email_notifications()` function, I call `user_load` right before `user_update`... field value is __1__
- perform `user_update` to change value to __0__
- call `user_load` again right after `user_update` ... field value is still __1__
- website value on user's page shows it was changed and unchecked
- navigate to another page in app and then back to the settings page
- checkbox still shows checked

**Comment by mkinnan** [comment]
I've got a reload on my settings page:

          items.push(bl('Settings', 'settings', {
              attributes: {
                'data-icon': 'lock',
                'class': 'menulinks'
              },
              reloadPage:true
          }));

**Comment by mkinnan** [comment]
I've also got a reload on my menu item:

    items['settings'] = {
      title: 'Settings',
      page_callback: 'my_module_user_settings_page',
      options:{
        reloadPage:true
      }
    };

**Comment by mkinnan** [comment]
@signalpoint I have verified the page is reloading. But I don't understand why the values of the fields in  __Drupal.user__ are not showing as changed. I view `console.log(Drupal.user)` in the app, then change field values on the website, then navigate pages in the app but `console.log(Drupal.user)` isn't showing the values have changed. When I view the edit page of the user in the app the fields show that the values were changed. I even tried saving the user edit page but `console.log(Drupal.user)` still shows values unchanged. Does DrupalGap store __Drupal.user__ in cache locally until restarting the app? Can it be forcefully cleared and rebuilt?

**Comment by mkinnan** [comment]
@signalpoint Is this a related issue? https://github.com/signalpoint/DrupalGap/issues/839

**Comment by signalpoint** [comment]
@mkinnan Maybe you need to overwrite `Drupal.user` after saving:

`Drupal.user = account`;

**Comment by mkinnan** [comment]
@signalpoint Great suggestion ... i got something working now ... what do you think of this approach:

    function user_settings_enable_email_notifications() {

      // get value of checkbox
      var een = Drupal.user.field_enable_email_notifications.und['0']['value'];
      
      // box has been unchecked
      if(een == '1') {
        var account = {
          uid: Drupal.user.uid,
          field_enable_email_notifications: { und: null }
        };
        Drupal.user.field_enable_email_notifications.und['0']['value'] = '0';
      }
      
      // box has been checked
      if(een == '0') {
        var account = {
          uid: Drupal.user.uid,
          field_enable_email_notifications: { und: [ { value: '1' } ] }
        };
        Drupal.user.field_enable_email_notifications.und['0']['value'] = '1';
      }
      
      // update user settings on server
      user_update(account, {
        success: function(result) {
          drupalgap_toast('<p>Updated!</p>', 1000);
        }
      });  
      
    }

**Comment by mkinnan** [comment]
Last reply still works great with no known issues.
