### ISSUE TITLE
WARNING: theme_view() - this id already exists in the DOM

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#896]
When I'm trying to reload a page (reload: true), I get this error:

`WARNING: theme_view() - this id already exists in the DOM: #open_tasks_view - the view will be rendered into the first container that is located in the DOM - if you are re-using this same view, it is recommended to append a unique identifier (e.g. an entity id) to your views id, that way you can re-use the same view across multiple pages.`

Can I ignore this warning? Is the page being removed from the DOM before it is reloaded?

**Comment by signalpoint** [comment]
@luxio Yes, you can ignore this warning. It's just meant to be a warning to help developers overcome oddities with this multi-page app. I've debated removing the warning from core, but I think it may help beginners when understanding the multi-page app structure. Thoughts?

**Comment by luxio** [comment]
The warning makes sense. But shouldn't the id of the "old" view be removed form the DOM, when a page is reloaded?

**Comment by signalpoint** [comment]
@luxio Correct, and I think the old view does get removed from the DOM, after the message is displayed, which is misleading for sure. After the message is displayed, a `reloadPage` will override this and then try to place the new page (and duplicate view id) back into the DOM.

It's really just meant to tell the developer to just make a more unique `id` attributes on their Views Render Array, then this warning will go away. It annoys me sometimes as well.

**Comment by luxio** [comment]
Thanks.
