### ISSUE TITLE
cordova bug, navigator.connection.type

### ISSUE THREAD

**Issue by lightsurge** [signalpoint/DrupalGap#9]
While it should be navigator.connection.type, there's a bug in cordova which means it still needs to be navigator.network.connection.type

https://issues.apache.org/jira/browse/CB-1807

https://github.com/signalpoint/DrupalGap/blob/7.x-2.x/drupalgap.js#L1044

**Comment by signalpoint** [comment]
Thanks for reporting this bug with cordova. I've adjusted DrupalGap to account for this.

Fixed. https://github.com/signalpoint/DrupalGap/commit/872408f6dcdd86ad54c72c13199af33924774b56
