### ISSUE TITLE
Possible to Add Form Element to a View with Exposed Filters?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#903]
I am currently using a Views Render Array to for a view to display a list of nodes near me using geolocation. The view already has an exposed filter. I want to provide a Select List Form Element to give the user the option to select within a distance (e.g. 10 miles, 25 miles, etc). Is this possible to add a filter option like that in order to append the lat/long with the user selected distance?

**Comment by signalpoint** [comment]
@mkinnan Possibly, use `hook_form_alter()` to make an alteration to the Views Exposed Filter form. Use conditions to limit the alteration to only the page(s) that you're interested in. You can then add a select list element to the form that way. You'd then have to use a Service Preprocess hook in DrupalGap to intercept the call off to Drupal, and then append your distance filter to the URL query string that retrieves the Views JSON data.

**Comment by mkinnan** [comment]
@signalpoint I haven't quite figured out the Service Preprocess hook yet ... but I follow the rest. What I have right now is a `default search radius` field for the user they can edit on their user page. Then I grab that field value when the view is being displayed.

**Comment by gs9999** [comment]
Hello mkinnan,

signalpoint has alluded to the service postprocess hook in other issues, specifically regarding editing the user object in a user_load.

Note this ticket number https://github.com/signalpoint/DrupalGap/issues/641

here is a sample code, but you will need the name of the callback to proceed.  Perhaps, all you need to do is change it from a postprocess to a preprocess.  Note also, this code belongs in a custom module on the Drupal side (php).  But I think this sends you in the right direction.  I find it useful to peruse all the issues (nearly 1000), with general searches in the issue threads--its been very helpful.

```
/**
 * Implements hook_services_request_postprocess_alter().
 */
function my_module_services_request_postprocess_alter($controller, $args, &$result) {
  if ($controller['callback'] == '_system_resource_connect') {
    global $user;
    if ($user->uid) {
      $account = user_load($user->uid);
      unset($account->pass);
      $result->user = $account;
    }
  }
}


```

**Comment by signalpoint** [comment]
@mkinnan I happened across a similar situation last evening, and wrote up a docs page about which should help you solve this situation. No exposed filters are used on the View, instead Contextual filters will be used. Then we add Input Widgets and a refresh-able Views Render Array to a custom page to simulate the concept of an exposed filter.

http://docs.drupalgap.org/7/Views/Views_Contextual_Filters

Also in regards to Views Exposed Filters support within DrupalGap, I am personally going to abandon it and continue to utilize the technique linked above instead. Here's the notice regarding non-support for Views Exposed Filters: http://docs.drupalgap.org/7/Views/Views_Exposed_Filters

**Comment by mkinnan** [comment]
@signalpoint This is a great example! I'll give it a shot. Thanks!

**Comment by mkinnan** [comment]
http://docs.drupalgap.org/7/Views/Views_Contextual_Filters is the way to go.
