### ISSUE TITLE
drupalgap_set_message() images missing?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#904]
The little icons inside the box on the left appear to be missing:
http://docs.drupalgap.org/7/Widgets/Messages

http://example.com/mobile-application/css/images/message-24-warning.png
... gives me `not found`.

**Comment by signalpoint** [comment]
@mkinnan The images should be loading from the `images/*` folder, not the `css/images/*` folder. https://github.com/signalpoint/DrupalGap/tree/7.x-1.x/images

I'm not sure how you're getting the `css` folder prepended on the image path, any ideas?

**Comment by signalpoint** [comment]
@mkinnan FYI, make sure you have the most up to date `drupalgap.css` file, and that the file is located in the `css` directory, and not in the root `www` directory of the PhoneGap/Cordova project.

**Comment by mkinnan** [comment]
@signalpoint It was the CSS file. Moved the changes over to my custom CSS file and it's good to go. I wish all my drupalgap issues were that easy ...
