### ISSUE TITLE
Add classes to links

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#91]
It would be nice to be able to add class as a property of menu links. That way, each drawn link could have a class for background images etc. Right now, just title and path are passed.

**Comment by signalpoint** [comment]
Hey Chris, luckily this is already possible, e.g.

l('My Link', 'node/123', {attributes:{class:'my_class_name'}});

Everything that runs through the theme() system has an opportunity for attributes. The theme system eventually calls drupalgap_attributes if it detects any attributes. Check out the drupalgap_attributes() function for details (and there is a bug with that function, so be careful passing in double quotes or single quotes to it).

**Comment by chrisschaub** [comment]
Yeah, I saw it with l , but I don't think it works from the menu definitions in settings.js. They are just an array of title and path. I looked at the function and it doesn't seem to take any other options? Sorry if I'm being dense.

**Comment by signalpoint** [comment]
@cschaub - no problem, sorry for the delay in response, I was out of town for the 4th.

Here's a quick example of a menu link in settings.js with a custom class:

{title:"Events", path:"events", options:{attributes:{class:"my_custom_class"}}},
