### ISSUE TITLE
Catching an error

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#92]
Just a high-level question. When your app has a fatal error, is there any way to catch it and just restart from the top? Basically force a reload? Just curious if you have a general approach the app handles errors gracefully.

**Comment by signalpoint** [comment]
When you say "fatal error", do you mean a 'white screen of death' when you compile it to an actual device, or is this in Ripple?

When compiling to a device, and if I get a WSD, I'll have to fix the code before the WSD will go away. When in Ripple, just an F5 for refresh will restart the App for me.

Honestly I don't really have a graceful approach to handling errors. I've always been frustrated by the way JS handles error (i.e. not telling exactly what line number and or function is causing the problem. This has lead me to to my best to wrap everything in a try/catch clause that will alert any errors and the function name.

**Comment by signalpoint** [comment]
Closing this issue in favor of #98.
