### ISSUE TITLE
Login session persistent only if you exit from app first.

### ISSUE THREAD

**Issue by sheshadri** [signalpoint/DrupalGap#920]
Hi,

Login sessions are destroyed as soon as you kill the app from the recent apps window, but when you exit the app from within the app using back button, login sessions are persistent. Once you exit the app using back button the session stays even after killing the app from recent app window.

Basically unless you exit from within the app the session are not stored.

Regards,

**Comment by sheshadri** [comment]
Hi,

Update: I was wrong, the login sessions are very intermittent, it works sometimes and logs out sometimes, I have set cookie lifetime to max and I have read other posts too but nothing works.

**Comment by mkinnan** [comment]
@sheshadri ... Did you try this:

https://github.com/signalpoint/DrupalGap/issues/908

**Comment by sheshadri** [comment]
@mkinnan yes I have that module installed too, I have set gc_maxlifetime to 2 years, we have tested in Kitkat, Marshmallow and Nougat also.  I thought it was related to cache being reset in Drupal website but then some users logged out when I did not touch the cache, like I mentioned its very intermittent like in some devices it never logs out no matter what you do(like even restart the phone itself) and in some devices as soon as you close the app it logs out. We checked with phone permissions giving storage access for caching if needed, but still same problem persists .

**Comment by mkinnan** [comment]
@sheshadri ... Does this happen on both iOS and Android? Have you taken daily snapshots of the sessions table in your database to see if you can spot trends of sessions being deleted?

**Comment by sheshadri** [comment]
@mkinnan  unfortunately no, I had to switch to another project. We are planning to develop another app and I shall certainly take a look at the sessions table and update here.
