### ISSUE TITLE
my drupalgap use block only show [object object]

### ISSUE THREAD

**Issue by SunBar226** [signalpoint/DrupalGap#923]
my drupalgap use block only show [object object]
I only use the example in drupalgap.org

```
/**
 * Implements hook_block_info().
 */
function my_module_block_info() {
  var blocks = {};
  blocks['my_custom_block'] = {
    delta: 'my_custom_block',
    module: 'my_module'
  };
  return blocks;
}

/**
 * Implements hook_block_view().
 */
function my_module_block_view(delta, region) {
  var content = {};
  if (delta == 'my_custom_block') {
    // Show today's date for the block's content.
    var d = new Date();
    content['date'] = {
      markup: '<h2><center>' + d.toDateString() + '</center></h2>'
    };
  }
  return content;
}
```

**Comment by signalpoint** [comment]
@Sanchiz please download the latest development snapshot of the `bin/drupalgap.min.js` file: http://drupalgap.org/download

It contains the fix for #403

**Comment by SunBar226** [comment]
@signalpoint I had updatethe drupalgap.min.js but it also show [object object]

**Comment by signalpoint** [comment]
@SunBar226 did you flush your browser's caches?

**Comment by SunBar226** [comment]
@signalpoint yes, I had flush my browser's caches

**Comment by SunBar226** [comment]
@signalpoint THX I know how to do that I can show it now

**Comment by signalpoint** [comment]
@SunBar226 Excellent, thank you for the follow up, good luck and happy coding!

**Comment by oluabbeys** [comment]
am having the same issue and I have cleared my cache, use the latest bin/drupalgap.min.js file. Kindly help me out. thank you

**Comment by signalpoint** [comment]
@oluabbeys This is the download link for the latest: https://raw.githubusercontent.com/signalpoint/DrupalGap/7.x-1.x/bin/drupalgap.min.js

**Comment by oluabbeys** [comment]
I have downloaded it but still having the object object issue. Thank you for prompt response

**Comment by oluabbeys** [comment]
This is my code, I used exact code in the documentation except the module name which I changed to my front.

```
/**
 * Implements hook_block_info().
 */
function front_block_info() {
  var blocks = {};
  blocks['my_custom_block'] = {
    delta: 'my_custom_block',
    module: 'front'
  };
  return blocks;
}

/**
 * Implements hook_block_view().
 */
function front_block_view(delta, region) {
  var content = {};
  if (delta == 'my_custom_block') {
    // Show today's date for the block's content.
    var d = new Date();
    content['date'] = {
      markup: '<h2><center>' + d.toDateString() + '</center></h2>'
    };
  }
  return content;
}
```
```
/** Custom Modules - www/app/modules/custom **/

Drupal.modules.custom['front'] = {};

 footer: {
   
	my_custom_block:{},
	 powered_by: { },
   
  }
```

**Comment by errand** [comment]
Hello! I'm having the same issue with latest code and snippets from tutorial:)

**Comment by errand** [comment]
OK, i've took an example from  drupalgap.js and used system_block_view() theme as an example:
here is the working example:
```
function my_module_block_view(delta) {
  try {
    switch (delta) {
      case 'my_module_block':
      	var d = new Date();
        var html =  '<h2><center>' + d.toDateString() + '</center></h2>';
        return html;
        break;
  }
}
  catch (error) { console.log('system_block_info - ' + error); }
}
```

**Comment by signalpoint** [comment]
@errand Yes, you can simply return an html string to render your block. The [object object] error just means to download the latest `bin/drupalgap.min.js` file, and then be sure to clear your browser cache and then you can use render arrays (widgets) within your block content too. I need to release a new recommended version of DrupalGap with this fix.

**Comment by wolesisme** [comment]
i also get the same issue and i have downloaded thet latest drupalgap.min.js but not work at all here is the code maybe i miss something
`function my_block_block_view(delta, region) {
var content = {};
  var uidnya = Drupal.user.uid;
  var usernya = user_load(uidnya, {
    success:function(account) {
    var namaku2 = account.field_nama_lengkap.und[0].value;
     if (delta == 'my_custom_block') {
    content = '<center>' + namaku2 + '</center>';
  //  alert(content);
   console.log(account);
     }
   }
});
   

  return content;
 
}
`
please help ! thanks

**Comment by signalpoint** [comment]
@wolesisme  Replace your existing `drupalgap.min.js` file with the latest [drupalgap.min.js file](https://raw.githubusercontent.com/signalpoint/DrupalGap/7.x-1.x/bin/drupalgap.min.js), then clear your browser's cache to fix it.

**Comment by wolesisme** [comment]
thanks for replying me, i have done that i replace my drupalgap.min.js in bin/ but did'nt work i got even more bug because my all block footer is disappears, i change the drupalgap.js as well and change this line  <script type="text/javascript" charset="utf-8" src="bin/drupalgap-7.0.2.min.js"></script> my module version is 7.17 my drupalgap js is 7.02 but nothing happen.

**Comment by yazzou** [comment]
I have created a new test site and used another computer with a fresh browser session. I have replaced the indicated files before loading the app but still getting the [object object] message. 
I finally edited the file **index.html**  located at the root of drupal development kit
and changed this 

```
<!-- DrupalGap -->
<script type="text/javascript" charset="utf-8" src="bin/drupalgap-7.0.2.min.js"></script>
 <script type="text/javascript" charset="utf-8" src="app/settings.js"></script>
   <link rel="stylesheet" href="css/drupalgap.css" />
```
to this 

```
  <!-- DrupalGap -->
	  
<script type="text/javascript" charset="utf-8" src="bin/drupalgap.min.js"></script>
      <script type="text/javascript" charset="utf-8" src="app/settings.js"></script>
      <link rel="stylesheet" href="css/drupalgap.css" />
```

The custom module of the docs works and displays the data as expected 
Thanks
