### ISSUE TITLE
My windows detected virus in Drupal GAP SDK

### ISSUE THREAD

**Issue by daroraghub** [signalpoint/DrupalGap#925]
Hi,
I was trying to install DrupalGap SDK from the link https://github.com/signalpoint/DrupalGap/archive/8.x-1.x.zip in step #2 on this documentation page
http://docs.drupalgap.org/8/Resources/Manual_Installation
But when I tried to download it, my windows virus protector detected the virus and didn't let me download the file. This is the error I got.  
Please check. 

=====================
Category: Trojan
Description: This program is dangerous and executes commands from an attacker.
Recommended action: Remove this software immediately.
Items: 
file:C:\ProgramData\Microsoft\Windows Defender\LocalCopy\{FAE7AF6B-2DEA-484C-AC9B-98786EB61A38}-DrupalGap-8.x-1.x.zip

**Comment by daroraghub** [comment]
Seems like the link on documentation page is old and pointing to archive location and probably that's why it's erroring out.

**Comment by signalpoint** [comment]
@daroraghub Thank you for pointing this out. I can assure you there is no virus in the DrupalGap SDK source code, it's purely HTML/CSS/JS.

**Comment by daroraghub** [comment]
Thanks. Strangely my system is not allowing me to download the zip even if I try to download it directly from branch 8.x-1.x https://github.com/signalpoint/DrupalGap/tree/8.x-1.x,  as I get the same error. 
I will clone the repo and work that way.  Thanks for assurance.
