### ISSUE TITLE
Page Callback for Remote Custom Data

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#927]
When I follow the guide here:
http://docs.drupalgap.org/7/Forms/Form_Elements/Autocomplete/Autocomplete_with_Remote_Custom_Data

I can't get the page callback to give the values from the actual page_callback. When I do something like this

    var terms = my_module_autocomplete_page();
    console.log(terms);

It only gives:
![capture-output](https://cloud.githubusercontent.com/assets/13283396/25464639/b325854c-2aba-11e7-960d-dae5cdde5a3b.PNG)

So, when it populates that autocomplete field the only 'option' is [OBJECT].

Is the guide outdated? Or am I missing something else?

Thanks!

**Comment by signalpoint** [comment]
@mkinnan Calling `my_module_autocomplete_page()` will literally return the `content` object defined in that function, as indicated by your console.log screen shot. If you're trying to intercept the terms returned by the autocomplete, you'll want to use a services post process hook: http://api.drupalgap.org/7/global.html#hook_services_postprocess

```
/**
 * Implements hook_services_postprocess().
 */
function my_module_services_postprocess(options, result) {
  console.log(options); // Inspect to look at the `service` and `resource` values.
  if (options.service == 'foo' && options.resource == 'bar') {
      var terms = result;
      console.log(terms);
  }
}
```

If you can't build an `if` condition using `service` and/or `resource`, you should be able to check if `options.path == dg/option-list-cities` for your if statement.

**Comment by mkinnan** [comment]
@signalpoint ... I think I am getting somewhere but getting an error. Is views_datasource supposed to be getting called since my page is _not_ a view?

Also, I noticed that a question mark isn't being applied before the parameter string ... a bug?

![capture-output2](https://cloud.githubusercontent.com/assets/13283396/25466438/ee4b3ee0-2ac5-11e7-9ce6-5a6425b1f95a.PNG)

**Comment by signalpoint** [comment]
@mkinnan It looks like the autocomplete widget is reporting that views_datasource is the service it is running through. Is your `dg/option-list-cities` page a View? If not, that's OK, it seems the autocomplete just defaults to saying that `views_datasource` is the `service` for remote custom data.

As for the question mark, that is OK, internnally jDrupal prepends the question mark to the front of the query string for any service calls.

**Comment by mkinnan** [comment]
@signalpoint My `dg/option-list-cities` page is not a View. I'm following the example at:
http://docs.drupalgap.org/7/Forms/Form_Elements/Autocomplete/Autocomplete_with_Remote_Custom_Data

I copy/pasted into `my_module.module` and then into `my_module.js`. Once the page in the app loads and I type a letter, I get the `TypeError: Cannot read property 'child' of undefined` as shown in my previous post. I'm not sure why I'm getting that error.

**Comment by mkinnan** [comment]
@signalpoint I don't see where in `views_datasource_get_view_result(path, options)` there would be a __child__ property. Any ideas? Or do I just console.log every line in `views_datasource_get_view_result(path, options)`?

**Comment by mkinnan** [comment]
@signalpoint ... can you please confirm that `_my_module_autocomplete` in __my_module.module__  should give this as the output that will be used as the input for the app:

`[{"nid":"2644","title":"Super Fun Cruise"},{"nid":"1102","title":"Weekly Meet"},{"nid":"1157","title":"Cars"}]`

I'm wondering if there is an issue with `_theme_autocomplete` and a handler that can't process the JSON like that and it expects it to be processed like Views JSON output. Thoughts?

**Comment by mkinnan** [comment]
In __drupal.js__, change the following code in ___theme_autocomplete(list, e, data, autocomplete_id)__

    // Finally call the sucess handler.
    var fn = _theme_autocomplete_success_handlers[autocomplete_id];
    fn(autocomplete_id, result_items, wrapped, results.view.child);

to

    // Finally call the sucess handler.
    var fn = _theme_autocomplete_success_handlers[autocomplete_id];
    fn(autocomplete_id, result_items, wrapped);

And it now works fine.

**Comment by mkinnan** [comment]
https://github.com/signalpoint/DrupalGap/pull/929

**Comment by signalpoint** [comment]
@mkinnan You're a life saver, this was burning me this morning, and you pin-pointed the line of code. I shall follow up soon and we'll get this one closed out.

`views_datasource_get_view_result - success - TypeError: Cannot read property 'child' of undefined`

**Comment by signalpoint** [comment]
@mkinnan I've merged in your changes and then made some minor adjustments We should be good to go now, thank you again for your help!

https://github.com/signalpoint/DrupalGap/commit/9fd14c87f13fab4ea39ceb54c8e5b509fafe8045

**Comment by emanuel-london** [comment]
Still running into the same error, even with the changes.

**Comment by signalpoint** [comment]
@emanuel-london Did you download the latest dev snapshot of the `drupalgap.min.js` file?
