### ISSUE TITLE
Add Blank Item To Select List Widget?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#931]
Using the __Select List Widget__, how does one forcibly add a _blank_ or _-- Please Select --_ for the first item? So how to modify this:

    var content = {};
    content['my_select_list'] = {
      theme: 'select',
      options: {
        0: 'No',
        1: 'Yes',
        2: 'Maybe So'
      },
      value: 2
    };

To be able to do something like this (http://stackoverflow.com/a/23638053):

    <select>
        <option disabled selected value> -- select an option -- </option>
        <option>Option 1</option>
        <option>Option 2</option>
        <option>Option 3</option>
    </select>

**Comment by mkinnan** [comment]
@signalpoint Here's what seems to be working for me:


    function my_module_post_process_page(variables) {
      try {

        document.getElementById('my_select_list').selectedIndex = -1;
        
      }
      catch (error) { console.log('my_module_post_process_page - ' + error); }
    }

If you like this approach, I'll update the documentation to include this example.

**Comment by mkinnan** [comment]
@signalpoint This works too in order to show helpful text to the user


    function my_module_post_process_page(variables) {
      try {

        $("#my_select_list").prepend("<option disabled selected value> -- select an option -- </option>");
        
      }
      catch (error) { console.log('my_module_post_process_page - ' + error); }
    }

**Comment by signalpoint** [comment]
@mkinnan I'll typically do something like this when using a render array:

```
content['my_select_list'] = {
  theme: 'select',
  options: {
    '': '-- ' + t('Please select') + ' --',
    0: 'No',
    1: 'Yes',
    2: 'Maybe So'
  }
};
```

Or preferably using a form element like this:

```
form.elements.my_select_list = {
  type: 'select',
  options: {
    '': '-- ' + t('Please select') + ' --',
    0: 'No',
    1: 'Yes',
    2: 'Maybe So'
  },
  required: true
};
```

**Comment by mkinnan** [comment]
@signalpoint Thanks!! It seems obvious now in hindsight :)
