### ISSUE TITLE
Query string parameters are removed during application start up

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#939]
To reproduce (an example)...

1. build a custom page with a path of `maps`
2. try linking to `#maps?nid=123` from an external source so it is the first page loaded upon application startup
3. the value of `nid` will not be available via `_GET('nid')` in the `page_callback`, `pageshow`, etc handler functions for the path

This is a bug, squash it.

**Comment by signalpoint** [comment]
This may be related to #935 .

FYI: @mkinnan

**Comment by mkinnan** [comment]
@signalpoint ... Definitely sounds related to me. No matter what I did, query string is removed from a link.

**Comment by signalpoint** [comment]
Upon application start up, any query string parameters will be set aside so they can be used in the page's handlers. When visually looking at a browser's URL address bar during application start up, the query string will still be removed, but internally it is retained so page handlers will be able to grab a copy of it.

During normal application navigation (via `l()`, `bl()`, `drupalgap_goto()`), the query string parameters should remain in the browser's URL address bar as usual.
