### ISSUE TITLE
drupalgap_file_exists() does not work correctly

### ISSUE THREAD

**Issue by Gys** [signalpoint/DrupalGap#94]
Today I installed the Kit and tried to run it.
I got two errors that related all to drupalgap_file_exists(): apparently two theme related files could not be found. But these files are there and if all runs fine I comment out the file checks.

**Comment by signalpoint** [comment]
@Gys - What are the two files in question?

**Comment by Gys** [comment]
The two files are referred to in common.inc.js:
themes/easystreet3/easystreet3.js
themes/easystreet3/page.tpl.html

**Comment by signalpoint** [comment]
Hmmm, that is a strange error. I'm curious to see the exact error message when you mention "I got two errors that related all to drupalgap_file_exists()". If an alert dialog pops up with an error, will you please copy/paste that here? Also, verify the 'debug' variable is set to true in your settings.js file, then please copy/paste any console.log information that is printed right before your error happens for more clues.

**Comment by signalpoint** [comment]
@Gys - are you still having problems with this? I haven't been able to reproduce this bug.

**Comment by Gys** [comment]
Thank you very much for getting back to me.

I decided Drupalgap is not the way to go for me: I want a simple js library for connecting only. Drupalgap seems to add complexity that I currently do not need for my projects.

**Comment by signalpoint** [comment]
@Gys - no problem, sorry it wasn't of use to you. Alternatively, you may want to check out this project:

https://github.com/travist/drupal.api.js

That looks like it provides a light weight solution for communicating with Drupal Services.

Good luck, and happy coding!
