### ISSUE TITLE
Page Transitions 

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#95]
Is it possible to change the page transition in drupalgap?

**Comment by chrisschaub** [comment]
Yes, use this in a top level events.js file ...

// default transition
$.mobile.defaultPageTransition = "none";

or

// default transition
$.mobile.defaultPageTransition = "slide";

**Comment by signalpoint** [comment]
I'd like to implement a more robust solution to this, re-opening.

**Comment by signalpoint** [comment]
@scotthooker & @cschaub - Page transitions are now supported! Documentation added:

http://drupalgap.org/node/135
