### ISSUE TITLE
CSRF validation failed error after new user registers

### ISSUE THREAD

**Issue by Jody-Lee** [signalpoint/DrupalGap#950]
When a new user registers with the cordova/phonegap App they get an error - CSRF validation failed.

I did a search or three and found the problem. However, I'm unsure how to fix it.

The problem is communicating with the services module. It needs an X-CSRF-Token to authenticate the session. I've found info here about the issue:

https://www.drupal.org/node/2013781
https://stackoverflow.com/questions/17975142/drupal-7-services-3-4-with-session-authentication-and-jquery
https://www.drupal.org/node/790416#comment-11975936
https://www.drupal.org/node/2056281

They provide advice and some code although it's not directly regarding DrupalGap.

As a novice App engineer that hasn't yet fallen off the Drupal cliff yet, it would be helpful if you could provide a clear solution. Maybe added to your really helpful Documentation as anyone new building an App with Drupal and DrupalGap must come across the same issue.

Thanks in advance for your help.

**Comment by signalpoint** [comment]
@Jody-Lee Are you using any contrib/custom modules in Drupal that are hooking into the user login/registration process? Some popular example are Login Toboggan, Email Registration, etc. These are known to conflict with Services+DrupalGap and cause CSRF errors during user registration, unless you have their corresponding module's installed in your DrupalGap application as well.

**Comment by Jody-Lee** [comment]
I've looked through the modules and can't see any that might be causing a conflict. However, here's a list of all installed module on Drupal, DrupalGap, and plugins. Maybe I missed something...
acl
addtoany
admin_menu
adsense
ckeditor
colorbox
content_access
context
ctools
dfp
drupalgap
ds
entity
entity_modified
features
fences
filefield_sources
flexiaccess
front
google_analytics
image_field_caption
imce
imce_filefield
jquery_update
libraries
link
metatag
node_view_permissions
nodeaccess
pathauto
profile2
push_notifications
rate
recipe
rules
schemaorg
services
services_votingapi
title
token
views
views_datasource
views_infinite_scroll
votingapi
wysiwyg
xmlsitemap

DrupalGap modules
colorbox
custom
ds
google_analytics
link
push_notifications
rate
title
url
votingapi

Plugins
com.devicepush.cordova-phonegap
cordova-plugin-admob-simple
cordova-plugin-console
cordova-plugin-device
cordova-plugin-dialogs
cordova-plugin-file
cordova-plugin-inappbrowser
cordova-plugin-network-information
cordova-plugin-whitelist
cordova-plugin-x-socialsharing

**Comment by signalpoint** [comment]
@Jody-Lee Any Rules on your site set to tinker with user login/registration workflows?

**Comment by Jody-Lee** [comment]
No, rules haven't been set yet. Going to send out emails when content is published but got side tracked with this issue.

**Comment by signalpoint** [comment]
@Jody-Lee ok. Please report your configuration for the **REGISTRATION AND CANCELLATION** section on this page in Drupal: `admin/config/people/accounts`. 

Also, on this additional page in Drupal `admin/structure/services/list/drupalgap/resources`, verify the **Services
Resource API Version** is set to `1.0` under the `login` and `register` resources provided within the **user** resources section.

**Comment by Jody-Lee** [comment]
OK, REGISTRATION AND CANCELLATION is set to Visitors and Disable the account and keep its content.

**Comment by Jody-Lee** [comment]
FINGER SLIPPED :-)
Login and logout are both set to 1.0, but register does not have a setting option.

**Comment by Jody-Lee** [comment]
@signalpoint Do you have an idea why this error is occurring?

**Comment by signalpoint** [comment]
This comment offers a possible solution: https://www.drupal.org/node/2862956#comment-12081906

**Comment by Jody-Lee** [comment]
Yep, that works. Thanks Tyler.
