### ISSUE TITLE
Drupal 8 http://demo.drupalgap.org/8/ doesn't load

### ISSUE THREAD

**Issue by powpow12** [signalpoint/DrupalGap#952]
Hey was looking at the demo and it doesn't load. 
![image](https://user-images.githubusercontent.com/3721535/31303540-34048ff8-aadd-11e7-86ed-03705f0b25fd.png)

**Comment by signalpoint** [comment]
@powpow12 Dang, thank you for pointing this out. I moved drupalgap.org to a new server about 2 weeks ago, and I thought I had the demos working properly. I am attending a wedding today, and visiting some waterfalls tomorrow, so surely there will be time on Monday to resolve this!

In the mean time, thank you for your interest in DrupalGap 8, it is really coming along (despite the demo site being broken). Please let me know if you have any other questions.

**Comment by powpow12** [comment]
@signalpoint no problem, that's what the issue queue is for, right 😄 ? Hope you have a good weekend, waterfalls are epic and any time away from the computer should be cherished.  I have a use case I am looking at DrupalGap for but need to play around with it first.

Did I see phonegap is not production ready? Is there a roadmap somewhere?

**Comment by signalpoint** [comment]
@powpow12 Ok, finally got it back up and running. Had to get Drupal 8.4.0 running properly and all dependencies updates. I even took the time to add some SSL!

https://demo.drupalgap.org/8/

The phonegap/cordova version is pretty much production ready IMO, I now need to find the time to properly release it and get all the docs updated, make a nice recipe or two then promote it on Drupal Planet.

There isn't a roadmap... just in my head, for now.
