### ISSUE TITLE
tel: links in body being wrapped in drupalgap_goto()

### ISSUE THREAD

**Issue by willtate** [signalpoint/DrupalGap#953]
I'm printing node content (long text field) which contains some anchor tags with an href that contains `tel:` links.
The HTML source of the node contains items like :
`<a href="tel:15555555555">1.555.555.55555</a>`

But they are being rendered in app as:
`<a href="" onclick="javasciprt:drupalgap_goto('tel:15555555555');" class="ui-link">1.555.555.55555</a>`

I'm displaying the pages via a page() and pageshow() call like:

```
function example_page() {
  return '<div id="example_page"></div>';
}

function example_pageshow() {
  try {
    node_load(46176, {
      success: function(node) {
        $('#example_page').append(node.content).trigger('create');
      }
    });
  } catch (error) {
    logError('example_pageshow', error);
  }
}
```

Is there anything I can add to the links in the wysywig such as a class, data attribute or rel value that'll prevent drupalgap from manipulating them?  I'm not seeing this issue with `mailto:` links on the same node.

Appreciate any assistance.  Thanks!

**Comment by signalpoint** [comment]
@willtate Are you using this sandbox module? https://www.drupal.org/sandbox/signalpoint/2068317

**Comment by willtate** [comment]
Yes I am, but I actually think I ended up not needing its capabilities after all.  Is that the offending module?

**Comment by signalpoint** [comment]
@willtate Yes it is. From here http://cgit.drupalcode.org/sandbox-signalpoint-2068317/tree/drupalgap_pathfix.module , take a look at the `// Replace external links with an InAppBrowser link.` section. Essentially it isn't taking into consideration any `tel` links, and is rewriting them to work in the app. If that snippet can be adjusted to ignore `tel` links, then it should work without issue.

**Comment by willtate** [comment]
Thanks so much! I can totally fix this with a workaround.  I just needed a point in the right direction.  Appreciate the hasty response, you're the best.

**Comment by signalpoint** [comment]
@willtate No problem, please let me know when you have the fix and what it is, then I'll drop it into the module. Feel free to make a patch if you'd like, then I can easily attribute the contribution to your d.o account.

**Comment by willtate** [comment]
Added the issue and patch @ d.o https://www.drupal.org/node/2918755
