### ISSUE TITLE
connection status page - jdrupal no base URL

### ISSUE THREAD

**Issue by zak-schlemmer** [signalpoint/DrupalGap#954]
when visiting:
`admin/config/services/drupalgap`
the status never changes from:

> Testing connection...

This appears to be due to a missing base path on this GET request:
`http://jdrupal/connect?_format=json`

**Comment by signalpoint** [comment]
Duplicate issue here: https://www.drupal.org/node/2906036

Please follow up there, I'm curious what your `drupalSettings` is reporting. I wonder if that got changed around in 8.4.x...?
