### ISSUE TITLE
DG create module command should insert into index.js

### ISSUE THREAD

**Issue by zak-schlemmer** [signalpoint/DrupalGap#955]
http://docs.drupalgap.org/8/Modules/Create_a_Custom_Module
Step 2 should not be needed when using option A from the doc above.
It should be no problem for a CLI tool to insert that line into the index.html file automatically.
If there is a particular reason to not do this automatically, perhaps you could prompt the option.

**Comment by signalpoint** [comment]
@zak-schlemmer I didn't want to add any dependencies to the project (except for jDrupal). So I think letting folks pick their own CI tool is a good way to go here. For example, I'm using gulp to minify all my module .js files, and then use a bash script when deploying to production to cat them all together, and then include just a single .js file in the `index.html` file.

**Comment by zak-schlemmer** [comment]
I was referring to the manual adding of the of the line to the file.
Rather than outputting:
`Created module in modules/custom/bla, next include it in the index.html file:`
Why not finish the job for the user?

**Comment by signalpoint** [comment]
@zak-schlemmer Can that be done easily within the `./dg` bash script's create module routine?

**Comment by zak-schlemmer** [comment]
The dg script could essentially do this:
```
output='<script src="modules/custom/mything/mything.js"></script>'
line_number=`cat index.html | grep -n "drupalgap.min.js" | awk '{ print $1 }' | tr -d ':'`
sed "$(( ${line_number} +1))i ${output}" index.html
```
So, you already have $output; as it prints to screen.
You find the line number of the drupalgap.min.js script include.
Then you add one to that number and insert your line.

**Comment by signalpoint** [comment]
@zak-schlemmer Would you like to put that in a PR with some nice code comments and then change that output message to something like `Created module in modules/custom/bla and added it to the index.html` ?

**Comment by zak-schlemmer** [comment]
#956 is open that would close this issue.

**Comment by signalpoint** [comment]
#956 has been merged.
