### ISSUE TITLE
Update menu documentation

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [signalpoint/DrupalGap#959]
Hello,

I think maybe the page Adding Links to Menus for DrupalGap 8 should be updated.
http://docs.drupalgap.org/8/Menus/Adding_Links_to_Menus
The current code is probably pasted from version 7 and does not work. It throws the error that dg.settings.menus is not defined.
I am new to DrupalGap but from what I've understood, adding a link to an existing menu in D8 should now be done via hook_block_view_alter() so the doc page should be updated to say pretty much the same thing than for Altering existing menu links 
http://docs.drupalgap.org/8/Menus/Altering_Existing_Menu_Links
Which is : Since DrupalGap 8 Menus are Blocks, we can alter existing blocks to change the way menus are output.
And maybe it would be worth give an example to save time:
```
/**
 *  Implements hook_block_view_alter
 */
function my_module_block_view_alter(element, block) {
  switch(block.get('id')) {
    //Add a link to the main menu
    case 'main_menu':
      element.menu._items.push(
        dg.l("Map", 'map')
      );
      break;
  }
}
```

**Comment by Nicolas-Bouteille** [comment]
For the same reason, I think maybe the page about the menu icons is out of date
http://docs.drupalgap.org/8/Menus/Menu_Icons

**Comment by Nicolas-Bouteille** [comment]
Looks like the page "Menus with Dynamic links" is outdated  as well and based on DrupalGap 7 hook_block_info and hook_block_view
http://docs.drupalgap.org/8/Menus/Menus_with_Dynamic_Links

**Comment by Nicolas-Bouteille** [comment]
Same for PopUp menus and Slide Menus...

**Comment by signalpoint** [comment]
@Nicolas-Bouteille thank you for your feedback here. As you noticed, the DG8 docs started as a straight clone of the DG7 docs, and the DG8 docs still need much attention.

**Comment by signalpoint** [comment]
@Nicolas-Bouteille I've updated my deployment scripts just now so I can now quickly deploy improvements to docs.* and api.* to drupalgap.org's new server, and have them built from the `docs` folder in the project root directory, and build the `api` from the source code. Look for many rapid improvements to come, in the mean time please feel free to submit pull requests on the `docs` folder and we can get you in as a contributor.

**Comment by Nicolas-Bouteille** [comment]
Thank you Tyler for your quick answer! And that's great news for the doc.

About contributing, right now I still need to decide if I go with DrupalGap or another framework like Ionic since you seem to advertise that DG8 is not production ready and I would really like to work on Drupal 8 from now on. 
It looks very promising though so I really wanted to give it a try. I really like the idea of using the same syntax (almost) than Drupal in JS. If I choose to go with DrupalGap 8 and spend some time on it, I will be glad to contribute to the documentation and maybe more! But I have to warn you that I don’t have much experience with GIT and pull requests so I may need some guidance and indulgence at first ^^

I am going to send you a mail so you can tell me more about the state of DrupalGap 8, jDrupal, Angular-Drupal etc, tell me what you mean by "not production ready", and help me make a decision…

**Comment by signalpoint** [comment]
@Nicolas-Bouteille 

> I think maybe the page Adding Links to Menus for DrupalGap 8 should be updated. http://docs.drupalgap.org/8/Menus/Adding_Links_to_Menus

I decided to delete this docs page all together since, as you pointed out, altering existing menu links is already covered in http://docs.drupalgap.org/8/Menus/Altering_Existing_Menu_Links (via altering a block), and the create a custom menu docs covers it for new menus: http://docs.drupalgap.org/8/Menus/Creating_Custom_Menus

> I am new to DrupalGap but from what I've understood, adding a link to an existing menu in D8 should now be done via hook_block_view_alter()

Correct. To alter an existing menu, utilize `hook_block_view_alter()`.

> For the same reason, I think maybe the page about the menu icons is out of date

Since DG8 blocks are so flexible, this doc really doesn't need to be present at this point, so I deleted it too. Folks utilizing Bootstrap, Foundation, etc can now easily use DG8 blocks to add icons to menus/links etc.

> Looks like the page "Menus with Dynamic links" is outdated as well and based on DrupalGap 7 hook_block_info and hook_block_view

Same thing here, DG8 blocks have overcome the shortcoming of DG7's menu+block system, and now it's way easier to make dynamic menus with a block and any number of widgets inside of it.

**Comment by signalpoint** [comment]
@Nicolas-Bouteille 

> About contributing, right now I still need to decide if I go with DrupalGap or another framework like Ionic...

Understandable. I've received your e-mail here. In the interest of open source, I'd like to copy/paste that into a new issue/discussion here, where I can publicly follow up to each of your questions. Thank you.

**Comment by Nicolas-Bouteille** [comment]
Of course! Be my guest :)
