### ISSUE TITLE
Doc 8 Bucket widget node.title should be node.getTitle() ?

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [signalpoint/DrupalGap#961]
Doc for 8 Bucket widget is not working for me
http://docs.drupalgap.org/8/Widgets/Bucket_Widget
node.title returns undefined
node.getTitle() works

**Comment by signalpoint** [comment]
@Nicolas-Bouteille Thank you, I've correct this: http://docs.drupalgap.org/8/Widgets/Bucket_Widget
