### ISSUE TITLE
Doc 8 Buttons needs update

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [signalpoint/DrupalGap#962]
Looks like the doc page about Button widget in 8 needs to be updated.
I have noticed that theme should now be _theme and text should be _value
from src/modules/widgets/widgets.button.js
however, for now I can't seem to make it link to some path.

**Comment by signalpoint** [comment]
@Nicolas-Bouteille Thank you for pointing this out. I've updated the Button docs for DG8 and included an example on how to make them link to a certain path: http://docs.drupalgap.org/8/Widgets/Button_Widget

**Comment by Nicolas-Bouteille** [comment]
Awesome I'll have a look :)
I contacted you via your Drupal profile page, did you receive the email? I don't mean to pressure you, take all the time you need to answer me but just wanted to know if you actually did receive it...

**Comment by signalpoint** [comment]
Got it and replied: #963
