### ISSUE TITLE
broken link in docs

### ISSUE THREAD

**Issue by zak-schlemmer** [signalpoint/DrupalGap#964]
http://docs.drupalgap.org/8/Hello_World/index
step 2 links to:
http://docs.drupalgap.org/8/Hello_World/Modules/Create_a_Custom_Module
which displays: "An error occured" and "The Page you requested is yet to be made. Try again later."
probably suppose to be:
http://docs.drupalgap.org/8/Modules/Create_a_Custom_Module

**Comment by signalpoint** [comment]
@zak-schlemmer Thanks, I've updated the docs, and will launch this with my next deployment (probably later tonight).

**Comment by signalpoint** [comment]
Deployed.
