### ISSUE TITLE
Entity Fields Not Being Rendered on Entity View Pages

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#97]
For example, the default Article content type will not render an image field value attached to the node, when viewing the node in DrupalGap.

**Comment by simonemarin** [comment]
Hi when I load a node I only get the title and the comment form, why aren t my fields loaded?
tx
Simone

**Comment by signalpoint** [comment]
@simonemarin - fields are not supported in 7.x-1.4-alpha. If you download the latest development snapshot of DrupalGap, field support has begun (text, image). Our goal is to support all core fields provided by Drupal, this issue has a high priority. Please list any core fields that you find are not yet supported, and we'll try to implement them as soon as possible.

**Comment by simonemarin** [comment]
Hi @signalpoint I am on 1.x but I can only see the title and the comment form when I load a node. at least I have both an image and a body text field
tx

**Comment by signalpoint** [comment]
@simonemarin - check out your Javascript console.log() messages, there you should see a warning(s) about missing field handlers. Please list any missing field handlers here.

**Comment by simonemarin** [comment]
I dont see any error related to fields just 
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/hello/assets/www/jquery.min.map
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/hello/assets/www/jquery.mobile-1.3.1.min.map
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/hello/assets/www/jquery.min.map
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/hello/assets/www/jquery.mobile-1.3.1.min.map
GET http://localhost/hello/assets/www/jquery.mobile-1.3.1.min.map 404 (Not Found) /hello/assets/www/jquery.mobile-1.3.1.min.map:1
GET http://localhost/hello/assets/www/jquery.min.map 404 (Not Found)

**Comment by signalpoint** [comment]
Any file with a *.map extension is not associated with DrupalGap in any way, and can't be supported. It looks like you're Android project is running inside your localhost, that seems odd. The hello directory for your Android project is related to native Android code, and shouldn't be in your localhost environment (I personally would put it in ~/Desktop/phonegap-code/hello). This is getting off track with the issue being discussed above. If you need additional support please open a different issue with a new topic.

**Comment by simonemarin** [comment]
Hi
I ve tested with a fresh install of Drupal and in fact text fields and imgaes do appear. I am attaching the json I got from the Chrome console  under node_access(), not sure if that can help 

working --- > http://codepad.org/3JtKC2eP
not working  ----> http://codepad.org/p8n1Z0gx

**Comment by simonemarin** [comment]
So, as mentioned in IRC, the problem is in a multi language site setup.
Language variable is present in : 

./modules/entity/entity.js:66:          var elements = fn(entity_type, entity, field, null, 'und', items, field['display']['default']);
./modules/entity/entity.js:299:          'default_value':'und', // TODO - not sure about this, need to learn
./app/settings.js:17:  'language':'und',

I haven t managed to do much of it though.

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.
