### ISSUE TITLE
Lots of Alerts

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#98]
From a UX perspective all of the instances of 

catch (error) {
    alert('drupalgap_service_resource_extract_results - ' + error);
    return null;
  }

and similar things. I don't think alerts is the best way to display an error. If my server has gone down and someone is using the app its horrible from a UX point to have all these alerts with messages the average user wouldn't understand.

**Comment by signalpoint** [comment]
@scotthooker - Agreed. The alerts can be bad especially when one leads to another, the average user can get bombarded with many meaningless popup messages. My first thought on handling this in another way would be to replace all the try/catch error alerts() with something like:

drupalgap_watchdog('services', 'drupalgap_service_resource_extract_results - ' + error, null, WATCHDOG_ERROR);

This function doesn't exist yet. So I'm thinking the drupalgap_watchdog() could be implemented to always output the error message to the console.log and we would add some variable to settings.js (i.e. drupalgap_watchdog_report = true) which could in turn e-mail the DG watchdog report to the site's e-mail address (via a DG service resource). That way while developing, we can always refer to the console.log(), and then we'd have the new option of being notified of any drastic errors that occur from our user's perspective.

How does this sound?

@cschaub - I'd be curious to also hear what you think about this issue.

Also, what do we display to the user in the event of one of these traumatic error? Something basic like:

"Sorry, an unexpected error occurred. Please contact the developer if the problem persists."

**Comment by chrisschaub** [comment]
Wow, very timely. I was just about to start hacking through the app and changing error messages. I wonder if we could bind to .error() and have a central hub, provide a hook to translate strings. I like the idea of writing to watchdog or sending emails during debug. Btw, using icenium.com with drupalgap and cordova, working well. Really makes testing on Android and IOS devices a lot easier.

**Comment by scotthooker** [comment]
@cschaub haven't heard of icenium. Any good? I'm currently going through the pain of trying to install eclipse and android sdk... Not my favourite IDE!

**Comment by chrisschaub** [comment]
Definitely try icenium, free for 30 days. The Android emulator is soooo bad anyway.

**Comment by chrisschaub** [comment]
I was thinking it might be nice to have an "error" page like the offline page. One that could display a message, be formatted etc. That way, we could just handle any error for the document, redirect to the error page and display the error? Maybe have an option to report it to the app developer? And a button to start over, go to homepage.

**Comment by signalpoint** [comment]
Related issue: #92 

@scotthooker - FYI, I only use Eclipse when it is time to compile the App for Android. Any other time, I just use my preferred IDE. The only trick is, any time you update your code, just hit F5 (refresh) on the project root in Eclipse to reload your code, then you can recompile the Android app.

I also definitely agree with @cschaub that the Android emulator is horribly slow. Compiling directly to an Android device is the way to go when getting ready for release (if possible). Other than that, using Ripple is definitely the fastest way to develop (I think we're still having issues with Authenticated users though #53).

**Comment by chrisschaub** [comment]
This looks very cool, thanks Tyler! So, are you going to swap all of the alerts for drupalgap_error()? I could do this today if you want, grunt work!

**Comment by signalpoint** [comment]
@cschaub - thanks, no problem! Yes, the plan is to replace the majority of the alert calls with a call to drupalgap_error(). Since drupalgap_error() will now tell us which function called it, we no longer have to add the function name as a prefix to the error message in the alert dialog. We'll need to be careful not to replace all the alerts (i.e. any bootstrap related functions), so any errors that need to be reported before the system is ready, can be alerted to us. That would be great if you'd like to start replacing them, I plan on slowly hacking away at them as well. Please reference this issue number any time you commit code, thanks so much!

**Comment by signalpoint** [comment]
Most, if not all, alerts have been changed to console.log() messages. Resolved with the 7.x-1.7-alpha release.
