### ISSUE TITLE
unlimited value field and node

### ISSUE THREAD

**Issue by sangasgar** [signalpoint/DrupalGap#992]
This [patch](https://www.drupal.org/project/services/issues/2224803#comment-11477609) not work for me
I use
drupal 7.56
drupalgap 7.0.2.0

Console error

POST: https://example.ru/?q=drupalgap/node.json - 406 - Not Acceptable : An illegal choice has been detected. Please contact the site administrator. An illegal choice has been detected. Please contact the site administrator. .
jdrupal-7.0.5.min.js:2 {"form_errors":{"field_12121][und":"\u0421\u0434\u0435\u043b\u0430\u043d \u043d\u0435\u0434\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u044b\u0439 \u0432\u044b\u0431\u043e\u0440. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043e\u0431\u0440\u0430\u0442\u0438\u0442\u0435\u0441\u044c \u043a \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0443 \u0441\u0430\u0439\u0442\u0430."}}
jdrupal-7.0.5.min.js:2 date: Wed, 06 Dec 2017 14:37:10 GMT
x-content-type-options: nosniff
server: nginx/1.12.0
x-powered-by: PHP/7.0.25
transfer-encoding: chunked
content-language: ru
cache-control: no-cache, must-revalidate
connection: keep-alive
content-type: application/json
expires: Sun, 19 Nov 1978 05:00:00 GMT

**Comment by signalpoint** [comment]
There are already multiple issues related to this topic.
